-- =====================================================
-- 成本管理系统数据库初始化脚本
-- 用途：创建所有表结构、视图、序列、存储过程
-- 导出时间: 2026-02-05
-- =====================================================

-- =====================================================
-- 第一部分：清理现有对象
-- =====================================================

-- 清理视图
BEGIN
  FOR v IN (SELECT view_name FROM user_views WHERE view_name LIKE 'T_COST_%' OR view_name LIKE 'V_COST_%') LOOP
    EXECUTE IMMEDIATE 'DROP VIEW ' || v.view_name;
  END LOOP;
END;
/

-- 清理表
BEGIN
  FOR t IN (
    SELECT table_name
      FROM user_tables
     WHERE table_name LIKE 'T_COST_%'
        OR table_name LIKE 'MV_COST_%'
        OR table_name LIKE 'T_WMS_%'
        ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- 清理序列
BEGIN
  FOR s IN (
    SELECT sequence_name
      FROM user_sequences
     WHERE sequence_name LIKE 'SEQ_COST_%'
        OR sequence_name LIKE 'ISEQ$$_%'
        OR sequence_name LIKE 'SEQ_WMS_%'
        ) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

-- =====================================================
-- 第二部分：创建序列
-- =====================================================

CREATE SEQUENCE SEQ_COST_AUDIT_LOG
  START WITH 521
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_COLUMN_METADATA
  START WITH 1521
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_CUSTOMER
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_DEPARTMENT
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_DICT_ITEM
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_DICT_TYPE
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_EXPORT_CONFIG
  START WITH 41
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_EXPORT_CONFIG_DTL
  START WITH 21
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_FORMONEY
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_GOODS
  START WITH 21
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_GOODS_PRICE
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_LOOKUP_CONFIG
  START WITH 121
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_OPERATION_LOG
  START WITH 281
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_OPERATION_LOG_DETAIL
  START WITH 1321
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_PAGE_COMPONENT
  START WITH 161
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_PAGE_RULE
  START WITH 561
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_PINGGU
  START WITH 100000
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_PINGGU_DTL
  START WITH 100300
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_RESOURCE
  START WITH 121
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_ROLE
  START WITH 61
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_ROLE_PAGE
  START WITH 141
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_TABLE_METADATA
  START WITH 161
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_TRANPOSER
  START WITH 21
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_USER
  START WITH 181
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_USER_GRID
  START WITH 61
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_COST_USER_ROLE
  START WITH 61
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_WMS_CON_DOC
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_WMS_QTY
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

CREATE SEQUENCE SEQ_WMS_QTY_DTL
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

COMMIT;


-- =====================================================
-- 第三部分：创建表结构
-- =====================================================

-- 元数据表
CREATE TABLE T_COST_TABLE_METADATA (
  ID NUMBER(19) NOT NULL,
  TABLE_CODE VARCHAR2(64) NOT NULL,
  TABLE_NAME VARCHAR2(128) NOT NULL,
  QUERY_VIEW VARCHAR2(64),
  TARGET_TABLE VARCHAR2(64) NOT NULL,
  SEQUENCE_NAME VARCHAR2(64),
  PK_COLUMN VARCHAR2(64) DEFAULT 'ID',
  PARENT_TABLE_CODE VARCHAR2(64),
  PARENT_FK_COLUMN VARCHAR2(64),
  AUDIT_ENABLED NUMBER(1) DEFAULT 0,
  VALIDATION_RULES CLOB,
  ACTION_RULES CLOB,
  DESCRIPTION VARCHAR2(500),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_TABLE_METADATA PRIMARY KEY (ID)
);

CREATE TABLE T_COST_COLUMN_METADATA (
  ID NUMBER(19) NOT NULL,
  TABLE_METADATA_ID NUMBER(19) NOT NULL,
  FIELD_NAME VARCHAR2(64) NOT NULL,
  COLUMN_NAME VARCHAR2(64) NOT NULL,
  QUERY_COLUMN VARCHAR2(128),
  TARGET_COLUMN VARCHAR2(64),
  HEADER_TEXT VARCHAR2(128) NOT NULL,
  DATA_TYPE VARCHAR2(32) DEFAULT 'text',
  DISPLAY_ORDER NUMBER(5) DEFAULT 0,
  SORTABLE NUMBER(1) DEFAULT 1,
  FILTERABLE NUMBER(1) DEFAULT 1,
  IS_VIRTUAL NUMBER(1) DEFAULT 0,
  DICT_TYPE VARCHAR2(64),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_COLUMN_METADATA PRIMARY KEY (ID)
);
CREATE INDEX IDX_COLUMN_TABLE_ID ON T_COST_COLUMN_METADATA(TABLE_METADATA_ID);

-- 页面规则表
CREATE TABLE T_COST_PAGE_RULE (
  ID NUMBER(19) NOT NULL,
  PAGE_CODE VARCHAR2(64) NOT NULL,
  COMPONENT_KEY VARCHAR2(64) NOT NULL,
  RULE_TYPE VARCHAR2(32) NOT NULL,
  RULES CLOB NOT NULL,
  SORT_ORDER NUMBER(5) DEFAULT 0,
  DESCRIPTION VARCHAR2(200),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_PAGE_RULE PRIMARY KEY (ID)
);
CREATE INDEX IDX_PAGE_RULE_PAGE ON T_COST_PAGE_RULE(PAGE_CODE);

-- 页面组件表
CREATE TABLE T_COST_PAGE_COMPONENT (
  ID NUMBER(19) NOT NULL,
  PAGE_CODE VARCHAR2(64) NOT NULL,
  COMPONENT_KEY VARCHAR2(64) NOT NULL,
  COMPONENT_TYPE VARCHAR2(32) NOT NULL,
  PARENT_KEY VARCHAR2(64),
  COMPONENT_CONFIG CLOB,
  REF_TABLE_CODE VARCHAR2(64),
  SLOT_NAME VARCHAR2(32),
  SORT_ORDER NUMBER(5) DEFAULT 0,
  DELETED NUMBER(1) DEFAULT 0,
  DESCRIPTION VARCHAR2(200),
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_PAGE_COMPONENT PRIMARY KEY (ID)
);
CREATE INDEX IDX_PAGE_COMP_PAGE ON T_COST_PAGE_COMPONENT(PAGE_CODE);
CREATE UNIQUE INDEX UK_PAGE_COMP_KEY ON T_COST_PAGE_COMPONENT(PAGE_CODE, COMPONENT_KEY);

-- Lookup配置表
CREATE TABLE T_COST_LOOKUP_CONFIG (
  ID NUMBER(19) NOT NULL,
  LOOKUP_CODE VARCHAR2(64) NOT NULL,
  LOOKUP_NAME VARCHAR2(128) NOT NULL,
  DATA_SOURCE VARCHAR2(200) NOT NULL,
  DISPLAY_COLUMNS CLOB,
  VALUE_FIELD VARCHAR2(64) NOT NULL,
  LABEL_FIELD VARCHAR2(64) NOT NULL,
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_LOOKUP_CONFIG PRIMARY KEY (ID)
);

-- 字典类型表
CREATE TABLE T_COST_DICTIONARY_TYPE (
  ID NUMBER(19) NOT NULL,
  TYPE_CODE VARCHAR2(64) NOT NULL,
  TYPE_NAME VARCHAR2(128) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_DICTIONARY_TYPE PRIMARY KEY (ID)
);

-- 字典项表
CREATE TABLE T_COST_DICTIONARY_ITEM (
  ID NUMBER(19) NOT NULL,
  TYPE_ID NUMBER(19) NOT NULL,
  ITEM_CODE VARCHAR2(64) NOT NULL,
  ITEM_NAME VARCHAR2(128) NOT NULL,
  ITEM_VALUE VARCHAR2(200),
  SORT_ORDER NUMBER(5) DEFAULT 0,
  EXTRA_CONFIG VARCHAR2(1000),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_DICTIONARY_ITEM PRIMARY KEY (ID)
);
CREATE INDEX IDX_DICT_ITEM_TYPE ON T_COST_DICTIONARY_ITEM(TYPE_ID);

-- 部门表
CREATE TABLE T_COST_DEPARTMENT (
  ID NUMBER(19) NOT NULL,
  DEPT_CODE VARCHAR2(64) NOT NULL,
  DEPT_NAME VARCHAR2(128) NOT NULL,
  PARENT_ID NUMBER(19),
  SORT_ORDER NUMBER(5) DEFAULT 0,
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_BY VARCHAR2(64),
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_BY VARCHAR2(64),
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_T_COST_DEPARTMENT PRIMARY KEY (ID)
);

-- 用户表
CREATE TABLE T_COST_USER (
  ID NUMBER(19) NOT NULL,
  USERNAME VARCHAR2(64) NOT NULL,
  PASSWORD VARCHAR2(256) NOT NULL,
  REAL_NAME VARCHAR2(128),
  EMAIL VARCHAR2(128),
  PHONE VARCHAR2(32),
  DEPARTMENT_ID NUMBER(19),
  STATUS VARCHAR2(32) DEFAULT 'ACTIVE',
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_BY VARCHAR2(64),
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_BY VARCHAR2(64),
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_T_COST_USER PRIMARY KEY (ID)
);

-- 角色表
CREATE TABLE T_COST_ROLE (
  ID NUMBER(19) NOT NULL,
  ROLE_CODE VARCHAR2(64) NOT NULL,
  ROLE_NAME VARCHAR2(128) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  CONSTRAINT PK_T_COST_ROLE PRIMARY KEY (ID)
);

-- 用户角色关联表
CREATE TABLE T_COST_USER_ROLE (
  ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  ROLE_ID NUMBER(19) NOT NULL,
  CONSTRAINT PK_T_COST_USER_ROLE PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_USER_ROLE ON T_COST_USER_ROLE(USER_ID, ROLE_ID);

-- 角色页面权限表
CREATE TABLE T_COST_ROLE_PAGE (
  ID NUMBER(19) NOT NULL,
  ROLE_ID NUMBER(19) NOT NULL,
  PAGE_CODE VARCHAR2(64) NOT NULL,
  BUTTON_POLICY VARCHAR2(1000),
  COLUMN_POLICY CLOB,
  ROW_POLICY VARCHAR2(2000),
  CONSTRAINT PK_T_COST_ROLE_PAGE PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_ROLE_PAGE ON T_COST_ROLE_PAGE(ROLE_ID, PAGE_CODE);

-- 资源菜单表
CREATE TABLE T_COST_RESOURCE (
  ID NUMBER(19) NOT NULL,
  RESOURCE_NAME VARCHAR2(128) NOT NULL,
  RESOURCE_TYPE VARCHAR2(20) NOT NULL,
  PAGE_CODE VARCHAR2(64),
  ICON VARCHAR2(64),
  ROUTE VARCHAR2(128),
  PARENT_ID NUMBER(19),
  SORT_ORDER NUMBER(5) DEFAULT 0,
  IS_HARDCODED NUMBER(1) DEFAULT 0,
  CONSTRAINT PK_T_COST_RESOURCE PRIMARY KEY (ID)
);

-- 用户表格配置表
CREATE TABLE T_COST_USER_GRID_CONFIG (
  ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  PAGE_CODE VARCHAR2(64) NOT NULL,
  GRID_KEY VARCHAR2(64) NOT NULL,
  CONFIG_DATA CLOB,
  DELETED NUMBER(1) DEFAULT 0,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_T_COST_USER_GRID_CONFIG PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_USER_GRID_CONF ON T_COST_USER_GRID_CONFIG(USER_ID, PAGE_CODE, GRID_KEY);

-- 导出配置主表
CREATE TABLE T_COST_EXPORT_CONFIG (
  ID NUMBER(19) NOT NULL,
  EXPORT_CODE VARCHAR2(100) NOT NULL,
  EXPORT_NAME VARCHAR2(200) NOT NULL,
  PAGE_CODE VARCHAR2(100) NOT NULL,
  MASTER_SQL CLOB NOT NULL,
  MASTER_TABLE_ALIAS VARCHAR2(50),
  PK_COLUMN VARCHAR2(100),
  PAGE_VIEW_ALIAS VARCHAR2(50) DEFAULT 'p',
  PAGE_FK_COLUMN VARCHAR2(100),
  MASTER_LINK_COLUMN VARCHAR2(100),
  COLUMNS CLOB,
  MASTER_SHEET_NAME VARCHAR2(100) DEFAULT 'master',
  DISPLAY_ORDER NUMBER(5) DEFAULT 0,
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_BY VARCHAR2(64),
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_BY VARCHAR2(64),
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_T_COST_EXPORT_CONFIG PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_EXPORT_CONFIG_CODE ON T_COST_EXPORT_CONFIG(EXPORT_CODE);

-- 导出配置从表
CREATE TABLE T_COST_EXPORT_CONFIG_DETAIL (
  ID NUMBER(19) NOT NULL,
  EXPORT_CONFIG_ID NUMBER(19) NOT NULL,
  TAB_KEY VARCHAR2(100),
  SHEET_NAME VARCHAR2(100),
  DETAIL_SQL CLOB NOT NULL,
  MASTER_TABLE_ALIAS VARCHAR2(50),
  DETAIL_TABLE_ALIAS VARCHAR2(50),
  DETAIL_LINK_COLUMN VARCHAR2(100),
  COLUMNS CLOB,
  DISPLAY_ORDER NUMBER(5) DEFAULT 0,
  CONSTRAINT PK_T_COST_EXPORT_CONFIG_DETAIL PRIMARY KEY (ID)
);
CREATE INDEX IDX_EXPORT_DTL_CONFIG ON T_COST_EXPORT_CONFIG_DETAIL(EXPORT_CONFIG_ID);

-- =====================================================
-- 业务表
-- =====================================================

-- 客户表
CREATE TABLE T_COST_CUSTOMER (
  CUSTOMID NUMBER(19) NOT NULL,
  ZONE VARCHAR2(500),
  CUSTOMNAME VARCHAR2(500),
  ISERP NUMBER(1) DEFAULT 0,
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_CUSTOMER PRIMARY KEY (CUSTOMID)
);

-- 分销商表
CREATE TABLE T_COST_TRANPOSER (
  TRANPOSID NUMBER(19) NOT NULL,
  CUSTOMID NUMBER(19),
  TRANPOSNAME VARCHAR2(500),
  ISERP NUMBER(1) DEFAULT 0,
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_TRANPOSER PRIMARY KEY (TRANPOSID)
);

-- 外币汇率表
CREATE TABLE T_COST_FORMONEY (
  FMID NUMBER(10) NOT NULL,
  FMOPCODE VARCHAR2(60),
  FMNAME VARCHAR2(120),
  FMSIGN VARCHAR2(60),
  FMUNIT VARCHAR2(60),
  FMRATE NUMBER(16,6),
  USESTATUS NUMBER(2),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_FORMONEY PRIMARY KEY (FMID)
);

-- 产品信息表
CREATE TABLE T_COST_GOODS (
  GOODSID NUMBER(19) NOT NULL,
  GOODSNO VARCHAR2(100),
  GOODSNAME VARCHAR2(1000),
  PRICE NUMBER,
  SUQTY NUMBER,
  USEFLAG VARCHAR2(100) DEFAULT '产成品',
  FACTORYNAME VARCHAR2(1500),
  STANDARDTYPE VARCHAR2(500),
  ZX_PL NUMBER,
  ZX_MINIMUM NUMBER,
  APPROVEDOCNO VARCHAR2(500),
  BASEUNITQTY NUMBER,
  ZX_CUSTOMERID NUMBER(19),
  TARGETMARKET VARCHAR2(1000),
  HOLDERSNAME VARCHAR2(1000),
  ISERP NUMBER(1) DEFAULT 0,
  GOODSTYPE VARCHAR2(500),
  PACKTYPE VARCHAR2(500),
  BOMID NUMBER(19),
  LASTSUQTY NUMBER,
  TRANPOSID NUMBER(19),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(320),
  UPDATE_BY VARCHAR2(320),
  CONSTRAINT PK_T_COST_GOODS PRIMARY KEY (GOODSID)
);

-- 物料价格表
CREATE TABLE T_COST_GOODS_PRICE (
  GOODSID NUMBER(10) NOT NULL,
  GOODSNAME VARCHAR2(300),
  PRICE NUMBER,
  USEFLAG VARCHAR2(15),
  GOODSTYPE VARCHAR2(3000),
  PACKTYPE VARCHAR2(600),
  FACTORYNAME VARCHAR2(300),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  ISERP NUMBER(1) DEFAULT 0,
  CONSTRAINT PK_T_COST_GOODS_PRICE PRIMARY KEY (GOODSID)
);

-- 物料成本核算主表
CREATE TABLE T_COST_PINGGU (
  GOODSID NUMBER,
  GOODSNAME VARCHAR2(100),
  STRENGTH VARCHAR2(50),
  MA_NO VARCHAR2(30),
  APEX_PL NUMBER,
  MAH VARCHAR2(100),
  P_PERPACK NUMBER,
  FORM VARCHAR2(20),
  S_PERBACK NUMBER,
  PACKTYPE VARCHAR2(30),
  X_PERBACK NUMBER,
  TOTAL_FL NUMBER,
  TOTAL_BC NUMBER,
  TOTAL_YL NUMBER,
  MEMO VARCHAR2(100),
  USESTATUS VARCHAR2(100) DEFAULT 0,
  DOCID NUMBER DEFAULT SEQ_COST_PINGGU.NEXTVAL NOT NULL,
  DOSAGE VARCHAR2(20),
  ANNUAL_QTY NUMBER,
  YIELD NUMBER,
  TOTAL_COST NUMBER,
  OUT_PRICE_F NUMBER,
  OUT_PRICE_RMB NUMBER,
  SALEMONEY NUMBER,
  JGF_BATCH NUMBER,
  JGF_PERQP NUMBER,
  COST_PERQP NUMBER,
  ML_PERQP NUMBER,
  Y_JG_RE NUMBER,
  Y_ML NUMBER,
  Y_SALE NUMBER,
  CUSTOMID NUMBER,
  CUSTOMNAME VARCHAR2(50),
  COUNTRY VARCHAR2(20),
  PROJECTNO VARCHAR2(20),
  USEFLAG NUMBER DEFAULT 0,
  YIELD_TIME DATE DEFAULT SYSDATE,
  APEX_PL_TIME DATE DEFAULT SYSDATE,
  FMNAME VARCHAR2(100) DEFAULT '人民币',
  FMRATE NUMBER DEFAULT 1,
  GOODSNAME_EN VARCHAR2(2000),
  LIVERY VARCHAR2(100),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  COST_PERBOX NUMBER,
  CONSTRAINT PK_T_COST_PINGGU PRIMARY KEY (DOCID)
);

-- 物料成本核算明细表
CREATE TABLE T_COST_PINGGU_DTL (
  DOCID NUMBER(10) NOT NULL,
  APEX_GOODSID NUMBER(10),
  APEX_GOODSNAME VARCHAR2(500),
  DTL_USEFLAG VARCHAR2(100),
  SPEC VARCHAR2(100),
  PER_HL NUMBER,
  EXADD_MATER NUMBER,
  BATCH_QTY NUMBER,
  PRICE NUMBER,
  COST_BATCH NUMBER,
  MEMO VARCHAR2(100),
  DTLID NUMBER(10) DEFAULT SEQ_COST_PINGGU_DTL.NEXTVAL NOT NULL,
  APEX_FACTORYNAME VARCHAR2(200),
  APEX_FACTORYID NUMBER(10),
  MODIFYDATE DATE,
  BASE_PRICE NUMBER,
  SUQTY NUMBER,
  GOODSTYPE VARCHAR2(4000),
  GOODSNAME_EN VARCHAR2(2000),
  DELETED NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  CONSTRAINT PK_T_COST_PINGGU_DTL PRIMARY KEY (DTLID)
);

-- 物料成本核算历史表
CREATE TABLE T_COST_PINGGU_HIS (
  GOODSID NUMBER,
  GOODSNAME VARCHAR2(100),
  STRENGTH VARCHAR2(50),
  MA_NO VARCHAR2(30),
  APEX_PL NUMBER,
  MAH VARCHAR2(100),
  P_PERPACK NUMBER,
  FORM VARCHAR2(20),
  S_PERBACK NUMBER,
  PACKTYPE VARCHAR2(30),
  X_PERBACK NUMBER,
  TOTAL_FL NUMBER,
  TOTAL_BC NUMBER,
  TOTAL_YL NUMBER,
  MEMO VARCHAR2(100),
  USESTATUS VARCHAR2(100),
  DOCID NUMBER NOT NULL,
  DOSAGE VARCHAR2(20),
  ANNUAL_QTY NUMBER,
  YIELD NUMBER,
  TOTAL_COST NUMBER,
  OUT_PRICE_F NUMBER,
  OUT_PRICE_RMB NUMBER,
  SALEMONEY NUMBER,
  JGF_BATCH NUMBER,
  JGF_PERQP NUMBER,
  COST_PERQP NUMBER,
  ML_PERQP NUMBER,
  Y_JG_RE NUMBER,
  Y_ML NUMBER,
  Y_SALE NUMBER,
  CUSTOMID NUMBER,
  CUSTOMNAME VARCHAR2(50),
  COUNTRY VARCHAR2(20),
  PROJECTNO VARCHAR2(20),
  USEFLAG NUMBER,
  YIELD_TIME DATE,
  APEX_PL_TIME DATE,
  ZX_SOURCE VARCHAR2(100),
  FMNAME VARCHAR2(100),
  FMRATE NUMBER,
  GOODSNAME_EN VARCHAR2(2000),
  LIVERY VARCHAR2(100),
  DELETED NUMBER(1),
  CREATE_TIME TIMESTAMP(6),
  UPDATE_TIME TIMESTAMP(6),
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  BACKUP_TIME DATE,
  COST_PERBOX NUMBER
);

-- 物料成本核算明细历史表
CREATE TABLE T_COST_PINGGU_DTL_HIS (
  DOCID NUMBER(10) NOT NULL,
  APEX_GOODSID NUMBER(10),
  APEX_GOODSNAME VARCHAR2(500),
  DTL_USEFLAG VARCHAR2(100),
  SPEC VARCHAR2(100),
  PER_HL NUMBER,
  EXADD_MATER NUMBER,
  BATCH_QTY NUMBER,
  PRICE NUMBER,
  COST_BATCH NUMBER,
  MEMO VARCHAR2(100),
  DTLID NUMBER(10) NOT NULL,
  APEX_FACTORYNAME VARCHAR2(200),
  APEX_FACTORYID NUMBER(10),
  MODIFYDATE DATE,
  ZX_SOURCE VARCHAR2(100),
  BASE_PRICE NUMBER,
  SUQTY NUMBER,
  GOODSTYPE VARCHAR2(4000),
  GOODSNAME_EN VARCHAR2(2000),
  DELETED NUMBER(1),
  CREATE_TIME TIMESTAMP(6),
  UPDATE_TIME TIMESTAMP(6),
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  BACKUP_TIME DATE
);

-- 物料成本核算计算历史表
CREATE TABLE T_COST_PINGGU_COMPUTE_HIS (
  GOODSID NUMBER,
  GOODSNAME VARCHAR2(100),
  STRENGTH VARCHAR2(50),
  MA_NO VARCHAR2(30),
  APEX_PL NUMBER,
  MAH VARCHAR2(100),
  P_PERPACK NUMBER,
  FORM VARCHAR2(20),
  S_PERBACK NUMBER,
  PACKTYPE VARCHAR2(30),
  X_PERBACK NUMBER,
  TOTAL_FL NUMBER,
  TOTAL_BC NUMBER,
  TOTAL_YL NUMBER,
  MEMO VARCHAR2(100),
  USESTATUS VARCHAR2(100),
  DOCID NUMBER NOT NULL,
  DOSAGE VARCHAR2(20),
  ANNUAL_QTY NUMBER,
  YIELD NUMBER,
  TOTAL_COST NUMBER,
  OUT_PRICE_F NUMBER,
  OUT_PRICE_RMB NUMBER,
  SALEMONEY NUMBER,
  JGF_BATCH NUMBER,
  JGF_PERQP NUMBER,
  COST_PERQP NUMBER,
  ML_PERQP NUMBER,
  Y_JG_RE NUMBER,
  Y_ML NUMBER,
  Y_SALE NUMBER,
  CUSTOMID NUMBER,
  CUSTOMNAME VARCHAR2(50),
  COUNTRY VARCHAR2(20),
  PROJECTNO VARCHAR2(20),
  USEFLAG NUMBER,
  YIELD_TIME DATE,
  APEX_PL_TIME DATE,
  ZX_SOURCE VARCHAR2(100),
  FMNAME VARCHAR2(100),
  FMRATE NUMBER,
  GOODSNAME_EN VARCHAR2(2000),
  LIVERY VARCHAR2(100),
  DELETED NUMBER(1),
  CREATE_TIME TIMESTAMP(6),
  UPDATE_TIME TIMESTAMP(6),
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  COST_PERBOX NUMBER,
  COMPUTE_DATE DATE
);

-- 物料成本核算明细计算历史表
CREATE TABLE T_COST_PINGGU_DTL_COMPUTE_HIS (
  DOCID NUMBER(10) NOT NULL,
  APEX_GOODSID NUMBER(10),
  APEX_GOODSNAME VARCHAR2(500),
  DTL_USEFLAG VARCHAR2(100),
  SPEC VARCHAR2(100),
  PER_HL NUMBER,
  EXADD_MATER NUMBER,
  BATCH_QTY NUMBER,
  PRICE NUMBER,
  COST_BATCH NUMBER,
  MEMO VARCHAR2(100),
  DTLID NUMBER(10) NOT NULL,
  APEX_FACTORYNAME VARCHAR2(200),
  APEX_FACTORYID NUMBER(10),
  MODIFYDATE DATE,
  ZX_SOURCE VARCHAR2(100),
  BASE_PRICE NUMBER,
  SUQTY NUMBER,
  GOODSTYPE VARCHAR2(4000),
  GOODSNAME_EN VARCHAR2(2000),
  DELETED NUMBER(1),
  CREATE_TIME TIMESTAMP(6),
  UPDATE_TIME TIMESTAMP(6),
  CREATE_BY VARCHAR2(64),
  UPDATE_BY VARCHAR2(64),
  COMPUTE_DATE DATE
);

-- 审计日志表
CREATE TABLE T_COST_AUDIT_LOG (
  ID NUMBER(19) NOT NULL,
  USER_NAME VARCHAR2(100),
  OPERATION_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  PAGE_CODE VARCHAR2(100),
  TABLE_CODE VARCHAR2(100),
  TABLE_NAME VARCHAR2(200),
  RECORD_ID NUMBER(19),
  OPERATION_TYPE VARCHAR2(20),
  FIELD_CHANGES CLOB,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_T_COST_AUDIT_LOG PRIMARY KEY (ID)
);

-- 操作日志表
CREATE TABLE T_COST_OPERATION_LOG (
  ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19),
  USER_NAME VARCHAR2(64),
  OPERATION_TYPE VARCHAR2(32) NOT NULL,
  TABLE_CODE VARCHAR2(64),
  RECORD_ID NUMBER(19),
  RECORD_DESC VARCHAR2(256),
  TOTAL_SQL_COUNT NUMBER(10) DEFAULT 0,
  TOTAL_COST_MS NUMBER(10) DEFAULT 0,
  STATUS VARCHAR2(16) DEFAULT 'SUCCESS',
  ERROR_MSG VARCHAR2(1000),
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_T_COST_OPERATION_LOG PRIMARY KEY (ID)
);

-- 操作日志明细表
CREATE TABLE T_COST_OPERATION_LOG_DETAIL (
  ID NUMBER(19) NOT NULL,
  LOG_ID NUMBER(19) NOT NULL,
  SEQ_NO NUMBER(5) NOT NULL,
  SQL_TYPE VARCHAR2(16),
  SQL_TEXT CLOB,
  COST_MS NUMBER(10) DEFAULT 0,
  AFFECTED_ROWS NUMBER(10),
  STATUS VARCHAR2(16) DEFAULT 'SUCCESS',
  ERROR_MSG VARCHAR2(1000),
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_T_COST_OPERATION_LOG_DETAIL PRIMARY KEY (ID)
);

-- WMS库存表
CREATE TABLE T_WMS_GOODS_QTY (
  ID NUMBER DEFAULT SEQ_WMS_QTY.NEXTVAL NOT NULL,
  GOODSOWNID VARCHAR2(50),
  LOTNO VARCHAR2(100),
  PACKNAME VARCHAR2(200),
  GOODSQTY NUMBER(18,6),
  ODDTRAY NUMBER,
  GOODSNAME VARCHAR2(500),
  GOODSNO VARCHAR2(100),
  PACKSIZE NUMBER(18,6),
  BASEPACKNAME VARCHAR2(200),
  VALIDDATE DATE,
  CREATEDATE DATE DEFAULT SYSDATE,
  CONSTRAINT PK_T_WMS_GOODS_QTY PRIMARY KEY (ID)
);

-- 物化视图表
CREATE TABLE MV_COST_PINGGU_DTL_HIS_LATEST (
  DTLID NUMBER(10) NOT NULL,
  PRICE NUMBER
);

-- 补充索引
CREATE INDEX IDX_EXPORT_CONFIG_PAGE ON T_COST_EXPORT_CONFIG (PAGE_CODE);
CREATE INDEX IDX_OPERATION_LOG_USER ON T_COST_OPERATION_LOG (USER_ID);
CREATE INDEX IDX_OPERATION_LOG_TIME ON T_COST_OPERATION_LOG (CREATE_TIME);
CREATE UNIQUE INDEX UK_PINGGU_DTL_HIS ON T_COST_PINGGU_DTL_HIS (DTLID, BACKUP_TIME);
CREATE UNIQUE INDEX UK_PINGGU_HIS ON T_COST_PINGGU_HIS (DOCID, BACKUP_TIME);
CREATE INDEX IDX_TWGQ_GOODSOWNID ON T_WMS_GOODS_QTY (GOODSOWNID);
CREATE INDEX IDX_TWGQ_CREATEDATE ON T_WMS_GOODS_QTY (CREATEDATE);
CREATE INDEX IDX_TWGQ_LOTNO ON T_WMS_GOODS_QTY (LOTNO);

COMMIT;


-- =====================================================
-- 第四部分：创建视图
-- =====================================================

-- BOM树视图（ERP）
CREATE OR REPLACE VIEW T_COST_BOM_GOODS_TREE_V AS
select a.treeid,
       a.pid,
       a.goodsid,
       b.goodsname,
       (case
         when b.zx_wms_goodsclass in (1, 12) and b.gspflag = 1 and
              b.goodsno like '%A%' then
          '4'
         when b.zx_wms_goodsclass in (10) and b.gspflag = 1 then
          '0'
         when b.zx_wms_goodsclass in (7, 8, 9) and b.gspflag = 1 then
          '1'
         when b.zx_wms_goodsclass in (5, 13) and b.gspflag = 1 then
          '3'
         when b.zx_wms_goodsclass in (6) and b.gspflag = 1 then
          '5'
         when b.zx_wms_goodsclass in (1, 2, 3, 4) and b.gspflag = 1 and
              b.goodsno not like '%A%' then
          '2'
       end) useflag,
       b.standardtype,
       a.lvcode,
       a.useqty,
       a.entryid
  from MPCS_MRP_GOODS_TREE_V@HYERP a, pub_goods@HYERP b
 where a.goodsid = b.goodsid;

-- ERP物料视图
CREATE OR REPLACE VIEW PUB_GOODS_V AS
SELECT B.GOODSID ,
       B.GOODSNAME ,b.GOODSNO,
       c.lastprice PRICE,
       c.lastsuqty suqty,
       (case
         when b.zx_wms_goodsclass in (1, 12) and b.gspflag = 1 and
              b.goodsno like '%A%' then
          '原料'
         when b.zx_wms_goodsclass in (10) and b.gspflag = 1 then
          '产成品'
         when b.zx_wms_goodsclass in (7, 8, 9) and b.gspflag = 1 then
          '半成品'
         when b.zx_wms_goodsclass in (5, 13) and b.gspflag = 1 then
          '非印字包材'
         when b.zx_wms_goodsclass in (6) and b.gspflag = 1 then
          '印字包材'
         when b.zx_wms_goodsclass in (1, 2, 3, 4) and b.gspflag = 1 and
              b.goodsno not like '%A%' then
          '辅料'
       end) USEFLAG,
       B.FACTORYNAME,
       B.standardtype,
       b.zx_pl,
       b.zx_minimum,
       b.approvedocno, --批准文号
       e.baseunitqty,
       b.zx_customerid,
       b.customname,
       f.targetmarket,
       b.holdersname,
       1 ISERP,
       b.goodstype,
       b.packtype,
       b.tranposname,
       d.bomid,
       c.lastsuqty,
       b.tranposid
  FROM PUB_GOODS_V@hyerp            B,
       bms_su_supplygoods_doc@Hyerp c,
       MPCS_PR_BOM_DOC@Hyerp        d,
       pub_goods_unit_v@hyerp       e,
       bms_tr_pos_def@hyerp         f
 where B.GOODSID = C.GOODSID(+)
   and b.goodsid = d.pgoodsid(+)
   and d.usestatus(+) = 1
   and b.usestatus = 1
   and c.entryid(+) = 1
   and b.goodsid = e.goodsid(+)
   and e.goodsdtlflag(+) = 1
   and e.baseflag(+) <> 1
   and b.goodsid < 1000000
   and b.zx_customerid = f.companyid(+)
   and b.tranposid = f.tranposid(+)
;

-- ERP外币视图
CREATE OR REPLACE VIEW ERP_FORMONEY_V AS
SELECT
       DECODE(b.fmid,     NULL, a.fmid,     b.fmid)     fmid,
       DECODE(b.fmopcode, NULL, a.fmopcode, b.fmopcode) fmopcode,
       DECODE(b.fmname,   NULL, a.fmname,   b.fmname)   fmname,
       DECODE(b.fmsign,   NULL, a.fmsign,   b.fmsign)   fmsign,
       DECODE(b.fmunit,   NULL, a.fmunit,   b.fmunit)   fmunit,
       DECODE(b.fmrate,   NULL, a.fmrate,   b.fmrate)   fmrate,
       DECODE(b.usestatus,NULL, a.usestatus,b.usestatus) usestatus,
       NVL(b.deleted, 0)  deleted,
       b.create_time,
       b.update_time,
       b.create_by,
       b.update_by
  FROM pub_formoney_v@hyerp a, T_COST_FORMONEY b
 WHERE a.fmid = b.fmid(+)
;

-- WMS合同视图
CREATE OR REPLACE VIEW T_WMS_CON_DOC_V AS
SELECT a.conid,
       a.conno,
       a.customname,
       a.targetposname,
       a.inputmanname,
       0 AS DELETED,
       NULL AS CREATE_TIME,
       NULL AS UPDATE_TIME,
       NULL AS CREATE_BY,
       NULL AS UPDATE_BY
  FROM bms_sa_con_doc_v@hyerp a
;

-- WMS库存汇总视图
CREATE OR REPLACE VIEW T_WMS_QTY_V AS
SELECT
    NVL(TO_CHAR(a.conid), '-') || '-' || NVL(TO_CHAR(a.goodsid), '-') || '-' || NVL(a.lotno, '-') || '-' || NVL(TO_CHAR(a.packtype), '-') AS ID,
    a.conid,
    a.goodsid,
    a.goodsno,
    a.goodsname,
    a.lotno,
    a.packtype,
    b.goodsqty_total,
    b.goodsqty_oddtray1,
    b.packname,

    /* 最终显示字段 */
    TO_CHAR(NVL(b.goodsqty_total, 0)) || b.packname
    || '（'
    || CASE
         WHEN NVL(b.goodsqty_oddtray1, 0) > 0
         THEN '含零托' || TO_CHAR(b.goodsqty_oddtray1) || b.packname || '）'
       END
    || '样品__' || b.packname
    || '）' AS QTY_SHOW,
    0 AS DELETED,
    NULL AS CREATE_TIME,
    NULL AS UPDATE_TIME,
    NULL AS CREATE_BY,
    NULL AS UPDATE_BY

FROM bms_sa_con_dtl_v@hyerp a,
     (
       SELECT
           x.goodsownid,
           x.lotno,
           x.packname,
           SUM(x.goodsqty) AS goodsqty_total,
           SUM(CASE WHEN x.oddtray = 1 THEN x.goodsqty ELSE 0 END) AS goodsqty_oddtray1
       FROM wms_st_qty_lst_baseunit_v@to_wms x
       GROUP BY x.goodsownid, x.lotno, x.packname
     ) b
WHERE a.goodsid = b.goodsownid(+)
  AND a.lotno   = b.lotno(+)
;

-- WMS库存明细视图
CREATE OR REPLACE VIEW T_WMS_QTY_DTL_V AS
SELECT
    NVL(TO_CHAR(a.conid), '-') || '-' || NVL(TO_CHAR(a.goodsid), '-') || '-' || NVL(a.lotno, '-') || '-' || NVL(TO_CHAR(b.packsize), '-') AS ID,
    NVL(b.goodsownid, a.goodsid) AS GOODSOWNID,
    b.goodsname,
    NVL(b.lotno, a.lotno) AS LOTNO,
    b.goodsqty,
    b.packsize,
    CEIL(b.goodsqty / NULLIF(b.packsize, 0)) AS QTY_BOX,
    b.validdate,
    NULL AS MEMO,
    NULL AS GROSS_WEIGHT_KG,
    NULL AS NET_WEIGHT_KG,
    NULL AS VOLUME_M2,
    a.conid,
    0 AS DELETED,
    NULL AS CREATE_TIME,
    NULL AS UPDATE_TIME,
    NULL AS CREATE_BY,
    NULL AS UPDATE_BY
FROM bms_sa_con_dtl_v@hyerp a, wms_st_qty_lst_baseunit_v@to_wms b
WHERE a.goodsid = b.goodsownid(+)
  AND a.lotno   = b.lotno(+)
;

-- 评估明细视图
CREATE OR REPLACE VIEW T_COST_PINGGU_DTL_V AS
select a.docid,
       a.apex_goodsid,
       a.apex_goodsname,
       a.dtl_useflag,
       a.spec,
       a.per_hl,
       a.exadd_mater,
       a.batch_qty,
       a.price,
       a.cost_batch,
       a.memo,
       a.dtlid,
       a.apex_factoryname,
       a.apex_factoryid,
       a.modifydate,
       a.base_price,
       a.suqty,
       a.goodstype,
       a.goodsname_en,
       b.APEX_PL,
       b.P_PERPACK,
       b.S_PERBACK,
       b.X_PERBACK
  from t_cost_pinggu_dtl a, t_cost_pinggu b
 where a.docid = b.docid
;

-- 客户视图
CREATE OR REPLACE VIEW T_COST_CUSTOMER_V AS
SELECT CUSTOMID, CUSTOMNAME, ZONE, ISERP, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY
FROM T_COST_CUSTOMER WHERE DELETED = 0;

-- 分销商视图
CREATE OR REPLACE VIEW T_COST_TRANPOSER_V AS
SELECT CUSTOMID, TRANPOSID, TRANPOSNAME, ISERP, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY
FROM T_COST_TRANPOSER WHERE DELETED = 0;

-- 外币视图
CREATE OR REPLACE VIEW T_COST_FORMONEY_V AS
SELECT a.FMID, NVL(a.FMOPCODE, b.FMOPCODE) AS FMOPCODE, NVL(a.FMNAME, b.FMNAME) AS FMNAME,
       NVL(a.FMSIGN, b.FMSIGN) AS FMSIGN, NVL(a.FMUNIT, b.FMUNIT) AS FMUNIT,
       NVL(a.FMRATE, b.FMRATE) AS FMRATE, a.USESTATUS, a.DELETED, a.CREATE_TIME, a.UPDATE_TIME, a.CREATE_BY, a.UPDATE_BY
FROM T_COST_FORMONEY a LEFT JOIN pub_formoney_v@hyerp b ON a.FMID = b.FMID
WHERE a.DELETED = 0 OR a.DELETED IS NULL;

-- 产品视图
CREATE OR REPLACE VIEW T_COST_GOODS_V AS
SELECT a.GOODSID, a.GOODSNO, a.GOODSNAME, a.PRICE, a.SUQTY, a.USEFLAG, a.FACTORYNAME, a.STANDARDTYPE,
       a.ZX_PL, a.ZX_MINIMUM, a.APPROVEDOCNO, a.BASEUNITQTY, a.ZX_CUSTOMERID, b.CUSTOMNAME, a.TARGETMARKET,
       a.HOLDERSNAME, a.ISERP, a.GOODSTYPE, a.PACKTYPE, c.TRANPOSNAME, a.BOMID, a.LASTSUQTY, a.TRANPOSID,
       b.ZONE, a.DELETED, a.CREATE_TIME, a.UPDATE_TIME, a.CREATE_BY, a.UPDATE_BY
FROM T_COST_GOODS a, T_COST_CUSTOMER b, T_COST_TRANPOSER c
WHERE a.USEFLAG = '产成品' AND a.DELETED = 0 AND a.ZX_CUSTOMERID = b.CUSTOMID(+) AND a.TRANPOSID = c.TRANPOSID(+);

-- 物料价格视图
CREATE OR REPLACE VIEW T_COST_GOODS_PRICE_V AS
SELECT GOODSID, GOODSNAME, PRICE, USEFLAG, GOODSTYPE, PACKTYPE, FACTORYNAME, DELETED, CREATE_TIME, UPDATE_TIME,
       CREATE_BY, UPDATE_BY, ISERP,
       CASE WHEN ISERP = 1 AND NVL(LOWER(UPDATE_BY), '#') <> 'system' AND PRICE IS NULL THEN 'erp-price-null'
            WHEN ISERP = 1 AND NVL(LOWER(UPDATE_BY), '#') <> 'system' THEN 'erp-updated'
            WHEN ISERP = 1 THEN 'erp' ELSE NULL END AS ROW_CLASS_FLAG
FROM T_COST_GOODS_PRICE;

-- 用户视图
CREATE OR REPLACE VIEW V_COST_USER AS
SELECT u.ID, u.USERNAME, u.PASSWORD, u.REAL_NAME, u.EMAIL, u.PHONE, u.DEPARTMENT_ID, d.DEPT_NAME,
       u.STATUS, u.DELETED, u.CREATE_BY, u.CREATE_TIME, u.UPDATE_BY, u.UPDATE_TIME
FROM T_COST_USER u LEFT JOIN T_COST_DEPARTMENT d ON u.DEPARTMENT_ID = d.ID WHERE u.DELETED = 0;

-- 审计日志视图
CREATE OR REPLACE VIEW V_COST_AUDIT_LOG AS
SELECT ID, USER_NAME, OPERATION_TIME, PAGE_CODE, TABLE_CODE, TABLE_NAME, RECORD_ID, OPERATION_TYPE,
       FIELD_CHANGES, CREATE_TIME, 0 AS DELETED FROM T_COST_AUDIT_LOG;


-- 客户选择视图
CREATE OR REPLACE VIEW V_COST_CUSTOMER_LOOKUP AS
SELECT a.CUSTOMID, a.CUSTOMNAME, a.ZONE AS COUNTRY, b.TRANPOSNAME AS LIVERY, b.TRANPOSID, 0 AS DELETED
FROM T_COST_CUSTOMER_V a, T_COST_TRANPOSER_V b WHERE a.CUSTOMID = b.CUSTOMID;

-- 产品选择视图
CREATE OR REPLACE VIEW V_COST_GOODS_LOOKUP AS
SELECT a.GOODSID, a.GOODSNAME, a.APPROVEDOCNO AS MA_NO, a.ZX_PL AS APEX_PL, a.HOLDERSNAME AS MAH,
       a.ZX_MINIMUM AS P_PERPACK, a.BASEUNITQTY AS S_PERBACK, a.ZX_CUSTOMERID AS CUSTOMID, a.CUSTOMNAME,
       CASE WHEN a.ISERP = 0 AND b.PGOODSID IS NULL THEN 'ERP未搭建BOM' ELSE 'ERP已搭建BOM' END AS MEMO,
       a.GOODSTYPE AS STRENGTH, a.TRANPOSNAME AS LIVERY, a.DELETED
FROM T_COST_GOODS_V a LEFT JOIN mpcs_pr_bom_doc@hyerp b ON a.GOODSID = b.PGOODSID AND b.USESTATUS = 1 AND a.ISERP = 1
WHERE a.USEFLAG = '产成品' AND (a.DELETED = 0 OR a.DELETED IS NULL);

-- 原辅料明细视图
CREATE OR REPLACE VIEW V_COST_PINGGU_MATERIAL AS
SELECT d.DTLID AS ID, d.DOCID AS MASTER_ID, d.APEX_GOODSID, d.APEX_GOODSNAME, d.DTL_USEFLAG,
       d.SPEC, d.PER_HL, d.PRICE, d.BATCH_QTY, d.COST_BATCH, d.APEX_FACTORYNAME, d.BASE_PRICE,
       d.GOODSTYPE, d.EXADD_MATER, d.MEMO, d.DELETED, d.CREATE_TIME, d.UPDATE_TIME, d.CREATE_BY, d.UPDATE_BY,
       CASE WHEN d.DTL_USEFLAG = '辅料' AND REGEXP_LIKE(d.APEX_GOODSNAME, '胶囊') THEN 'B'
            WHEN d.DTL_USEFLAG IN ('原料', '辅料') THEN 'C' ELSE NULL END AS FORMULA_TYPE
FROM T_COST_PINGGU_DTL d WHERE d.DTL_USEFLAG IN ('原料', '辅料') AND (d.DELETED = 0 OR d.DELETED IS NULL);

-- 包材明细视图
CREATE OR REPLACE VIEW V_COST_PINGGU_PACKAGE AS
SELECT d.DTLID AS ID, d.DOCID AS MASTER_ID, d.APEX_GOODSID, d.APEX_GOODSNAME, d.DTL_USEFLAG,
       d.SPEC, d.PER_HL, d.EXADD_MATER, d.PRICE, d.BATCH_QTY, d.COST_BATCH, d.SUQTY, d.APEX_FACTORYNAME,
       d.MEMO, d.DELETED, d.CREATE_TIME, d.UPDATE_TIME, d.CREATE_BY, d.UPDATE_BY,
       CASE WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '桶|说明书|小盒|标签|瓶|盖') THEN 'A'
            WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '硬片|铝箔|复合膜') THEN 'D'
            WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '大纸箱') THEN 'E'
            WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '托盘') THEN 'F' ELSE NULL END AS FORMULA_TYPE
FROM T_COST_PINGGU_DTL d WHERE d.DTL_USEFLAG IN ('非印字包材', '印字包材') AND (d.DELETED = 0 OR d.DELETED IS NULL);

-- 角色视图
CREATE OR REPLACE VIEW V_COST_ROLE AS
SELECT r.ID, r.ROLE_CODE, r.ROLE_NAME, r.DESCRIPTION FROM T_COST_ROLE r;

-- 用户角色视图
CREATE OR REPLACE VIEW V_COST_USER_ROLE AS
SELECT ur.ID, ur.USER_ID, u.USERNAME, u.REAL_NAME, ur.ROLE_ID
FROM T_COST_USER_ROLE ur LEFT JOIN T_COST_USER u ON ur.USER_ID = u.ID AND u.DELETED = 0;

-- 角色页面视图
CREATE OR REPLACE VIEW V_COST_ROLE_PAGE AS
SELECT rp.ID, rp.ROLE_ID, rp.PAGE_CODE, res.RESOURCE_NAME AS PAGE_NAME, rp.BUTTON_POLICY, rp.COLUMN_POLICY, rp.ROW_POLICY
FROM T_COST_ROLE_PAGE rp LEFT JOIN T_COST_RESOURCE res ON rp.PAGE_CODE = res.PAGE_CODE;


-- 资源权限视图
CREATE OR REPLACE VIEW V_COST_RESOURCE_PERMISSION AS
SELECT res.ID, res.PAGE_CODE, res.RESOURCE_NAME, res.RESOURCE_TYPE, res.IS_HARDCODED, res.ICON, res.ROUTE,
       res.PARENT_ID, res.SORT_ORDER, r.ID AS ROLE_ID, r.ROLE_CODE, r.ROLE_NAME, rp.ID AS ROLE_PAGE_ID,
       rp.BUTTON_POLICY, rp.COLUMN_POLICY, rp.ROW_POLICY,
       CASE WHEN rp.ID IS NOT NULL THEN 1 ELSE 0 END AS IS_AUTHORIZED
FROM T_COST_RESOURCE res CROSS JOIN T_COST_ROLE r
LEFT JOIN T_COST_ROLE_PAGE rp ON rp.PAGE_CODE = res.PAGE_CODE AND rp.ROLE_ID = r.ID
ORDER BY res.SORT_ORDER;

-- 按物料查产品视图
CREATE OR REPLACE VIEW V_COST_GOODS_BY_APEX AS
SELECT c.GOODSID AS P_GOODSID, c.GOODSNAME, c.GOODSTYPE, c.PACKTYPE, c.TRANPOSID, c.TRANPOSNAME,
       c.ZX_CUSTOMERID, c.CUSTOMNAME, c.ZONE, a.APEX_GOODSID AS GOODSID, 0 AS DELETED
FROM T_COST_PINGGU_DTL a, T_COST_PINGGU b, T_COST_GOODS_V c
WHERE a.DOCID = b.DOCID AND b.GOODSID = c.GOODSID;

-- 按物料查产品视图(带价格)
CREATE OR REPLACE VIEW V_COST_PGOODS_BY_MGOODS AS
SELECT a.apex_goodsid goodsid, a.apex_goodsname, a.dtl_useflag, b.factoryname, a.price, b.goodsno,
       d.goodsid pgoodsid, d.goodsno pgoodsno, d.goodsname, c.apex_pl, a.batch_qty, a.deleted
FROM T_COST_PINGGU_DTL a, t_cost_goods b, t_cost_pinggu c, t_cost_goods d
WHERE a.apex_goodsid = b.goodsid AND a.docid = c.docid AND c.goodsid = d.goodsid
  AND a.deleted = 0 AND b.deleted = 0 AND c.deleted = 0 AND d.deleted = 0;

-- =====================================================
-- 第五部分：创建存储过程
-- =====================================================

-- 同步客户数据存储过程
CREATE OR REPLACE PROCEDURE PROC_SYNC_CUSTOMER AS
BEGIN
    MERGE INTO T_COST_CUSTOMER t USING (SELECT CUSTOMID, CUSTOMNAME, ZONE FROM PUB_CUSTOMER@hyerp) s
    ON (t.CUSTOMID = s.CUSTOMID)
    WHEN MATCHED THEN UPDATE SET t.CUSTOMNAME = s.CUSTOMNAME, t.ZONE = s.ZONE,
                                 t.UPDATE_TIME = SYSTIMESTAMP, t.ISERP = 1, t.DELETED = 0
    WHEN NOT MATCHED THEN INSERT (CUSTOMID, CUSTOMNAME, ZONE, ISERP, DELETED, CREATE_BY, CREATE_TIME)
                          VALUES (s.CUSTOMID, s.CUSTOMNAME, s.ZONE, 1, 0, 'sync', SYSTIMESTAMP);
    MERGE INTO T_COST_TRANPOSER t USING (SELECT TRANPOSID, COMPANYID AS CUSTOMID, TRANPOSNAME FROM BMS_TR_POS_DEF@hyerp) s
    ON (t.TRANPOSID = s.TRANPOSID)
    WHEN MATCHED THEN UPDATE SET t.CUSTOMID = s.CUSTOMID, t.TRANPOSNAME = s.TRANPOSNAME,
                                 t.UPDATE_TIME = SYSTIMESTAMP, t.ISERP = 1, t.DELETED = 0
    WHEN NOT MATCHED THEN INSERT (TRANPOSID, CUSTOMID, TRANPOSNAME, ISERP, DELETED, CREATE_BY, CREATE_TIME)
                          VALUES (s.TRANPOSID, s.CUSTOMID, s.TRANPOSNAME, 1, 0, 'sync', SYSTIMESTAMP);
    COMMIT;
END;
/


-- 同步物料价格存储过程
CREATE OR REPLACE PROCEDURE PROC_SYNC_GOODS_PRICE AS
BEGIN
  MERGE INTO T_COST_GOODS_PRICE T
  USING (SELECT a.GOODSID, a.GOODSNAME, a.price AS NEW_PRICE, a.USEFLAG, a.goodstype, a.packtype, a.FACTORYNAME
         FROM pub_goods_v a WHERE a.USEFLAG NOT IN ('产成品','半成品')) S
  ON (T.GOODSID = S.GOODSID)
  WHEN MATCHED THEN UPDATE SET T.GOODSNAME = S.GOODSNAME, T.USEFLAG = S.USEFLAG, T.GOODSTYPE = S.goodstype,
       T.PACKTYPE = S.packtype, T.FACTORYNAME = S.FACTORYNAME, T.ISERP = 1, T.UPDATE_TIME = SYSTIMESTAMP,
       T.PRICE = CASE WHEN T.PRICE IS NULL OR T.UPDATE_BY IS NULL OR T.UPDATE_BY = 'system' THEN S.NEW_PRICE ELSE T.PRICE END,
       T.UPDATE_BY = CASE WHEN T.PRICE IS NULL OR T.UPDATE_BY IS NULL OR T.UPDATE_BY = 'system' THEN 'system' ELSE T.UPDATE_BY END
  WHEN NOT MATCHED THEN INSERT (GOODSID, GOODSNAME, PRICE, USEFLAG, GOODSTYPE, PACKTYPE, FACTORYNAME, ISERP, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
       VALUES (S.GOODSID, S.GOODSNAME, S.NEW_PRICE, S.USEFLAG, S.goodstype, S.packtype, S.FACTORYNAME, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system', 'system');
  COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

-- 同步WMS库存数据存储过程
CREATE OR REPLACE PROCEDURE PROC_SYNC_WMS_GOODS_QTY AS
BEGIN
    -- 清空旧数据（全量同步）
    DELETE FROM t_wms_goods_qty;

    -- 插入新数据    INSERT INTO t_wms_goods_qty (
        goodsownid,
        lotno,
        packname,
        goodsqty,
        oddtray,
        goodsname,
        goodsno,
        packsize,
        basepackname,
        validdate,
        createdate
    )
    SELECT
        goodsownid,
        lotno,
        packname,
        goodsqty,
        oddtray,
        goodsname,
        goodsno,
        packsize,
        basepackname,
        validdate,
        SYSDATE
    FROM t_wms_goods_qty_v@to_wms;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        -- 记录错误日志（可选）
        DBMS_OUTPUT.PUT_LINE('同步失败: ' || SQLERRM);
        RAISE;
END PROC_SYNC_WMS_GOODS_QTY;
/

-- 同步产品信息存储过程
CREATE OR REPLACE PROCEDURE SP_SYNC_COST_GOODS AS
BEGIN
    MERGE INTO T_COST_GOODS T
    USING (SELECT B.GOODSID, B.GOODSNO, B.GOODSNAME, C.LASTPRICE AS PRICE, C.LASTSUQTY AS SUQTY,
           (CASE WHEN B.ZX_WMS_GOODSCLASS IN (1, 12) AND B.GSPFLAG = 1 AND B.GOODSNO LIKE '%A%' THEN '原料'
                 WHEN B.ZX_WMS_GOODSCLASS IN (10) AND B.GSPFLAG = 1 THEN '产成品'
                 WHEN B.ZX_WMS_GOODSCLASS IN (7, 8, 9) AND B.GSPFLAG = 1 THEN '半成品'
                 WHEN B.ZX_WMS_GOODSCLASS IN (5, 13) AND B.GSPFLAG = 1 THEN '非印字包材'
                 WHEN B.ZX_WMS_GOODSCLASS IN (6) AND B.GSPFLAG = 1 THEN '印字包材'
                 WHEN B.ZX_WMS_GOODSCLASS IN (1, 2, 3, 4) AND B.GSPFLAG = 1 AND B.GOODSNO NOT LIKE '%A%' THEN '辅料' END) AS USEFLAG,
           B.FACTORYNAME, B.STANDARDTYPE, B.ZX_PL, B.ZX_MINIMUM, B.APPROVEDOCNO, E.BASEUNITQTY, B.ZX_CUSTOMERID,
           F.TARGETMARKET, B.HOLDERSNAME, B.GOODSTYPE, B.PACKTYPE, D.BOMID, C.LASTSUQTY AS LASTSUQTY2, B.TRANPOSID
           FROM PUB_GOODS_V@hyerp B, BMS_SU_SUPPLYGOODS_DOC@hyerp C, MPCS_PR_BOM_DOC@hyerp D, PUB_GOODS_UNIT_V@hyerp E, BMS_TR_POS_DEF@hyerp F
           WHERE B.GOODSID = C.GOODSID(+) AND B.GOODSID = D.PGOODSID(+) AND D.USESTATUS(+) = 1 AND B.USESTATUS = 1
             AND C.ENTRYID(+) = 1 AND B.GOODSID = E.GOODSID(+) AND E.GOODSDTLFLAG(+) = 1 AND E.BASEFLAG(+) <> 1
             AND B.GOODSID < 1000000 AND B.ZX_CUSTOMERID = F.COMPANYID(+) AND B.TRANPOSID = F.TRANPOSID(+)) S
    ON (T.GOODSID = S.GOODSID)
    WHEN MATCHED THEN UPDATE SET T.GOODSNO = S.GOODSNO, T.GOODSNAME = S.GOODSNAME, T.PRICE = S.PRICE, T.SUQTY = S.SUQTY,
         T.USEFLAG = S.USEFLAG, T.FACTORYNAME = S.FACTORYNAME, T.STANDARDTYPE = S.STANDARDTYPE, T.ZX_PL = S.ZX_PL,
         T.ZX_MINIMUM = S.ZX_MINIMUM, T.APPROVEDOCNO = S.APPROVEDOCNO, T.BASEUNITQTY = S.BASEUNITQTY, T.ZX_CUSTOMERID = S.ZX_CUSTOMERID,
         T.TARGETMARKET = S.TARGETMARKET, T.HOLDERSNAME = S.HOLDERSNAME, T.GOODSTYPE = S.GOODSTYPE, T.PACKTYPE = S.PACKTYPE,
         T.BOMID = S.BOMID, T.LASTSUQTY = S.LASTSUQTY2, T.TRANPOSID = S.TRANPOSID, T.ISERP = 1, T.UPDATE_TIME = SYSTIMESTAMP, T.UPDATE_BY = 'ERP_SYNC', T.DELETED = 0
    WHEN NOT MATCHED THEN INSERT (GOODSID, GOODSNO, GOODSNAME, PRICE, SUQTY, USEFLAG, FACTORYNAME, STANDARDTYPE, ZX_PL, ZX_MINIMUM, APPROVEDOCNO, BASEUNITQTY, ZX_CUSTOMERID, TARGETMARKET, HOLDERSNAME, ISERP, GOODSTYPE, PACKTYPE, BOMID, LASTSUQTY, TRANPOSID, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
         VALUES (S.GOODSID, S.GOODSNO, S.GOODSNAME, S.PRICE, S.SUQTY, S.USEFLAG, S.FACTORYNAME, S.STANDARDTYPE, S.ZX_PL, S.ZX_MINIMUM, S.APPROVEDOCNO, S.BASEUNITQTY, S.ZX_CUSTOMERID, S.TARGETMARKET, S.HOLDERSNAME, 1, S.GOODSTYPE, S.PACKTYPE, S.BOMID, S.LASTSUQTY2, S.TRANPOSID, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'ERP_SYNC', 'ERP_SYNC');
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/


-- 重置密码存储过程
CREATE OR REPLACE PROCEDURE P_RESET_PASSWORD(
    p_ids IN VARCHAR2, p_user_id IN NUMBER, p_result OUT NUMBER, p_message OUT VARCHAR2
) AS
    v_count NUMBER := 0; v_operator VARCHAR2(50);
    v_new_password VARCHAR2(100) := '$2a$10$igs26ZAhFQFArWFszhIrn.MSMheCLYW9ertSP5J53jrgjKRpFhdE.';
BEGIN
    BEGIN SELECT USERNAME INTO v_operator FROM T_COST_USER WHERE ID = p_user_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN v_operator := 'system'; END;
    UPDATE T_COST_USER SET PASSWORD = v_new_password, UPDATE_TIME = SYSDATE, UPDATE_BY = v_operator
    WHERE ID IN (SELECT TO_NUMBER(TRIM(REGEXP_SUBSTR(p_ids, '[^,]+', 1, LEVEL))) FROM DUAL CONNECT BY LEVEL <= REGEXP_COUNT(p_ids, ',') + 1);
    v_count := SQL%ROWCOUNT;
    IF v_count > 0 THEN p_result := 0; p_message := '已重置' || v_count || ' 个用户的密码为admin'; COMMIT;
    ELSE p_result := 1; p_message := '未找到要重置的用户'; END IF;
EXCEPTION WHEN OTHERS THEN ROLLBACK; p_result := 1; p_message := '重置密码失败: ' || SQLERRM;
END P_RESET_PASSWORD;
/

-- 备份评估表存储过程
CREATE OR REPLACE PROCEDURE sp_backup_pinggu_tables AS
BEGIN
  INSERT INTO t_cost_pinggu_his SELECT t.*, SYSDATE FROM t_cost_pinggu t;
  INSERT INTO t_cost_pinggu_dtl_his SELECT t.*, SYSDATE FROM t_cost_pinggu_dtl t;
  COMMIT;
END;
/

-- 评估主表计算存储过程(简化版)
CREATE OR REPLACE PROCEDURE p_pinggu_compute (p_docid IN NUMBER) IS
  v_apex_pl NUMBER; v_p_perpack NUMBER; v_yield NUMBER; v_out_price_rmb NUMBER; v_annual_qty NUMBER;
  v_total_fl NUMBER; v_total_bc NUMBER; v_total_yl NUMBER; v_total_cost NUMBER; v_cost_perqp NUMBER;
  v_salemoney NUMBER; v_jgf_batch NUMBER; v_jgf_perqp NUMBER; v_ml_perqp NUMBER;
  v_y_jg_re NUMBER; v_y_ml NUMBER; v_y_sale NUMBER; v_cost_perbox NUMBER; v_sum_yl NUMBER := 0; is_exists NUMBER;
BEGIN
  SELECT COUNT(1) INTO is_exists FROM t_cost_pinggu WHERE docid = p_docid;
  IF is_exists > 0 THEN
    SELECT apex_pl, p_perpack, yield, out_price_rmb, annual_qty, cost_perqp
    INTO v_apex_pl, v_p_perpack, v_yield, v_out_price_rmb, v_annual_qty, v_cost_perqp
    FROM t_cost_pinggu WHERE docid = p_docid;
    SELECT NVL(SUM(CASE WHEN dtl_useflag = '原料' THEN cost_batch ELSE 0 END), 0) INTO v_sum_yl FROM t_cost_pinggu_dtl WHERE docid = p_docid;
    IF v_sum_yl > 0 THEN
      SELECT NVL(SUM(CASE WHEN dtl_useflag = '原料' THEN cost_batch / 1.13 ELSE 0 END), 0),
             NVL(SUM(CASE WHEN dtl_useflag = '辅料' THEN cost_batch / 1.13 ELSE 0 END), 0),
             NVL(SUM(CASE WHEN dtl_useflag IN ('非印字包材', '印字包材') THEN cost_batch / 1.13 ELSE 0 END), 0)
      INTO v_total_yl, v_total_fl, v_total_bc FROM t_cost_pinggu_dtl WHERE docid = p_docid;
    ELSE
      SELECT NVL(SUM(CASE WHEN dtl_useflag = '原料' THEN cost_batch ELSE 0 END), 0),
             NVL(SUM(CASE WHEN dtl_useflag = '辅料' THEN cost_batch ELSE 0 END), 0),
             NVL(SUM(CASE WHEN dtl_useflag IN ('非印字包材', '印字包材') THEN cost_batch ELSE 0 END), 0)
      INTO v_total_yl, v_total_fl, v_total_bc FROM t_cost_pinggu_dtl WHERE docid = p_docid;
    END IF;
    v_total_cost := v_total_fl + v_total_bc + v_total_yl;
    v_salemoney := ROUND(NVL(v_out_price_rmb, 0) / NULLIF(v_p_perpack, 0) * NVL(v_apex_pl, 0) * (NVL(v_yield, 0) / 100), 2);
    v_jgf_batch := ROUND(NVL(v_salemoney, 0) - NVL(v_total_cost, 0), 2);
    v_cost_perbox := ROUND(NVL(v_total_cost, 0) / NULLIF(v_apex_pl, 0) * NVL(v_p_perpack, 0), 2);
    v_jgf_perqp := ROUND(NVL(v_jgf_batch, 0) / NULLIF(v_apex_pl, 0) * 1000, 2);
    v_ml_perqp := ROUND(NVL(v_jgf_perqp, 0) - NVL(v_cost_perqp, 0), 2);
    v_y_jg_re := ROUND(NVL(v_jgf_perqp, 0) / 1000 * NVL(v_annual_qty, 0), 2);
    v_y_ml := ROUND(NVL(v_ml_perqp, 0) / 1000 * NVL(v_annual_qty, 0), 2);
    v_y_sale := ROUND(NVL(v_salemoney, 0) / NULLIF(v_apex_pl, 0) * NVL(v_annual_qty, 0), 2);
    UPDATE t_cost_pinggu SET salemoney = v_salemoney, jgf_batch = v_jgf_batch, jgf_perqp = v_jgf_perqp,
           cost_perbox = v_cost_perbox, ml_perqp = v_ml_perqp, y_jg_re = v_y_jg_re, y_ml = v_y_ml, y_sale = v_y_sale,
           total_fl = v_total_fl, total_bc = v_total_bc, total_yl = v_total_yl, total_cost = v_total_cost
    WHERE docid = p_docid;
  END IF;
EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK; RAISE; WHEN OTHERS THEN ROLLBACK; RAISE;
END p_pinggu_compute;
/


-- 评估明细计算存储过程(简化版)
CREATE OR REPLACE PROCEDURE p_pinggu_dtl_compute(p_docid NUMBER, is_all_comp NUMBER) AS
  v_apex_pl NUMBER; v_dtl_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_dtl_count FROM t_cost_pinggu_dtl WHERE docid = p_docid;
  IF v_dtl_count = 0 THEN RETURN; END IF;
  BEGIN SELECT a.apex_pl INTO v_apex_pl FROM t_cost_pinggu a WHERE a.docid = p_docid;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN; END;
  IF is_all_comp = 0 THEN
    UPDATE t_cost_pinggu_dtl a SET a.per_hl = a.batch_qty / v_apex_pl * 1000000
    WHERE a.docid = p_docid AND a.dtl_useflag IN ('原料', '辅料');
    UPDATE t_cost_pinggu_dtl a SET a.per_hl = a.batch_qty / v_apex_pl * 1000000
    WHERE a.docid = p_docid AND a.dtl_useflag IN ('印字包材', '非印字包材') AND REGEXP_LIKE(a.apex_goodsname, '硬片|铝箔');
  END IF;
  UPDATE t_cost_pinggu_dtl a SET a.cost_batch = a.batch_qty * a.price WHERE a.docid = p_docid;
END;
/

-- 全量计算存储过程
CREATE OR REPLACE PROCEDURE p_pinggu_compute_all AS
BEGIN
  INSERT INTO t_cost_pinggu_compute_his SELECT a.*, SYSDATE compute_date FROM t_cost_pinggu a;
  INSERT INTO t_cost_pinggu_dtl_compute_his SELECT a.*, SYSDATE compute_date FROM t_cost_pinggu_dtl a;
  UPDATE t_cost_pinggu_dtl a SET a.price = (SELECT PRICE FROM t_cost_goods_price x WHERE x.GOODSID = a.apex_goodsid AND x.USEFLAG NOT IN ('产成品'));
  FOR i IN (SELECT DOCID FROM t_cost_pinggu) LOOP
    p_pinggu_dtl_compute(i.docid, 1);
    p_pinggu_compute(i.docid);
  END LOOP;
END;
/

-- BOM生成明细存储过程
CREATE OR REPLACE PROCEDURE P_COST_BOM_INSERT (p_docid IN t_cost_pinggu.docid%TYPE) AS
    v_goodsid VARCHAR2(20); v_raw_goodsid t_cost_pinggu.goodsid%TYPE;
BEGIN
    SELECT goodsid INTO v_raw_goodsid FROM t_cost_pinggu WHERE docid = p_docid;
    IF v_raw_goodsid IS NULL THEN RAISE_APPLICATION_ERROR(-20003, '该产品在ERP中不存在BOM'); END IF;
    v_goodsid := '-' || v_raw_goodsid || '-';
    DELETE FROM t_cost_pinggu_dtl WHERE docid = p_docid;
    INSERT INTO t_cost_pinggu_dtl (dtlid, docid, apex_goodsid, spec, batch_qty, price, BASE_PRICE, modifydate, cost_batch, DTL_USEFLAG, APEX_GOODSNAME, APEX_FACTORYNAME, GOODSTYPE, zx_source)
    SELECT SEQ_COST_PINGGU_DTL.NEXTVAL, p_docid, v.goodsid, v.standardtype, v.useqty, f.PRICE, f.PRICE, SYSDATE, NVL(v.useqty,0)*NVL(f.price,0),
           DECODE(v.useflag,4,'原料',2,'辅料',3,'非印字包材',5,'印字包材'), f.GOODSNAME, f.FACTORYNAME, f.GOODSTYPE, 'ERP'
    FROM t_cost_bom_goods_tree_v v, PUB_GOODS_V f WHERE v.treeid LIKE v_goodsid||'%' AND v.pid<>'-1' AND v.USEFLAG NOT IN (0,1) AND v.goodsid=f.goodsid(+);
    p_pinggu_dtl_compute(p_docid, 0);
    p_pinggu_compute(p_docid);
    COMMIT;
END P_COST_BOM_INSERT;
/

COMMIT;

-- =====================================================
-- 数据库初始化脚本结束
-- =====================================================
