-- =====================================================
-- 成本管理系统数据库初始化脚本（精简版）
-- 用途：清理当前用户所有对象，建立元数据表、基础数据表和权限表
-- =====================================================

-- =====================================================
-- 清理当前用户下所有对象
-- =====================================================

-- 清理 T_COST 开头的视图
BEGIN
  FOR v IN (SELECT view_name FROM user_views WHERE view_name LIKE 'T_COST_%' OR view_name LIKE 'V_COST_%') LOOP
    EXECUTE IMMEDIATE 'DROP VIEW ' || v.view_name;
  END LOOP;
END;
/

-- 清理 T_COST 开头的表
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name LIKE 'T_COST_%') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- 清理 SEQ_COST 开头的序列
BEGIN
  FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SEQ_COST_%') LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

-- =====================================================
-- A1. 元数据模块表结构
-- =====================================================

CREATE TABLE T_COST_TABLE_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_CODE          VARCHAR2(64)    NOT NULL UNIQUE,
    TABLE_NAME          VARCHAR2(128)   NOT NULL,
    QUERY_VIEW          VARCHAR2(64),
    TARGET_TABLE        VARCHAR2(64)    NOT NULL,
    SEQUENCE_NAME       VARCHAR2(64),
    PK_COLUMN           VARCHAR2(64)    DEFAULT 'ID',
    PARENT_TABLE_CODE   VARCHAR2(64),
    PARENT_FK_COLUMN    VARCHAR2(64),
    AUDIT_ENABLED       NUMBER(1)       DEFAULT 0,
    VALIDATION_RULES    CLOB,
    DESCRIPTION         VARCHAR2(500),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_TABLE_METADATA START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_COLUMN_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_METADATA_ID   NUMBER(19)      NOT NULL,
    FIELD_NAME          VARCHAR2(64)    NOT NULL,
    COLUMN_NAME         VARCHAR2(64)    NOT NULL,
    QUERY_COLUMN        VARCHAR2(128),
    TARGET_COLUMN       VARCHAR2(64),
    HEADER_TEXT         VARCHAR2(128)   NOT NULL,
    DATA_TYPE           VARCHAR2(32)    DEFAULT 'text',
    DISPLAY_ORDER       NUMBER(5)       DEFAULT 0,
    SORTABLE            NUMBER(1)       DEFAULT 1,
    FILTERABLE          NUMBER(1)       DEFAULT 1,
    IS_VIRTUAL          NUMBER(1)       DEFAULT 0,
    DICT_TYPE           VARCHAR2(64),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_COLUMN_TABLE FOREIGN KEY (TABLE_METADATA_ID) REFERENCES T_COST_TABLE_METADATA(ID)
);
CREATE SEQUENCE SEQ_COST_COLUMN_METADATA START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_COLUMN_TABLE_ID ON T_COST_COLUMN_METADATA(TABLE_METADATA_ID);

-- 页面规则表（计算/验证/弹窗/列覆盖/聚合）
CREATE TABLE T_COST_PAGE_RULE (
    ID              NUMBER(19)      PRIMARY KEY,
    PAGE_CODE       VARCHAR2(64)    NOT NULL,
    COMPONENT_KEY   VARCHAR2(64)    NOT NULL,
    RULE_TYPE       VARCHAR2(32)    NOT NULL,
    RULES           CLOB            NOT NULL,
    SORT_ORDER      NUMBER(5)       DEFAULT 0,
    DESCRIPTION     VARCHAR2(200),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_PAGE_RULE START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_PAGE_RULE_PAGE ON T_COST_PAGE_RULE(PAGE_CODE);

CREATE TABLE T_COST_LOOKUP_CONFIG (
    ID                  NUMBER(19)      PRIMARY KEY,
    LOOKUP_CODE         VARCHAR2(64)    NOT NULL UNIQUE,
    LOOKUP_NAME         VARCHAR2(128)   NOT NULL,
    DATA_SOURCE         VARCHAR2(200)   NOT NULL,
    DISPLAY_COLUMNS     CLOB,
    SEARCH_COLUMNS      CLOB,
    VALUE_FIELD         VARCHAR2(64)    NOT NULL,
    LABEL_FIELD         VARCHAR2(64)    NOT NULL,
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_LOOKUP_CONFIG START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_PAGE_COMPONENT (
    ID                  NUMBER(19)      PRIMARY KEY,
    PAGE_CODE           VARCHAR2(64)    NOT NULL,
    COMPONENT_KEY       VARCHAR2(64)    NOT NULL,
    COMPONENT_TYPE      VARCHAR2(32)    NOT NULL,
    PARENT_KEY          VARCHAR2(64),
    COMPONENT_CONFIG    CLOB,
    REF_TABLE_CODE      VARCHAR2(64),
    SLOT_NAME           VARCHAR2(32),
    SORT_ORDER          NUMBER(5)       DEFAULT 0,
    DELETED             NUMBER(1)       DEFAULT 0,
    DESCRIPTION         VARCHAR2(200),
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_PAGE_COMPONENT START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_PAGE_COMP_PAGE ON T_COST_PAGE_COMPONENT(PAGE_CODE);
CREATE UNIQUE INDEX UK_PAGE_COMP_KEY ON T_COST_PAGE_COMPONENT(PAGE_CODE, COMPONENT_KEY);

CREATE TABLE T_COST_DICTIONARY_TYPE (
    ID                  NUMBER(19)      PRIMARY KEY,
    TYPE_CODE           VARCHAR2(64)    NOT NULL UNIQUE,
    TYPE_NAME           VARCHAR2(128)   NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_DICT_TYPE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_DICTIONARY_ITEM (
    ID                  NUMBER(19)      PRIMARY KEY,
    TYPE_ID             NUMBER(19)      NOT NULL,
    ITEM_CODE           VARCHAR2(64)    NOT NULL,
    ITEM_NAME           VARCHAR2(128)   NOT NULL,
    ITEM_VALUE          VARCHAR2(200),
    SORT_ORDER          NUMBER(5)       DEFAULT 0,
    EXTRA_CONFIG        VARCHAR2(1000),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_DICT_ITEM_TYPE FOREIGN KEY (TYPE_ID) REFERENCES T_COST_DICTIONARY_TYPE(ID)
);
CREATE SEQUENCE SEQ_COST_DICT_ITEM START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DICT_ITEM_TYPE ON T_COST_DICTIONARY_ITEM(TYPE_ID);

COMMIT;

-- =====================================================
-- A2. 权限模块表结构
-- =====================================================

CREATE TABLE T_COST_DEPARTMENT (
    ID              NUMBER(19) PRIMARY KEY,
    DEPT_CODE       VARCHAR2(64) NOT NULL UNIQUE,
    DEPT_NAME       VARCHAR2(128) NOT NULL,
    PARENT_ID       NUMBER(19),
    SORT_ORDER      NUMBER(5) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_DEPARTMENT START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_USER (
    ID              NUMBER(19) PRIMARY KEY,
    USERNAME        VARCHAR2(64) NOT NULL UNIQUE,
    PASSWORD        VARCHAR2(256) NOT NULL,
    REAL_NAME       VARCHAR2(128),
    EMAIL           VARCHAR2(128),
    PHONE           VARCHAR2(32),
    DEPARTMENT_ID   NUMBER(19),
    STATUS          VARCHAR2(32) DEFAULT 'ACTIVE',
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_ROLE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_CODE       VARCHAR2(64) NOT NULL UNIQUE,
    ROLE_NAME       VARCHAR2(128) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_ROLE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_USER_ROLE (
    ID              NUMBER(19) PRIMARY KEY,
    USER_ID         NUMBER(19) NOT NULL,
    ROLE_ID         NUMBER(19) NOT NULL,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER_ROLE START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_USER_ROLE ON T_COST_USER_ROLE(USER_ID, ROLE_ID);

CREATE TABLE T_COST_ROLE_PAGE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_ID         NUMBER(19) NOT NULL,
    PAGE_CODE       VARCHAR2(64) NOT NULL,
    BUTTON_POLICY   VARCHAR2(1000),
    COLUMN_POLICY   CLOB,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_ROLE_PAGE START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_ROLE_PAGE ON T_COST_ROLE_PAGE(ROLE_ID, PAGE_CODE);

CREATE TABLE T_COST_ROLE_PAGE_DATA_RULE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_PAGE_ID    NUMBER(19) NOT NULL,
    RULE_TYPE       VARCHAR2(32) NOT NULL,
    RULE_CONFIG     CLOB NOT NULL,
    PRIORITY        NUMBER(3) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_DATA_RULE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_USER_GRID_CONFIG (
    ID              NUMBER(19) PRIMARY KEY,
    USER_ID         NUMBER(19) NOT NULL,
    PAGE_CODE       VARCHAR2(64) NOT NULL,
    GRID_KEY        VARCHAR2(64) NOT NULL,
    CONFIG_DATA     CLOB,
    DELETED         NUMBER(1) DEFAULT 0,
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER_GRID START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_USER_GRID_CONF ON T_COST_USER_GRID_CONFIG(USER_ID, PAGE_CODE, GRID_KEY);

-- 自定义导出配置主表
CREATE TABLE T_COST_EXPORT_CONFIG (
    ID                  NUMBER(19) PRIMARY KEY,
    EXPORT_CODE         VARCHAR2(100) NOT NULL,
    EXPORT_NAME         VARCHAR2(200) NOT NULL,
    PAGE_CODE           VARCHAR2(100) NOT NULL,
    MASTER_SQL          CLOB NOT NULL,
    MASTER_TABLE_ALIAS  VARCHAR2(50),
    PK_COLUMN           VARCHAR2(100),
    PAGE_VIEW_ALIAS     VARCHAR2(50) DEFAULT 'p',
    PAGE_FK_COLUMN      VARCHAR2(100),
    MASTER_LINK_COLUMN  VARCHAR2(100),
    COLUMNS             CLOB,
    MASTER_SHEET_NAME   VARCHAR2(100) DEFAULT 'master',
    DISPLAY_ORDER       NUMBER(5) DEFAULT 0,
    DELETED             NUMBER(1) DEFAULT 0,
    CREATE_BY           VARCHAR2(64),
    CREATE_TIME         TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY           VARCHAR2(64),
    UPDATE_TIME         TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_EXPORT_CONFIG START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_EXPORT_CONFIG_CODE ON T_COST_EXPORT_CONFIG(EXPORT_CODE);
CREATE INDEX IDX_EXPORT_CONFIG_PAGE ON T_COST_EXPORT_CONFIG(PAGE_CODE);

-- 自定义导出配置从表
CREATE TABLE T_COST_EXPORT_CONFIG_DETAIL (
    ID                  NUMBER(19) PRIMARY KEY,
    EXPORT_CONFIG_ID    NUMBER(19) NOT NULL,
    TAB_KEY             VARCHAR2(100),
    SHEET_NAME          VARCHAR2(100),
    DETAIL_SQL          CLOB NOT NULL,
    MASTER_TABLE_ALIAS  VARCHAR2(50),
    DETAIL_TABLE_ALIAS  VARCHAR2(50),
    DETAIL_LINK_COLUMN  VARCHAR2(100),
    COLUMNS             CLOB,
    DISPLAY_ORDER       NUMBER(5) DEFAULT 0,
    CONSTRAINT FK_EXPORT_DTL_CONFIG FOREIGN KEY (EXPORT_CONFIG_ID) REFERENCES T_COST_EXPORT_CONFIG(ID)
);
CREATE SEQUENCE SEQ_COST_EXPORT_CONFIG_DTL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_EXPORT_DTL_CONFIG ON T_COST_EXPORT_CONFIG_DETAIL(EXPORT_CONFIG_ID);

CREATE TABLE T_COST_RESOURCE (
    ID              NUMBER(19) PRIMARY KEY,
    RESOURCE_CODE   VARCHAR2(64) NOT NULL UNIQUE,
    RESOURCE_NAME   VARCHAR2(128) NOT NULL,
    RESOURCE_TYPE   VARCHAR2(20) NOT NULL,
    PAGE_CODE       VARCHAR2(64),
    ICON            VARCHAR2(64),
    ROUTE           VARCHAR2(128),
    PARENT_ID       NUMBER(19),
    SORT_ORDER      NUMBER(5) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_RESOURCE START WITH 1 INCREMENT BY 1;

COMMIT;

-- =====================================================
-- A3. 日志模块表结构
-- =====================================================

CREATE TABLE T_COST_OPERATION_LOG (
    ID              NUMBER(19)      PRIMARY KEY,
    USER_ID         NUMBER(19),
    USER_NAME       VARCHAR2(64),
    OPERATION_TYPE  VARCHAR2(32)    NOT NULL,
    TABLE_CODE      VARCHAR2(64),
    RECORD_ID       NUMBER(19),
    RECORD_DESC     VARCHAR2(256),
    TOTAL_SQL_COUNT NUMBER(10)      DEFAULT 0,
    TOTAL_COST_MS   NUMBER(10)      DEFAULT 0,
    STATUS          VARCHAR2(16)    DEFAULT 'SUCCESS',
    ERROR_MSG       VARCHAR2(1000),
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_OPERATION_LOG START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_OPERATION_LOG_USER ON T_COST_OPERATION_LOG(USER_ID);
CREATE INDEX IDX_OPERATION_LOG_TIME ON T_COST_OPERATION_LOG(CREATE_TIME);

CREATE TABLE T_COST_OPERATION_LOG_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    LOG_ID          NUMBER(19)      NOT NULL,
    SEQ_NO          NUMBER(5)       NOT NULL,
    SQL_TYPE        VARCHAR2(16),
    SQL_TEXT        CLOB,
    COST_MS         NUMBER(10)      DEFAULT 0,
    AFFECTED_ROWS   NUMBER(10),
    STATUS          VARCHAR2(16)    DEFAULT 'SUCCESS',
    ERROR_MSG       VARCHAR2(1000),
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LOG_DETAIL_LOG FOREIGN KEY (LOG_ID) REFERENCES T_COST_OPERATION_LOG(ID)
);
CREATE SEQUENCE SEQ_COST_OPERATION_LOG_DETAIL START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_AUDIT_LOG (
    ID              NUMBER(19)      PRIMARY KEY,
    USER_NAME       VARCHAR2(100),
    OPERATION_TIME  TIMESTAMP       DEFAULT SYSTIMESTAMP,
    PAGE_CODE       VARCHAR2(100),
    TABLE_CODE      VARCHAR2(100),
    TABLE_NAME      VARCHAR2(200),
    RECORD_ID       NUMBER(19),
    OPERATION_TYPE  VARCHAR2(20),
    FIELD_CHANGES   CLOB,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_AUDIT_LOG START WITH 1 INCREMENT BY 1;

COMMIT;

-- =====================================================
-- 初始化完成
-- =====================================================
