-- 业务审计日志表（用户可见）
-- 只记录用户手动修改的字段，不记录级联计算

CREATE TABLE T_COST_AUDIT_LOG (
    ID NUMBER(19) PRIMARY KEY,
    USER_NAME VARCHAR2(100),                    -- 操作用户
    OPERATION_TIME TIMESTAMP DEFAULT SYSTIMESTAMP, -- 操作时间
    PAGE_CODE VARCHAR2(100),                    -- 页面编码
    TABLE_CODE VARCHAR2(100),                   -- 表编码
    TABLE_NAME VARCHAR2(200),                   -- 表中文名
    RECORD_ID NUMBER(19),                       -- 记录ID
    OPERATION_TYPE VARCHAR2(20),                -- INSERT/UPDATE/DELETE
    FIELD_CHANGES CLOB,                         -- JSON: [{field, fieldName, oldValue, newValue}]
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE SEQ_COST_AUDIT_LOG START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_AUDIT_LOG_TIME ON T_COST_AUDIT_LOG(OPERATION_TIME);
CREATE INDEX IDX_AUDIT_LOG_USER ON T_COST_AUDIT_LOG(USER_NAME);
CREATE INDEX IDX_AUDIT_LOG_TABLE ON T_COST_AUDIT_LOG(TABLE_CODE);

COMMENT ON TABLE T_COST_AUDIT_LOG IS '业务审计日志（用户可见）';
COMMENT ON COLUMN T_COST_AUDIT_LOG.FIELD_CHANGES IS '字段变更JSON，只记录用户手动修改';
