-- 修复成本评估主键字段名：docid -> id
-- 前端统一用 id 作为主键字段名

-- 主表主键
UPDATE T_COST_COLUMN_METADATA 
SET FIELD_NAME = 'id'
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPinggu')
  AND COLUMN_NAME = 'DOCID';

-- 明细表主键
UPDATE T_COST_COLUMN_METADATA 
SET FIELD_NAME = 'id'
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguDtl')
  AND COLUMN_NAME = 'DTLID';

-- 明细表外键
UPDATE T_COST_COLUMN_METADATA 
SET FIELD_NAME = 'masterId'
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguDtl')
  AND COLUMN_NAME = 'DOCID';

COMMIT;
