-- =====================================================
-- 物料基础数据表 + Lookup 配置
-- =====================================================

-- 删除已有对象
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_MATERIAL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_MATERIAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================================================
-- 1. 物料基础数据表
-- =====================================================
CREATE TABLE T_COST_MATERIAL (
    ID              NUMBER(19)      PRIMARY KEY,
    MATERIAL_CODE   VARCHAR2(32)    NOT NULL UNIQUE,
    MATERIAL_NAME   VARCHAR2(128)   NOT NULL,
    USE_FLAG        VARCHAR2(32)    NOT NULL,       -- 物料类型：原料/辅料/包材
    PER_HL          NUMBER(18,6)    DEFAULT 0,      -- 百万片用量
    PRICE           NUMBER(18,4)    DEFAULT 0,      -- 单价
    UNIT            VARCHAR2(32),                   -- 单位
    SPEC            VARCHAR2(64),                   -- 规格
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_MATERIAL START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 2. 物料表元数据
-- =====================================================
DECLARE
    v_material_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_material_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_material_id, 'CostMaterial', '物料基础数据', 'T_COST_MATERIAL', 'T_COST_MATERIAL', 'SEQ_COST_MATERIAL', 'ID', 'system');
    
    -- 列元数据
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'id', 'ID', 'ID', 'number', 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'materialCode', 'MATERIAL_CODE', '物料编码', 'text', 1, 1, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'materialName', 'MATERIAL_NAME', '物料名称', 'text', 2, 1, 1, 150, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'useFlag', 'USE_FLAG', '物料类型', 'text', 3, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'perHl', 'PER_HL', '百万片用量', 'number', 4, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'price', 'PRICE', '单价', 'number', 5, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'unit', 'UNIT', '单位', 'text', 6, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'spec', 'SPEC', '规格', 'text', 7, 1, 100, 'system');
    
    COMMIT;
END;
/

-- =====================================================
-- 3. 物料测试数据
-- =====================================================
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL001', '阿莫西林原料', '原料', 125.5, 280, 'kg', '医药级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL002', '淀粉', '原料', 45.2, 15, 'kg', '食品级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL003', '头孢克肟原料', '原料', 200, 450, 'kg', '医药级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL001', '空心胶囊', '辅料', 1050, 0.035, '粒', '0号', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL002', '硬脂酸镁', '辅料', 2.5, 45, 'kg', '医药级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL003', '微晶纤维素', '辅料', 80, 25, 'kg', '医药级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC001', '铝塑板', '包材', 0, 0.12, '张', '10粒/板', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC002', '纸盒', '包材', 0, 0.35, '个', '2板/盒', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC003', '说明书', '包材', 0, 0.05, '张', 'A4', 'system');

COMMIT;

-- =====================================================
-- 4. 更新 CostEvalDetail 的 materialName 列，添加 Lookup 配置
-- =====================================================
UPDATE T_COST_COLUMN_METADATA 
SET RULES_CONFIG = '{"lookup":{"tableCode":"CostMaterial","displayField":"materialName","title":"选择物料","mapping":{"materialName":"materialName","perHl":"perHl","price":"price"}}}'
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostEvalDetail')
AND FIELD_NAME = 'materialName';

COMMIT;
