-- =============================================
-- 元数据表结构 - Phase 1
-- 先删除再创建
-- =============================================

-- 删除已有对象
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_COLUMN_METADATA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_TABLE_METADATA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_DEMO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_TABLE_METADATA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_COLUMN_METADATA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_DEMO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1. 表元数据
CREATE TABLE T_COST_TABLE_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_CODE          VARCHAR2(64)    NOT NULL UNIQUE,
    TABLE_NAME          VARCHAR2(128)   NOT NULL,
    QUERY_VIEW          VARCHAR2(64),
    TARGET_TABLE        VARCHAR2(64)    NOT NULL,
    SEQUENCE_NAME       VARCHAR2(64),
    PK_COLUMN           VARCHAR2(64)    DEFAULT 'ID',
    PARENT_TABLE_CODE   VARCHAR2(64),                      -- 父表编码（从表才有）
    PARENT_FK_COLUMN    VARCHAR2(64),                      -- 关联父表的外键列名
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);

CREATE SEQUENCE SEQ_COST_TABLE_METADATA START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE T_COST_TABLE_METADATA IS '表元数据';
COMMENT ON COLUMN T_COST_TABLE_METADATA.TABLE_CODE IS '表编码，大驼峰命名';
COMMENT ON COLUMN T_COST_TABLE_METADATA.QUERY_VIEW IS '查询用的视图或表名';
COMMENT ON COLUMN T_COST_TABLE_METADATA.TARGET_TABLE IS '增删改操作的目标物理表';
COMMENT ON COLUMN T_COST_TABLE_METADATA.PARENT_TABLE_CODE IS '父表编码，从表才有值';
COMMENT ON COLUMN T_COST_TABLE_METADATA.PARENT_FK_COLUMN IS '关联父表的外键列名';

-- 2. 列元数据
CREATE TABLE T_COST_COLUMN_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_METADATA_ID   NUMBER(19)      NOT NULL,
    FIELD_NAME          VARCHAR2(64)    NOT NULL,
    COLUMN_NAME         VARCHAR2(64)    NOT NULL,
    QUERY_COLUMN        VARCHAR2(128),
    TARGET_COLUMN       VARCHAR2(64),
    HEADER_TEXT         VARCHAR2(128)   NOT NULL,
    DATA_TYPE           VARCHAR2(32)    DEFAULT 'text',
    DISPLAY_ORDER       NUMBER(5)       DEFAULT 0,
    WIDTH               NUMBER(5)       DEFAULT 120,
    VISIBLE             NUMBER(1)       DEFAULT 1,
    EDITABLE            NUMBER(1)       DEFAULT 1,
    REQUIRED            NUMBER(1)       DEFAULT 0,
    SEARCHABLE          NUMBER(1)       DEFAULT 0,
    SORTABLE            NUMBER(1)       DEFAULT 1,
    DICT_TYPE           VARCHAR2(64),
    LOOKUP_CODE         VARCHAR2(64),
    DEFAULT_VALUE       VARCHAR2(256),
    RULES_CONFIG        CLOB,
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_COLUMN_TABLE FOREIGN KEY (TABLE_METADATA_ID) REFERENCES T_COST_TABLE_METADATA(ID)
);

CREATE SEQUENCE SEQ_COST_COLUMN_METADATA START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_COLUMN_TABLE_ID ON T_COST_COLUMN_METADATA(TABLE_METADATA_ID);

COMMENT ON TABLE T_COST_COLUMN_METADATA IS '列元数据';
COMMENT ON COLUMN T_COST_COLUMN_METADATA.FIELD_NAME IS '前端字段名，小驼峰';
COMMENT ON COLUMN T_COST_COLUMN_METADATA.COLUMN_NAME IS '数据库列名，大写下划线（兼容旧逻辑）';
COMMENT ON COLUMN T_COST_COLUMN_METADATA.QUERY_COLUMN IS '查询时的列表达式，支持别名，如 M.CREATE_DATE AS MASTER_CREATE_DATE';
COMMENT ON COLUMN T_COST_COLUMN_METADATA.TARGET_COLUMN IS '保存时的目标列名';
COMMENT ON COLUMN T_COST_COLUMN_METADATA.DATA_TYPE IS '数据类型：text/number/date/datetime/select/lookup';

-- =============================================
-- 示例业务表
-- =============================================
CREATE TABLE T_COST_DEMO (
    ID              NUMBER(19)      PRIMARY KEY,
    CODE            VARCHAR2(64)    NOT NULL,
    NAME            VARCHAR2(128)   NOT NULL,
    AMOUNT          NUMBER(18,2),
    COST_DATE       DATE,
    STATUS          VARCHAR2(32)    DEFAULT 'DRAFT',
    REMARK          VARCHAR2(512),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);

CREATE SEQUENCE SEQ_COST_DEMO START WITH 1 INCREMENT BY 1;

-- =============================================
-- 插入示例元数据
-- =============================================
DECLARE
    v_table_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_table_id FROM DUAL;
    
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN)
    VALUES (v_table_id, 'CostDemo', '成本示例表', 'T_COST_DEMO', 'T_COST_DEMO', 'SEQ_COST_DEMO', 'ID');
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_table_id, 'id', 'ID', 'ID', 'ID', 'ID', 'number', 0, 0, 0, 0);
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_table_id, 'code', 'CODE', 'CODE', 'CODE', '编码', 'text', 1, 1, 1, 1);
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_table_id, 'name', 'NAME', 'NAME', 'NAME', '名称', 'text', 2, 1, 1, 1);
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_table_id, 'amount', 'AMOUNT', 'AMOUNT', 'AMOUNT', '金额', 'number', 3, 1, 0, 0);
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_table_id, 'costDate', 'COST_DATE', 'COST_DATE', 'COST_DATE', '成本日期', 'date', 4, 1, 0, 1);
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_table_id, 'status', 'STATUS', 'STATUS', 'STATUS', '状态', 'select', 5, 1, 0, 1);
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_table_id, 'remark', 'REMARK', 'REMARK', 'REMARK', '备注', 'text', 6, 1, 0, 0);
    
    COMMIT;
END;
/
