-- =====================================================
-- 元数据模块表结构
-- =====================================================

-- 删除已有对象
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_COLUMN_METADATA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_TABLE_METADATA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_LOOKUP_CONFIG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_PAGE_COMPONENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_DICTIONARY_ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_DICTIONARY_TYPE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_TABLE_METADATA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_COLUMN_METADATA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_LOOKUP_CONFIG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_PAGE_COMPONENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_DICT_TYPE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_DICT_ITEM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================================================
-- 1. 表元数据
-- =====================================================
CREATE TABLE T_COST_TABLE_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_CODE          VARCHAR2(64)    NOT NULL UNIQUE,
    TABLE_NAME          VARCHAR2(128)   NOT NULL,
    QUERY_VIEW          VARCHAR2(64),
    TARGET_TABLE        VARCHAR2(64)    NOT NULL,
    SEQUENCE_NAME       VARCHAR2(64),
    PK_COLUMN           VARCHAR2(64)    DEFAULT 'ID',
    PARENT_TABLE_CODE   VARCHAR2(64),
    PARENT_FK_COLUMN    VARCHAR2(64),
    AUDIT_ENABLED       NUMBER(1)       DEFAULT 0,
    VALIDATION_RULES    CLOB,
    DESCRIPTION         VARCHAR2(500),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_TABLE_METADATA START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 2. 列元数据
-- =====================================================
CREATE TABLE T_COST_COLUMN_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_METADATA_ID   NUMBER(19)      NOT NULL,
    FIELD_NAME          VARCHAR2(64)    NOT NULL,
    COLUMN_NAME         VARCHAR2(64)    NOT NULL,
    QUERY_COLUMN        VARCHAR2(128),
    TARGET_COLUMN       VARCHAR2(64),
    HEADER_TEXT         VARCHAR2(128)   NOT NULL,
    DATA_TYPE           VARCHAR2(32)    DEFAULT 'text',
    DISPLAY_ORDER       NUMBER(5)       DEFAULT 0,
    WIDTH               NUMBER(5)       DEFAULT 120,
    VISIBLE             NUMBER(1)       DEFAULT 1,
    EDITABLE            NUMBER(1)       DEFAULT 1,
    REQUIRED            NUMBER(1)       DEFAULT 0,
    SEARCHABLE          NUMBER(1)       DEFAULT 0,
    SORTABLE            NUMBER(1)       DEFAULT 1,
    FILTERABLE          NUMBER(1)       DEFAULT 1,
    IS_VIRTUAL          NUMBER(1)       DEFAULT 0,
    DICT_TYPE           VARCHAR2(64),
    LOOKUP_CONFIG_ID    NUMBER(19),
    DEFAULT_VALUE       VARCHAR2(256),
    RULES_CONFIG        CLOB,
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_COLUMN_TABLE FOREIGN KEY (TABLE_METADATA_ID) REFERENCES T_COST_TABLE_METADATA(ID)
);
CREATE SEQUENCE SEQ_COST_COLUMN_METADATA START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_COLUMN_TABLE_ID ON T_COST_COLUMN_METADATA(TABLE_METADATA_ID);

-- =====================================================
-- 3. 弹窗选择器配置
-- =====================================================
CREATE TABLE T_COST_LOOKUP_CONFIG (
    ID                  NUMBER(19)      PRIMARY KEY,
    LOOKUP_CODE         VARCHAR2(64)    NOT NULL UNIQUE,
    LOOKUP_NAME         VARCHAR2(128)   NOT NULL,
    DATA_SOURCE         VARCHAR2(200)   NOT NULL,
    DISPLAY_COLUMNS     CLOB,
    SEARCH_COLUMNS      CLOB,
    VALUE_FIELD         VARCHAR2(64)    NOT NULL,
    LABEL_FIELD         VARCHAR2(64)    NOT NULL,
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_LOOKUP_CONFIG START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 4. 页面组件树
-- =====================================================
CREATE TABLE T_COST_PAGE_COMPONENT (
    ID                  NUMBER(19)      PRIMARY KEY,
    PAGE_CODE           VARCHAR2(64)    NOT NULL,
    COMPONENT_KEY       VARCHAR2(64)    NOT NULL,
    COMPONENT_TYPE      VARCHAR2(32)    NOT NULL,
    PARENT_KEY          VARCHAR2(64),
    COMPONENT_CONFIG    CLOB,
    REF_TABLE_CODE      VARCHAR2(64),
    SLOT_NAME           VARCHAR2(32),
    SORT_ORDER          NUMBER(5)       DEFAULT 0,
    DELETED             NUMBER(1)       DEFAULT 0,
    DESCRIPTION         VARCHAR2(200),
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_PAGE_COMPONENT START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_PAGE_COMP_PAGE ON T_COST_PAGE_COMPONENT(PAGE_CODE);
CREATE UNIQUE INDEX UK_PAGE_COMP_KEY ON T_COST_PAGE_COMPONENT(PAGE_CODE, COMPONENT_KEY);

-- =====================================================
-- 5. 字典类型
-- =====================================================
CREATE TABLE T_COST_DICTIONARY_TYPE (
    ID                  NUMBER(19)      PRIMARY KEY,
    TYPE_CODE           VARCHAR2(64)    NOT NULL UNIQUE,
    TYPE_NAME           VARCHAR2(128)   NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_DICT_TYPE START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 6. 字典项
-- =====================================================
CREATE TABLE T_COST_DICTIONARY_ITEM (
    ID                  NUMBER(19)      PRIMARY KEY,
    TYPE_ID             NUMBER(19)      NOT NULL,
    ITEM_CODE           VARCHAR2(64)    NOT NULL,
    ITEM_NAME           VARCHAR2(128)   NOT NULL,
    ITEM_VALUE          VARCHAR2(200),
    SORT_ORDER          NUMBER(5)       DEFAULT 0,
    EXTRA_CONFIG        VARCHAR2(1000),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_DICT_ITEM_TYPE FOREIGN KEY (TYPE_ID) REFERENCES T_COST_DICTIONARY_TYPE(ID)
);
CREATE SEQUENCE SEQ_COST_DICT_ITEM START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DICT_ITEM_TYPE ON T_COST_DICTIONARY_ITEM(TYPE_ID);

COMMIT;
