-- =============================================
-- 元数据表结构 - Phase 1
-- =============================================

-- 1. 表元数据
CREATE TABLE T_COST_TABLE_METADATA (
    ID              NUMBER(19)      PRIMARY KEY,
    TABLE_CODE      VARCHAR2(64)    NOT NULL UNIQUE,
    TABLE_NAME      VARCHAR2(128)   NOT NULL,
    QUERY_VIEW      VARCHAR2(64),
    TARGET_TABLE    VARCHAR2(64)    NOT NULL,
    SEQUENCE_NAME   VARCHAR2(64),
    PK_COLUMN       VARCHAR2(64)    DEFAULT 'ID',
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);

CREATE SEQUENCE SEQ_COST_TABLE_METADATA START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE T_COST_TABLE_METADATA IS '表元数据';
COMMENT ON COLUMN T_COST_TABLE_METADATA.TABLE_CODE IS '表编码，大驼峰命名';
COMMENT ON COLUMN T_COST_TABLE_METADATA.QUERY_VIEW IS '查询用的视图或表名';
COMMENT ON COLUMN T_COST_TABLE_METADATA.TARGET_TABLE IS '增删改操作的目标物理表';

-- 2. 列元数据
CREATE TABLE T_COST_COLUMN_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_METADATA_ID   NUMBER(19)      NOT NULL,
    FIELD_NAME          VARCHAR2(64)    NOT NULL,
    COLUMN_NAME         VARCHAR2(64)    NOT NULL,
    HEADER_TEXT         VARCHAR2(128)   NOT NULL,
    DATA_TYPE           VARCHAR2(32)    DEFAULT 'text',
    DISPLAY_ORDER       NUMBER(5)       DEFAULT 0,
    WIDTH               NUMBER(5)       DEFAULT 120,
    VISIBLE             NUMBER(1)       DEFAULT 1,
    EDITABLE            NUMBER(1)       DEFAULT 1,
    REQUIRED            NUMBER(1)       DEFAULT 0,
    SEARCHABLE          NUMBER(1)       DEFAULT 0,
    SORTABLE            NUMBER(1)       DEFAULT 1,
    DICT_TYPE           VARCHAR2(64),
    LOOKUP_CODE         VARCHAR2(64),
    DEFAULT_VALUE       VARCHAR2(256),
    RULES_CONFIG        CLOB,
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_COLUMN_TABLE FOREIGN KEY (TABLE_METADATA_ID) REFERENCES T_COST_TABLE_METADATA(ID)
);

CREATE SEQUENCE SEQ_COST_COLUMN_METADATA START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_COLUMN_TABLE_ID ON T_COST_COLUMN_METADATA(TABLE_METADATA_ID);

COMMENT ON TABLE T_COST_COLUMN_METADATA IS '列元数据';
COMMENT ON COLUMN T_COST_COLUMN_METADATA.FIELD_NAME IS '前端字段名，小驼峰';
COMMENT ON COLUMN T_COST_COLUMN_METADATA.COLUMN_NAME IS '数据库列名，大写下划线';
COMMENT ON COLUMN T_COST_COLUMN_METADATA.DATA_TYPE IS '数据类型：text/number/date/datetime/select/lookup';

-- =============================================
-- 示例数据
-- =============================================

CREATE TABLE T_COST_DEMO (
    ID              NUMBER(19)      PRIMARY KEY,
    CODE            VARCHAR2(64)    NOT NULL,
    NAME            VARCHAR2(128)   NOT NULL,
    AMOUNT          NUMBER(18,2),
    COST_DATE       DATE,
    STATUS          VARCHAR2(32)    DEFAULT 'DRAFT',
    REMARK          VARCHAR2(512),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);

CREATE SEQUENCE SEQ_COST_DEMO START WITH 1 INCREMENT BY 1;

INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostDemo', '成本示例表', 'T_COST_DEMO', 'T_COST_DEMO', 'SEQ_COST_DEMO', 'ID');

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, 1, 'id', 'ID', 'ID', 'number', 0, 0, 0, 0);

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, 1, 'code', 'CODE', '编码', 'text', 1, 1, 1, 1);

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, 1, 'name', 'NAME', '名称', 'text', 2, 1, 1, 1);

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, 1, 'amount', 'AMOUNT', '金额', 'number', 3, 1, 0, 0);

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, 1, 'costDate', 'COST_DATE', '成本日期', 'date', 4, 1, 0, 1);

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, 1, 'status', 'STATUS', '状态', 'select', 5, 1, 0, 1);

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, 1, 'remark', 'REMARK', '备注', 'text', 6, 1, 0, 0);

COMMIT;
