-- =====================================================
-- 权限模块表结构
-- =====================================================

-- 删除已有对象
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_ROLE_PAGE_DATA_RULE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_USER_GRID_CONFIG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_ROLE_PAGE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_USER_ROLE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_USER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_ROLE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_DEPARTMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_RESOURCE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_DEPARTMENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_RESOURCE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_USER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_USER_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_ROLE_PAGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_DATA_RULE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_USER_GRID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================================================
-- 1. 部门表
-- =====================================================
CREATE TABLE T_COST_DEPARTMENT (
    ID              NUMBER(19) PRIMARY KEY,
    DEPT_CODE       VARCHAR2(64) NOT NULL UNIQUE,
    DEPT_NAME       VARCHAR2(128) NOT NULL,
    PARENT_ID       NUMBER(19),
    SORT_ORDER      NUMBER(5) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_DEPARTMENT START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 2. 用户表
-- =====================================================
CREATE TABLE T_COST_USER (
    ID              NUMBER(19) PRIMARY KEY,
    USERNAME        VARCHAR2(64) NOT NULL UNIQUE,
    PASSWORD        VARCHAR2(256) NOT NULL,
    REAL_NAME       VARCHAR2(128),
    EMAIL           VARCHAR2(128),
    PHONE           VARCHAR2(32),
    DEPARTMENT_ID   NUMBER(19),
    STATUS          VARCHAR2(32) DEFAULT 'ACTIVE',
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 3. 角色表
-- =====================================================
CREATE TABLE T_COST_ROLE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_CODE       VARCHAR2(64) NOT NULL UNIQUE,
    ROLE_NAME       VARCHAR2(128) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_ROLE START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 4. 用户角色关联表
-- =====================================================
CREATE TABLE T_COST_USER_ROLE (
    ID              NUMBER(19) PRIMARY KEY,
    USER_ID         NUMBER(19) NOT NULL,
    ROLE_ID         NUMBER(19) NOT NULL,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER_ROLE START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_USER_ROLE ON T_COST_USER_ROLE(USER_ID, ROLE_ID);

-- =====================================================
-- 5. 角色页面权限表（含按钮权限、列权限）
-- =====================================================
CREATE TABLE T_COST_ROLE_PAGE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_ID         NUMBER(19) NOT NULL,
    PAGE_CODE       VARCHAR2(64) NOT NULL,
    BUTTON_POLICY   VARCHAR2(1000),
    COLUMN_POLICY   CLOB,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_ROLE_PAGE START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_ROLE_PAGE ON T_COST_ROLE_PAGE(ROLE_ID, PAGE_CODE);

-- =====================================================
-- 6. 数据权限规则表
-- =====================================================
CREATE TABLE T_COST_ROLE_PAGE_DATA_RULE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_PAGE_ID    NUMBER(19) NOT NULL,
    RULE_TYPE       VARCHAR2(32) NOT NULL,
    RULE_CONFIG     CLOB NOT NULL,
    PRIORITY        NUMBER(3) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_DATA_RULE START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 7. 用户网格配置表（个人偏好）
-- =====================================================
CREATE TABLE T_COST_USER_GRID_CONFIG (
    ID              NUMBER(19) PRIMARY KEY,
    USER_ID         NUMBER(19) NOT NULL,
    PAGE_CODE       VARCHAR2(64) NOT NULL,
    GRID_KEY        VARCHAR2(64) NOT NULL,
    CONFIG_DATA     CLOB,
    DELETED         NUMBER(1) DEFAULT 0,
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER_GRID START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_USER_GRID_CONF ON T_COST_USER_GRID_CONFIG(USER_ID, PAGE_CODE, GRID_KEY);

-- =====================================================
-- 8. 菜单资源表
-- =====================================================
CREATE TABLE T_COST_RESOURCE (
    ID              NUMBER(19) PRIMARY KEY,
    RESOURCE_CODE   VARCHAR2(64) NOT NULL UNIQUE,
    RESOURCE_NAME   VARCHAR2(128) NOT NULL,
    RESOURCE_TYPE   VARCHAR2(20) NOT NULL,   -- DIRECTORY, PAGE
    PAGE_CODE       VARCHAR2(64),            -- PAGE 类型关联组件树
    ICON            VARCHAR2(64),
    ROUTE           VARCHAR2(128),           -- 前端路由路径
    PARENT_ID       NUMBER(19),
    SORT_ORDER      NUMBER(5) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_RESOURCE START WITH 1 INCREMENT BY 1;

COMMIT;
