-- =====================================================
-- 业务表结构
-- =====================================================

-- 删除已有对象
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_EVAL_DETAIL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_EVAL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_ORDER_FEE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_ORDER_DETAIL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_ORDER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_CUSTOMER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_MATERIAL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_SALES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_DEMO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_EVAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_EVAL_DETAIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_ORDER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_ORDER_DETAIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_ORDER_FEE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_CUSTOMER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_MATERIAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_SALES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_DEMO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================================================
-- 1. 评估单主表
-- =====================================================
CREATE TABLE T_COST_EVAL (
    ID              NUMBER(19)      PRIMARY KEY,
    EVAL_NO         VARCHAR2(32)    NOT NULL UNIQUE,
    PRODUCT_NAME    VARCHAR2(128)   NOT NULL,
    APEX_PL         NUMBER(18,4)    DEFAULT 0,      -- 批量(万片)
    YIELD           NUMBER(18,4)    DEFAULT 100,    -- 收率(%)
    OUT_PRICE_RMB   NUMBER(18,4)    DEFAULT 0,      -- 出厂价
    TOTAL_YL        NUMBER(18,2)    DEFAULT 0,      -- 原料合计
    TOTAL_FL        NUMBER(18,2)    DEFAULT 0,      -- 辅料合计
    TOTAL_PACK      NUMBER(18,2)    DEFAULT 0,      -- 包材合计
    TOTAL_COST      NUMBER(18,2)    DEFAULT 0,      -- 总成本
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_EVAL START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 2. 评估单物料明细从表
-- =====================================================
CREATE TABLE T_COST_EVAL_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    EVAL_ID         NUMBER(19)      NOT NULL,
    MATERIAL_NAME   VARCHAR2(128)   NOT NULL,
    USE_FLAG        VARCHAR2(32)    NOT NULL,       -- 物料类型：原料/辅料/包材
    PER_HL          NUMBER(18,6)    DEFAULT 0,      -- 百万片用量
    PRICE           NUMBER(18,4)    DEFAULT 0,      -- 单价
    BATCH_QTY       NUMBER(18,4)    DEFAULT 0,      -- 批用量（计算列）
    COST_BATCH      NUMBER(18,2)    DEFAULT 0,      -- 批成本（计算列）
    PACK_SPEC       VARCHAR2(64),                   -- 包材规格
    PACK_QTY        NUMBER(18,4)    DEFAULT 0,      -- 包装数量（计算列）
    PACK_COST       NUMBER(18,2)    DEFAULT 0,      -- 包装成本（计算列）
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64),
    CONSTRAINT FK_EVAL_DETAIL FOREIGN KEY (EVAL_ID) REFERENCES T_COST_EVAL(ID)
);
CREATE SEQUENCE SEQ_COST_EVAL_DETAIL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_EVAL_DETAIL_EVAL_ID ON T_COST_EVAL_DETAIL(EVAL_ID);

-- =====================================================
-- 3. 成本单主表
-- =====================================================
CREATE TABLE T_COST_ORDER (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_NO        VARCHAR2(32)    NOT NULL UNIQUE,
    ORDER_DATE      DATE            NOT NULL,
    CUSTOMER_NAME   VARCHAR2(128),
    TOTAL_AMOUNT    NUMBER(18,2)    DEFAULT 0,
    TOTAL_FEE       NUMBER(18,2)    DEFAULT 0,
    STATUS          VARCHAR2(32)    DEFAULT 'DRAFT',
    REMARK          VARCHAR2(512),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_ORDER START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 4. 成本单明细从表
-- =====================================================
CREATE TABLE T_COST_ORDER_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_ID        NUMBER(19)      NOT NULL,
    ITEM_NAME       VARCHAR2(128)   NOT NULL,
    SPEC            VARCHAR2(64),
    UNIT            VARCHAR2(32),
    QUANTITY        NUMBER(18,4)    DEFAULT 0,
    UNIT_PRICE      NUMBER(18,4)    DEFAULT 0,
    AMOUNT          NUMBER(18,2)    DEFAULT 0,
    REMARK          VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64),
    CONSTRAINT FK_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES T_COST_ORDER(ID)
);
CREATE SEQUENCE SEQ_COST_ORDER_DETAIL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DETAIL_ORDER_ID ON T_COST_ORDER_DETAIL(ORDER_ID);

-- =====================================================
-- 5. 成本单费用从表
-- =====================================================
CREATE TABLE T_COST_ORDER_FEE (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_ID        NUMBER(19)      NOT NULL,
    FEE_TYPE        VARCHAR2(32)    NOT NULL,
    FEE_NAME        VARCHAR2(128)   NOT NULL,
    FEE_AMOUNT      NUMBER(18,2)    DEFAULT 0,
    REMARK          VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64),
    CONSTRAINT FK_FEE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES T_COST_ORDER(ID)
);
CREATE SEQUENCE SEQ_COST_ORDER_FEE START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_FEE_ORDER_ID ON T_COST_ORDER_FEE(ORDER_ID);

-- =====================================================
-- 6. 客户表
-- =====================================================
CREATE TABLE T_COST_CUSTOMER (
    ID              NUMBER(19)      PRIMARY KEY,
    CUSTOMER_CODE   VARCHAR2(32)    NOT NULL UNIQUE,
    CUSTOMER_NAME   VARCHAR2(128)   NOT NULL,
    CONTACT_PERSON  VARCHAR2(64),
    PHONE           VARCHAR2(32),
    ADDRESS         VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_CUSTOMER START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 7. 物料基础数据表
-- =====================================================
CREATE TABLE T_COST_MATERIAL (
    ID              NUMBER(19)      PRIMARY KEY,
    MATERIAL_CODE   VARCHAR2(32)    NOT NULL UNIQUE,
    MATERIAL_NAME   VARCHAR2(128)   NOT NULL,
    USE_FLAG        VARCHAR2(32)    NOT NULL,       -- 物料类型：原料/辅料/包材
    PER_HL          NUMBER(18,6)    DEFAULT 0,      -- 百万片用量
    PRICE           NUMBER(18,4)    DEFAULT 0,      -- 单价
    UNIT            VARCHAR2(32),                   -- 单位
    SPEC            VARCHAR2(64),                   -- 规格
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_MATERIAL START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 8. 销售记录表（执行器目标表）
-- =====================================================
CREATE TABLE T_COST_SALES (
    ID              NUMBER(19)      PRIMARY KEY,
    EVAL_ID         NUMBER(19)      NOT NULL,
    EVAL_NO         VARCHAR2(32)    NOT NULL,
    PRODUCT_NAME    VARCHAR2(128)   NOT NULL,
    TOTAL_COST      NUMBER(18,2)    DEFAULT 0,
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_SALES START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 9. 成本示例表（简单CRUD演示）
-- =====================================================
CREATE TABLE T_COST_DEMO (
    ID              NUMBER(19)      PRIMARY KEY,
    CODE            VARCHAR2(64)    NOT NULL,
    NAME            VARCHAR2(128)   NOT NULL,
    AMOUNT          NUMBER(18,2),
    COST_DATE       DATE,
    STATUS          VARCHAR2(32)    DEFAULT 'DRAFT',
    REMARK          VARCHAR2(512),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_DEMO START WITH 1 INCREMENT BY 1;

COMMIT;
