-- =====================================================
-- 日志表结构
-- =====================================================

-- 删除已有对象
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_OPERATION_LOG_DETAIL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_OPERATION_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_AUDIT_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_OPERATION_LOG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_OPERATION_LOG_DETAIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_AUDIT_LOG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================================================
-- 1. 操作日志主表
-- =====================================================
CREATE TABLE T_COST_OPERATION_LOG (
    ID              NUMBER(19)      PRIMARY KEY,
    USER_ID         NUMBER(19),
    USER_NAME       VARCHAR2(64),
    OPERATION_TYPE  VARCHAR2(32)    NOT NULL,  -- SAVE/DELETE/QUERY
    TABLE_CODE      VARCHAR2(64),
    RECORD_ID       NUMBER(19),
    RECORD_DESC     VARCHAR2(256),             -- 记录描述
    TOTAL_SQL_COUNT NUMBER(10)      DEFAULT 0,
    TOTAL_COST_MS   NUMBER(10)      DEFAULT 0, -- 总耗时(毫秒)
    STATUS          VARCHAR2(16)    DEFAULT 'SUCCESS', -- SUCCESS/FAILED
    ERROR_MSG       VARCHAR2(1000),
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_OPERATION_LOG START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_OPERATION_LOG_USER ON T_COST_OPERATION_LOG(USER_ID);
CREATE INDEX IDX_OPERATION_LOG_TIME ON T_COST_OPERATION_LOG(CREATE_TIME);
CREATE INDEX IDX_OPERATION_LOG_TABLE ON T_COST_OPERATION_LOG(TABLE_CODE);

-- =====================================================
-- 2. 操作日志明细表
-- =====================================================
CREATE TABLE T_COST_OPERATION_LOG_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    LOG_ID          NUMBER(19)      NOT NULL,  -- 关联主表
    SEQ_NO          NUMBER(5)       NOT NULL,  -- 执行顺序
    SQL_TYPE        VARCHAR2(16),              -- SELECT/INSERT/UPDATE/DELETE
    SQL_TEXT        CLOB,                      -- SQL 语句
    COST_MS         NUMBER(10)      DEFAULT 0, -- 耗时(毫秒)
    AFFECTED_ROWS   NUMBER(10),                -- 影响行数
    STATUS          VARCHAR2(16)    DEFAULT 'SUCCESS',
    ERROR_MSG       VARCHAR2(1000),
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LOG_DETAIL_LOG FOREIGN KEY (LOG_ID) REFERENCES T_COST_OPERATION_LOG(ID)
);
CREATE SEQUENCE SEQ_COST_OPERATION_LOG_DETAIL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_LOG_DETAIL_LOG ON T_COST_OPERATION_LOG_DETAIL(LOG_ID);

-- =====================================================
-- 3. 业务审计日志表（用户可见）
-- =====================================================
CREATE TABLE T_COST_AUDIT_LOG (
    ID              NUMBER(19)      PRIMARY KEY,
    USER_NAME       VARCHAR2(100),                    -- 操作用户
    OPERATION_TIME  TIMESTAMP       DEFAULT SYSTIMESTAMP, -- 操作时间
    PAGE_CODE       VARCHAR2(100),                    -- 页面编码
    TABLE_CODE      VARCHAR2(100),                    -- 表编码
    TABLE_NAME      VARCHAR2(200),                    -- 表中文名
    RECORD_ID       NUMBER(19),                       -- 记录ID
    OPERATION_TYPE  VARCHAR2(20),                     -- INSERT/UPDATE/DELETE
    FIELD_CHANGES   CLOB,                             -- JSON: [{field, fieldName, oldValue, newValue}]
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_AUDIT_LOG START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_AUDIT_LOG_TIME ON T_COST_AUDIT_LOG(OPERATION_TIME);
CREATE INDEX IDX_AUDIT_LOG_USER ON T_COST_AUDIT_LOG(USER_NAME);
CREATE INDEX IDX_AUDIT_LOG_TABLE ON T_COST_AUDIT_LOG(TABLE_CODE);

COMMENT ON TABLE T_COST_AUDIT_LOG IS '业务审计日志（用户可见）';
COMMENT ON COLUMN T_COST_AUDIT_LOG.FIELD_CHANGES IS '字段变更JSON，只记录用户手动修改';

COMMIT;
