-- =====================================================
-- Lookup 弹窗选择器示例：客户表 + 成本单客户字段 Lookup 配置
-- =====================================================

-- 1. 创建客户表
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_CUSTOMER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_CUSTOMER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE T_COST_CUSTOMER (
    ID              NUMBER(19)      PRIMARY KEY,
    CUSTOMER_CODE   VARCHAR2(32)    NOT NULL UNIQUE,
    CUSTOMER_NAME   VARCHAR2(128)   NOT NULL,
    CONTACT_PERSON  VARCHAR2(64),
    PHONE           VARCHAR2(32),
    ADDRESS         VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_CUSTOMER START WITH 1 INCREMENT BY 1;

-- 2. 客户表元数据
DECLARE
    v_customer_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_customer_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_customer_id, 'Customer', '客户', 'T_COST_CUSTOMER', 'T_COST_CUSTOMER', 'SEQ_COST_CUSTOMER', 'ID', 'system');
    
    -- 客户表列
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'id', 'ID', 'ID', 'number', 0, 0, 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'customerCode', 'CUSTOMER_CODE', '客户编码', 'text', 1, 1, 1, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'customerName', 'CUSTOMER_NAME', '客户名称', 'text', 2, 1, 1, 1, 180, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'contactPerson', 'CONTACT_PERSON', '联系人', 'text', 3, 1, 0, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'phone', 'PHONE', '电话', 'text', 4, 1, 0, 0, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, REQUIRED, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'address', 'ADDRESS', '地址', 'text', 5, 1, 0, 0, 200, 'system');

    COMMIT;
END;
/

-- 3. 客户测试数据
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C001', '华为技术有限公司', '张三', '13800138001', '深圳市龙岗区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C002', '阿里巴巴集团', '李四', '13800138002', '杭州市余杭区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C003', '腾讯科技', '王五', '13800138003', '深圳市南山区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C004', '字节跳动', '赵六', '13800138004', '北京市海淀区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C005', '美团点评', '钱七', '13800138005', '北京市朝阳区', 'system');

COMMIT;

-- 4. 更新成本单主表的"客户名称"字段，添加 Lookup 配置
UPDATE T_COST_COLUMN_METADATA 
SET RULES_CONFIG = '{"lookup":{"tableCode":"Customer","displayField":"customerName","title":"选择客户","mapping":{"customerName":"customerName"}}}'
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostOrder')
AND FIELD_NAME = 'customerName';

UPDATE T_COST_COLUMN_METADATA 
SET RULES_CONFIG = '{"lookup":{"tableCode":"Customer","displayField":"customerName","title":"选择客户","mapping":{"customerName":"customerName","remark":"contactPerson"}}}'
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostOrder')
AND FIELD_NAME = 'customerName';

COMMIT;
 