-- =====================================================
-- V6: 添加包材支持
-- =====================================================

-- 1. 主表添加包材合计字段
ALTER TABLE T_COST_EVAL ADD TOTAL_PACK NUMBER(18,2) DEFAULT 0;

-- 2. 从表添加包材特有字段
ALTER TABLE T_COST_EVAL_DETAIL ADD PACK_SPEC VARCHAR2(64);      -- 包装规格
ALTER TABLE T_COST_EVAL_DETAIL ADD PACK_QTY NUMBER(18,4) DEFAULT 0;   -- 包装数量（计算列）
ALTER TABLE T_COST_EVAL_DETAIL ADD PACK_COST NUMBER(18,2) DEFAULT 0;  -- 包装成本（计算列）

-- 3. 添加包材测试数据
DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT ID INTO v_eval_id FROM T_COST_EVAL WHERE EVAL_NO = 'EVAL-2025-001';
    
    -- 包材数据
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, PACK_SPEC, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '铝塑板', '包材', 0, 0.15, '10粒/板', 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, PACK_SPEC, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '纸盒', '包材', 0, 0.35, '3板/盒', 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, PACK_SPEC, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '说明书', '包材', 0, 0.02, '1张/盒', 'system');
    
    COMMIT;
END;
/

-- 4. 更新元数据：主表添加 totalPack 列
DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT ID INTO v_eval_id FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostEval';
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'totalPack', 'TOTAL_PACK', '包材合计', 'number', 7, 0, 100, 'system');
    
    COMMIT;
END;
/

-- 5. 更新元数据：从表添加包材字段
DECLARE
    v_detail_id NUMBER;
BEGIN
    SELECT ID INTO v_detail_id FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostEvalDetail';
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'packSpec', 'PACK_SPEC', '包装规格', 'text', 8, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, RULES_CONFIG, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'packQty', 'PACK_QTY', '包装数量', 'number', 9, 0, 1, 100, '{"expression":"_ctx.apexPl * 1000"}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, RULES_CONFIG, CREATE_BY) 
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'packCost', 'PACK_COST', '包装成本', 'number', 10, 0, 1, 100, '{"expression":"packQty * price"}', 'system');
    
    COMMIT;
END;
/
