-- =====================================================
-- 测试数据初始化
-- =====================================================

-- =====================================================
-- 1. 物料基础数据
-- =====================================================
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL001', '阿莫西林原料', '原料', 125.5, 280, 'kg', '医药级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL002', '淀粉', '原料', 45.2, 15, 'kg', '食品级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL003', '头孢克肟原料', '原料', 200, 450, 'kg', '医药级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL001', '空心胶囊', '辅料', 1050, 0.035, '粒', '0号', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL002', '硬脂酸镁', '辅料', 2.5, 45, 'kg', '医药级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL003', '微晶纤维素', '辅料', 80, 25, 'kg', '医药级', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC001', '铝塑板', '包材', 0, 0.12, '张', '10粒/板', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC002', '纸盒', '包材', 0, 0.35, '个', '2板/盒', 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC003', '说明书', '包材', 0, 0.05, '张', 'A4', 'system');

-- =====================================================
-- 2. 客户数据
-- =====================================================
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C001', '华为技术有限公司', '张三', '13800138001', '深圳市龙岗区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C002', '阿里巴巴集团', '李四', '13800138002', '杭州市余杭区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C003', '腾讯科技', '王五', '13800138003', '深圳市南山区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C004', '字节跳动', '赵六', '13800138004', '北京市海淀区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C005', '美团点评', '钱七', '13800138005', '北京市朝阳区', 'system');

-- =====================================================
-- 3. 评估单测试数据
-- =====================================================
DECLARE
    v_eval_id NUMBER;
BEGIN
    -- 评估单1：阿莫西林胶囊
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-001', '阿莫西林胶囊', 100, 98, 35.5, 'system');
    
    -- 原料
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '阿莫西林原料', '原料', 125.5, 280, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '淀粉', '原料', 45.2, 15, 'system');
    
    -- 辅料
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '空心胶囊', '辅料', 1050, 0.035, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '硬脂酸镁', '辅料', 2.5, 45, 'system');
    
    -- 包材
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PACK_SPEC, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '铝塑板', '包材', '10粒/板', 0.12, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PACK_SPEC, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '纸盒', '包材', '2板/盒', 0.35, 'system');
    
    COMMIT;
END;
/

DECLARE
    v_eval_id NUMBER;
BEGIN
    -- 评估单2：头孢克肟片
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-002', '头孢克肟片', 80, 95, 42.0, 'system');
    
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '头孢克肟原料', '原料', 200, 450, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '微晶纤维素', '辅料', 80, 25, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PACK_SPEC, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '铝塑板', '包材', '12粒/板', 0.15, 'system');
    
    COMMIT;
END;
/

DECLARE
    v_eval_id NUMBER;
BEGIN
    -- 评估单3：阿莫西林口服液瓶装（测试"瓶"文字变色）
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-003', '阿莫西林口服液瓶装', 50, 96, 28.0, 'system');
    
    COMMIT;
END;
/

DECLARE
    v_eval_id NUMBER;
BEGIN
    -- 评估单4：清热解毒颗粒（测试"清"整行变色）
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-004', '清热解毒颗粒', 60, 94, 32.0, 'system');
    
    COMMIT;
END;
/

COMMIT;
