-- =====================================================
-- 审计追踪页面元数据配置
-- =====================================================

-- 0. 清理旧数据
DELETE FROM T_COST_PAGE_RULE WHERE PAGE_CODE = 'audit_log';
DELETE FROM T_COST_PAGE_COMPONENT WHERE PAGE_CODE = 'audit_log';
DELETE FROM T_COST_COLUMN_METADATA WHERE TABLE_METADATA_ID IN (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'audit_log');
DELETE FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'audit_log';
DELETE FROM T_COST_RESOURCE WHERE PAGE_CODE = 'audit_log';

-- 1. 表元数据
INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, AUDIT_ENABLED, DESCRIPTION)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'audit_log', '审计追踪', 'T_COST_AUDIT_LOG', 'T_COST_AUDIT_LOG', 'SEQ_COST_AUDIT_LOG', 'ID', 0, '系统审计日志');

-- 2. 列元数据
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'id', 'ID', 'ID', 'number', 1, 1, 1
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'userName', 'USER_NAME', '操作用户', 'text', 2, 1, 1
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'operationTime', 'OPERATION_TIME', '操作时间', 'datetime', 3, 1, 1
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'pageCode', 'PAGE_CODE', '页面编码', 'text', 4, 1, 1
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'tableCode', 'TABLE_CODE', '表编码', 'text', 5, 1, 1
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'tableName', 'TABLE_NAME', '表名称', 'text', 6, 1, 1
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'recordId', 'RECORD_ID', '记录ID', 'number', 7, 1, 1
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'operationType', 'OPERATION_TYPE', '操作类型', 'text', 8, 1, 1
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'fieldChanges', 'FIELD_CHANGES', '字段变更', 'text', 9, 1, 0
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE)
SELECT SEQ_COST_COLUMN_METADATA.NEXTVAL, tm.ID, 'createTime', 'CREATE_TIME', '创建时间', 'datetime', 10, 1, 1
FROM T_COST_TABLE_METADATA tm WHERE tm.TABLE_CODE = 'audit_log';

-- 3. 页面组件配置（单表Grid）
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, REF_TABLE_CODE, SORT_ORDER, DESCRIPTION)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'audit_log', 'masterGrid', 'GRID', NULL, 'audit_log', 1, '审计追踪主表格');

-- 4. 页面规则 - 列覆盖（只读、宽度等）
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DESCRIPTION)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'audit_log', 'masterGrid', 'COLUMN_OVERRIDE', 
'[
  {"field":"id","width":80,"editable":false},
  {"field":"userName","width":120,"editable":false},
  {"field":"operationTime","width":180,"editable":false},
  {"field":"pageCode","width":150,"editable":false},
  {"field":"tableCode","width":150,"editable":false},
  {"field":"tableName","width":150,"editable":false},
  {"field":"recordId","width":100,"editable":false},
  {"field":"operationType","width":100,"editable":false},
  {"field":"fieldChanges","width":400,"editable":false,"wrapText":true,"autoHeight":true},
  {"field":"createTime","width":180,"editable":false}
]', 1, '列覆盖配置');

-- 5. 菜单资源（独立一级菜单）
INSERT INTO T_COST_RESOURCE (ID, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, IS_HARDCODED)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, '审计追踪', 'PAGE', 'audit_log', 'mdi:file-document-outline', '/audit-log', NULL, 99, 0);

COMMIT;
