-- =====================================================
-- 物料成本核算表 数据库脚本
-- 执行顺序：删除表 -> 删除元数据 -> 建表 -> 插入元数据
-- =====================================================

-- =====================================================
-- A. 删除视图和表
-- =====================================================
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_COST_GOODS_LOOKUP'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_COST_CUSTOMER_LOOKUP'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_COST_PINGGU_MATERIAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_COST_PINGGU_PACKAGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_PINGGU_DTL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_COST_PINGGU CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_PINGGU'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COST_PINGGU_DTL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================================================
-- B. 删除元数据
-- =====================================================
DELETE FROM T_COST_PAGE_COMPONENT WHERE PAGE_CODE = 'cost-pinggu';
DELETE FROM T_COST_PAGE_RULE WHERE PAGE_CODE = 'cost-pinggu';
DELETE FROM T_COST_LOOKUP_CONFIG WHERE LOOKUP_CODE IN ('costGoods', 'costMaterial', 'formoney', 'costCustomer');
DELETE FROM T_COST_COLUMN_METADATA WHERE TABLE_METADATA_ID IN (
  SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE IN ('CostPinggu', 'CostMaterial', 'CostPackage', 'CostGoodsLookup', 'CostCustomerLookup')
);
DELETE FROM T_COST_TABLE_METADATA WHERE TABLE_CODE IN ('CostPinggu', 'CostMaterial', 'CostPackage', 'CostGoodsLookup', 'CostCustomerLookup');
DELETE FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'cost-pinggu';
COMMIT;

-- =====================================================
-- C. 创建表结构
-- =====================================================
CREATE TABLE T_COST_PINGGU (
    GOODSID NUMBER, GOODSNAME VARCHAR2(100), STRENGTH VARCHAR2(50), MA_NO VARCHAR2(30),
    APEX_PL NUMBER, MAH VARCHAR2(100), P_PERPACK NUMBER, FORM VARCHAR2(20),
    S_PERBACK NUMBER, PACKTYPE VARCHAR2(30), X_PERBACK NUMBER,
    TOTAL_FL NUMBER, TOTAL_BC NUMBER, TOTAL_YL NUMBER, MEMO VARCHAR2(100),
    USESTATUS VARCHAR2(100) DEFAULT 0,
    DOCID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DOSAGE VARCHAR2(20), ANNUAL_QTY NUMBER, YIELD NUMBER, TOTAL_COST NUMBER,
    OUT_PRICE_F NUMBER, OUT_PRICE_RMB NUMBER, SALEMONEY NUMBER,
    JGF_BATCH NUMBER, JGF_PERQP NUMBER, COST_PERQP NUMBER, ML_PERQP NUMBER,
    Y_JG_RE NUMBER, Y_ML NUMBER, Y_SALE NUMBER,
    CUSTOMID NUMBER, CUSTOMNAME VARCHAR2(50), COUNTRY VARCHAR2(20), PROJECTNO VARCHAR2(20),
    USEFLAG NUMBER DEFAULT 0, YIELD_TIME DATE DEFAULT SYSDATE, APEX_PL_TIME DATE DEFAULT SYSDATE,
    ZX_SOURCE VARCHAR2(100), FMNAME VARCHAR2(100) DEFAULT '人民币', FMRATE NUMBER DEFAULT 1,
    GOODSNAME_EN VARCHAR2(2000), LIVERY VARCHAR2(100),
    DELETED NUMBER(1) DEFAULT 0, CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP, CREATE_BY VARCHAR2(64), UPDATE_BY VARCHAR2(64),
    CONSTRAINT PK_COST_PINGGU PRIMARY KEY (DOCID)
);
CREATE SEQUENCE SEQ_COST_PINGGU START WITH 100000 INCREMENT BY 1;

CREATE TABLE T_COST_PINGGU_DTL (
    DOCID NUMBER(10) NOT NULL, APEX_GOODSID NUMBER(10), APEX_GOODSNAME VARCHAR2(500),
    DTL_USEFLAG VARCHAR2(100), SPEC VARCHAR2(100), PER_HL NUMBER, EXADD_MATER NUMBER,
    BATCH_QTY VARCHAR2(100), PRICE NUMBER, COST_BATCH NUMBER, MEMO VARCHAR2(100),
    DTLID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APEX_FACTORYNAME VARCHAR2(200), APEX_FACTORYID NUMBER(10), MODIFYDATE DATE,
    ZX_SOURCE VARCHAR2(100), BASE_PRICE NUMBER, SUQTY NUMBER,
    GOODSTYPE VARCHAR2(4000), GOODSNAME_EN VARCHAR2(2000),
    DELETED NUMBER(1) DEFAULT 0, CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP, CREATE_BY VARCHAR2(64), UPDATE_BY VARCHAR2(64),
    CONSTRAINT PK_COST_PINGGU_DTL PRIMARY KEY (DTLID)
);
CREATE SEQUENCE SEQ_COST_PINGGU_DTL START WITH 100000 INCREMENT BY 1;
COMMIT;

-- =====================================================
-- D. 创建视图
-- =====================================================
CREATE OR REPLACE VIEW V_COST_PINGGU_MATERIAL AS
SELECT d.DTLID AS ID, d.DOCID AS MASTER_ID, d.APEX_GOODSID, d.APEX_GOODSNAME, d.DTL_USEFLAG,
    d.SPEC, d.PER_HL, d.PRICE, d.BATCH_QTY, d.COST_BATCH, d.APEX_FACTORYNAME, d.ZX_SOURCE,
    d.BASE_PRICE, d.GOODSTYPE, d.EXADD_MATER, d.MEMO, d.DELETED, d.CREATE_TIME, d.UPDATE_TIME,
    d.CREATE_BY, d.UPDATE_BY,
    CASE WHEN d.DTL_USEFLAG = '辅料' AND REGEXP_LIKE(d.APEX_GOODSNAME, '胶囊') THEN 'B'
         WHEN d.DTL_USEFLAG IN ('原料', '辅料') THEN 'C' ELSE NULL END AS FORMULA_TYPE
FROM T_COST_PINGGU_DTL d
WHERE d.DTL_USEFLAG IN ('原料', '辅料') AND (d.DELETED = 0 OR d.DELETED IS NULL);

CREATE OR REPLACE VIEW V_COST_PINGGU_PACKAGE AS
SELECT d.DTLID AS ID, d.DOCID AS MASTER_ID, d.APEX_GOODSID, d.APEX_GOODSNAME, d.DTL_USEFLAG,
    d.SPEC, d.PER_HL, d.EXADD_MATER, d.PRICE, d.BATCH_QTY, d.COST_BATCH, d.SUQTY,
    d.APEX_FACTORYNAME, d.ZX_SOURCE, d.MEMO, d.DELETED, d.CREATE_TIME, d.UPDATE_TIME,
    d.CREATE_BY, d.UPDATE_BY,
    CASE WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '桶|说明书|小盒|标签|瓶|盖') THEN 'A'
         WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '硬片|铝箔|复合膜') THEN 'D'
         WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '大纸箱') THEN 'E'
         WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '托盘') THEN 'F' ELSE NULL END AS FORMULA_TYPE
FROM T_COST_PINGGU_DTL d
WHERE d.DTL_USEFLAG IN ('非印字包材', '印字包材') AND (d.DELETED = 0 OR d.DELETED IS NULL);

-- 产品选择弹窗视图（用于回填到物料成本核算表主表）
CREATE OR REPLACE VIEW V_COST_GOODS_LOOKUP AS
SELECT a.GOODSID,
       a.GOODSNAME,
       a.APPROVEDOCNO AS MA_NO,
       a.ZX_PL AS APEX_PL,
       a.HOLDERSNAME AS MAH,
       a.ZX_MINIMUM AS P_PERPACK,
       a.BASEUNITQTY AS S_PERBACK,
       a.ZX_CUSTOMERID AS CUSTOMID,
       a.CUSTOMNAME,
       CASE WHEN a.ISERP = 0 AND b.PGOODSID IS NULL THEN 'ERP未搭建BOM'
            ELSE 'ERP已搭建BOM' END AS MEMO,
       a.GOODSTYPE AS STRENGTH,
       a.TRANPOSNAME AS LIVERY,
       a.DELETED
  FROM T_COST_GOODS a
  LEFT JOIN mpcs_pr_bom_doc@hyerp b ON a.GOODSID = b.PGOODSID AND b.USESTATUS = 1 AND a.ISERP = 1
 WHERE a.USEFLAG = '产成品'
   AND (a.DELETED = 0 OR a.DELETED IS NULL);

-- 客户选择弹窗视图（用于回填到物料成本核算表主表）
CREATE OR REPLACE VIEW V_COST_CUSTOMER_LOOKUP AS
SELECT a.CUSTOMID,
       a.CUSTOMNAME,
       a.ZONE AS COUNTRY,
       b.TRANPOSNAME AS LIVERY,
       0 AS DELETED
  FROM T_COST_CUSTOMER_V a, T_COST_TRANPOSER_V b
 WHERE a.CUSTOMID = b.CUSTOMID;
COMMIT;

-- =====================================================
-- E. 插入表元数据
-- =====================================================
DECLARE
    v_master_id NUMBER;
    v_material_id NUMBER;
    v_package_id NUMBER;
BEGIN
    -- 主表元数据
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_master_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_master_id, 'CostPinggu', '物料成本核算表', 'T_COST_PINGGU', 'T_COST_PINGGU', 'SEQ_COST_PINGGU', 'DOCID', 'system');
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'id', 'DOCID', 'ID', 'number', 0, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'goodsname', 'GOODSNAME', '产品名称', 'text', 1, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'goodsnameEn', 'GOODSNAME_EN', '产品英文名', 'text', 2, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'strength', 'STRENGTH', '剂量', 'text', 3, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'customname', 'CUSTOMNAME', '客户名称', 'text', 4, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'country', 'COUNTRY', '国家', 'text', 5, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'projectno', 'PROJECTNO', '项目号', 'text', 6, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'apexPl', 'APEX_PL', '批量', 'number', 7, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'annualQty', 'ANNUAL_QTY', '年需求量', 'number', 8, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'yield', 'YIELD', '收率(%)', 'number', 9, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'pPerpack', 'P_PERPACK', '每盒片数', 'number', 10, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'sPerback', 'S_PERBACK', '每箱装盒数', 'number', 11, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'xPerback', 'X_PERBACK', '每托盘箱数', 'number', 12, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'packtype', 'PACKTYPE', '包装形式', 'text', 13, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalYl', 'TOTAL_YL', '原料合计', 'number', 20, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalFl', 'TOTAL_FL', '辅料合计', 'number', 21, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalBc', 'TOTAL_BC', '包材合计', 'number', 22, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalCost', 'TOTAL_COST', '总物料成本', 'number', 23, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'outPriceRmb', 'OUT_PRICE_RMB', '出厂价(RMB)', 'number', 24, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'salemoney', 'SALEMONEY', '每批销售额', 'number', 25, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'jgfBatch', 'JGF_BATCH', '每批加工费', 'number', 26, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'costPerqp', 'COST_PERQP', '千片成本', 'number', 27, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'jgfPerqp', 'JGF_PERQP', '千片加工费', 'number', 28, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'mlPerqp', 'ML_PERQP', '千片毛利', 'number', 29, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'yJgRe', 'Y_JG_RE', '年加工费', 'number', 30, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'yMl', 'Y_ML', '年毛利', 'number', 31, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'ySale', 'Y_SALE', '年销售额', 'number', 32, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'fmname', 'FMNAME', '币种', 'text', 33, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'fmrate', 'FMRATE', '汇率', 'number', 34, 'system');

    -- 原辅料从表元数据
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_material_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, CREATE_BY)
    VALUES (v_material_id, 'CostMaterial', '原辅料明细', 'V_COST_PINGGU_MATERIAL', 'T_COST_PINGGU_DTL', 'SEQ_COST_PINGGU_DTL', 'DTLID', 'CostPinggu', 'DOCID', 'system');
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'id', 'ID', 'ID', 'number', 0, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'masterId', 'MASTER_ID', 'MASTER_ID', 'DOCID', '主表ID', 'number', 1, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'dtlUseflag', 'DTL_USEFLAG', '分类', 'text', 2, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'apexGoodsname', 'APEX_GOODSNAME', '物料名称', 'text', 3, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'spec', 'SPEC', '规格', 'text', 4, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'perHl', 'PER_HL', '每片含量', 'number', 5, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'exaddMater', 'EXADD_MATER', '额外投料量', 'number', 6, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'price', 'PRICE', '单价', 'number', 7, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'batchQty', 'BATCH_QTY', '每批数量', 'number', 8, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'costBatch', 'COST_BATCH', '每批成本', 'number', 9, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'apexFactoryname', 'APEX_FACTORYNAME', '供应商', 'text', 10, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, IS_VIRTUAL, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'formulaType', 'FORMULA_TYPE', '公式类型', 'text', 11, 1, 'system');

    -- 包材从表元数据
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_package_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, CREATE_BY)
    VALUES (v_package_id, 'CostPackage', '包材明细', 'V_COST_PINGGU_PACKAGE', 'T_COST_PINGGU_DTL', 'SEQ_COST_PINGGU_DTL', 'DTLID', 'CostPinggu', 'DOCID', 'system');
    
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'id', 'ID', 'ID', 'number', 0, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'masterId', 'MASTER_ID', 'MASTER_ID', 'DOCID', '主表ID', 'number', 1, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'dtlUseflag', 'DTL_USEFLAG', '包材类型', 'text', 2, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'apexGoodsname', 'APEX_GOODSNAME', '包材名称', 'text', 3, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'spec', 'SPEC', '规格型号', 'text', 4, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'suqty', 'SUQTY', '用量', 'number', 5, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'price', 'PRICE', '包材单价', 'number', 6, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'batchQty', 'BATCH_QTY', '每批数量', 'number', 7, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'costBatch', 'COST_BATCH', '包材成本', 'number', 8, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'apexFactoryname', 'APEX_FACTORYNAME', '包材供应商', 'text', 9, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, IS_VIRTUAL, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_package_id, 'formulaType', 'FORMULA_TYPE', '公式类型', 'text', 10, 1, 'system');
    COMMIT;
END;
/

-- 产品选择弹窗元数据
DECLARE
    v_lookup_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_lookup_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, PK_COLUMN, CREATE_BY)
    VALUES (v_lookup_id, 'CostGoodsLookup', '产品选择', 'V_COST_GOODS_LOOKUP', 'T_COST_GOODS', 'GOODSID', 'system');

    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'goodsid', 'GOODSID', '产品ID', 'number', 0, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'goodsname', 'GOODSNAME', '产品名称', 'text', 1, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'maNo', 'MA_NO', '批准文号', 'text', 2, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'apexPl', 'APEX_PL', '批量', 'number', 3, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'mah', 'MAH', '持证商', 'text', 4, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'pPerpack', 'P_PERPACK', '每盒片数', 'number', 5, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'sPerback', 'S_PERBACK', '每箱装盒数', 'number', 6, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'customid', 'CUSTOMID', '客户ID', 'number', 7, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'customname', 'CUSTOMNAME', '客户名称', 'text', 8, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'memo', 'MEMO', 'BOM状态', 'text', 9, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'strength', 'STRENGTH', '剂量', 'text', 10, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'livery', 'LIVERY', '分销商', 'text', 11, 'system');
    COMMIT;
END;
/

-- 客户选择弹窗元数据
DECLARE
    v_lookup_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_lookup_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, PK_COLUMN, CREATE_BY)
    VALUES (v_lookup_id, 'CostCustomerLookup', '客户选择', 'V_COST_CUSTOMER_LOOKUP', 'T_COST_CUSTOMER_V', 'CUSTOMID', 'system');

    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'customid', 'CUSTOMID', '客户ID', 'number', 0, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'customname', 'CUSTOMNAME', '客户名称', 'text', 1, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'country', 'COUNTRY', '国家', 'text', 2, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, CREATE_BY) VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_lookup_id, 'livery', 'LIVERY', '分销商', 'text', 3, 'system');
    COMMIT;
END;
/

-- =====================================================
-- F. 插入Lookup配置
-- =====================================================
-- 产品选择（使用专用Lookup视图，显示全部12列）
INSERT INTO T_COST_LOOKUP_CONFIG (ID, LOOKUP_CODE, LOOKUP_NAME, DATA_SOURCE, DISPLAY_COLUMNS, SEARCH_COLUMNS, VALUE_FIELD, LABEL_FIELD, CREATE_BY)
VALUES (SEQ_COST_LOOKUP_CONFIG.NEXTVAL, 'costGoods', '产品选择', 'CostGoodsLookup',
  '[{"field":"goodsid","header":"产品ID","width":80},{"field":"goodsname","header":"产品名称","width":200},{"field":"maNo","header":"批准文号","width":150},{"field":"apexPl","header":"批量","width":80},{"field":"mah","header":"持证商","width":150},{"field":"pPerpack","header":"每盒片数","width":100},{"field":"sPerback","header":"每箱装盒数","width":100},{"field":"customid","header":"客户ID","width":80},{"field":"customname","header":"客户名称","width":150},{"field":"memo","header":"BOM状态","width":120},{"field":"strength","header":"剂量","width":100},{"field":"livery","header":"分销商","width":150}]',
  '["goodsname","customname","maNo"]', 'goodsid', 'goodsname', 'system');

-- 物料选择（从物料清单及成本中选择）
INSERT INTO T_COST_LOOKUP_CONFIG (ID, LOOKUP_CODE, LOOKUP_NAME, DATA_SOURCE, DISPLAY_COLUMNS, SEARCH_COLUMNS, VALUE_FIELD, LABEL_FIELD, CREATE_BY)
VALUES (SEQ_COST_LOOKUP_CONFIG.NEXTVAL, 'costMaterial', '物料选择', 'CostGoodsPrice',
  '[{"field":"goodsname","header":"物料名称","width":200},{"field":"useflag","header":"用途","width":80},{"field":"goodstype","header":"规格","width":150},{"field":"price","header":"单价","width":100},{"field":"factoryname","header":"供应商","width":150}]',
  '["goodsname","factoryname"]', 'goodsid', 'goodsname', 'system');

-- 币种选择（从外币管理中选择）
INSERT INTO T_COST_LOOKUP_CONFIG (ID, LOOKUP_CODE, LOOKUP_NAME, DATA_SOURCE, DISPLAY_COLUMNS, SEARCH_COLUMNS, VALUE_FIELD, LABEL_FIELD, CREATE_BY)
VALUES (SEQ_COST_LOOKUP_CONFIG.NEXTVAL, 'formoney', '币种选择', 'CostFormoney',
  '[{"field":"fmname","header":"币种名称","width":150},{"field":"fmrate","header":"汇率","width":100},{"field":"fmsign","header":"符号","width":80}]',
  '["fmname"]', 'fmid', 'fmname', 'system');

-- 客户选择（从客户信息中选择）
INSERT INTO T_COST_LOOKUP_CONFIG (ID, LOOKUP_CODE, LOOKUP_NAME, DATA_SOURCE, DISPLAY_COLUMNS, SEARCH_COLUMNS, VALUE_FIELD, LABEL_FIELD, CREATE_BY)
VALUES (SEQ_COST_LOOKUP_CONFIG.NEXTVAL, 'costCustomer', '客户选择', 'CostCustomerLookup',
  '[{"field":"customid","header":"客户ID","width":80},{"field":"customname","header":"客户名称","width":200},{"field":"country","header":"国家","width":100},{"field":"livery","header":"分销商","width":150}]',
  '["customname"]', 'customid', 'customname', 'system');

COMMIT;

-- =====================================================
-- G. 插入页面规则
-- =====================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'masterGrid', 'COLUMN_OVERRIDE', '[{"field":"id","visible":false,"editable":false},{"field":"goodsname","width":null,"editable":true,"searchable":true},{"field":"goodsnameEn","width":null,"editable":true},{"field":"strength","width":null,"editable":true},{"field":"customname","width":null,"editable":true,"searchable":true},{"field":"country","width":null,"editable":true},{"field":"projectno","width":null,"editable":true},{"field":"apexPl","width":null,"editable":true},{"field":"annualQty","width":null,"editable":true},{"field":"yield","width":null,"editable":true},{"field":"pPerpack","width":null,"editable":true},{"field":"sPerback","width":null,"editable":true},{"field":"xPerback","width":null,"editable":true},{"field":"packtype","width":null,"editable":true},{"field":"totalYl","width":null,"editable":false},{"field":"totalFl","width":null,"editable":false},{"field":"totalBc","width":null,"editable":false},{"field":"totalCost","width":null,"editable":false},{"field":"outPriceRmb","width":null,"editable":true},{"field":"salemoney","width":null,"editable":false},{"field":"jgfBatch","width":null,"editable":false},{"field":"costPerqp","width":null,"editable":true},{"field":"jgfPerqp","width":null,"editable":false},{"field":"mlPerqp","width":null,"editable":false},{"field":"yJgRe","width":null,"editable":false},{"field":"yMl","width":null,"editable":false},{"field":"ySale","width":null,"editable":false},{"field":"fmname","width":null,"editable":true},{"field":"fmrate","width":null,"editable":true}]', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'masterGrid', 'VALIDATION', '[]', 'system');

-- 主表计算规则
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'masterGrid', 'CALC',
'[
  {"field":"salemoney","expression":"outPriceRmb / pPerpack * apexPl * (yield / 100)","triggerFields":["outPriceRmb","pPerpack","apexPl","yield"]},
  {"field":"jgfBatch","expression":"salemoney - totalCost","triggerFields":["salemoney","totalCost"]},
  {"field":"jgfPerqp","expression":"jgfBatch / apexPl * 1000","triggerFields":["jgfBatch","apexPl"]},
  {"field":"mlPerqp","expression":"jgfPerqp - costPerqp","triggerFields":["jgfPerqp","costPerqp"]},
  {"field":"yJgRe","expression":"jgfPerqp / 1000 * annualQty","triggerFields":["jgfPerqp","annualQty"]},
  {"field":"yMl","expression":"mlPerqp / 1000 * annualQty","triggerFields":["mlPerqp","annualQty"]},
  {"field":"ySale","expression":"salemoney / apexPl * annualQty","triggerFields":["salemoney","apexPl","annualQty"]}
]', 'system');

-- 主表汇总规则（从明细汇总到主表，含1.13去税逻辑）
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'masterGrid', 'AGGREGATE',
q'~[
  {"sourceField":"costBatch","targetField":"totalYl","algorithm":"SUM","sourceTab":"material","filter":"dtlUseflag === '原料'"},
  {"sourceField":"costBatch","targetField":"totalFl","algorithm":"SUM","sourceTab":"material","filter":"dtlUseflag === '辅料'"},
  {"sourceField":"costBatch","targetField":"totalBc","algorithm":"SUM","sourceTab":"package","filter":"dtlUseflag === '非印字包材' || dtlUseflag === '印字包材'"},
  {"targetField":"totalYl","expression":"totalYl > 0 ? totalYl / 1.13 : totalYl"},
  {"targetField":"totalFl","expression":"totalYl > 0 ? totalFl / 1.13 : totalFl"},
  {"targetField":"totalBc","expression":"totalYl > 0 ? totalBc / 1.13 : totalBc"},
  {"targetField":"totalCost","expression":"totalYl + totalFl + totalBc"}
]~', 'system');

-- 产品选择弹窗（从产品信息维护中选择产成品回填）
-- 币种选择弹窗（从外币管理中选择币种回填）
-- 客户选择弹窗（从客户信息中选择客户回填）
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'masterGrid', 'LOOKUP', '[{"field":"goodsname","lookupCode":"costGoods","mapping":{"goodsid":"goodsid","goodsname":"goodsname","maNo":"maNo","apexPl":"apexPl","mah":"mah","pPerpack":"pPerpack","sPerback":"sPerback","customid":"customid","customname":"customname","memo":"memo","strength":"strength","livery":"livery"}},{"field":"fmname","lookupCode":"formoney","mapping":{"fmname":"fmname","fmrate":"fmrate"}},{"field":"customname","lookupCode":"costCustomer","mapping":{"customid":"customid","customname":"customname","country":"country","livery":"livery"}}]', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'material', 'COLUMN_OVERRIDE', '[{"field":"id","visible":false,"editable":false},{"field":"masterId","visible":false,"editable":false},{"field":"dtlUseflag","width":null,"editable":true,"cellEditor":"agSelectCellEditor","cellEditorParams":{"values":["原料","辅料"]}},{"field":"apexGoodsname","width":null,"editable":true},{"field":"spec","width":null,"editable":true},{"field":"perHl","width":null,"editable":true},{"field":"exaddMater","width":null,"editable":true},{"field":"price","width":null,"editable":true},{"field":"batchQty","width":null,"editable":false},{"field":"costBatch","width":null,"editable":false},{"field":"apexFactoryname","width":null,"editable":true},{"field":"formulaType","visible":false,"editable":false}]', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'material', 'VALIDATION', '[{"field":"perHl","required":true,"min":0.001,"message":"每片含量必填且必须大于0"},{"field":"price","required":true,"min":0,"message":"单价必填且不能为负数"}]', 'system');

-- 原辅料计算规则
-- formulaType: B=辅料+胶囊, C=原料/辅料
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'material', 'CALC',
'[
  {"field":"batchQty","formulaField":"formulaType","formulas":{
    "B":{"expression":"apexPl / 10000","triggerFields":["apexPl"]},
    "C":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]}
  }},
  {"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]}
]', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'material', 'LOOKUP', '[{"field":"apexGoodsname","lookupCode":"costMaterial","mapping":{"apexGoodsid":"goodsid","apexGoodsname":"goodsname","spec":"goodstype","price":"price","apexFactoryname":"factoryname","goodstype":"goodstype","basePrice":"price"}}]', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'package', 'COLUMN_OVERRIDE', '[{"field":"id","visible":true,"editable":false},{"field":"masterId","visible":false,"editable":false},{"field":"dtlUseflag","width":null,"editable":true,"cellEditor":"agSelectCellEditor","cellEditorParams":{"values":["印字包材","非印字包材"]}},{"field":"apexGoodsname","width":null,"editable":true},{"field":"spec","width":null,"editable":true},{"field":"suqty","width":null,"editable":true},{"field":"price","width":null,"editable":true},{"field":"batchQty","width":null,"editable":false},{"field":"costBatch","width":null,"editable":false},{"field":"apexFactoryname","width":null,"editable":true},{"field":"formulaType","visible":false,"editable":false}]', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'package', 'VALIDATION', '[{"field":"price","min":0,"message":"包材单价不能为负数"}]', 'system');

-- 包材计算规则
-- formulaType: A=桶/瓶/盖/说明书/小盒/标签, D=硬片/铝箔/复合膜, E=大纸箱, F=托盘
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'package', 'CALC',
'[
  {"field":"batchQty","formulaField":"formulaType","formulas":{
    "A":{"expression":"apexPl / pPerpack * (1 + exaddMater)","triggerFields":["apexPl","pPerpack","exaddMater"]},
    "D":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]},
    "E":{"expression":"ceil(apexPl / (pPerpack * sPerback))","triggerFields":["apexPl","pPerpack","sPerback"]},
    "F":{"expression":"ceil(apexPl / (pPerpack * sPerback * xPerback))","triggerFields":["apexPl","pPerpack","sPerback","xPerback"]}
  }},
  {"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]}
]', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'package', 'LOOKUP', '[{"field":"apexGoodsname","lookupCode":"costMaterial","mapping":{"apexGoodsid":"goodsid","apexGoodsname":"goodsname","spec":"goodstype","price":"price","apexFactoryname":"factoryname","suqty":"lastsuqty"}}]', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'masterGrid', 'ROLE_BINDING', '{"role":"MASTER_GRID"}', 'system');
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'masterGrid', 'GRID_OPTIONS', '{"cellSelection":true}', 'system');
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'detailTabs', 'ROLE_BINDING', '{"role":"DETAIL_TABS"}', 'system');
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'detailTabs', 'RELATION', '{"masterKey":"masterGrid","detailKey":"detailTabs"}', 'system');
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'detailTabs', 'BROADCAST', '["apexPl","pPerpack","sPerback","xPerback"]', 'system');
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'detailTabs', 'SUMMARY_CONFIG', '{"enabled":true,"groupLabelField":"groupLabel","groupLabelHeader":"分类","summaryColumns":[{"field":"totalAmount","headerName":"汇总金额","width":null},{"field":"rowCount","headerName":"行数","width":null}],"summaryAggregates":[{"sourceField":"costBatch","targetField":"totalAmount","algorithm":"SUM"},{"sourceField":"costBatch","targetField":"rowCount","algorithm":"COUNT"}]}', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'masterGrid', 'CONTEXT_MENU', '{"items":[{"action":"addRow"},{"action":"copyRow","requiresRow":true},{"action":"deleteRow","requiresRow":true},{"type":"separator"},{"action":"saveGridConfig"},{"type":"separator"},{"label":"导出","items":[{"action":"exportSelected","requiresSelection":true},{"action":"exportCurrent"},{"action":"exportAll"},{"type":"separator"},{"action":"resetExportConfig"},{"action":"openHeaderConfig"}]},{"type":"separator"},{"action":"save"},{"type":"separator"},{"action":"clipboard.copy"},{"action":"clipboard.paste"}]}', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'material', 'CONTEXT_MENU', '{"items":[{"action":"addRow"},{"action":"copyRow","requiresRow":true},{"action":"deleteRow","requiresRow":true},{"type":"separator"},{"action":"saveGridConfig"},{"type":"separator"},{"action":"clipboard.copy"},{"action":"clipboard.paste"}]}', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'package', 'CONTEXT_MENU', '{"items":[{"action":"addRow"},{"action":"copyRow","requiresRow":true},{"action":"deleteRow","requiresRow":true},{"type":"separator"},{"action":"saveGridConfig"},{"type":"separator"},{"action":"clipboard.copy"},{"action":"clipboard.paste"}]}', 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, CREATE_BY) VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu', 'detailTabs', 'CONTEXT_MENU', '{"items":[{"action":"addRow"},{"action":"copyRow","requiresRow":true},{"action":"deleteRow","requiresRow":true},{"type":"separator"},{"action":"saveGridConfig"},{"type":"separator"},{"action":"clipboard.copy"},{"action":"clipboard.paste"}]}', 'system');

COMMIT;

-- =====================================================
-- H. 插入页面组件
-- =====================================================
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu', 'root', 'LAYOUT', NULL, 0, '{"direction":"vertical","gap":8}', 'system');

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu', 'masterGrid', 'GRID', 'root', 1, 'CostPinggu', '{"height":"50%","selectionMode":"single"}', 'system');

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu', 'detailTabs', 'TABS', 'root', 2, '{"mode":"multi","tabs":[{"key":"material","title":"原料/辅料","tableCode":"CostMaterial"},{"key":"package","title":"包材","tableCode":"CostPackage"}]}', 'system');

COMMIT;

-- =====================================================
-- I. 插入菜单资源
-- =====================================================
DECLARE
    v_cost_id NUMBER;
BEGIN
    SELECT ID INTO v_cost_id FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'cost-manage' AND ROWNUM = 1;
    INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
    VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'cost-pinggu', '物料成本核算表', 'PAGE', 'cost-pinggu', 'mdi:calculator-variant', '/cost/cost-pinggu', v_cost_id, 1, 'system');
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
        VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'cost-pinggu', '物料成本核算表', 'PAGE', 'cost-pinggu', 'mdi:calculator-variant', '/cost/cost-pinggu', NULL, 1, 'system');
        COMMIT;
END;
/

-- =====================================================
-- J. 导入业务数据（从ERP同步）
-- =====================================================

-- 导入主表数据
INSERT INTO T_COST_PINGGU (
    GOODSID, GOODSNAME, STRENGTH, MA_NO, APEX_PL, MAH, P_PERPACK, FORM, S_PERBACK, PACKTYPE,
    X_PERBACK, TOTAL_FL, TOTAL_BC, TOTAL_YL, MEMO, USESTATUS, DOCID, DOSAGE, ANNUAL_QTY, YIELD,
    TOTAL_COST, OUT_PRICE_F, OUT_PRICE_RMB, SALEMONEY, JGF_BATCH, JGF_PERQP, COST_PERQP, ML_PERQP,
    Y_JG_RE, Y_ML, Y_SALE, CUSTOMID, CUSTOMNAME, COUNTRY, PROJECTNO, USEFLAG, YIELD_TIME, APEX_PL_TIME,
    ZX_SOURCE, FMNAME, FMRATE, GOODSNAME_EN, LIVERY
)
SELECT 
    GOODSID, GOODSNAME, STRENGTH, MA_NO, APEX_PL, MAH, P_PERPACK, FORM, S_PERBACK, PACKTYPE,
    X_PERBACK, TOTAL_FL, TOTAL_BC, TOTAL_YL, MEMO, USESTATUS, DOCID, DOSAGE, ANNUAL_QTY, YIELD,
    TOTAL_COST, OUT_PRICE_F, OUT_PRICE_RMB, SALEMONEY, JGF_BATCH, JGF_PERQP, COST_PERQP, ML_PERQP,
    Y_JG_RE, Y_ML, Y_SALE, CUSTOMID, CUSTOMNAME, COUNTRY, PROJECTNO, USEFLAG, YIELD_TIME, APEX_PL_TIME,
    ZX_SOURCE, FMNAME, FMRATE, GOODSNAME_EN, LIVERY
FROM hy.apex_sa_pinggu m;

-- 导入从表数据
INSERT INTO T_COST_PINGGU_DTL (
    DOCID, APEX_GOODSID, APEX_GOODSNAME, DTL_USEFLAG, SPEC, PER_HL, EXADD_MATER, BATCH_QTY, PRICE,
    COST_BATCH, MEMO, DTLID, APEX_FACTORYNAME, APEX_FACTORYID, MODIFYDATE, ZX_SOURCE, BASE_PRICE,
    SUQTY, GOODSTYPE, GOODSNAME_EN
)
SELECT 
    d.DOCID, d.APEX_GOODSID, d.APEX_GOODSNAME, d.DTL_USEFLAG, d.SPEC, d.PER_HL, d.EXADD_MATER, d.BATCH_QTY, d.PRICE,
    d.COST_BATCH, d.MEMO, d.DTLID, d.APEX_FACTORYNAME, d.APEX_FACTORYID, d.MODIFYDATE, d.ZX_SOURCE, d.BASE_PRICE,
    d.SUQTY, d.GOODSTYPE, d.GOODSNAME_EN
FROM hy.apex_sa_pinggu_dtl d;

COMMIT;
