-- =====================================================
-- 权限相关表重构
-- 1. T_COST_RESOURCE: 统一使用 PAGE_CODE，删除 RESOURCE_CODE，添加 IS_HARDCODED
-- 2. 所有权限表删除审计字段和逻辑删除字段
-- 3. T_COST_ROLE_PAGE 添加 ROW_POLICY 字段（行权限从独立表迁移到此）
-- 4. 删除 T_COST_ROLE_PAGE_DATA_RULE 表（行权限已合并到 T_COST_ROLE_PAGE.ROW_POLICY）
-- =====================================================

-- =====================================================
-- 第一部分：T_COST_RESOURCE 字段重构
-- =====================================================

-- 1. 添加 IS_HARDCODED 字段
ALTER TABLE T_COST_RESOURCE ADD IS_HARDCODED NUMBER(1) DEFAULT 0;

-- 2. 标记硬编码页面（当前 PAGE_CODE 为空的 PAGE 类型）
UPDATE T_COST_RESOURCE 
SET IS_HARDCODED = 1 
WHERE PAGE_CODE IS NULL AND RESOURCE_TYPE = 'PAGE';

-- 3. 硬编码页面的 PAGE_CODE 用 RESOURCE_CODE 填充
UPDATE T_COST_RESOURCE 
SET PAGE_CODE = RESOURCE_CODE 
WHERE PAGE_CODE IS NULL AND RESOURCE_TYPE = 'PAGE';

-- 4. 目录的 PAGE_CODE 也用 RESOURCE_CODE 填充
UPDATE T_COST_RESOURCE 
SET PAGE_CODE = RESOURCE_CODE 
WHERE PAGE_CODE IS NULL AND RESOURCE_TYPE = 'DIRECTORY';

COMMIT;

-- 5. 删除 RESOURCE_CODE 字段
ALTER TABLE T_COST_RESOURCE DROP COLUMN RESOURCE_CODE;

COMMIT;

-- =====================================================
-- 第二部分：删除审计字段和逻辑删除字段
-- =====================================================

-- T_COST_RESOURCE 删除审计字段和逻辑删除
ALTER TABLE T_COST_RESOURCE DROP COLUMN DELETED;
ALTER TABLE T_COST_RESOURCE DROP COLUMN CREATE_BY;
ALTER TABLE T_COST_RESOURCE DROP COLUMN CREATE_TIME;
ALTER TABLE T_COST_RESOURCE DROP COLUMN UPDATE_BY;
ALTER TABLE T_COST_RESOURCE DROP COLUMN UPDATE_TIME;

-- T_COST_ROLE 删除审计字段和逻辑删除
ALTER TABLE T_COST_ROLE DROP COLUMN DELETED;
ALTER TABLE T_COST_ROLE DROP COLUMN CREATE_BY;
ALTER TABLE T_COST_ROLE DROP COLUMN CREATE_TIME;
ALTER TABLE T_COST_ROLE DROP COLUMN UPDATE_BY;
ALTER TABLE T_COST_ROLE DROP COLUMN UPDATE_TIME;

-- T_COST_USER_ROLE 删除审计字段和逻辑删除
ALTER TABLE T_COST_USER_ROLE DROP COLUMN DELETED;
ALTER TABLE T_COST_USER_ROLE DROP COLUMN CREATE_BY;
ALTER TABLE T_COST_USER_ROLE DROP COLUMN CREATE_TIME;
ALTER TABLE T_COST_USER_ROLE DROP COLUMN UPDATE_BY;
ALTER TABLE T_COST_USER_ROLE DROP COLUMN UPDATE_TIME;

-- T_COST_ROLE_PAGE 删除审计字段和逻辑删除
ALTER TABLE T_COST_ROLE_PAGE DROP COLUMN DELETED;
ALTER TABLE T_COST_ROLE_PAGE DROP COLUMN CREATE_BY;
ALTER TABLE T_COST_ROLE_PAGE DROP COLUMN CREATE_TIME;
ALTER TABLE T_COST_ROLE_PAGE DROP COLUMN UPDATE_BY;
ALTER TABLE T_COST_ROLE_PAGE DROP COLUMN UPDATE_TIME;

COMMIT;

-- =====================================================
-- 第三部分：T_COST_ROLE_PAGE 添加 ROW_POLICY 字段
-- =====================================================

ALTER TABLE T_COST_ROLE_PAGE ADD ROW_POLICY VARCHAR2(2000);

COMMIT;

-- =====================================================
-- 第四部分：删除 T_COST_ROLE_PAGE_DATA_RULE 表
-- 行权限已合并到 T_COST_ROLE_PAGE.ROW_POLICY
-- =====================================================

-- 先删除序列
DROP SEQUENCE SEQ_COST_DATA_RULE;

-- 删除表
DROP TABLE T_COST_ROLE_PAGE_DATA_RULE;

COMMIT;

-- =====================================================
-- 第五部分：更新视图（无逻辑删除版本）
-- =====================================================

-- 角色主表视图
CREATE OR REPLACE VIEW V_COST_ROLE AS
SELECT 
    r.ID,
    r.ROLE_CODE,
    r.ROLE_NAME,
    r.DESCRIPTION
FROM T_COST_ROLE r;

-- 角色人员关联视图
-- 注意：T_COST_USER 仍保留逻辑删除
CREATE OR REPLACE VIEW V_COST_USER_ROLE AS
SELECT 
    ur.ID,
    ur.USER_ID,
    u.USERNAME,
    u.REAL_NAME,
    ur.ROLE_ID
FROM T_COST_USER_ROLE ur
LEFT JOIN T_COST_USER u ON ur.USER_ID = u.ID AND u.DELETED = 0;

-- 角色页面关联视图
CREATE OR REPLACE VIEW V_COST_ROLE_PAGE AS
SELECT 
    rp.ID,
    rp.ROLE_ID,
    rp.PAGE_CODE,
    res.RESOURCE_NAME AS PAGE_NAME,
    rp.BUTTON_POLICY,
    rp.COLUMN_POLICY,
    rp.ROW_POLICY
FROM T_COST_ROLE_PAGE rp
LEFT JOIN T_COST_RESOURCE res ON rp.PAGE_CODE = res.PAGE_CODE;

-- 资源权限树视图
CREATE OR REPLACE VIEW V_COST_RESOURCE_PERMISSION AS
SELECT 
    res.ID,
    res.PAGE_CODE,
    res.RESOURCE_NAME,
    res.RESOURCE_TYPE,
    res.IS_HARDCODED,
    res.ICON,
    res.ROUTE,
    res.PARENT_ID,
    res.SORT_ORDER,
    r.ID AS ROLE_ID,
    r.ROLE_CODE,
    r.ROLE_NAME,
    rp.ID AS ROLE_PAGE_ID,
    rp.BUTTON_POLICY,
    rp.COLUMN_POLICY,
    rp.ROW_POLICY,
    CASE WHEN rp.ID IS NOT NULL THEN 1 ELSE 0 END AS IS_AUTHORIZED
FROM T_COST_RESOURCE res
CROSS JOIN T_COST_ROLE r
LEFT JOIN T_COST_ROLE_PAGE rp 
    ON rp.PAGE_CODE = res.PAGE_CODE
    AND rp.ROLE_ID = r.ID
ORDER BY res.SORT_ORDER;

COMMIT;
