-- 项目审批：设置业务接收处理人
-- 用于审批节点动作测试：
--   P_BILL_ID      当前页面主表 ID，固定对应 T_DEMAND_APPLICATION.ID
--   P_PARAMS_JSON  前台传参 JSON，支持 receiverName/name/businessReceiver/handlerName

CREATE OR REPLACE PROCEDURE P_DEMAND_APPROVAL_SET_RECEIVER (
  P_BILL_ID     IN NUMBER,
  P_PARAMS_JSON IN CLOB
) AS
  V_RECEIVER VARCHAR2(200);
BEGIN
  IF P_BILL_ID IS NULL THEN
    RAISE_APPLICATION_ERROR(-20001, '页面主表ID不能为空');
  END IF;

  IF P_PARAMS_JSON IS NOT NULL THEN
    SELECT COALESCE(
             JSON_VALUE(P_PARAMS_JSON, '$.receiverName' RETURNING VARCHAR2(200) NULL ON ERROR),
             JSON_VALUE(P_PARAMS_JSON, '$.name' RETURNING VARCHAR2(200) NULL ON ERROR),
             JSON_VALUE(P_PARAMS_JSON, '$.businessReceiver' RETURNING VARCHAR2(200) NULL ON ERROR),
             JSON_VALUE(P_PARAMS_JSON, '$.handlerName' RETURNING VARCHAR2(200) NULL ON ERROR)
           )
      INTO V_RECEIVER
      FROM DUAL;
  END IF;

  V_RECEIVER := TRIM(V_RECEIVER);
  IF V_RECEIVER IS NULL THEN
    RAISE_APPLICATION_ERROR(-20002, '业务接收处理人不能为空，请在页面参数中传 receiverName 或 name');
  END IF;

  UPDATE T_DEMAND_APPLICATION
     SET BUSINESS_RECEIVER = V_RECEIVER,
         UPDATE_TIME = SYSDATE,
         UPDATE_BY = 'approval-procedure'
   WHERE ID = P_BILL_ID
     AND NVL(DELETED, 0) = 0;

  IF SQL%ROWCOUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20003, '未找到项目审批表单据，ID=' || P_BILL_ID);
  END IF;
END P_DEMAND_APPROVAL_SET_RECEIVER;
/
