-- ============================================================
-- ROW_CLASS → GRID_STYLE 规则类型重命名
-- 统一行颜色、单元格颜色、字体颜色控制
-- ============================================================

-- 1. 备份当前 ROW_CLASS 规则
CREATE TABLE T_COST_PAGE_RULE_BAK_GRIDSTYLE AS
SELECT * FROM T_COST_PAGE_RULE WHERE RULE_TYPE = 'ROW_CLASS' AND DELETED = 0;

-- 2. 将 ROW_CLASS 重命名为 GRID_STYLE
UPDATE T_COST_PAGE_RULE
SET RULE_TYPE = 'GRID_STYLE',
    UPDATE_TIME = SYSTIMESTAMP
WHERE RULE_TYPE = 'ROW_CLASS'
  AND DELETED = 0;

COMMIT;

-- 验证
SELECT ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, SUBSTR(RULES, 1, 80) AS RULES_PREVIEW
FROM T_COST_PAGE_RULE
WHERE RULE_TYPE = 'GRID_STYLE' AND DELETED = 0
ORDER BY ID;
