-- Filtered from 00_schema_tables.sql at 2026-05-23 21:49:44
SET DEFINE OFF;

-- TABLE T_COST_COLUMN_METADATA

  CREATE TABLE "CMX"."T_COST_COLUMN_METADATA" 
   (	"ID" NUMBER(19,0), 
	"TABLE_METADATA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"COLUMN_NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"QUERY_COLUMN" VARCHAR2(128), 
	"TARGET_COLUMN" VARCHAR2(64), 
	"HEADER_TEXT" VARCHAR2(128) NOT NULL ENABLE, 
	"DATA_TYPE" VARCHAR2(32) DEFAULT 'text', 
	"DISPLAY_ORDER" NUMBER(5,0) DEFAULT 0, 
	"SORTABLE" NUMBER(1,0) DEFAULT 1, 
	"FILTERABLE" NUMBER(1,0) DEFAULT 1, 
	"IS_VIRTUAL" NUMBER(1,0) DEFAULT 0, 
	"DICT_TYPE" VARCHAR2(64), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATE_BY" VARCHAR2(64), 
	"UPDATE_BY" VARCHAR2(64), 
	"VISIBLE" NUMBER(1,0) DEFAULT 1, 
	"EDITABLE" NUMBER(1,0) DEFAULT 1, 
	"REQUIRED" NUMBER(1,0) DEFAULT 0, 
	"SEARCHABLE" NUMBER(1,0) DEFAULT 1, 
	"WIDTH" NUMBER(5,0), 
	"PINNED" VARCHAR2(10), 
	"CELL_EDITOR" VARCHAR2(64), 
	"DEFAULT_VALUE" VARCHAR2(1000), 
	"RULES_CONFIG" CLOB, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_COLUMN_TABLE" FOREIGN KEY ("TABLE_METADATA_ID")
	  REFERENCES "CMX"."T_COST_TABLE_METADATA" ("ID") ENABLE
   ) ;
/

-- TABLE T_COST_DEPARTMENT

  CREATE TABLE "CMX"."T_COST_DEPARTMENT" 
   (	"ID" NUMBER(19,0), 
	"DEPT_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(19,0), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_BY" VARCHAR2(64), 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"XXX" NUMBER(5,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("DEPT_CODE")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_DICTIONARY_ITEM

  CREATE TABLE "CMX"."T_COST_DICTIONARY_ITEM" 
   (	"ID" NUMBER(19,0), 
	"TYPE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ITEM_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"ITEM_VALUE" VARCHAR2(200), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"EXTRA_CONFIG" VARCHAR2(1000), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATE_BY" VARCHAR2(64), 
	"UPDATE_BY" VARCHAR2(64), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_DICT_ITEM_TYPE" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "CMX"."T_COST_DICTIONARY_TYPE" ("ID") ENABLE
   ) ;
/

-- TABLE T_COST_DICTIONARY_TYPE

  CREATE TABLE "CMX"."T_COST_DICTIONARY_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"TYPE_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATE_BY" VARCHAR2(64), 
	"UPDATE_BY" VARCHAR2(64), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("TYPE_CODE")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_EXPORT_CONFIG

  CREATE TABLE "CMX"."T_COST_EXPORT_CONFIG" 
   (	"ID" NUMBER(19,0), 
	"EXPORT_CODE" VARCHAR2(100) NOT NULL ENABLE, 
	"EXPORT_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"PAGE_CODE" VARCHAR2(100) NOT NULL ENABLE, 
	"MASTER_SQL" CLOB NOT NULL ENABLE, 
	"MASTER_TABLE_ALIAS" VARCHAR2(50), 
	"PK_COLUMN" VARCHAR2(100), 
	"PAGE_VIEW_ALIAS" VARCHAR2(50) DEFAULT 'p', 
	"PAGE_FK_COLUMN" VARCHAR2(100), 
	"MASTER_LINK_COLUMN" VARCHAR2(100), 
	"COLUMNS" CLOB, 
	"MASTER_SHEET_NAME" VARCHAR2(100) DEFAULT 'master', 
	"DISPLAY_ORDER" NUMBER(5,0) DEFAULT 0, 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_BY" VARCHAR2(64), 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_EXPORT_CONFIG_DETAIL

  CREATE TABLE "CMX"."T_COST_EXPORT_CONFIG_DETAIL" 
   (	"ID" NUMBER(19,0), 
	"EXPORT_CONFIG_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"TAB_KEY" VARCHAR2(100), 
	"SHEET_NAME" VARCHAR2(100), 
	"DETAIL_SQL" CLOB NOT NULL ENABLE, 
	"MASTER_TABLE_ALIAS" VARCHAR2(50), 
	"DETAIL_TABLE_ALIAS" VARCHAR2(50), 
	"DETAIL_LINK_COLUMN" VARCHAR2(100), 
	"COLUMNS" CLOB, 
	"DISPLAY_ORDER" NUMBER(5,0) DEFAULT 0, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_EXPORT_DTL_CONFIG" FOREIGN KEY ("EXPORT_CONFIG_ID")
	  REFERENCES "CMX"."T_COST_EXPORT_CONFIG" ("ID") ENABLE
   ) ;
/

-- TABLE T_COST_LOOKUP_CONFIG

  CREATE TABLE "CMX"."T_COST_LOOKUP_CONFIG" 
   (	"ID" NUMBER(19,0), 
	"LOOKUP_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"LOOKUP_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"DATA_SOURCE" VARCHAR2(200) NOT NULL ENABLE, 
	"DISPLAY_COLUMNS" CLOB, 
	"VALUE_FIELD" VARCHAR2(64) NOT NULL ENABLE, 
	"LABEL_FIELD" VARCHAR2(64) NOT NULL ENABLE, 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATE_BY" VARCHAR2(64), 
	"UPDATE_BY" VARCHAR2(64), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("LOOKUP_CODE")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_PAGE_COMPONENT

  CREATE TABLE "CMX"."T_COST_PAGE_COMPONENT" 
   (	"ID" NUMBER(19,0), 
	"PAGE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"COMPONENT_KEY" VARCHAR2(64) NOT NULL ENABLE, 
	"COMPONENT_TYPE" VARCHAR2(32) NOT NULL ENABLE, 
	"PARENT_KEY" VARCHAR2(64), 
	"COMPONENT_CONFIG" CLOB, 
	"REF_TABLE_CODE" VARCHAR2(64), 
	"SLOT_NAME" VARCHAR2(32), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"DESCRIPTION" VARCHAR2(200), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATE_BY" VARCHAR2(64), 
	"UPDATE_BY" VARCHAR2(64), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_PAGE_RULE

  CREATE TABLE "CMX"."T_COST_PAGE_RULE" 
   (	"ID" NUMBER(19,0), 
	"PAGE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"COMPONENT_KEY" VARCHAR2(64) NOT NULL ENABLE, 
	"RULE_TYPE" VARCHAR2(32) NOT NULL ENABLE, 
	"RULES" CLOB NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"DESCRIPTION" VARCHAR2(200), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATE_BY" VARCHAR2(64), 
	"UPDATE_BY" VARCHAR2(64), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_RESOURCE

  CREATE TABLE "CMX"."T_COST_RESOURCE" 
   (	"ID" NUMBER(19,0), 
	"RESOURCE_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"RESOURCE_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"PAGE_CODE" VARCHAR2(64), 
	"ICON" VARCHAR2(64), 
	"ROUTE" VARCHAR2(128), 
	"PARENT_ID" NUMBER(19,0), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"IS_HARDCODED" NUMBER(1,0) DEFAULT 0, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_ROLE

  CREATE TABLE "CMX"."T_COST_ROLE" 
   (	"ID" NUMBER(19,0), 
	"ROLE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("ROLE_CODE")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_ROLE_PAGE

  CREATE TABLE "CMX"."T_COST_ROLE_PAGE" 
   (	"ID" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PAGE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"BUTTON_POLICY" VARCHAR2(1000), 
	"COLUMN_POLICY" CLOB, 
	"ROW_POLICY" VARCHAR2(2000), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_TABLE_METADATA

  CREATE TABLE "CMX"."T_COST_TABLE_METADATA" 
   (	"ID" NUMBER(19,0), 
	"TABLE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"QUERY_VIEW" VARCHAR2(64), 
	"TARGET_TABLE" VARCHAR2(64) NOT NULL ENABLE, 
	"SEQUENCE_NAME" VARCHAR2(64), 
	"PK_COLUMN" VARCHAR2(64) DEFAULT 'ID', 
	"PARENT_TABLE_CODE" VARCHAR2(64), 
	"PARENT_FK_COLUMN" VARCHAR2(64), 
	"AUDIT_ENABLED" NUMBER(1,0) DEFAULT 0, 
	"VALIDATION_RULES" CLOB, 
	"ACTION_RULES" CLOB, 
	"DESCRIPTION" VARCHAR2(500), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATE_BY" VARCHAR2(64), 
	"UPDATE_BY" VARCHAR2(64), 
	"PAGE_CODE" VARCHAR2(64), 
	"COMPONENT_KEY" VARCHAR2(64), 
	"SOURCE_TABLE_CODE" VARCHAR2(64), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("TABLE_CODE")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_USER

  CREATE TABLE "CMX"."T_COST_USER" 
   (	"ID" NUMBER(19,0), 
	"USERNAME" VARCHAR2(64) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(256) DEFAULT '$2a$10$9hqLChNh3AYaEthrJQJjCuEJRnO/.IOwh1gblXrjDkdPx2utxYRB2', 
	"REAL_NAME" VARCHAR2(128), 
	"EMAIL" VARCHAR2(128), 
	"PHONE" VARCHAR2(32), 
	"DEPARTMENT_ID" NUMBER(19,0), 
	"STATUS" VARCHAR2(32) DEFAULT 'ACTIVE', 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_BY" VARCHAR2(64), 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("USERNAME")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_USER_GRID_CONFIG

  CREATE TABLE "CMX"."T_COST_USER_GRID_CONFIG" 
   (	"ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PAGE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"GRID_KEY" VARCHAR2(64) NOT NULL ENABLE, 
	"CONFIG_DATA" CLOB, 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE T_COST_USER_ROLE

  CREATE TABLE "CMX"."T_COST_USER_ROLE" 
   (	"ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE WF_APPROVAL_DETAIL

  CREATE TABLE "CMX"."WF_APPROVAL_DETAIL" 
   (	"DETAIL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"APPROVAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NODE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"APPROVAL_LEVEL" NUMBER(10,0) NOT NULL ENABLE, 
	"NODE_NAME" VARCHAR2(200), 
	"APPROVAL_MODE" VARCHAR2(20) DEFAULT 'OR' NOT NULL ENABLE, 
	"TARGET_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"TARGET_USER_ID" NUMBER(19,0), 
	"TARGET_USER_NAME" VARCHAR2(128), 
	"TARGET_ROLE_ID" NUMBER(19,0), 
	"TARGET_ROLE_CODE" VARCHAR2(64), 
	"TARGET_ROLE_NAME" VARCHAR2(128), 
	"STATUS" VARCHAR2(30) NOT NULL ENABLE, 
	"OPERATE_USER_ID" NUMBER(19,0), 
	"OPERATE_USERNAME" VARCHAR2(64), 
	"OPERATE_REAL_NAME" VARCHAR2(128), 
	"APPROVE_COMMENT" VARCHAR2(1000), 
	"APPROVE_TIME" TIMESTAMP (6), 
	"OPERATE_TIME" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_BY" VARCHAR2(64), 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ROUND_NO" NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 
	"IS_FORCED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"AUTO_REASON" VARCHAR2(50), 
	 CONSTRAINT "CK_WF_DETAIL_TARGET_TYPE" CHECK (TARGET_TYPE IN ('USER', 'ROLE')) ENABLE, 
	 CONSTRAINT "CK_WF_DETAIL_MODE" CHECK (APPROVAL_MODE IN ('OR', 'AND')) ENABLE, 
	 CONSTRAINT "PK_WF_APPROVAL_DETAIL" PRIMARY KEY ("DETAIL_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CK_WF_DETAIL_STATUS" CHECK (STATUS IN ('WAITING', 'PENDING', 'APPROVED', 'REJECTED', 'SKIPPED', 'CANCELED', 'AUTO_APPROVED')) ENABLE, 
	 CONSTRAINT "FK_WF_DETAIL_MAIN" FOREIGN KEY ("APPROVAL_ID")
	  REFERENCES "CMX"."WF_APPROVAL_MAIN" ("APPROVAL_ID") ENABLE, 
	 CONSTRAINT "FK_WF_DETAIL_NODE" FOREIGN KEY ("NODE_ID")
	  REFERENCES "CMX"."WF_FLOW_NODE" ("NODE_ID") ENABLE, 
	 CONSTRAINT "FK_WF_DETAIL_USER" FOREIGN KEY ("TARGET_USER_ID")
	  REFERENCES "CMX"."T_COST_USER" ("ID") ENABLE, 
	 CONSTRAINT "FK_WF_DETAIL_ROLE" FOREIGN KEY ("TARGET_ROLE_ID")
	  REFERENCES "CMX"."T_COST_ROLE" ("ID") ENABLE, 
	 CONSTRAINT "FK_WF_DETAIL_OPER_USER" FOREIGN KEY ("OPERATE_USER_ID")
	  REFERENCES "CMX"."T_COST_USER" ("ID") ENABLE
   ) ;
/

-- TABLE WF_APPROVAL_LOG

  CREATE TABLE "CMX"."WF_APPROVAL_LOG" 
   (	"LOG_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"APPROVAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"DETAIL_ID" NUMBER(19,0), 
	"ACTION_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"ACTION_USER_ID" NUMBER(19,0), 
	"ACTION_USERNAME" VARCHAR2(64), 
	"ACTION_REAL_NAME" VARCHAR2(128), 
	"ACTION_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"FROM_STATUS" VARCHAR2(30), 
	"TO_STATUS" VARCHAR2(30), 
	"ACTION_COMMENT" VARCHAR2(1000), 
	"DETAIL_MESSAGE" VARCHAR2(2000), 
	"ROUND_NO" NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "PK_WF_APPROVAL_LOG" PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_WF_LOG_MAIN" FOREIGN KEY ("APPROVAL_ID")
	  REFERENCES "CMX"."WF_APPROVAL_MAIN" ("APPROVAL_ID") ENABLE, 
	 CONSTRAINT "FK_WF_LOG_DETAIL" FOREIGN KEY ("DETAIL_ID")
	  REFERENCES "CMX"."WF_APPROVAL_DETAIL" ("DETAIL_ID") ENABLE, 
	 CONSTRAINT "FK_WF_LOG_USER" FOREIGN KEY ("ACTION_USER_ID")
	  REFERENCES "CMX"."T_COST_USER" ("ID") ENABLE
   ) ;
/

-- TABLE WF_APPROVAL_MAIN

  CREATE TABLE "CMX"."WF_APPROVAL_MAIN" 
   (	"APPROVAL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"FLOW_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PAGE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"PAGE_NAME" VARCHAR2(128), 
	"TABLE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"BILL_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BILL_NO" VARCHAR2(100), 
	"BILL_TITLE" VARCHAR2(500), 
	"START_USER_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"START_USERNAME" VARCHAR2(64), 
	"START_REAL_NAME" VARCHAR2(128), 
	"START_DEPT_ID" NUMBER(19,0), 
	"START_DEPT_NAME" VARCHAR2(128), 
	"START_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"STATUS" VARCHAR2(30) NOT NULL ENABLE, 
	"CURRENT_LEVEL" NUMBER(10,0), 
	"APPROVED_TIME" TIMESTAMP (6), 
	"REJECTED_TIME" TIMESTAMP (6), 
	"CANCELED_TIME" TIMESTAMP (6), 
	"FINISHED_TIME" TIMESTAMP (6), 
	"CONDITION_JSON" CLOB, 
	"BUSINESS_SNAPSHOT" CLOB, 
	"REMARK" VARCHAR2(1000), 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_BY" VARCHAR2(64), 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CURRENT_ROUND" NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "CK_WF_MAIN_STATUS" CHECK (STATUS IN ('DRAFT', 'APPROVING', 'APPROVED', 'REJECTED', 'CANCELED')) ENABLE, 
	 CONSTRAINT "PK_WF_APPROVAL_MAIN" PRIMARY KEY ("APPROVAL_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_WF_MAIN_FLOW" FOREIGN KEY ("FLOW_ID")
	  REFERENCES "CMX"."WF_FLOW_DEF" ("FLOW_ID") ENABLE, 
	 CONSTRAINT "FK_WF_MAIN_USER" FOREIGN KEY ("START_USER_ID")
	  REFERENCES "CMX"."T_COST_USER" ("ID") ENABLE, 
	 CONSTRAINT "FK_WF_MAIN_DEPT" FOREIGN KEY ("START_DEPT_ID")
	  REFERENCES "CMX"."T_COST_DEPARTMENT" ("ID") ENABLE
   ) ;
/

-- TABLE WF_FLOW_APPROVER

  CREATE TABLE "CMX"."WF_FLOW_APPROVER" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NODE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"APPLY_DEPT_ID" NUMBER(19,0), 
	"APPLY_DEPT_NAME" VARCHAR2(128), 
	"TARGET_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"TARGET_USER_ID" NUMBER(19,0), 
	"TARGET_USER_NAME" VARCHAR2(128), 
	"TARGET_ROLE_ID" NUMBER(19,0), 
	"TARGET_ROLE_CODE" VARCHAR2(64), 
	"TARGET_ROLE_NAME" VARCHAR2(128), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"IS_ENABLED" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_BY" VARCHAR2(64), 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CONDITION_MODE" VARCHAR2(20) DEFAULT 'ALWAYS' NOT NULL ENABLE, 
	"LOGIC_TREE" CLOB, 
	"SQL_EXPR" CLOB, 
	"ON_ERROR" VARCHAR2(30) DEFAULT 'REQUIRE_APPROVAL' NOT NULL ENABLE, 
	 CONSTRAINT "CK_WF_APPROVER_TYPE" CHECK (TARGET_TYPE IN ('USER', 'ROLE')) ENABLE, 
	 CONSTRAINT "CK_WF_APPROVER_ENABLED" CHECK (IS_ENABLED IN (0, 1)) ENABLE, 
	 CONSTRAINT "CK_WF_APPROVER_TARGET" CHECK (
    (TARGET_TYPE = 'USER' AND TARGET_USER_ID IS NOT NULL AND TARGET_ROLE_ID IS NULL)
    OR
    (TARGET_TYPE = 'ROLE' AND TARGET_ROLE_ID IS NOT NULL AND TARGET_USER_ID IS NULL)
  ) ENABLE, 
	 CONSTRAINT "PK_WF_FLOW_APPROVER" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_WF_APPROVER_NODE" FOREIGN KEY ("NODE_ID")
	  REFERENCES "CMX"."WF_FLOW_NODE" ("NODE_ID") ENABLE, 
	 CONSTRAINT "FK_WF_APPROVER_DEPT" FOREIGN KEY ("APPLY_DEPT_ID")
	  REFERENCES "CMX"."T_COST_DEPARTMENT" ("ID") ENABLE, 
	 CONSTRAINT "FK_WF_APPROVER_USER" FOREIGN KEY ("TARGET_USER_ID")
	  REFERENCES "CMX"."T_COST_USER" ("ID") ENABLE, 
	 CONSTRAINT "FK_WF_APPROVER_ROLE" FOREIGN KEY ("TARGET_ROLE_ID")
	  REFERENCES "CMX"."T_COST_ROLE" ("ID") ENABLE
   ) ;
/

-- TABLE WF_FLOW_CONDITION

  CREATE TABLE "CMX"."WF_FLOW_CONDITION" 
   (	"CONDITION_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"FLOW_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CONDITION_NAME" VARCHAR2(200) DEFAULT '默认条件' NOT NULL ENABLE, 
	"CONDITION_MODE" VARCHAR2(20) DEFAULT 'VISUAL' NOT NULL ENABLE, 
	"LOGIC_TREE" CLOB, 
	"SQL_EXPR" CLOB, 
	"ON_ERROR" VARCHAR2(30) DEFAULT 'REQUIRE_APPROVAL' NOT NULL ENABLE, 
	"IS_ENABLED" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_BY" VARCHAR2(64), 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 CONSTRAINT "CK_WF_COND_MODE" CHECK (CONDITION_MODE IN ('VISUAL', 'SQL', 'ALWAYS')) ENABLE, 
	 CONSTRAINT "CK_WF_COND_ON_ERROR" CHECK (ON_ERROR IN ('REQUIRE_APPROVAL', 'BLOCK')) ENABLE, 
	 CONSTRAINT "CK_WF_COND_ENABLED" CHECK (IS_ENABLED IN (0, 1)) ENABLE, 
	 CONSTRAINT "PK_WF_FLOW_CONDITION" PRIMARY KEY ("CONDITION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_WF_COND_FLOW" FOREIGN KEY ("FLOW_ID")
	  REFERENCES "CMX"."WF_FLOW_DEF" ("FLOW_ID") ENABLE
   ) ;
/

-- TABLE WF_FLOW_DEF

  CREATE TABLE "CMX"."WF_FLOW_DEF" 
   (	"FLOW_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PAGE_CODE" VARCHAR2(64) NOT NULL ENABLE, 
	"PAGE_NAME" VARCHAR2(128), 
	"FLOW_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"FLOW_VERSION" NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 
	"IS_ENABLED" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"REMARK" VARCHAR2(1000), 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_BY" VARCHAR2(64), 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"FLOW_PRIORITY" NUMBER(10,0) DEFAULT 100 NOT NULL ENABLE, 
	 CONSTRAINT "CK_WF_FLOW_DEF_ENABLED" CHECK (IS_ENABLED IN (0, 1)) ENABLE, 
	 CONSTRAINT "PK_WF_FLOW_DEF" PRIMARY KEY ("FLOW_ID")
  USING INDEX  ENABLE
   ) ;
/

-- TABLE WF_FLOW_NODE

  CREATE TABLE "CMX"."WF_FLOW_NODE" 
   (	"NODE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"FLOW_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"APPROVAL_LEVEL" NUMBER(10,0) NOT NULL ENABLE, 
	"NODE_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"APPROVAL_MODE" VARCHAR2(20) DEFAULT 'OR' NOT NULL ENABLE, 
	"IS_ENABLED" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_BY" VARCHAR2(64), 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CONDITION_MODE" VARCHAR2(20) DEFAULT 'ALWAYS' NOT NULL ENABLE, 
	"LOGIC_TREE" CLOB, 
	"SQL_EXPR" CLOB, 
	"ON_ERROR" VARCHAR2(30) DEFAULT 'REQUIRE_APPROVAL' NOT NULL ENABLE, 
	"ACTION_CONFIG" CLOB, 
	 CONSTRAINT "CK_WF_NODE_MODE" CHECK (APPROVAL_MODE IN ('OR', 'AND')) ENABLE, 
	 CONSTRAINT "CK_WF_NODE_ENABLED" CHECK (IS_ENABLED IN (0, 1)) ENABLE, 
	 CONSTRAINT "PK_WF_FLOW_NODE" PRIMARY KEY ("NODE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_WF_NODE_FLOW" FOREIGN KEY ("FLOW_ID")
	  REFERENCES "CMX"."WF_FLOW_DEF" ("FLOW_ID") ENABLE
   ) ;
/

