-- Generated by scripts/OracleSqlExporter.java at 2026-05-23T15:45:26.346167100
SET DEFINE OFF;

-- VIEW ERP_FORMONEY_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."ERP_FORMONEY_V" ("FMID", "FMOPCODE", "FMNAME", "FMSIGN", "FMUNIT", "FMRATE", "USESTATUS", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY") AS 
  SELECT
       DECODE(b.fmid,     NULL, a.fmid,     b.fmid)     fmid,
       DECODE(b.fmopcode, NULL, a.fmopcode, b.fmopcode) fmopcode,
       DECODE(b.fmname,   NULL, a.fmname,   b.fmname)   fmname,
       DECODE(b.fmsign,   NULL, a.fmsign,   b.fmsign)   fmsign,
       DECODE(b.fmunit,   NULL, a.fmunit,   b.fmunit)   fmunit,
       DECODE(b.fmrate,   NULL, a.fmrate,   b.fmrate)   fmrate,
       DECODE(b.usestatus,NULL, a.usestatus,b.usestatus) usestatus,
       NVL(b.deleted, 0)  deleted,
       b.create_time,
       b.update_time,
       b.create_by,
       b.update_by
  FROM pub_formoney_v@hyerp a, T_COST_FORMONEY b
 WHERE a.fmid = b.fmid(+)
;
/

-- VIEW PUB_GOODS_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."PUB_GOODS_V" ("GOODSID", "GOODSNAME", "GOODSNO", "PRICE", "SUQTY", "USEFLAG", "FACTORYNAME", "STANDARDTYPE", "ZX_PL", "ZX_MINIMUM", "APPROVEDOCNO", "BASEUNITQTY", "ZX_CUSTOMERID", "CUSTOMNAME", "TARGETMARKET", "HOLDERSNAME", "ISERP", "GOODSTYPE", "PACKTYPE", "TRANPOSNAME", "BOMID", "LASTSUQTY", "TRANPOSID") AS 
  SELECT B.GOODSID ,
       B.GOODSNAME ,b.GOODSNO,
       c.lastprice PRICE,
       c.lastsuqty suqty,
       (case
         when b.zx_wms_goodsclass in (1, 12) and b.gspflag = 1 and
              b.goodsno like '%A%' then
          '原料'
         when b.zx_wms_goodsclass in (10) and b.gspflag = 1 then
          '产成品'
         when b.zx_wms_goodsclass in (7, 8, 9) and b.gspflag = 1 then
          '半成品'
         when b.zx_wms_goodsclass in (5, 13) and b.gspflag = 1 then
          '非印字包材'
         when b.zx_wms_goodsclass in (6) and b.gspflag = 1 then
          '印字包材'
         when b.zx_wms_goodsclass in (1, 2, 3, 4) and b.gspflag = 1 and
              b.goodsno not like '%A%' then
          '辅料'
       end) USEFLAG,
       B.FACTORYNAME,
       B.standardtype,
       b.zx_pl,
       b.zx_minimum,
       b.approvedocno, --批准文号
       e.baseunitqty,
       b.zx_customerid,
       b.customname,
       f.targetmarket,
       b.holdersname,
       1 ISERP,
       b.goodstype,
       b.packtype,
       b.tranposname,
       d.bomid,
       c.lastsuqty,
       b.tranposid
  FROM PUB_GOODS_V@hyerp            B,
       bms_su_supplygoods_doc@Hyerp c,
       MPCS_PR_BOM_DOC@Hyerp        d,
       pub_goods_unit_v@hyerp       e,
       bms_tr_pos_def@hyerp         f
 where B.GOODSID = C.GOODSID(+)
   and b.goodsid = d.pgoodsid(+)
   and d.usestatus(+) = 1
   and b.usestatus = 1
   and c.entryid(+) = 1
   and b.goodsid = e.goodsid(+)
   and e.goodsdtlflag(+) = 1
   and e.baseflag(+) <> 1
   and b.goodsid < 1000000
   and b.zx_customerid = f.companyid(+)
   and b.tranposid = f.tranposid(+)
;
/

-- VIEW T_COST_BOM_GOODS_TREE_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_COST_BOM_GOODS_TREE_V" ("TREEID", "PID", "GOODSID", "GOODSNAME", "USEFLAG", "STANDARDTYPE", "LVCODE", "USEQTY", "ENTRYID") AS 
  select a.treeid,
       a.pid,
       a.goodsid,
       b.goodsname,
       (case
         when b.zx_wms_goodsclass in (1, 12) and b.gspflag = 1 and
              b.goodsno like '%A%' then
          '4'
         when b.zx_wms_goodsclass in (10) and b.gspflag = 1 then
          '0'
         when b.zx_wms_goodsclass in (7, 8, 9) and b.gspflag = 1 then
          '1'
         when b.zx_wms_goodsclass in (5, 13) and b.gspflag = 1 then
          '3'
         when b.zx_wms_goodsclass in (6) and b.gspflag = 1 then
          '5'
         when b.zx_wms_goodsclass in (1, 2, 3, 4) and b.gspflag = 1 and
              b.goodsno not like '%A%' then
          '2'
       end) useflag,
       b.standardtype,
       a.lvcode,
       a.useqty,
       a.entryid
  from MPCS_MRP_GOODS_TREE_V@HYERP a, pub_goods@HYERP b
 where a.goodsid = b.goodsid
;
/

-- VIEW T_COST_CUSTOMER_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_COST_CUSTOMER_V" ("CUSTOMID", "CUSTOMNAME", "ZONE", "ISERP", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY") AS 
  SELECT CUSTOMID,
       CUSTOMNAME,
       ZONE,
       ISERP,
       DELETED,
       CREATE_TIME,
       UPDATE_TIME,
       CREATE_BY,
       UPDATE_BY
  FROM T_COST_CUSTOMER
 WHERE DELETED = 0
;
/

-- VIEW T_COST_FORMONEY_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_COST_FORMONEY_V" ("FMID", "FMOPCODE", "FMNAME", "FMSIGN", "FMUNIT", "FMRATE", "USESTATUS", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY") AS 
  SELECT
    a.FMID,
    NVL(a.FMOPCODE, b.FMOPCODE) AS FMOPCODE,
    NVL(a.FMNAME, b.FMNAME) AS FMNAME,
    NVL(a.FMSIGN, b.FMSIGN) AS FMSIGN,
    NVL(a.FMUNIT, b.FMUNIT) AS FMUNIT,
    NVL(a.FMRATE, b.FMRATE) AS FMRATE,
    a.USESTATUS,
    a.DELETED,
    a.CREATE_TIME,
    a.UPDATE_TIME,
    a.CREATE_BY,
    a.UPDATE_BY
FROM T_COST_FORMONEY a
LEFT JOIN pub_formoney_v@hyerp b ON a.FMID = b.FMID
WHERE a.DELETED = 0 OR a.DELETED IS NULL
;
/

-- VIEW T_COST_GOODS_PRICE_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_COST_GOODS_PRICE_V" ("GOODSID", "GOODSNAME", "PRICE", "USEFLAG", "GOODSTYPE", "PACKTYPE", "FACTORYNAME", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY", "ISERP", "ROW_CLASS_FLAG", "STANDARDTYPE", "GOODSNAME_EN") AS 
  SELECT GOODSID,
       GOODSNAME,
       PRICE,
       USEFLAG,
       GOODSTYPE,
       PACKTYPE,
       FACTORYNAME,
       DELETED,
       CREATE_TIME,
       UPDATE_TIME,
       CREATE_BY,
       UPDATE_BY,
       ISERP,
       CASE
           WHEN ISERP = 1
            AND UPDATE_BY <> 'ERP_SYNC'
            AND PRICE IS NULL THEN 'erp-price-null'
           WHEN ISERP = 1
            AND UPDATE_BY <> 'ERP_SYNC' THEN 'erp-updated'
           WHEN ISERP = 1 THEN 'erp'
           ELSE NULL
       END AS ROW_CLASS_FLAG,
       STANDARDTYPE,
       GOODSNAME_EN
  FROM T_COST_GOODS WHERE USEFLAG NOT IN ('产成品','半成品')
;
/

-- VIEW T_COST_GOODS_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_COST_GOODS_V" ("GOODSID", "GOODSNO", "GOODSNAME", "PRICE", "SUQTY", "USEFLAG", "FACTORYNAME", "STANDARDTYPE", "ZX_PL", "ZX_MINIMUM", "APPROVEDOCNO", "BASEUNITQTY", "ZX_CUSTOMERID", "CUSTOMNAME", "TARGETMARKET", "HOLDERSNAME", "ISERP", "GOODSTYPE", "PACKTYPE", "TRANPOSNAME", "BOMID", "LASTSUQTY", "TRANPOSID", "ZONE", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY") AS 
  SELECT a.GOODSID,
       a.GOODSNO,
       a.GOODSNAME,
       a.PRICE,
       a.SUQTY,
       a.USEFLAG,
       a.FACTORYNAME,
       a.STANDARDTYPE,
       a.ZX_PL,
       a.ZX_MINIMUM,
       a.APPROVEDOCNO,
       a.BASEUNITQTY,
       a.ZX_CUSTOMERID,
       b.CUSTOMNAME,
       a.TARGETMARKET,
       a.HOLDERSNAME,
       a.ISERP,
       a.GOODSTYPE,
       a.PACKTYPE,
       c.TRANPOSNAME,
       a.BOMID,
       a.LASTSUQTY,
       a.TRANPOSID,
       b.ZONE,
       a.DELETED,
       a.CREATE_TIME,
       a.UPDATE_TIME,
       a.CREATE_BY,
       a.UPDATE_BY
  FROM T_COST_GOODS a, T_COST_CUSTOMER b, T_COST_TRANPOSER c
 WHERE a.USEFLAG = '产成品'
   AND a.DELETED = 0
   AND a.ZX_CUSTOMERID = b.CUSTOMID(+)
   AND a.TRANPOSID = c.TRANPOSID(+)
;
/

-- VIEW T_COST_PINGGU_DTL_LQ_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_COST_PINGGU_DTL_LQ_V" ("DOCID", "GOODSID", "GOODSNAME", "DTL_USEFLAG", "STANDARDTYPE", "PER_HL", "EXADD_MATER", "BATCH_QTY", "PRICE", "COST_BATCH", "MEMO", "DTLID", "FACTORYNAME", "FACTORYID", "MODIFYDATE", "BASE_PRICE", "SUQTY", "GOODSTYPE", "GOODSNAME_EN", "APEX_PL", "P_PERPACK", "S_PERBACK", "X_PERBACK", "M_PERPACK") AS 
  select a.docid,
       a.goodsid,
       a.goodsname,
       a.dtl_useflag,
       a.standardtype,
       a.per_hl,
       a.exadd_mater,
       a.batch_qty,
       a.price,
       a.cost_batch,
       a.memo,
       a.dtlid,
       a.factoryname,
       a.factoryid,
       a.modifydate,
       a.base_price,
       a.suqty,
       a.goodstype,
       a.goodsname_en,
       b.APEX_PL,
       b.P_PERPACK,
       b.S_PERBACK,
       b.X_PERBACK,
       b.m_Perpack
  from t_cost_pinggu_dtl_lq a, t_cost_pinggu_lq b
 where a.docid = b.docid
;
/

-- VIEW T_COST_PINGGU_DTL_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_COST_PINGGU_DTL_V" ("DOCID", "GOODSID", "GOODSNAME", "DTL_USEFLAG", "STANDARDTYPE", "PER_HL", "EXADD_MATER", "BATCH_QTY", "PRICE", "COST_BATCH", "MEMO", "DTLID", "FACTORYNAME", "FACTORYID", "MODIFYDATE", "BASE_PRICE", "SUQTY", "GOODSTYPE", "GOODSNAME_EN", "APEX_PL", "P_PERPACK", "S_PERBACK", "X_PERBACK", "M_PERPACK") AS 
  select a.docid,
       a.goodsid,
       a.goodsname,
       a.dtl_useflag,
       a.standardtype,
       a.per_hl,
       a.exadd_mater,
       a.batch_qty,
       a.price,
       a.cost_batch,
       a.memo,
       a.dtlid,
       a.factoryname,
       a.factoryid,
       a.modifydate,
       a.base_price,
       a.suqty,
       a.goodstype,
       a.goodsname_en,
       b.APEX_PL,
       b.P_PERPACK,
       b.S_PERBACK,
       b.X_PERBACK,
       b.m_Perpack
  from t_cost_pinggu_dtl a, t_cost_pinggu b
 where a.docid = b.docid
;
/

-- VIEW T_COST_PINGGU_DTL__LQ_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_COST_PINGGU_DTL__LQ_V" ("DOCID", "GOODSID", "GOODSNAME", "DTL_USEFLAG", "STANDARDTYPE", "PER_HL", "EXADD_MATER", "BATCH_QTY", "PRICE", "COST_BATCH", "MEMO", "DTLID", "FACTORYNAME", "FACTORYID", "MODIFYDATE", "BASE_PRICE", "SUQTY", "GOODSTYPE", "GOODSNAME_EN", "APEX_PL", "P_PERPACK", "S_PERBACK", "X_PERBACK", "M_PERPACK") AS 
  select a.docid,
       a.goodsid,
       a.goodsname,
       a.dtl_useflag,
       a.standardtype,
       a.per_hl,
       a.exadd_mater,
       a.batch_qty,
       a.price,
       a.cost_batch,
       a.memo,
       a.dtlid,
       a.factoryname,
       a.factoryid,
       a.modifydate,
       a.base_price,
       a.suqty,
       a.goodstype,
       a.goodsname_en,
       b.APEX_PL,
       b.P_PERPACK,
       b.S_PERBACK,
       b.X_PERBACK,
       b.m_Perpack
  from t_cost_pinggu_dtl a, t_cost_pinggu b
 where a.docid = b.docid
;
/

-- VIEW T_COST_TRANPOSER_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_COST_TRANPOSER_V" ("CUSTOMID", "TRANPOSID", "TRANPOSNAME", "ISERP", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY") AS 
  SELECT CUSTOMID,
       TRANPOSID,
       TRANPOSNAME,
       ISERP,
       DELETED,
       CREATE_TIME,
       UPDATE_TIME,
       CREATE_BY,
       UPDATE_BY
  FROM T_COST_TRANPOSER
 WHERE DELETED = 0
;
/

-- VIEW T_WMS_CON_DOC_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_WMS_CON_DOC_V" ("CONID", "CONNO", "CUSTOMNAME", "TARGETPOSNAME", "INPUTMANNAME", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY") AS 
  SELECT a.conid,
       a.conno,
       a.customname,
       a.targetposname,
       a.inputmanname,
       0 AS DELETED,
       NULL AS CREATE_TIME,
       NULL AS UPDATE_TIME,
       NULL AS CREATE_BY,
       NULL AS UPDATE_BY
  FROM bms_sa_con_doc_v@hyerp a
;
/

-- VIEW T_WMS_QTY_DETAIL_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_WMS_QTY_DETAIL_V" ("RN", "CONID", "GOODSID", "GOODSNAME", "LOTNO", "GOODSQTY", "PCS", "VALIDDATE", "CONTAINERNO", "MEMO", "JZ", "MZ", "TJ", "DELETED") AS 
  SELECT
    ROW_NUMBER() OVER (PARTITION BY a.conid ORDER BY b.containerno, a.goodsid, a.lotno) AS rn,
    a.conid,
    a.goodsid,
    a.goodsname,
    a.lotno,
    b.goodsqty,
    b.pcs,
    b.validdate,
    b.containerno,
    null memo,
    NULL AS jz,
    NULL AS mz,
    NULL AS tj,
    0 AS DELETED
FROM (
    SELECT a.conid, a.goodsid, a.goodsno, a.goodsname, a.lotno, a.packtype
    FROM bms_sa_con_dtl_v@hyerp a
    GROUP BY a.conid, a.goodsid, a.goodsno, a.goodsname, a.lotno, a.packtype
) a,
(
    SELECT
        x.goodsownid,
        x.lotno,
        x.packname,
        x.packsize,
        x.goodsqty,
        x.validdate,
        CEIL(x.goodsqty / x.packsize) AS pcs,
        x.containerno
    FROM wms_st_qty_lst_baseunit_v@to_wms x
) b
WHERE a.goodsid = b.goodsownid
  AND a.lotno = b.lotno
;
/

-- VIEW T_WMS_QTY_V

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."T_WMS_QTY_V" ("CONID", "GOODSID", "GOODSGP", "LOTNO", "GOODSNO", "PACKSIZE", "QTY_SHOW", "PCS", "TRANPOSNAME", "DELETED") AS 
  SELECT a.conid,
       a.goodsid,
       a.goodsname || '(' || a.packtype || ')' AS goodsgp,
       a.lotno,
       a.goodsno,
       b.packsize,
       TO_CHAR(NVL(b.goodsqty_total, 0)) || b.basepackname || '（含零头' ||
       TO_CHAR(NVL(b.goodsqty_oddtray1, 0)) || b.basepackname || '，样品__' ||
       b.basepackname || '）' AS QTY_SHOW,
       b.pcs,
       a.tranposname, 0 AS DELETED
  FROM (SELECT a.conid,
               a.goodsid,
               a.goodsno,
               a.goodsname,
               a.lotno,
               a.packtype,
               a.tranposname
          FROM bms_sa_con_dtl_v@hyerp a
         GROUP BY a.conid,
                  a.goodsid,
                  a.goodsno,
                  a.goodsname,
                  a.lotno,
                  a.packtype,a.tranposname) a,
(SELECT x.goodsownid,
        x.lotno,
        x.packname,
        x.basepackname,
        x.packsize,
        SUM(x.goodsqty) AS goodsqty_total,
        SUM(MOD(x.goodsqty, x.packsize)) AS goodsqty_oddtray1,
        SUM(CEIL(x.goodsqty / x.packsize)) AS pcs
 FROM wms_st_qty_lst_baseunit_v@to_wms x
 GROUP BY x.goodsownid, x.lotno, x.packname, x.packsize, x.basepackname) b

 WHERE a.goodsid = b.goodsownid
   AND a.lotno = b.lotno
;
/

-- VIEW V_COST_AUDIT_LOG

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_AUDIT_LOG" ("ID", "USER_NAME", "OPERATION_TIME", "PAGE_CODE", "TABLE_CODE", "TABLE_NAME", "RECORD_ID", "OPERATION_TYPE", "FIELD_CHANGES", "CREATE_TIME", "DELETED") AS 
  SELECT
    ID,
    USER_NAME,
    OPERATION_TIME,
    PAGE_CODE,
    TABLE_CODE,
    TABLE_NAME,
    RECORD_ID,
    OPERATION_TYPE,
    FIELD_CHANGES,
    CREATE_TIME,
    0 AS DELETED
FROM T_COST_AUDIT_LOG
;
/

-- VIEW V_COST_CUSTOMER_LOOKUP

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_CUSTOMER_LOOKUP" ("CUSTOMID", "CUSTOMNAME", "COUNTRY", "LIVERY", "TRANPOSID", "DELETED") AS 
  SELECT a.CUSTOMID,
       a.CUSTOMNAME,
       a.ZONE AS COUNTRY,
       b.TRANPOSNAME AS LIVERY,
       b.TRANPOSID,
       0 AS DELETED
  FROM T_COST_CUSTOMER_V a, T_COST_TRANPOSER_V b
 WHERE a.CUSTOMID = b.CUSTOMID
;
/

-- VIEW V_COST_GOODS_BY_APEX

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_GOODS_BY_APEX" ("P_GOODSID", "GOODSNAME", "GOODSTYPE", "PACKTYPE", "TRANPOSID", "TRANPOSNAME", "ZX_CUSTOMERID", "CUSTOMNAME", "ZONE", "GOODSID", "DELETED") AS 
  SELECT c.GOODSID AS P_GOODSID,
       c.GOODSNAME,
       c.GOODSTYPE,
       c.PACKTYPE,
       c.TRANPOSID,
       c.TRANPOSNAME,
       c.ZX_CUSTOMERID,
       c.CUSTOMNAME,
       c.ZONE,
       a.GOODSID,
       0 AS DELETED
  FROM T_COST_PINGGU_DTL a, T_COST_PINGGU b, T_COST_GOODS_V c
 WHERE a.DOCID = b.DOCID
   AND b.GOODSID = c.GOODSID
;
/

-- VIEW V_COST_GOODS_LOOKUP

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_GOODS_LOOKUP" ("GOODSID", "GOODSNAME", "MA_NO", "APEX_PL", "MAH", "P_PERPACK", "S_PERBACK", "CUSTOMID", "CUSTOMNAME", "MEMO", "STRENGTH", "LIVERY", "DELETED") AS 
  SELECT a.GOODSID,
       a.GOODSNAME,
       a.APPROVEDOCNO AS MA_NO,
       a.ZX_PL AS APEX_PL,
       a.HOLDERSNAME AS MAH,
       a.ZX_MINIMUM AS P_PERPACK,
       a.BASEUNITQTY AS S_PERBACK,
       a.ZX_CUSTOMERID AS CUSTOMID,
       a.CUSTOMNAME,
       CASE WHEN a.ISERP = 0 AND b.PGOODSID IS NULL THEN 'ERP未搭建BOM'
            ELSE 'ERP已搭建BOM' END AS MEMO,
       a.GOODSTYPE AS STRENGTH,
       a.TRANPOSNAME AS LIVERY,
       a.DELETED
  FROM T_COST_GOODS_V a
  LEFT JOIN mpcs_pr_bom_doc@hyerp b ON a.GOODSID = b.PGOODSID AND b.USESTATUS = 1 AND a.ISERP = 1
 WHERE a.USEFLAG = '产成品'
   AND (a.DELETED = 0 OR a.DELETED IS NULL)
;
/

-- VIEW V_COST_PGOODS_BY_MGOODS

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_PGOODS_BY_MGOODS" ("GOODSID", "GOODSNAME", "DTL_USEFLAG", "FACTORYNAME", "PRICE", "GOODSNO", "PGOODSID", "PGOODSNO", "PGOODSNAME", "APEX_PL", "BATCH_QTY", "DELETED") AS 
  SELECT a.goodsid,
       a.goodsname,
       a.dtl_useflag,
       b.factoryname,
       a.price,
       b.goodsno,
       d.goodsid        pgoodsid,
       d.goodsno        pgoodsno,
       d.goodsname pgoodsname,
       c.apex_pl,
       a.batch_qty,
       a.deleted
  FROM T_COST_PINGGU_DTL a, t_cost_goods b, t_cost_pinggu c, t_cost_goods d
 WHERE a.goodsid = b.goodsid
   AND a.docid = c.docid
   AND c.goodsid = d.goodsid
   and a.deleted = 0
   and b.deleted = 0
   and c.deleted = 0
   and d.deleted = 0
;
/

-- VIEW V_COST_PGOODS_BY_MGOODS_LQ

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_PGOODS_BY_MGOODS_LQ" ("GOODSID", "GOODSNAME", "DTL_USEFLAG", "FACTORYNAME", "PRICE", "GOODSNO", "PGOODSID", "PGOODSNO", "PGOODSNAME", "APEX_PL", "BATCH_QTY", "DELETED") AS 
  SELECT a.goodsid,
       a.goodsname,
       a.dtl_useflag,
       b.factoryname,
       a.price,
       b.goodsno,
       d.goodsid        pgoodsid,
       d.goodsno        pgoodsno,
       d.goodsname pgoodsname,
       c.apex_pl,
       a.batch_qty,
       a.deleted
  FROM T_COST_PINGGU_DTL_LQ a,
       t_cost_goods         b,
       t_cost_pinggu_lq     c,
       t_cost_goods         d
 WHERE a.goodsid = b.goodsid
   AND a.docid = c.docid
   AND c.goodsid = d.goodsid
   AND a.deleted = 0
   AND b.deleted = 0
   AND c.deleted = 0
   AND d.deleted = 0
;
/

-- VIEW V_COST_PINGGU_MATERIAL

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_PINGGU_MATERIAL" ("DTLID", "DOCID", "GOODSID", "PER_HL", "PRICE", "BATCH_QTY", "COST_BATCH", "EXADD_MATER", "MEMO", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY", "GOODSNAME_EN", "BASE_PRICE", "SUQTY", "GOODSNAME", "DTL_USEFLAG", "STANDARDTYPE", "FACTORYNAME", "GOODSTYPE") AS 
  SELECT d.DTLID ,
       d.DOCID ,
       d.GOODSID,
       d.PER_HL,
       d.PRICE,
       d.BATCH_QTY,
       d.COST_BATCH,
       d.EXADD_MATER,
       d.MEMO,
       d.DELETED,
       d.CREATE_TIME,
       d.UPDATE_TIME,
       d.CREATE_BY,
       d.UPDATE_BY,
       f.GOODSNAME_EN,
       f.price BASE_PRICE,
       f.suqty,
       f.goodsname ,
       f.useflag DTL_USEFLAG,
       f.standardtype,
       f.factoryname ,
       f.GOODSTYPE
  FROM T_COST_PINGGU_DTL d, t_cost_goods f
 WHERE f.useflag IN ('原料', '辅料')
   AND (d.DELETED = 0 OR d.DELETED IS NULL)
   and d.goodsid = f.goodsid
;
/

-- VIEW V_COST_PINGGU_MATERIAL_LQ

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_PINGGU_MATERIAL_LQ" ("DTLID", "DOCID", "GOODSID", "PER_HL", "PRICE", "BATCH_QTY", "COST_BATCH", "EXADD_MATER", "MEMO", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY", "GOODSNAME_EN", "BASE_PRICE", "SUQTY", "GOODSNAME", "DTL_USEFLAG", "STANDARDTYPE", "FACTORYNAME", "GOODSTYPE") AS 
  SELECT d.DTLID,
       d.DOCID ,
       d.GOODSID,
       d.PER_HL,
       d.PRICE,
       d.BATCH_QTY,
       d.COST_BATCH,
       d.EXADD_MATER,
       d.MEMO,
       d.DELETED,
       d.CREATE_TIME,
       d.UPDATE_TIME,
       d.CREATE_BY,
       d.UPDATE_BY,
       f.GOODSNAME_EN,
       f.price BASE_PRICE,
       f.suqty,
       f.goodsname ,
       f.useflag DTL_USEFLAG,
       f.standardtype ,
       f.factoryname ,
       f.GOODSTYPE
  FROM T_COST_PINGGU_DTL_LQ d, t_cost_goods f
 WHERE f.useflag IN ('原料', '辅料')
   AND (d.DELETED = 0 OR d.DELETED IS NULL)
   and d.goodsid = f.goodsid
;
/

-- VIEW V_COST_PINGGU_PACKAGE

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_PINGGU_PACKAGE" ("DTLID", "DOCID", "GOODSID", "PER_HL", "EXADD_MATER", "PRICE", "BATCH_QTY", "COST_BATCH", "MEMO", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY", "GOODSNAME_EN", "BASE_PRICE", "SUQTY", "GOODSNAME", "DTL_USEFLAG", "STANDARDTYPE", "FACTORYNAME", "GOODSTYPE") AS 
  SELECT d.DTLID ,
       d.DOCID ,
       d.GOODSID,
       d.PER_HL,
       d.EXADD_MATER,
       d.PRICE,
       d.BATCH_QTY,
       d.COST_BATCH,
       d.MEMO,
       d.DELETED,
       d.CREATE_TIME,
       d.UPDATE_TIME,
       d.CREATE_BY,
       d.UPDATE_BY,
       f.GOODSNAME_EN,
       f.price BASE_PRICE,
       f.suqty,
       f.goodsname ,
       f.useflag DTL_USEFLAG,
       f.standardtype ,
       f.factoryname ,
       f.GOODSTYPE
  FROM T_COST_PINGGU_DTL d, t_cost_goods f
 WHERE f.useflag IN ('非印字包材', '印字包材')
   AND (d.DELETED = 0 OR d.DELETED IS NULL)
   and d.goodsid = f.goodsid
;
/

-- VIEW V_COST_PINGGU_PACKAGE_LQ

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_PINGGU_PACKAGE_LQ" ("DTLID", "DOCID", "GOODSID", "PER_HL", "EXADD_MATER", "PRICE", "BATCH_QTY", "COST_BATCH", "MEMO", "DELETED", "CREATE_TIME", "UPDATE_TIME", "CREATE_BY", "UPDATE_BY", "GOODSNAME_EN", "BASE_PRICE", "SUQTY", "GOODSNAME", "DTL_USEFLAG", "SPEC", "FACTORYNAME", "GOODSTYPE") AS 
  SELECT d.DTLID ,
       d.DOCID ,
       d.GOODSID,
       d.PER_HL,
       d.EXADD_MATER,
       d.PRICE,
       d.BATCH_QTY,
       d.COST_BATCH,
       d.MEMO,
       d.DELETED,
       d.CREATE_TIME,
       d.UPDATE_TIME,
       d.CREATE_BY,
       d.UPDATE_BY,
       f.GOODSNAME_EN,
       f.price BASE_PRICE,
       f.suqty,
       f.goodsname ,
       f.useflag DTL_USEFLAG,
       f.standardtype SPEC,
       f.factoryname ,
       f.GOODSTYPE
  FROM T_COST_PINGGU_DTL_LQ d, t_cost_goods f
 WHERE f.useflag IN ('非印字包材', '印字包材')
   AND (d.DELETED = 0 OR d.DELETED IS NULL)
   and d.goodsid = f.goodsid
;
/

-- VIEW V_COST_RESOURCE_PERMISSION

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_RESOURCE_PERMISSION" ("ID", "PAGE_CODE", "RESOURCE_NAME", "RESOURCE_TYPE", "IS_HARDCODED", "ICON", "ROUTE", "PARENT_ID", "SORT_ORDER", "ROLE_ID", "ROLE_CODE", "ROLE_NAME", "ROLE_PAGE_ID", "BUTTON_POLICY", "COLUMN_POLICY", "ROW_POLICY", "IS_AUTHORIZED") AS 
  SELECT
    res.ID,
    res.PAGE_CODE,
    res.RESOURCE_NAME,
    res.RESOURCE_TYPE,
    res.IS_HARDCODED,
    res.ICON,
    res.ROUTE,
    res.PARENT_ID,
    res.SORT_ORDER,
    r.ID AS ROLE_ID,
    r.ROLE_CODE,
    r.ROLE_NAME,
    rp.ID AS ROLE_PAGE_ID,
    rp.BUTTON_POLICY,
    rp.COLUMN_POLICY,
    rp.ROW_POLICY,
    CASE WHEN rp.ID IS NOT NULL THEN 1 ELSE 0 END AS IS_AUTHORIZED
FROM T_COST_RESOURCE res
CROSS JOIN T_COST_ROLE r
LEFT JOIN T_COST_ROLE_PAGE rp
    ON rp.PAGE_CODE = res.PAGE_CODE
    AND rp.ROLE_ID = r.ID
ORDER BY res.SORT_ORDER
;
/

-- VIEW V_COST_ROLE

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_ROLE" ("ID", "ROLE_CODE", "ROLE_NAME", "DESCRIPTION") AS 
  SELECT
    r.ID,
    r.ROLE_CODE,
    r.ROLE_NAME,
    r.DESCRIPTION
FROM T_COST_ROLE r
;
/

-- VIEW V_COST_ROLE_PAGE

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_ROLE_PAGE" ("ID", "ROLE_ID", "PAGE_CODE", "PAGE_NAME", "BUTTON_POLICY", "COLUMN_POLICY", "ROW_POLICY") AS 
  SELECT
    rp.ID,
    rp.ROLE_ID,
    rp.PAGE_CODE,
    res.RESOURCE_NAME AS PAGE_NAME,
    rp.BUTTON_POLICY,
    rp.COLUMN_POLICY,
    rp.ROW_POLICY
FROM T_COST_ROLE_PAGE rp
LEFT JOIN T_COST_RESOURCE res ON rp.PAGE_CODE = res.PAGE_CODE
;
/

-- VIEW V_COST_USER

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_USER" ("ID", "USERNAME", "PASSWORD", "REAL_NAME", "EMAIL", "PHONE", "DEPARTMENT_ID", "DEPT_NAME", "STATUS", "DELETED", "CREATE_BY", "CREATE_TIME", "UPDATE_BY", "UPDATE_TIME") AS 
  SELECT
    u.ID,
    u.USERNAME,
    u.PASSWORD,
    u.REAL_NAME,
    u.EMAIL,
    u.PHONE,
    u.DEPARTMENT_ID,
    d.DEPT_NAME,
    u.STATUS,
    u.DELETED,
    u.CREATE_BY,
    u.CREATE_TIME,
    u.UPDATE_BY,
    u.UPDATE_TIME
FROM T_COST_USER u
LEFT JOIN T_COST_DEPARTMENT d ON u.DEPARTMENT_ID = d.ID
WHERE u.DELETED = 0
;
/

-- VIEW V_COST_USER_ROLE

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CMX"."V_COST_USER_ROLE" ("ID", "USER_ID", "USERNAME", "REAL_NAME", "ROLE_ID") AS 
  SELECT
    ur.ID,
    ur.USER_ID,
    u.USERNAME,
    u.REAL_NAME,
    ur.ROLE_ID
FROM T_COST_USER_ROLE ur
LEFT JOIN T_COST_USER u ON ur.USER_ID = u.ID AND u.DELETED = 0
;
/

