-- 查询用户管理页面的右键菜单配置
SELECT 
    PAGE_CODE,
    COMPONENT_KEY,
    COMPONENT_TYPE,
    DBMS_LOB.SUBSTR(COMPONENT_CONFIG, 4000, 1) AS CONFIG_PREVIEW
FROM T_COST_PAGE_COMPONENT
WHERE PAGE_CODE = 'cost-user' 
  AND COMPONENT_TYPE = 'CONTEXT_MENU';

-- 如果没有记录，查看所有 cost-user 页面的组件
SELECT 
    PAGE_CODE,
    COMPONENT_KEY,
    COMPONENT_TYPE
FROM T_COST_PAGE_COMPONENT
WHERE PAGE_CODE = 'cost-user';
