-- BEGIN rebuild_cost_schema.sql
-- Rebuild cost schema (drops T_COST_*, SEQ_COST_*, V_COST_* then replays baseline data).
-- Run with SQL*Plus/SQLcl/SQL Developer from repo root.

BEGIN
  FOR v IN (SELECT view_name FROM user_views WHERE view_name LIKE 'V_COST_%') LOOP
    EXECUTE IMMEDIATE 'DROP VIEW ' || v.view_name;
  END LOOP;
END;
/

BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name LIKE 'T_COST_%') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

BEGIN
  FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SEQ_COST_%') LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

-- =====================================================
-- 鎴愭湰绠＄悊绯荤粺鏁版嵁搴撹剼鏈紙鏁村悎鐗堬級
-- 鍒嗙被锛氬熀纭€缁撴瀯 / 鍒濆鍖栨暟鎹? 鍏冩暟鎹笌椤甸潰閰嶇疆 / 淇琛ヤ竵
-- 鐢ㄩ€旓細涓€娆℃墽琛屽畬鎴愭墍鏈夊缓琛ㄣ€佸垵濮嬪寲涓庨厤缃紝渚夸簬缁存姢
-- =====================================================

-- =====================================================
-- A. 鍩虹琛ㄧ粨鏋?
-- =====================================================

-- A1. 鍏冩暟鎹ā鍧楄〃缁撴瀯

CREATE TABLE T_COST_TABLE_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_CODE          VARCHAR2(64)    NOT NULL UNIQUE,
    TABLE_NAME          VARCHAR2(128)   NOT NULL,
    QUERY_VIEW          VARCHAR2(64),
    TARGET_TABLE        VARCHAR2(64)    NOT NULL,
    SEQUENCE_NAME       VARCHAR2(64),
    PK_COLUMN           VARCHAR2(64)    DEFAULT 'ID',
    PARENT_TABLE_CODE   VARCHAR2(64),
    PARENT_FK_COLUMN    VARCHAR2(64),
    AUDIT_ENABLED       NUMBER(1)       DEFAULT 0,
    VALIDATION_RULES    CLOB,
    ACTION_RULES        CLOB,
    DESCRIPTION         VARCHAR2(500),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_TABLE_METADATA START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_COLUMN_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_METADATA_ID   NUMBER(19)      NOT NULL,
    FIELD_NAME          VARCHAR2(64)    NOT NULL,
    COLUMN_NAME         VARCHAR2(64)    NOT NULL,
    QUERY_COLUMN        VARCHAR2(128),
    TARGET_COLUMN       VARCHAR2(64),
    HEADER_TEXT         VARCHAR2(128)   NOT NULL,
    DATA_TYPE           VARCHAR2(32)    DEFAULT 'text',
    DISPLAY_ORDER       NUMBER(5)       DEFAULT 0,
    WIDTH               NUMBER(5)       DEFAULT 120,
    VISIBLE             NUMBER(1)       DEFAULT 1,
    EDITABLE            NUMBER(1)       DEFAULT 1,
    REQUIRED            NUMBER(1)       DEFAULT 0,
    SEARCHABLE          NUMBER(1)       DEFAULT 0,
    SORTABLE            NUMBER(1)       DEFAULT 1,
    FILTERABLE          NUMBER(1)       DEFAULT 1,
    IS_VIRTUAL          NUMBER(1)       DEFAULT 0,
    DICT_TYPE           VARCHAR2(64),
    LOOKUP_CONFIG_ID    NUMBER(19),
    DEFAULT_VALUE       VARCHAR2(256),
    RULES_CONFIG        CLOB,
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_COLUMN_TABLE FOREIGN KEY (TABLE_METADATA_ID) REFERENCES T_COST_TABLE_METADATA(ID)
);
CREATE SEQUENCE SEQ_COST_COLUMN_METADATA START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_COLUMN_TABLE_ID ON T_COST_COLUMN_METADATA(TABLE_METADATA_ID);

CREATE TABLE T_COST_LOOKUP_CONFIG (
    ID                  NUMBER(19)      PRIMARY KEY,
    LOOKUP_CODE         VARCHAR2(64)    NOT NULL UNIQUE,
    LOOKUP_NAME         VARCHAR2(128)   NOT NULL,
    DATA_SOURCE         VARCHAR2(200)   NOT NULL,
    DISPLAY_COLUMNS     CLOB,
    SEARCH_COLUMNS      CLOB,
    VALUE_FIELD         VARCHAR2(64)    NOT NULL,
    LABEL_FIELD         VARCHAR2(64)    NOT NULL,
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_LOOKUP_CONFIG START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_PAGE_COMPONENT (
    ID                  NUMBER(19)      PRIMARY KEY,
    PAGE_CODE           VARCHAR2(64)    NOT NULL,
    COMPONENT_KEY       VARCHAR2(64)    NOT NULL,
    COMPONENT_TYPE      VARCHAR2(32)    NOT NULL,
    PARENT_KEY          VARCHAR2(64),
    COMPONENT_CONFIG    CLOB,
    REF_TABLE_CODE      VARCHAR2(64),
    SLOT_NAME           VARCHAR2(32),
    SORT_ORDER          NUMBER(5)       DEFAULT 0,
    DELETED             NUMBER(1)       DEFAULT 0,
    DESCRIPTION         VARCHAR2(200),
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_PAGE_COMPONENT START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_PAGE_COMP_PAGE ON T_COST_PAGE_COMPONENT(PAGE_CODE);
CREATE UNIQUE INDEX UK_PAGE_COMP_KEY ON T_COST_PAGE_COMPONENT(PAGE_CODE, COMPONENT_KEY);

CREATE TABLE T_COST_DICTIONARY_TYPE (
    ID                  NUMBER(19)      PRIMARY KEY,
    TYPE_CODE           VARCHAR2(64)    NOT NULL UNIQUE,
    TYPE_NAME           VARCHAR2(128)   NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_DICT_TYPE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_DICTIONARY_ITEM (
    ID                  NUMBER(19)      PRIMARY KEY,
    TYPE_ID             NUMBER(19)      NOT NULL,
    ITEM_CODE           VARCHAR2(64)    NOT NULL,
    ITEM_NAME           VARCHAR2(128)   NOT NULL,
    ITEM_VALUE          VARCHAR2(200),
    SORT_ORDER          NUMBER(5)       DEFAULT 0,
    EXTRA_CONFIG        VARCHAR2(1000),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_DICT_ITEM_TYPE FOREIGN KEY (TYPE_ID) REFERENCES T_COST_DICTIONARY_TYPE(ID)
);
CREATE SEQUENCE SEQ_COST_DICT_ITEM START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DICT_ITEM_TYPE ON T_COST_DICTIONARY_ITEM(TYPE_ID);

COMMIT;

-- A2. 鏉冮檺妯″潡琛ㄧ粨鏋?

CREATE TABLE T_COST_DEPARTMENT (
    ID              NUMBER(19) PRIMARY KEY,
    DEPT_CODE       VARCHAR2(64) NOT NULL UNIQUE,
    DEPT_NAME       VARCHAR2(128) NOT NULL,
    PARENT_ID       NUMBER(19),
    SORT_ORDER      NUMBER(5) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_DEPARTMENT START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_USER (
    ID              NUMBER(19) PRIMARY KEY,
    USERNAME        VARCHAR2(64) NOT NULL UNIQUE,
    PASSWORD        VARCHAR2(256) NOT NULL,
    REAL_NAME       VARCHAR2(128),
    EMAIL           VARCHAR2(128),
    PHONE           VARCHAR2(32),
    DEPARTMENT_ID   NUMBER(19),
    STATUS          VARCHAR2(32) DEFAULT 'ACTIVE',
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_ROLE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_CODE       VARCHAR2(64) NOT NULL UNIQUE,
    ROLE_NAME       VARCHAR2(128) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_ROLE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_USER_ROLE (
    ID              NUMBER(19) PRIMARY KEY,
    USER_ID         NUMBER(19) NOT NULL,
    ROLE_ID         NUMBER(19) NOT NULL,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER_ROLE START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_USER_ROLE ON T_COST_USER_ROLE(USER_ID, ROLE_ID);

CREATE TABLE T_COST_ROLE_PAGE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_ID         NUMBER(19) NOT NULL,
    PAGE_CODE       VARCHAR2(64) NOT NULL,
    BUTTON_POLICY   VARCHAR2(1000),
    COLUMN_POLICY   CLOB,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_ROLE_PAGE START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_ROLE_PAGE ON T_COST_ROLE_PAGE(ROLE_ID, PAGE_CODE);

CREATE TABLE T_COST_ROLE_PAGE_DATA_RULE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_PAGE_ID    NUMBER(19) NOT NULL,
    RULE_TYPE       VARCHAR2(32) NOT NULL,
    RULE_CONFIG     CLOB NOT NULL,
    PRIORITY        NUMBER(3) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_DATA_RULE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_USER_GRID_CONFIG (
    ID              NUMBER(19) PRIMARY KEY,
    USER_ID         NUMBER(19) NOT NULL,
    PAGE_CODE       VARCHAR2(64) NOT NULL,
    GRID_KEY        VARCHAR2(64) NOT NULL,
    CONFIG_DATA     CLOB,
    DELETED         NUMBER(1) DEFAULT 0,
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER_GRID START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_USER_GRID_CONF ON T_COST_USER_GRID_CONFIG(USER_ID, PAGE_CODE, GRID_KEY);

CREATE TABLE T_COST_RESOURCE (
    ID              NUMBER(19) PRIMARY KEY,
    RESOURCE_CODE   VARCHAR2(64) NOT NULL UNIQUE,
    RESOURCE_NAME   VARCHAR2(128) NOT NULL,
    RESOURCE_TYPE   VARCHAR2(20) NOT NULL,
    PAGE_CODE       VARCHAR2(64),
    ICON            VARCHAR2(64),
    ROUTE           VARCHAR2(128),
    PARENT_ID       NUMBER(19),
    SORT_ORDER      NUMBER(5) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_RESOURCE START WITH 1 INCREMENT BY 1;

COMMIT;

-- A3. 涓氬姟妯″潡琛ㄧ粨鏋?

CREATE TABLE T_COST_EVAL (
    ID              NUMBER(19)      PRIMARY KEY,
    EVAL_NO         VARCHAR2(32)    NOT NULL UNIQUE,
    PRODUCT_NAME    VARCHAR2(128)   NOT NULL,
    APEX_PL         NUMBER(18,4)    DEFAULT 0,
    YIELD           NUMBER(18,4)    DEFAULT 100,
    OUT_PRICE_RMB   NUMBER(18,4)    DEFAULT 0,
    TOTAL_YL        NUMBER(18,2)    DEFAULT 0,
    TOTAL_FL        NUMBER(18,2)    DEFAULT 0,
    TOTAL_PACK      NUMBER(18,2)    DEFAULT 0,
    TOTAL_COST      NUMBER(18,2)    DEFAULT 0,
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_EVAL START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_EVAL_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    EVAL_ID         NUMBER(19)      NOT NULL,
    MATERIAL_NAME   VARCHAR2(128)   NOT NULL,
    USE_FLAG        VARCHAR2(32)    NOT NULL,
    PER_HL          NUMBER(18,6)    DEFAULT 0,
    PRICE           NUMBER(18,4)    DEFAULT 0,
    BATCH_QTY       NUMBER(18,4)    DEFAULT 0,
    COST_BATCH      NUMBER(18,2)    DEFAULT 0,
    PACK_SPEC       VARCHAR2(64),
    PACK_QTY        NUMBER(18,4)    DEFAULT 0,
    PACK_COST       NUMBER(18,2)    DEFAULT 0,
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64),
    CONSTRAINT FK_EVAL_DETAIL FOREIGN KEY (EVAL_ID) REFERENCES T_COST_EVAL(ID)
);
CREATE SEQUENCE SEQ_COST_EVAL_DETAIL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_EVAL_DETAIL_EVAL_ID ON T_COST_EVAL_DETAIL(EVAL_ID);

CREATE TABLE T_COST_PINGGU (
    GOODSID       NUMBER,
    GOODSNAME     VARCHAR2(100),
    STRENGTH      VARCHAR2(50),
    MA_NO         VARCHAR2(30),
    APEX_PL       NUMBER,
    MAH           VARCHAR2(100),
    P_PERPACK     NUMBER,
    FORM          VARCHAR2(20),
    S_PERBACK     NUMBER,
    PACKTYPE      VARCHAR2(30),
    X_PERBACK     NUMBER,
    TOTAL_FL      NUMBER,
    TOTAL_BC      NUMBER,
    TOTAL_YL      NUMBER,
    MEMO          VARCHAR2(100),
    USESTATUS     VARCHAR2(100) DEFAULT 0,
    DOCID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DOSAGE        VARCHAR2(20),
    ANNUAL_QTY    NUMBER,
    YIELD         NUMBER,
    TOTAL_COST    NUMBER,
    OUT_PRICE_F   NUMBER,
    OUT_PRICE_RMB NUMBER,
    SALEMONEY     NUMBER,
    JGF_BATCH     NUMBER,
    JGF_PERQP     NUMBER,
    COST_PERQP    NUMBER,
    ML_PERQP      NUMBER,
    Y_JG_RE       NUMBER,
    Y_ML          NUMBER,
    Y_SALE        NUMBER,
    CUSTOMID      NUMBER,
    CUSTOMNAME    VARCHAR2(50),
    COUNTRY       VARCHAR2(20),
    PROJECTNO     VARCHAR2(20),
    USEFLAG       NUMBER DEFAULT 0,
    YIELD_TIME    DATE DEFAULT SYSDATE,
    APEX_PL_TIME  DATE DEFAULT SYSDATE,
    ZX_SOURCE     VARCHAR2(100),
    FMNAME        VARCHAR2(100) DEFAULT '浜烘皯甯?,
    FMRATE        NUMBER DEFAULT 1,
    GOODSNAME_EN  VARCHAR2(2000),
    LIVERY        VARCHAR2(100),
    DELETED       NUMBER(1)       DEFAULT 0,
    CREATE_TIME   TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME   TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY     VARCHAR2(64),
    UPDATE_BY     VARCHAR2(64),
    CONSTRAINT PK_COST_PINGGU PRIMARY KEY (DOCID)
);

CREATE TABLE T_COST_PINGGU_DTL (
    DOCID            NUMBER(10) NOT NULL,
    APEX_GOODSID     NUMBER(10),
    APEX_GOODSNAME   VARCHAR2(500),
    DTL_USEFLAG      VARCHAR2(100),
    SPEC             VARCHAR2(100),
    PER_HL           NUMBER,
    EXADD_MATER      NUMBER,
    BATCH_QTY        VARCHAR2(100),
    PRICE            NUMBER,
    COST_BATCH       NUMBER,
    MEMO             VARCHAR2(100),
    DTLID            NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APEX_FACTORYNAME VARCHAR2(200),
    APEX_FACTORYID   NUMBER(10),
    MODIFYDATE       DATE,
    ZX_SOURCE        VARCHAR2(100),
    BASE_PRICE       NUMBER,
    SUQTY            NUMBER,
    GOODSTYPE        VARCHAR2(4000),
    GOODSNAME_EN     VARCHAR2(2000),
    DELETED          NUMBER(1)       DEFAULT 0,
    CREATE_TIME      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY        VARCHAR2(64),
    UPDATE_BY        VARCHAR2(64),
    CONSTRAINT PK_COST_PINGGU_DTL PRIMARY KEY (DTLID)
);

CREATE TABLE T_COST_ORDER (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_NO        VARCHAR2(32)    NOT NULL UNIQUE,
    ORDER_DATE      DATE            NOT NULL,
    CUSTOMER_NAME   VARCHAR2(128),
    TOTAL_AMOUNT    NUMBER(18,2)    DEFAULT 0,
    TOTAL_FEE       NUMBER(18,2)    DEFAULT 0,
    STATUS          VARCHAR2(32)    DEFAULT 'DRAFT',
    REMARK          VARCHAR2(512),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_ORDER START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_ORDER_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_ID        NUMBER(19)      NOT NULL,
    ITEM_NAME       VARCHAR2(128)   NOT NULL,
    SPEC            VARCHAR2(64),
    UNIT            VARCHAR2(32),
    QUANTITY        NUMBER(18,4)    DEFAULT 0,
    UNIT_PRICE      NUMBER(18,4)    DEFAULT 0,
    AMOUNT          NUMBER(18,2)    DEFAULT 0,
    REMARK          VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64),
    CONSTRAINT FK_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES T_COST_ORDER(ID)
);
CREATE SEQUENCE SEQ_COST_ORDER_DETAIL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DETAIL_ORDER_ID ON T_COST_ORDER_DETAIL(ORDER_ID);

CREATE TABLE T_COST_ORDER_FEE (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_ID        NUMBER(19)      NOT NULL,
    FEE_TYPE        VARCHAR2(32)    NOT NULL,
    FEE_NAME        VARCHAR2(128)   NOT NULL,
    FEE_AMOUNT      NUMBER(18,2)    DEFAULT 0,
    REMARK          VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64),
    CONSTRAINT FK_FEE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES T_COST_ORDER(ID)
);
CREATE SEQUENCE SEQ_COST_ORDER_FEE START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_FEE_ORDER_ID ON T_COST_ORDER_FEE(ORDER_ID);

CREATE TABLE T_COST_CUSTOMER (
    ID              NUMBER(19)      PRIMARY KEY,
    CUSTOMER_CODE   VARCHAR2(32)    NOT NULL UNIQUE,
    CUSTOMER_NAME   VARCHAR2(128)   NOT NULL,
    CONTACT_PERSON  VARCHAR2(64),
    PHONE           VARCHAR2(32),
    ADDRESS         VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_CUSTOMER START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_MATERIAL (
    ID              NUMBER(19)      PRIMARY KEY,
    MATERIAL_CODE   VARCHAR2(32)    NOT NULL UNIQUE,
    MATERIAL_NAME   VARCHAR2(128)   NOT NULL,
    USE_FLAG        VARCHAR2(32)    NOT NULL,
    PER_HL          NUMBER(18,6)    DEFAULT 0,
    PRICE           NUMBER(18,4)    DEFAULT 0,
    UNIT            VARCHAR2(32),
    SPEC            VARCHAR2(64),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_MATERIAL START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_SALES (
    ID              NUMBER(19)      PRIMARY KEY,
    EVAL_ID         NUMBER(19)      NOT NULL,
    EVAL_NO         VARCHAR2(32)    NOT NULL,
    PRODUCT_NAME    VARCHAR2(128)   NOT NULL,
    TOTAL_COST      NUMBER(18,2)    DEFAULT 0,
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_SALES START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_DEMO (
    ID              NUMBER(19)      PRIMARY KEY,
    CODE            VARCHAR2(64)    NOT NULL,
    NAME            VARCHAR2(128)   NOT NULL,
    AMOUNT          NUMBER(18,2),
    COST_DATE       DATE,
    STATUS          VARCHAR2(32)    DEFAULT 'DRAFT',
    REMARK          VARCHAR2(512),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_DEMO START WITH 1 INCREMENT BY 1;

COMMIT;

-- A4. 鏃ュ織妯″潡琛ㄧ粨鏋?

CREATE TABLE T_COST_OPERATION_LOG (
    ID              NUMBER(19)      PRIMARY KEY,
    USER_ID         NUMBER(19),
    USER_NAME       VARCHAR2(64),
    OPERATION_TYPE  VARCHAR2(32)    NOT NULL,
    TABLE_CODE      VARCHAR2(64),
    RECORD_ID       NUMBER(19),
    RECORD_DESC     VARCHAR2(256),
    TOTAL_SQL_COUNT NUMBER(10)      DEFAULT 0,
    TOTAL_COST_MS   NUMBER(10)      DEFAULT 0,
    STATUS          VARCHAR2(16)    DEFAULT 'SUCCESS',
    ERROR_MSG       VARCHAR2(1000),
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_OPERATION_LOG START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_OPERATION_LOG_USER ON T_COST_OPERATION_LOG(USER_ID);
CREATE INDEX IDX_OPERATION_LOG_TIME ON T_COST_OPERATION_LOG(CREATE_TIME);
CREATE INDEX IDX_OPERATION_LOG_TABLE ON T_COST_OPERATION_LOG(TABLE_CODE);

CREATE TABLE T_COST_OPERATION_LOG_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    LOG_ID          NUMBER(19)      NOT NULL,
    SEQ_NO          NUMBER(5)       NOT NULL,
    SQL_TYPE        VARCHAR2(16),
    SQL_TEXT        CLOB,
    COST_MS         NUMBER(10)      DEFAULT 0,
    AFFECTED_ROWS   NUMBER(10),
    STATUS          VARCHAR2(16)    DEFAULT 'SUCCESS',
    ERROR_MSG       VARCHAR2(1000),
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LOG_DETAIL_LOG FOREIGN KEY (LOG_ID) REFERENCES T_COST_OPERATION_LOG(ID)
);
CREATE SEQUENCE SEQ_COST_OPERATION_LOG_DETAIL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_LOG_DETAIL_LOG ON T_COST_OPERATION_LOG_DETAIL(LOG_ID);

CREATE TABLE T_COST_AUDIT_LOG (
    ID              NUMBER(19)      PRIMARY KEY,
    USER_NAME       VARCHAR2(100),
    OPERATION_TIME  TIMESTAMP       DEFAULT SYSTIMESTAMP,
    PAGE_CODE       VARCHAR2(100),
    TABLE_CODE      VARCHAR2(100),
    TABLE_NAME      VARCHAR2(200),
    RECORD_ID       NUMBER(19),
    OPERATION_TYPE  VARCHAR2(20),
    FIELD_CHANGES   CLOB,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_AUDIT_LOG START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_AUDIT_LOG_TIME ON T_COST_AUDIT_LOG(OPERATION_TIME);
CREATE INDEX IDX_AUDIT_LOG_USER ON T_COST_AUDIT_LOG(USER_NAME);
CREATE INDEX IDX_AUDIT_LOG_TABLE ON T_COST_AUDIT_LOG(TABLE_CODE);

COMMENT ON TABLE T_COST_AUDIT_LOG IS '涓氬姟瀹¤鏃ュ織锛堢敤鎴峰彲瑙侊級';
COMMENT ON COLUMN T_COST_AUDIT_LOG.FIELD_CHANGES IS '瀛楁鍙樻洿JSON锛屽彧璁板綍鐢ㄦ埛鎵嬪姩淇敼';

COMMIT;

-- =====================================================
-- B. 鍒濆鍖栧熀纭€鏁版嵁
-- =====================================================

-- B1. 瀛楀吀鍒濆鍖栨暟鎹?
INSERT INTO T_COST_DICTIONARY_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_DICT_TYPE.NEXTVAL, 'COST_STATUS', '鎴愭湰鐘舵€?, '鎴愭湰鍗曟嵁鐘舵€?, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, EXTRA_CONFIG, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'COST_STATUS'), 'DRAFT', '鑽夌', 'DRAFT', 1, '{"color":"#909399"}', 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, EXTRA_CONFIG, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'COST_STATUS'), 'SUBMITTED', '宸叉彁浜?, 'SUBMITTED', 2, '{"color":"#E6A23C"}', 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, EXTRA_CONFIG, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'COST_STATUS'), 'APPROVED', '宸插鏍?, 'APPROVED', 3, '{"color":"#67C23A"}', 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, EXTRA_CONFIG, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'COST_STATUS'), 'REJECTED', '宸查┏鍥?, 'REJECTED', 4, '{"color":"#F56C6C"}', 'system');

INSERT INTO T_COST_DICTIONARY_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_DICT_TYPE.NEXTVAL, 'FEE_TYPE', '璐圭敤绫诲瀷', '鎴愭湰鍗曡垂鐢ㄧ被鍨?, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'FEE_TYPE'), 'TRANSPORT', '杩愯緭璐?, 'TRANSPORT', 1, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'FEE_TYPE'), 'PACKAGE', '鍖呰璐?, 'PACKAGE', 2, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'FEE_TYPE'), 'TAX', '绋庤垂', 'TAX', 3, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'FEE_TYPE'), 'OTHER', '鍏朵粬', 'OTHER', 4, 'system');

COMMIT;

-- B2. 鐢ㄦ埛/瑙掕壊/鑿滃崟鍒濆鍖?
INSERT INTO T_COST_DEPARTMENT (ID, DEPT_CODE, DEPT_NAME, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DEPARTMENT.NEXTVAL, 'ROOT', '鎬诲叕鍙?, NULL, 0, 'system');
INSERT INTO T_COST_DEPARTMENT (ID, DEPT_CODE, DEPT_NAME, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DEPARTMENT.NEXTVAL, 'FINANCE', '璐㈠姟閮?, 1, 1, 'system');
INSERT INTO T_COST_DEPARTMENT (ID, DEPT_CODE, DEPT_NAME, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DEPARTMENT.NEXTVAL, 'PURCHASE', '閲囪喘閮?, 1, 2, 'system');

INSERT INTO T_COST_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_ROLE.NEXTVAL, 'ADMIN', '绯荤粺绠＄悊鍛?, '鎷ユ湁鎵€鏈夋潈闄?, 'system');
INSERT INTO T_COST_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_ROLE.NEXTVAL, 'FINANCE_MANAGER', '璐㈠姟缁忕悊', '璐㈠姟閮ㄩ棬绠＄悊鏉冮檺', 'system');
INSERT INTO T_COST_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_ROLE.NEXTVAL, 'FINANCE_STAFF', '璐㈠姟涓撳憳', '璐㈠姟閮ㄩ棬鏅€氭潈闄?, 'system');

-- 榛樿鐢ㄦ埛锛屽瘑鐮?123456锛圔Crypt 宸插姞瀵嗭級
INSERT INTO T_COST_USER (ID, USERNAME, PASSWORD, REAL_NAME, DEPARTMENT_ID, CREATE_BY)
VALUES (SEQ_COST_USER.NEXTVAL, 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKt6Z5EH', '绯荤粺绠＄悊鍛?, 1, 'system');
INSERT INTO T_COST_USER (ID, USERNAME, PASSWORD, REAL_NAME, DEPARTMENT_ID, CREATE_BY)
VALUES (SEQ_COST_USER.NEXTVAL, 'zhangsan', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKt6Z5EH', '寮犱笁', 2, 'system');
INSERT INTO T_COST_USER (ID, USERNAME, PASSWORD, REAL_NAME, DEPARTMENT_ID, CREATE_BY)
VALUES (SEQ_COST_USER.NEXTVAL, 'lisi', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKt6Z5EH', '鏉庡洓', 2, 'system');

INSERT INTO T_COST_USER_ROLE (ID, USER_ID, ROLE_ID, CREATE_BY) VALUES (SEQ_COST_USER_ROLE.NEXTVAL, 1, 1, 'system');
INSERT INTO T_COST_USER_ROLE (ID, USER_ID, ROLE_ID, CREATE_BY) VALUES (SEQ_COST_USER_ROLE.NEXTVAL, 2, 2, 'system');
INSERT INTO T_COST_USER_ROLE (ID, USER_ID, ROLE_ID, CREATE_BY) VALUES (SEQ_COST_USER_ROLE.NEXTVAL, 3, 3, 'system');

INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, CREATE_BY)
VALUES (SEQ_COST_ROLE_PAGE.NEXTVAL, 1, 'cost-eval', '["*"]', NULL, 'system');
INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, CREATE_BY)
VALUES (SEQ_COST_ROLE_PAGE.NEXTVAL, 2, 'cost-eval', '["CREATE","EDIT","DELETE","EXPORT"]', NULL, 'system');
INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, CREATE_BY)
VALUES (SEQ_COST_ROLE_PAGE.NEXTVAL, 3, 'cost-eval', '["EXPORT"]', NULL, 'system');

INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'home', '棣栭〉', 'PAGE', 'home', 'mdi:monitor-dashboard', '/home', NULL, 0, 'system');
INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'cost', '鎴愭湰绠＄悊', 'DIRECTORY', NULL, 'mdi:currency-usd', '/cost', NULL, 1, 'system');
DECLARE
    v_parent_id NUMBER;
BEGIN
    SELECT ID INTO v_parent_id FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'cost';
    INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
    VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'eval-v4', '璇勪及鍗?, 'PAGE', 'cost-eval', 'mdi:calculator', '/cost/eval-v4', v_parent_id, 1, 'system');
END;
/

COMMIT;

-- B3. 涓氬姟娴嬭瘯鏁版嵁
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL001', '闃胯帿瑗挎灄鍘熸枡', '鍘熸枡', 125.5, 280, 'kg', '鍖昏嵂绾?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL002', '娣€绮?, '鍘熸枡', 45.2, 15, 'kg', '椋熷搧绾?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL003', '澶村鍏嬭偀鍘熸枡', '鍘熸枡', 200, 450, 'kg', '鍖昏嵂绾?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL001', '绌哄績鑳跺泭', '杈呮枡', 1050, 0.035, '绮?, '0鍙?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL002', '纭剛閰搁晛', '杈呮枡', 2.5, 45, 'kg', '鍖昏嵂绾?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL003', '寰櫠绾ょ淮绱?, '杈呮枡', 80, 25, 'kg', '鍖昏嵂绾?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC001', '閾濆娉＄僵', '鍖呮潗', 0, 0.12, '鏉?, '10鏉?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC002', '绾哥洅', '鍖呮潗', 0, 0.35, '鐩?, '2鐩?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC003', '璇存槑涔?, '鍖呮潗', 0, 0.05, '寮?, 'A4', 'system');

INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C001', '鍗庝负鎶€鏈湁闄愬叕鍙?, '寮犱笁', '13800138001', '娣卞湷甯傞緳宀楀尯', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C002', '闃块噷宸村反闆嗗洟', '鏉庡洓', '13800138002', '鏉窞甯備綑鏉尯', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C003', '鑵捐绉戞妧', '鐜嬩簲', '13800138003', '娣卞湷甯傚崡灞卞尯', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C004', '瀛楄妭璺冲姩', '璧靛叚', '13800138004', '鍖椾含甯傛捣娣€鍖?, 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C005', '缇庡洟鐐硅瘎', '閽变竷', '13800138005', '鍖椾含甯傛湞闃冲尯', 'system');

DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-001', '闃胯帿瑗挎灄鑳跺泭', 100, 98, 35.5, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '闃胯帿瑗挎灄鍘熸枡', '鍘熸枡', 125.5, 280, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '娣€绮?, '鍘熸枡', 45.2, 15, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '绌哄績鑳跺泭', '杈呮枡', 1050, 0.035, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '纭剛閰搁晛', '杈呮枡', 2.5, 45, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PACK_SPEC, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '閾濆娉＄僵', '鍖呮潗', '10鏉?, 0.12, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PACK_SPEC, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '绾哥洅', '鍖呮潗', '2鐩?, 0.35, 'system');
    COMMIT;
END;
/

DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-002', '澶村鍏嬭偀鐗?, 80, 95, 42.0, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '澶村鍏嬭偀鍘熸枡', '鍘熸枡', 200, 450, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '寰櫠绾ょ淮绱?, '杈呮枡', 80, 25, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PACK_SPEC, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '閾濆娉＄僵', '鍖呮潗', '12鏉?, 0.15, 'system');
    COMMIT;
END;
/

DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-003', '闃胯帿瑗挎灄鍙ｆ湇娑茬摱瑁?, 50, 96, 28.0, 'system');
    COMMIT;
END;
/

DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-004', '娓呯儹瑙ｆ瘨棰楃矑', 60, 94, 32.0, 'system');
    COMMIT;
END;
/

COMMIT;

-- =====================================================
-- C. 鍏冩暟鎹笌椤甸潰閰嶇疆
-- =====================================================

-- C1. 鍩虹鍒楀厓鏁版嵁鍒濆鍖栵紙CostEval銆丆ostMaterial銆丆ustomer 绛夛級
DECLARE
    v_eval_id NUMBER;
    v_detail_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, VALIDATION_RULES, CREATE_BY)
    VALUES (v_eval_id, 'CostEval', '璇勪及鍗?, 'T_COST_EVAL', 'T_COST_EVAL', 'SEQ_COST_EVAL', 'ID',
    '[{"order":1,"name":"evalNoUnique","sql":"SELECT COUNT(*) FROM T_COST_EVAL WHERE EVAL_NO = :evalNo AND ID != NVL(:id, -1) AND DELETED = 0","condition":"result == 0","message":"璇勪及鍗曞彿宸插瓨鍦?},{"order":2,"name":"apexPlPositive","sql":"SELECT CASE WHEN :apexPl > 0 THEN 1 ELSE 0 END FROM DUAL","condition":"result == 1","message":"鎵归噺蹇呴』澶т簬0"}]',
    'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'id', 'ID', 'ID', 'number', 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'evalNo', 'EVAL_NO', '璇勪及鍗曞彿', 'text', 1, 0, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'productName', 'PRODUCT_NAME', '浜у搧鍚嶇О', 'text', 2, 1, NULL, '{"style":[{"condition":{"type":"contains","pattern":"浜?},"cellStyle":{"color":"red","fontWeight":"bold"}},{"condition":{"type":"contains","pattern":"鍋?},"rowStyle":{"backgroundColor":"#e3f2fd"}}]}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'apexPl', 'APEX_PL', '鎵归噺(涓囩墖)', 'number', 3, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'yield', 'YIELD', '鏀剁巼(%)', 'number', 4, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'outPriceRmb', 'OUT_PRICE_RMB', '鍑哄巶浠?, 'number', 5, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'totalYl', 'TOTAL_YL', '鍘熸枡鍚堣', 'number', 6, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'totalFl', 'TOTAL_FL', '杈呮枡鍚堣', 'number', 7, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'totalPack', 'TOTAL_PACK', '鍖呮潗鍚堣', 'number', 8, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'totalCost', 'TOTAL_COST', '鎬绘垚鏈?, 'number', 9, 0, NULL, 'system');

    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_detail_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, CREATE_BY)
    VALUES (v_detail_id, 'CostEvalDetail', '鐗╂枡鏄庣粏', 'T_COST_EVAL_DETAIL', 'T_COST_EVAL_DETAIL', 'SEQ_COST_EVAL_DETAIL', 'ID', 'CostEval', 'EVAL_ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'id', 'ID', 'ID', 'number', 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'evalId', 'EVAL_ID', '涓昏〃ID', 'number', 1, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'materialName', 'MATERIAL_NAME', '鐗╂枡鍚嶇О', 'text', 2, 1, NULL, '{"lookup":{"code":"material","mapping":{"materialName":"materialName","useFlag":"useFlag","perHl":"perHl","price":"price"}}}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'useFlag', 'USE_FLAG', '鐗╂枡绫诲瀷', 'text', 3, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'perHl', 'PER_HL', '鐧句竾鐗囩敤閲?, 'number', 4, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'price', 'PRICE', '鍗曚环', 'number', 5, 1, NULL, '{"validate":[{"order":1,"type":"notZero","message":"鍗曚环涓嶈兘涓?"},{"order":2,"type":"min","value":0,"message":"鍗曚环涓嶈兘涓鸿礋鏁?}],"compare":{"enabled":true,"format":"both"}}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'batchQty', 'BATCH_QTY', '鎵圭敤閲?, 'number', 6, 0, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'costBatch', 'COST_BATCH', '鎵规垚鏈?, 'number', 7, 0, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'packSpec', 'PACK_SPEC', '瑙勬牸', 'text', 8, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'packQty', 'PACK_QTY', '鍖呰鏁伴噺', 'number', 9, 0, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'packCost', 'PACK_COST', '鍖呰鎴愭湰', 'number', 10, 0, 1, NULL, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-eval', 'root', 'LAYOUT', NULL, 0, '{"direction":"vertical","gap":8}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-eval', 'masterGrid', 'GRID', 'root', 1, 'CostEval', '{"height":"50%","selectionMode":"single"}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-eval', 'detailTabs', 'TABS', 'root', 2, 'CostEvalDetail',
'{
  "mode": "group",
  "groupField": "useFlag",
  "tabs": [
    {"key": "material", "title": "鍘熸枡", "value": "鍘熸枡", "columns": ["materialName", "perHl", "price", "batchQty", "costBatch"]},
    {"key": "auxiliary", "title": "杈呮枡", "value": "杈呮枡", "columns": ["materialName", "perHl", "price", "batchQty", "costBatch"]},
    {"key": "package", "title": "鍖呮潗", "value": "鍖呮潗", "columns": ["materialName", "packSpec", "price", "packQty", "packCost"]}
  ],
  "broadcast": ["apexPl", "yield"],
  "calcRules": [
    {"field": "batchQty", "expression": "apexPl * perHl / 100 / yield * 100", "triggerFields": ["perHl"], "condition": "useFlag !== ''鍖呮潗''"},
    {"field": "costBatch", "expression": "batchQty * price", "triggerFields": ["batchQty", "price"], "condition": "useFlag !== ''鍖呮潗''"},
    {"field": "packQty", "expression": "apexPl * 1000", "triggerFields": [], "condition": "useFlag === ''鍖呮潗''"},
    {"field": "packCost", "expression": "packQty * price", "triggerFields": ["packQty", "price"], "condition": "useFlag === ''鍖呮潗''"}
  ],
  "aggregates": [
    {"sourceField": "costBatch", "targetField": "totalYl", "algorithm": "SUM", "filter": "useFlag === ''鍘熸枡''"},
    {"sourceField": "costBatch", "targetField": "totalFl", "algorithm": "SUM", "filter": "useFlag === ''杈呮枡''"},
    {"sourceField": "packCost", "targetField": "totalPack", "algorithm": "SUM", "filter": "useFlag === ''鍖呮潗''"},
    {"targetField": "totalCost", "expression": "totalYl + totalFl + totalPack"}
  ]
}', 'system');

COMMIT;

DECLARE
    v_material_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_material_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_material_id, 'CostMaterial', '鐗╂枡鍩虹鏁版嵁', 'T_COST_MATERIAL', 'T_COST_MATERIAL', 'SEQ_COST_MATERIAL', 'ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'id', 'ID', 'ID', 'number', 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'materialCode', 'MATERIAL_CODE', '鐗╂枡缂栫爜', 'text', 1, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'materialName', 'MATERIAL_NAME', '鐗╂枡鍚嶇О', 'text', 2, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'useFlag', 'USE_FLAG', '鐗╂枡绫诲瀷', 'text', 3, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'perHl', 'PER_HL', '鐧句竾鐗囩敤閲?, 'number', 4, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'price', 'PRICE', '鍗曚环', 'number', 5, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'unit', 'UNIT', '鍗曚綅', 'text', 6, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'spec', 'SPEC', '瑙勬牸', 'text', 7, 1, NULL, 'system');
    COMMIT;
END;
/

DECLARE
    v_customer_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_customer_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_customer_id, 'Customer', '瀹㈡埛', 'T_COST_CUSTOMER', 'T_COST_CUSTOMER', 'SEQ_COST_CUSTOMER', 'ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'id', 'ID', 'ID', 'number', 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'customerCode', 'CUSTOMER_CODE', '瀹㈡埛缂栫爜', 'text', 1, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'customerName', 'CUSTOMER_NAME', '瀹㈡埛鍚嶇О', 'text', 2, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'contactPerson', 'CONTACT_PERSON', '鑱旂郴浜?, 'text', 3, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'phone', 'PHONE', '鐢佃瘽', 'text', 4, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'address', 'ADDRESS', '鍦板潃', 'text', 5, 1, NULL, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_LOOKUP_CONFIG (ID, LOOKUP_CODE, LOOKUP_NAME, DATA_SOURCE, DISPLAY_COLUMNS, SEARCH_COLUMNS, VALUE_FIELD, LABEL_FIELD, CREATE_BY)
VALUES (SEQ_COST_LOOKUP_CONFIG.NEXTVAL, 'material', '鐗╂枡閫夋嫨', 'CostMaterial',
  '[{"field":"materialCode","header":"鐗╂枡缂栫爜","width":100},{"field":"materialName","header":"鐗╂枡鍚嶇О","width":150},{"field":"useFlag","header":"绫诲瀷","width":80},{"field":"price","header":"鍗曚环","width":80}]',
  '["materialCode","materialName"]', 'id', 'materialName', 'system');
INSERT INTO T_COST_LOOKUP_CONFIG (ID, LOOKUP_CODE, LOOKUP_NAME, DATA_SOURCE, DISPLAY_COLUMNS, SEARCH_COLUMNS, VALUE_FIELD, LABEL_FIELD, CREATE_BY)
VALUES (SEQ_COST_LOOKUP_CONFIG.NEXTVAL, 'customer', '瀹㈡埛閫夋嫨', 'Customer',
  '[{"field":"customerCode","header":"瀹㈡埛缂栫爜","width":100},{"field":"customerName","header":"瀹㈡埛鍚嶇О","width":180},{"field":"contactPerson","header":"鑱旂郴浜?,"width":100}]',
  '["customerCode","customerName"]', 'id', 'customerName', 'system');

COMMIT;

-- C2. 浜哄憳绠＄悊椤甸潰閰嶇疆锛堣鍥? 鍏冩暟鎹? 椤甸潰甯冨眬锛?
INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'system', '绯荤粺绠＄悊', 'DIRECTORY', NULL, 'mdi:cog', '/system', NULL, 99, 'system');
DECLARE
    v_parent_id NUMBER;
BEGIN
    SELECT ID INTO v_parent_id FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'system';
    INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
    VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'user', '浜哄憳绠＄悊', 'PAGE', 'user-manage', 'mdi:account-group', '/system/user', v_parent_id, 1, 'system');
END;
/

DECLARE
    v_user_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_user_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, ACTION_RULES, CREATE_BY)
    VALUES (v_user_id, 'CostUser', '鐢ㄦ埛', 'V_COST_USER', 'T_COST_USER', 'SEQ_COST_USER', 'ID', '[
  {
    "code": "resetPassword",
    "group": "manual",
    "type": "java",
    "method": "userService.resetPassword",
    "description": "閲嶇疆鐢ㄦ埛瀵嗙爜涓洪粯璁ゅ€?
  }
]', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'id', 'ID', 'ID', 'number', 0, 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'username', 'USERNAME', '鐢ㄦ埛鍚?, 'text', 1, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'realName', 'REAL_NAME', '濮撳悕', 'text', 2, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'email', 'EMAIL', '閭', 'text', 3, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'phone', 'PHONE', '鎵嬫満鍙?, 'text', 4, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, IS_VIRTUAL, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'deptName', 'DEPT_NAME', '閮ㄩ棬', 'text', 5, 0, NULL, 1, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'status', 'STATUS', '鐘舵€?, 'select', 6, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'createTime', 'CREATE_TIME', '鍒涘缓鏃堕棿', 'datetime', 7, 0, NULL, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'user-manage', 'root', 'LAYOUT', NULL, 0, '{"direction":"vertical","gap":8}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'user-manage', 'masterGrid', 'GRID', 'root', 1, 'CostUser', '{"height":"100%","selectionMode":"single"}', 'system');

CREATE OR REPLACE VIEW V_COST_USER AS
SELECT 
    u.ID,
    u.USERNAME,
    u.REAL_NAME,
    u.EMAIL,
    u.PHONE,
    u.DEPARTMENT_ID,
    d.DEPT_NAME,
    u.STATUS,
    u.DELETED,
    u.CREATE_BY,
    u.CREATE_TIME,
    u.UPDATE_BY,
    u.UPDATE_TIME
FROM T_COST_USER u
LEFT JOIN T_COST_DEPARTMENT d ON u.DEPARTMENT_ID = d.ID AND d.DELETED = 0;

-- C3. 瑙掕壊绠＄悊椤甸潰閰嶇疆锛堣鑹蹭富琛? 鐢ㄦ埛鍏宠仈浠庤〃锛?
DECLARE
    v_parent_id NUMBER;
BEGIN
    SELECT ID INTO v_parent_id FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'system';
    INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
    VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'role', '瑙掕壊绠＄悊', 'PAGE', 'role-manage', 'mdi:shield-account', '/system/role', v_parent_id, 2, 'system');
END;
/

DECLARE
    v_role_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_role_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_role_id, 'CostRole', '瑙掕壊', 'T_COST_ROLE', 'T_COST_ROLE', 'SEQ_COST_ROLE', 'ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'id', 'ID', 'ID', 'number', 0, 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'roleCode', 'ROLE_CODE', '瑙掕壊缂栫爜', 'text', 1, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'roleName', 'ROLE_NAME', '瑙掕壊鍚嶇О', 'text', 2, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'description', 'DESCRIPTION', '鎻忚堪', 'text', 3, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'createTime', 'CREATE_TIME', '鍒涘缓鏃堕棿', 'datetime', 4, 0, NULL, 'system');
    COMMIT;
END;
/

DECLARE
    v_user_role_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_user_role_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, CREATE_BY)
    VALUES (v_user_role_id, 'CostUserRole', '瑙掕壊鐢ㄦ埛', 'V_COST_USER_ROLE', 'T_COST_USER_ROLE', 'SEQ_COST_USER_ROLE', 'ID', 'CostRole', 'ROLE_ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'id', 'ID', 'ID', 'number', 0, 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'roleId', 'ROLE_ID', '瑙掕壊ID', 'number', 1, 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'userId', 'USER_ID', '鐢ㄦ埛ID', 'number', 2, 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'username', 'USERNAME', '鐢ㄦ埛鍚?, 'text', 3, 0, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, IS_VIRTUAL, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'realName', 'REAL_NAME', '濮撳悕', 'text', 4, 0, 1, NULL, 1, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, IS_VIRTUAL, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'deptName', 'DEPT_NAME', '閮ㄩ棬', 'text', 5, 0, NULL, 1, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'createTime', 'CREATE_TIME', '鍒嗛厤鏃堕棿', 'datetime', 6, 0, NULL, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'role-manage', 'root', 'LAYOUT', NULL, 0, '{"direction":"vertical","gap":8}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'role-manage', 'masterGrid', 'GRID', 'root', 1, 'CostRole', '{"height":"50%","selectionMode":"single"}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'role-manage', 'detailTabs', 'TABS', 'root', 2, 'CostUserRole',
'{
  "mode": "group",
  "tabs": [
    {"key": "users", "title": "瑙掕壊鐢ㄦ埛", "columns": ["username", "realName", "deptName", "createTime"]}
  ]
}', 'system');

CREATE OR REPLACE VIEW V_COST_USER_ROLE AS
SELECT 
    ur.ID,
    ur.USER_ID,
    ur.ROLE_ID,
    u.USERNAME,
    u.REAL_NAME,
    d.DEPT_NAME,
    ur.DELETED,
    ur.CREATE_BY,
    ur.CREATE_TIME
FROM T_COST_USER_ROLE ur
LEFT JOIN T_COST_USER u ON ur.USER_ID = u.ID AND u.DELETED = 0
LEFT JOIN T_COST_DEPARTMENT d ON u.DEPARTMENT_ID = d.ID AND d.DELETED = 0;

-- C4. 鎴愭湰璇勪及椤甸潰閰嶇疆锛堝惈瑙嗗浘涓庝富浠庡厓鏁版嵁锛?
CREATE OR REPLACE VIEW V_COST_PINGGU_DTL AS
SELECT 
    d.DTLID,
    d.DOCID,
    d.DTL_USEFLAG,
    d.APEX_GOODSNAME,
    d.SPEC,
    d.PER_HL,
    d.EXADD_MATER,
    d.BATCH_QTY,
    d.PRICE,
    d.COST_BATCH,
    d.MEMO,
    d.APEX_FACTORYNAME,
    d.APEX_FACTORYID,
    d.APEX_GOODSID,
    d.MODIFYDATE,
    d.ZX_SOURCE,
    d.BASE_PRICE,
    d.SUQTY,
    d.GOODSTYPE,
    d.GOODSNAME_EN,
    d.DELETED,
    d.CREATE_TIME,
    d.UPDATE_TIME,
    d.CREATE_BY,
    d.UPDATE_BY,
    CASE
        WHEN d.DTL_USEFLAG IN ('鍗板瓧鍖呮潗', '闈炲嵃瀛楀寘鏉?) AND REGEXP_LIKE(d.APEX_GOODSNAME, '妗秥璇存槑涔灏忕洅|鏍囩|鐡秥绾哥') THEN 'A'
        WHEN d.DTL_USEFLAG = '杈呮枡' AND REGEXP_LIKE(d.APEX_GOODSNAME, '鑳跺泭') THEN 'B'
        WHEN d.DTL_USEFLAG IN ('鍗板瓧鍖呮潗', '闈炲嵃瀛楀寘鏉?) AND REGEXP_LIKE(d.APEX_GOODSNAME, '纭墖|閾濈當') THEN 'D'
        WHEN d.DTL_USEFLAG IN ('鍗板瓧鍖呮潗', '闈炲嵃瀛楀寘鏉?) AND REGEXP_LIKE(d.APEX_GOODSNAME, '澶х焊绠?) THEN 'E'
        WHEN d.DTL_USEFLAG IN ('鍗板瓧鍖呮潗', '闈炲嵃瀛楀寘鏉?) AND REGEXP_LIKE(d.APEX_GOODSNAME, '鎵樼洏') THEN 'F'
        WHEN d.DTL_USEFLAG IN ('鍘熸枡', '杈呮枡') THEN 'C'
        ELSE NULL
    END AS FORMULA_TYPE
FROM T_COST_PINGGU_DTL d;

DECLARE
    v_parent_id NUMBER;
BEGIN
    SELECT ID INTO v_parent_id FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'cost';
    INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
    VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'pinggu', '鎴愭湰璇勪及', 'PAGE', 'cost-pinggu', 'mdi:calculator-variant', '/cost/pinggu', v_parent_id, 2, 'system');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
        VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'pinggu', '鎴愭湰璇勪及', 'PAGE', 'cost-pinggu', 'mdi:calculator-variant', '/pinggu', NULL, 10, 'system');
END;
/

DECLARE
    v_master_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_master_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, PK_COLUMN, CREATE_BY)
    VALUES (v_master_id, 'CostPinggu', '鎴愭湰璇勪及', 'T_COST_PINGGU', 'T_COST_PINGGU', 'DOCID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'id', 'DOCID', 'ID', 'number', 0, 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'goodsname', 'GOODSNAME', '浜у搧鍚嶇О', 'text', 1, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'goodsnameEn', 'GOODSNAME_EN', '浜у搧鑻辨枃鍚?, 'text', 2, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'strength', 'STRENGTH', '鍓傞噺', 'text', 3, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'dosage', 'DOSAGE', '鍓傚瀷', 'text', 4, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'form', 'FORM', '鐗囧瀷', 'text', 5, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'maNo', 'MA_NO', '娉ㄥ唽鍙?, 'text', 6, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'mah', 'MAH', '娉ㄥ唽鎸佹湁浜?, 'text', 7, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'customname', 'CUSTOMNAME', '瀹㈡埛鍚嶇О', 'text', 8, 1, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'country', 'COUNTRY', '鍥藉', 'text', 9, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'projectno', 'PROJECTNO', '椤圭洰鍙?, 'text', 10, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'apexPl', 'APEX_PL', '鎵归噺', 'number', 11, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'annualQty', 'ANNUAL_QTY', '骞撮渶姹傞噺', 'number', 12, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'yield', 'YIELD', '鏀剁巼(%)', 'number', 13, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'pPerpack', 'P_PERPACK', '姣忕洅鐗囨暟', 'number', 14, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'sPerback', 'S_PERBACK', '姣忕瑁呯洅鏁?, 'number', 15, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'xPerback', 'X_PERBACK', '姣忔墭鐩樼鏁?, 'number', 16, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'packtype', 'PACKTYPE', '鍖呰褰㈠紡', 'text', 17, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalYl', 'TOTAL_YL', '鍘熸枡鍚堣', 'number', 20, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalFl', 'TOTAL_FL', '杈呮枡鍚堣', 'number', 21, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalBc', 'TOTAL_BC', '鍖呮潗鍚堣', 'number', 22, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalCost', 'TOTAL_COST', '鎬荤墿鏂欐垚鏈?, 'number', 23, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'outPriceRmb', 'OUT_PRICE_RMB', '鍑哄巶浠?RMB)', 'number', 24, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'salemoney', 'SALEMONEY', '姣忔壒閿€鍞', 'number', 25, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'jgfBatch', 'JGF_BATCH', '姣忔壒鍔犲伐璐?, 'number', 26, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'costPerqp', 'COST_PERQP', '鍗冪墖鎴愭湰', 'number', 27, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'jgfPerqp', 'JGF_PERQP', '鍗冪墖鍔犲伐璐?, 'number', 28, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'mlPerqp', 'ML_PERQP', '鍗冪墖姣涘埄', 'number', 29, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'yJgRe', 'Y_JG_RE', '骞村姞宸ユ敹鍏?, 'number', 30, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'yMl', 'Y_ML', '骞存瘺鍒?, 'number', 31, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'ySale', 'Y_SALE', '骞撮攢鍞', 'number', 32, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'usestatus', 'USESTATUS', '鐘舵€?, 'text', 33, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'memo', 'MEMO', '澶囨敞', 'text', 34, 1, NULL, 'system');
    COMMIT;
END;
/

DECLARE
    v_detail_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_detail_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, CREATE_BY)
    VALUES (v_detail_id, 'CostPingguDtl', '鎴愭湰璇勪及鏄庣粏', 'V_COST_PINGGU_DTL', 'T_COST_PINGGU_DTL', 'DTLID', 'CostPinggu', 'DOCID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'id', 'DTLID', 'ID', 'number', 0, 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'masterId', 'DOCID', '涓昏〃ID', 'number', 1, 0, 0, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'dtlUseflag', 'DTL_USEFLAG', '鍒嗙被', 'text', 2, 1, 1, NULL, '{"comparator":"customCategorySort"}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'apexGoodsname', 'APEX_GOODSNAME', '璐у搧鍚嶇О', 'text', 3, 1, 1, NULL, '{"lookup":{"code":"material","mapping":{"apexGoodsname":"materialName","price":"price"}}}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'spec', 'SPEC', '瑙勬牸', 'text', 4, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'perHl', 'PER_HL', '姣忕墖鍚噺', 'number', 5, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'exaddMater', 'EXADD_MATER', '棰濆鎶曟枡閲?, 'number', 6, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'batchQty', 'BATCH_QTY', '姣忔壒鏁伴噺', 'number', 7, 0, NULL, '{"calculate":{"formulaField":"formulaType","formulas":{"A":{"expression":"apexPl / pPerpack","triggerFields":["apexPl","pPerpack"]},"B":{"expression":"apexPl / 10000","triggerFields":["apexPl"]},"C":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]},"D":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]},"E":{"expression":"ceil(apexPl / (pPerpack * sPerback))","triggerFields":["apexPl","pPerpack","sPerback"]},"F":{"expression":"ceil(apexPl / (pPerpack * sPerback * xPerback))","triggerFields":["apexPl","pPerpack","sPerback","xPerback"]}}}}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'price', 'PRICE', '浠锋牸', 'number', 8, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'costBatch', 'COST_BATCH', '姣忔壒鎴愭湰', 'number', 9, 0, NULL, '{"calculate":{"expression":"batchQty * price","triggerFields":["batchQty","price"]}}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'apexFactoryname', 'APEX_FACTORYNAME', '鍘傚鍚嶇О', 'text', 10, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'memo', 'MEMO', '澶囨敞', 'text', 11, 1, NULL, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'formulaType', 'FORMULA_TYPE', '鍏紡绫诲瀷', 'text', 12, 0, 0, 1, NULL, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu', 'root', 'LAYOUT', NULL, 0, '{"direction":"vertical","gap":8}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu', 'masterGrid', 'GRID', 'root', 1, 'CostPinggu', '{"height":"50%","selectionMode":"single"}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu', 'detailTabs', 'TABS', 'root', 2, 'CostPingguDtl',
'{
  "mode": "group",
  "groupField": "dtlUseflag",
  "tabs": [
    {"key": "ylfl", "title": "鍘熸枡/杈呮枡", "values": ["鍘熸枡", "杈呮枡"]},
    {"key": "bc", "title": "鍖呮潗", "values": ["鍗板瓧鍖呮潗", "闈炲嵃瀛楀寘鏉?]}
  ],
  "broadcast": ["apexPl", "pPerpack", "sPerback", "xPerback"],
  "aggregates": [
    {"sourceField": "costBatch", "targetField": "totalYl", "algorithm": "SUM", "filter": "dtlUseflag === ''鍘熸枡''"},
    {"sourceField": "costBatch", "targetField": "totalFl", "algorithm": "SUM", "filter": "dtlUseflag === ''杈呮枡''"},
    {"sourceField": "costBatch", "targetField": "totalBc", "algorithm": "SUM", "filter": "dtlUseflag === ''鍗板瓧鍖呮潗'' || dtlUseflag === ''闈炲嵃瀛楀寘鏉?'"},
    {"targetField": "totalCost", "expression": "totalYl + totalFl + totalBc"}
  ],
  "postProcess": "if (totalYl > 0) { totalYl /= 1.13; totalFl /= 1.13; totalBc /= 1.13; totalCost = totalYl + totalFl + totalBc; }",
  "masterCalcRules": [
    {"field": "salemoney", "expression": "outPriceRmb / pPerpack * apexPl * (yield / 100)", "triggerFields": ["outPriceRmb", "pPerpack", "apexPl", "yield", "totalCost"]},
    {"field": "jgfBatch", "expression": "salemoney - totalCost", "triggerFields": ["salemoney", "totalCost"]},
    {"field": "jgfPerqp", "expression": "jgfBatch / apexPl * 1000", "triggerFields": ["jgfBatch", "apexPl"]},
    {"field": "mlPerqp", "expression": "jgfPerqp - costPerqp", "triggerFields": ["jgfPerqp", "costPerqp"]},
    {"field": "yJgRe", "expression": "jgfPerqp / 1000 * annualQty", "triggerFields": ["jgfPerqp", "annualQty"]},
    {"field": "yMl", "expression": "mlPerqp / 1000 * annualQty", "triggerFields": ["mlPerqp", "annualQty"]},
    {"field": "ySale", "expression": "salemoney / apexPl * annualQty", "triggerFields": ["salemoney", "apexPl", "annualQty"]}
  ]
}', 'system');

COMMIT;

-- =====================================================
-- D. 淇琛ヤ竵锛堝吋瀹瑰墠绔瓧娈靛懡鍚嶏級
-- =====================================================

-- D1. 浜哄憳鐩稿叧瑙嗗浘瀛楁鏍囪涓鸿櫄鎷熷垪
-- D2. 鎴愭湰璇勪及涓婚敭銆佸閿瓧娈靛懡鍚嶇粺涓€
COMMIT;


-- V2: 娣诲姞 Lookup 閰嶇疆鍜屾祴璇曠敤鎴锋潈闄?
-- 1. 缁?CostPingguDtl.apexGoodsname 瀛楁閰嶇疆 Lookup锛堝叧鑱旂墿鏂欒〃锛?
-- mapping: 璐у搧鍚?<- materialName, 浠锋牸 <- price
-- 2. 缁欐祴璇曠敤鎴凤紙user 瑙掕壊锛夋坊鍔?cost-pinggu 椤甸潰鏉冮檺
INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, CREATE_BY)
SELECT SEQ_COST_ROLE_PAGE.NEXTVAL, r.ID, 'cost-pinggu', '["CREATE","EDIT","DELETE"]', NULL, 'system'
FROM T_COST_ROLE r
WHERE r.ROLE_CODE = 'USER'
  AND NOT EXISTS (SELECT 1 FROM T_COST_ROLE_PAGE rp WHERE rp.ROLE_ID = r.ID AND rp.PAGE_CODE = 'cost-pinggu');

-- 3. 缁欑鐞嗗憳瑙掕壊娣诲姞 cost-pinggu 椤甸潰鏉冮檺锛堝叏閮ㄦ寜閽級
INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, CREATE_BY)
SELECT SEQ_COST_ROLE_PAGE.NEXTVAL, r.ID, 'cost-pinggu', '["*"]', NULL, 'system'
FROM T_COST_ROLE r
WHERE r.ROLE_CODE = 'ADMIN'
  AND NOT EXISTS (SELECT 1 FROM T_COST_ROLE_PAGE rp WHERE rp.ROLE_ID = r.ID AND rp.PAGE_CODE = 'cost-pinggu');

COMMIT;
COMMIT;

DELETE FROM T_COST_PAGE_COMPONENT
WHERE PAGE_CODE = 'cost-user' AND COMPONENT_TYPE = 'CONTEXT_MENU';

DELETE FROM T_COST_PAGE_COMPONENT
WHERE PAGE_CODE = 'user-manage' AND COMPONENT_TYPE = 'CONTEXT_MENU';

INSERT INTO T_COST_PAGE_COMPONENT (
    ID,
    PAGE_CODE,
    COMPONENT_KEY,
    COMPONENT_TYPE,
    PARENT_KEY,
    SORT_ORDER,
    COMPONENT_CONFIG
)
VALUES (
    SEQ_COST_PAGE_COMPONENT.NEXTVAL,
    'user-manage',
    'contextMenu',
    'CONTEXT_MENU',
    NULL,
    99,
    '{
        "items": [
            {
                "label": "鏂板琛?,
                "key": "add",
                "icon": "mdi:plus",
                "action": "addRow"
            },
            {
                "label": "澶嶅埗琛?,
                "key": "copy",
                "icon": "mdi:content-copy",
                "action": "copyRow",
                "disabled": "!selectedRow"
            },
            {
                "label": "鍒犻櫎",
                "key": "delete",
                "icon": "mdi:delete",
                "action": "deleteRow",
                "confirm": true,
                "confirmMessage": "纭鍒犻櫎閫変腑鐨勭敤鎴峰悧锛?,
                "disabled": "!selectedRow"
            }
        ]
    }'
);

COMMIT;

INSERT INTO T_COST_PINGGU (
    GOODSID,
    GOODSNAME,
    STRENGTH,
    MA_NO,
    APEX_PL,
    MAH,
    P_PERPACK,
    FORM,
    S_PERBACK,
    PACKTYPE,
    X_PERBACK,
    TOTAL_FL,
    TOTAL_BC,
    TOTAL_YL,
    MEMO,
    USESTATUS,
    DOCID,
    DOSAGE,
    ANNUAL_QTY,
    YIELD,
    TOTAL_COST,
    OUT_PRICE_F,
    OUT_PRICE_RMB,
    SALEMONEY,
    JGF_BATCH,
    JGF_PERQP,
    COST_PERQP,
    ML_PERQP,
    Y_JG_RE,
    Y_ML,
    Y_SALE,
    CUSTOMID,
    CUSTOMNAME,
    COUNTRY,
    PROJECTNO,
    USEFLAG,
    YIELD_TIME,
    APEX_PL_TIME,
    ZX_SOURCE,
    FMNAME,
    FMRATE,
    GOODSNAME_EN,
    LIVERY,
    DELETED,
    CREATE_TIME,
    UPDATE_TIME,
    CREATE_BY,
    UPDATE_BY
)
SELECT
    a.GOODSID,
    a.GOODSNAME,
    a.STRENGTH,
    a.MA_NO,
    a.APEX_PL,
    a.MAH,
    a.P_PERPACK,
    a.FORM,
    a.S_PERBACK,
    a.PACKTYPE,
    a.X_PERBACK,
    a.TOTAL_FL,
    a.TOTAL_BC,
    a.TOTAL_YL,
    a.MEMO,
    a.USESTATUS,
    a.DOCID,
    a.DOSAGE,
    a.ANNUAL_QTY,
    a.YIELD,
    a.TOTAL_COST,
    a.OUT_PRICE_F,
    a.OUT_PRICE_RMB,
    a.SALEMONEY,
    a.JGF_BATCH,
    a.JGF_PERQP,
    a.COST_PERQP,
    a.ML_PERQP,
    a.Y_JG_RE,
    a.Y_ML,
    a.Y_SALE,
    a.CUSTOMID,
    a.CUSTOMNAME,
    a.COUNTRY,
    a.PROJECTNO,
    a.USEFLAG,
    a.YIELD_TIME,
    a.APEX_PL_TIME,
    a.ZX_SOURCE,
    a.FMNAME,
    a.FMRATE,
    a.GOODSNAME_EN,
    a.LIVERY,
    0,
    SYSTIMESTAMP,
    SYSTIMESTAMP,
    'system',
    'system'
FROM hy.apex_sa_pinggu a
WHERE a.DOCID IN (3452, 2943);

INSERT INTO T_COST_PINGGU_DTL (
    DOCID,
    APEX_GOODSID,
    APEX_GOODSNAME,
    DTL_USEFLAG,
    SPEC,
    PER_HL,
    EXADD_MATER,
    BATCH_QTY,
    PRICE,
    COST_BATCH,
    MEMO,
    DTLID,
    APEX_FACTORYNAME,
    APEX_FACTORYID,
    MODIFYDATE,
    ZX_SOURCE,
    BASE_PRICE,
    SUQTY,
    GOODSTYPE,
    GOODSNAME_EN,
    DELETED,
    CREATE_TIME,
    UPDATE_TIME,
    CREATE_BY,
    UPDATE_BY
)
SELECT
    a.DOCID,
    a.APEX_GOODSID,
    a.APEX_GOODSNAME,
    a.DTL_USEFLAG,
    a.SPEC,
    a.PER_HL,
    a.EXADD_MATER,
    a.BATCH_QTY,
    a.PRICE,
    a.COST_BATCH,
    a.MEMO,
    a.DTLID,
    a.APEX_FACTORYNAME,
    a.APEX_FACTORYID,
    a.MODIFYDATE,
    a.ZX_SOURCE,
    a.BASE_PRICE,
    a.SUQTY,
    a.GOODSTYPE,
    a.GOODSNAME_EN,
    0,
    SYSTIMESTAMP,
    SYSTIMESTAMP,
    'system',
    'system'
FROM hy.apex_sa_pinggu_dtl a
WHERE a.DOCID IN (3452, 2943);

COMMIT;

SELECT 
    TABLE_CODE,
    DBMS_LOB.SUBSTR(ACTION_RULES, 4000, 1) AS ACTION_RULES_TEXT
FROM T_COST_TABLE_METADATA
WHERE TABLE_CODE = 'CostUser';

SELECT 
    PAGE_CODE,
    COMPONENT_KEY,
    COMPONENT_TYPE,
    DBMS_LOB.SUBSTR(COMPONENT_CONFIG, 4000, 1) AS CONFIG_PREVIEW
FROM T_COST_PAGE_COMPONENT
WHERE PAGE_CODE = 'user-manage' AND COMPONENT_TYPE = 'CONTEXT_MENU';

-- END rebuild_cost_schema.sql
-- BEGIN merge_detail_tabs.sql
-- =====================================================
-- 鎴愭湰璇勪及椤甸潰鏀归€狅細鍚堝苟鍘熸枡/杈呮枡/鍖呮潗鍒颁竴涓〃鏍?
-- 鍘绘帀渚ц竟鏍?Tab锛屾墍鏈夋槑缁嗗湪涓€涓?Grid 涓睍绀?
-- =====================================================

-- 1. 鍒犻櫎鏃х殑 TABS 缁勪欢閰嶇疆
DELETE FROM T_COST_PAGE_COMPONENT
WHERE PAGE_CODE = 'cost-pinggu' AND COMPONENT_KEY = 'detailTabs';

-- 2. 鏂板鍗曚竴 TABS 缁勪欢锛堝彧鏈変竴涓?Tab锛屾樉绀烘墍鏈夋槑缁嗭紝鍖呭惈鑱氬悎鍜岀骇鑱旇绠楋級
INSERT INTO T_COST_PAGE_COMPONENT (
    ID,
    PAGE_CODE,
    COMPONENT_KEY,
    COMPONENT_TYPE,
    PARENT_KEY,
    SORT_ORDER,
    REF_TABLE_CODE,
    COMPONENT_CONFIG,
    CREATE_BY
)
VALUES (
    SEQ_COST_PAGE_COMPONENT.NEXTVAL,
    'cost-pinggu',
    'detailTabs',
    'TABS',
    'root',
    2,
    'CostPingguDtl',
    '{
      "mode": "group",
      "tabs": [
        {
          "key": "all",
          "title": "鏄庣粏",
          "columns": ["dtlUseflag", "apexGoodsname", "spec", "perHl", "exaddMater", "batchQty", "price", "costBatch", "apexFactoryname", "memo"],
          "initialSort": [
            {"colId": "dtlUseflag", "sort": "asc"}
          ]
        }
      ],
      "broadcast": ["apexPl", "pPerpack", "sPerback", "xPerback"],
      "aggregates": [
        {"sourceField": "costBatch", "targetField": "totalYl", "algorithm": "SUM", "filter": "dtlUseflag === ''鍘熸枡''"},
        {"sourceField": "costBatch", "targetField": "totalFl", "algorithm": "SUM", "filter": "dtlUseflag === ''杈呮枡''"},
        {"sourceField": "costBatch", "targetField": "totalBc", "algorithm": "SUM", "filter": "dtlUseflag === ''鍗板瓧鍖呮潗'' || dtlUseflag === ''闈炲嵃瀛楀寘鏉?'"},
        {"targetField": "totalCost", "expression": "totalYl + totalFl + totalBc"}
      ],
      "postProcess": "if (totalYl > 0) { totalYl /= 1.13; totalFl /= 1.13; totalBc /= 1.13; totalCost = totalYl + totalFl + totalBc; }",
      "masterCalcRules": [
        {"field": "salemoney", "expression": "outPriceRmb / pPerpack * apexPl * (yield / 100)", "triggerFields": ["outPriceRmb", "pPerpack", "apexPl", "yield", "totalCost"]},
        {"field": "jgfBatch", "expression": "salemoney - totalCost", "triggerFields": ["salemoney", "totalCost"]},
        {"field": "jgfPerqp", "expression": "jgfBatch / apexPl * 1000", "triggerFields": ["jgfBatch", "apexPl"]},
        {"field": "mlPerqp", "expression": "jgfPerqp - costPerqp", "triggerFields": ["jgfPerqp", "costPerqp"]},
        {"field": "yJgRe", "expression": "jgfPerqp / 1000 * annualQty", "triggerFields": ["jgfPerqp", "annualQty"]},
        {"field": "yMl", "expression": "mlPerqp / 1000 * annualQty", "triggerFields": ["mlPerqp", "annualQty"]},
        {"field": "ySale", "expression": "salemoney / apexPl * annualQty", "triggerFields": ["salemoney", "apexPl", "annualQty"]}
      ]
    }',
    'system'
);

COMMIT;

-- 楠岃瘉閰嶇疆
SELECT 
    COMPONENT_KEY,
    COMPONENT_TYPE,
    SORT_ORDER,
    COMPONENT_CONFIG
FROM T_COST_PAGE_COMPONENT
WHERE PAGE_CODE = 'cost-pinggu'
ORDER BY SORT_ORDER;

-- END merge_detail_tabs.sql
-- BEGIN add_sort_config.sql
-- =====================================================
-- 涓烘垚鏈瘎浼版槑缁嗚〃娣诲姞鑷畾涔夋帓搴忛厤缃?
-- 鏂规锛氫娇鐢?comparator 鑷畾涔夋帓搴忥紙鍘熸枡 鈫?杈呮枡 鈫?鍗板瓧鍖呮潗 鈫?闈炲嵃瀛楀寘鏉愶級
-- =====================================================

-- 1. 鏇存柊 dtlUseflag 鍒楀厓鏁版嵁锛屾坊鍔?comparator 閰嶇疆
-- 2. 鏇存柊 TABS 閰嶇疆锛屾坊鍔?initialSort
totalFl /= 1.13; totalBc /= 1.13; totalCost = totalYl + totalFl + totalBc; }",
  "masterCalcRules": [
    {"field": "salemoney", "expression": "outPriceRmb / pPerpack * apexPl * (yield / 100)", "triggerFields": ["outPriceRmb", "pPerpack", "apexPl", "yield", "totalCost"]},
    {"field": "jgfBatch", "expression": "salemoney - totalCost", "triggerFields": ["salemoney", "totalCost"]},
    {"field": "jgfPerqp", "expression": "jgfBatch / apexPl * 1000", "triggerFields": ["jgfBatch", "apexPl"]},
    {"field": "mlPerqp", "expression": "jgfPerqp - costPerqp", "triggerFields": ["jgfPerqp", "costPerqp"]},
    {"field": "yJgRe", "expression": "jgfPerqp / 1000 * annualQty", "triggerFields": ["jgfPerqp", "annualQty"]},
    {"field": "yMl", "expression": "mlPerqp / 1000 * annualQty", "triggerFields": ["mlPerqp", "annualQty"]},
    {"field": "ySale", "expression": "salemoney / apexPl * annualQty", "triggerFields": ["salemoney", "apexPl", "annualQty"]}
  ]
}'
WHERE PAGE_CODE = 'cost-pinggu' AND COMPONENT_KEY = 'detailTabs';

COMMIT;

-- END add_sort_config.sql
-- BEGIN reset_column_width.sql
-- =====================================================
-- 灏嗘墍鏈夊垪鐨勫搴﹁缃负 NULL锛岃 AG Grid 鑷姩璋冩暣鍒楀
-- =====================================================

COMMIT;

-- 鏌ョ湅鏇存柊缁撴灉
SELECT COUNT(*) AS updated_count
FROM T_COST_COLUMN_METADATA
WHERE WIDTH IS NULL;

-- END reset_column_width.sql
