CREATE OR REPLACE PACKAGE BODY PKG_WF_APPROVAL AS

  PROCEDURE ADD_LOG(P_APPROVAL_ID IN NUMBER, P_ROUND_NO IN NUMBER, P_DETAIL_ID IN NUMBER, P_ACTION_TYPE IN VARCHAR2, P_ACTION_USER_ID IN NUMBER, P_ACTION_USERNAME IN VARCHAR2, P_ACTION_REAL_NAME IN VARCHAR2, P_FROM_STATUS IN VARCHAR2, P_TO_STATUS IN VARCHAR2, P_ACTION_COMMENT IN VARCHAR2, P_DETAIL_MESSAGE IN VARCHAR2) AS
  BEGIN
    INSERT INTO WF_APPROVAL_LOG (LOG_ID, APPROVAL_ID, ROUND_NO, DETAIL_ID, ACTION_TYPE, ACTION_USER_ID, ACTION_USERNAME, ACTION_REAL_NAME, ACTION_TIME, FROM_STATUS, TO_STATUS, ACTION_COMMENT, DETAIL_MESSAGE)
    VALUES (SEQ_WF_APPROVAL_LOG.NEXTVAL, P_APPROVAL_ID, P_ROUND_NO, P_DETAIL_ID, P_ACTION_TYPE, P_ACTION_USER_ID, P_ACTION_USERNAME, P_ACTION_REAL_NAME, SYSTIMESTAMP, P_FROM_STATUS, P_TO_STATUS, P_ACTION_COMMENT, P_DETAIL_MESSAGE);
  END;

  PROCEDURE GET_USER_INFO(P_USER_ID IN NUMBER, O_USERNAME OUT VARCHAR2, O_REAL_NAME OUT VARCHAR2, O_DEPT_ID OUT NUMBER, O_DEPT_NAME OUT VARCHAR2) AS
  BEGIN
    SELECT U.USERNAME, U.REAL_NAME, U.DEPARTMENT_ID, D.DEPT_NAME INTO O_USERNAME, O_REAL_NAME, O_DEPT_ID, O_DEPT_NAME
      FROM T_COST_USER U LEFT JOIN T_COST_DEPARTMENT D ON D.ID=U.DEPARTMENT_ID AND D.DELETED=0
     WHERE U.ID=P_USER_ID AND U.STATUS='ACTIVE' AND U.DELETED=0;
  END;

  PROCEDURE GET_TABLE_INFO(P_TABLE_CODE IN VARCHAR2, O_TARGET_TABLE OUT VARCHAR2, O_PK_COLUMN OUT VARCHAR2) AS
  BEGIN
    SELECT TARGET_TABLE, PK_COLUMN INTO O_TARGET_TABLE, O_PK_COLUMN FROM T_COST_TABLE_METADATA WHERE TABLE_CODE=P_TABLE_CODE AND DELETED=0;
  END;

  PROCEDURE VALIDATE_IDENTIFIER(P_VALUE IN VARCHAR2, P_NAME IN VARCHAR2) AS
  BEGIN
    IF P_VALUE IS NULL OR NOT REGEXP_LIKE(P_VALUE, '^[A-Za-z][A-Za-z0-9_]*$') THEN RAISE_APPLICATION_ERROR(-20901, P_NAME || ' invalid: ' || P_VALUE); END IF;
  END;

  PROCEDURE UPDATE_BIZ_APPROVAL_STATUS(P_TABLE_CODE IN VARCHAR2, P_BILL_ID IN NUMBER, P_APPROVAL_ID IN NUMBER, P_APPROVAL_STATUS IN VARCHAR2, P_USERNAME IN VARCHAR2) AS
    V_TARGET_TABLE VARCHAR2(128); V_PK_COLUMN VARCHAR2(128); V_SQL VARCHAR2(4000);
  BEGIN
    GET_TABLE_INFO(P_TABLE_CODE, V_TARGET_TABLE, V_PK_COLUMN); VALIDATE_IDENTIFIER(V_TARGET_TABLE,'TARGET_TABLE'); VALIDATE_IDENTIFIER(V_PK_COLUMN,'PK_COLUMN');
    V_SQL := 'UPDATE '||V_TARGET_TABLE||' SET APPROVAL_ID=:1, APPROVAL_STATUS=:2, UPDATE_BY=:3, UPDATE_TIME=SYSDATE WHERE '||V_PK_COLUMN||'=:4 AND DELETED=0';
    EXECUTE IMMEDIATE V_SQL USING P_APPROVAL_ID, P_APPROVAL_STATUS, P_USERNAME, P_BILL_ID;
    IF SQL%ROWCOUNT=0 THEN RAISE_APPLICATION_ERROR(-20902, 'Business row not found'); END IF;
  END;

  FUNCTION SQL_HAS_FORBIDDEN_KEYWORD(P_SQL IN CLOB) RETURN VARCHAR2 AS V_SQL VARCHAR2(32767);
  BEGIN
    IF P_SQL IS NULL THEN RETURN 'N'; END IF;
    V_SQL := UPPER(DBMS_LOB.SUBSTR(P_SQL,32767,1));
    IF INSTR(V_SQL,';')>0 OR INSTR(V_SQL,'--')>0 OR INSTR(V_SQL,'/*')>0 OR REGEXP_LIKE(V_SQL,'(^|[^A-Z])(INSERT|UPDATE|DELETE|MERGE|DROP|ALTER|TRUNCATE|CREATE|GRANT|REVOKE|EXECUTE|BEGIN|DECLARE)([^A-Z]|$)') THEN RETURN 'Y'; END IF;
    RETURN 'N';
  END;

  FUNCTION EVAL_CONDITION(P_MODE IN VARCHAR2, P_SQL_EXPR IN CLOB, P_ON_ERROR IN VARCHAR2, P_TABLE_CODE IN VARCHAR2, P_BILL_ID IN NUMBER, P_CURRENT_USER_ID IN NUMBER, P_PAGE_CODE IN VARCHAR2) RETURN VARCHAR2 AS
    V_TARGET_TABLE VARCHAR2(128); V_PK_COLUMN VARCHAR2(128); V_SQL VARCHAR2(32767); V_EXPR VARCHAR2(30000); V_COUNT NUMBER; V_MODE VARCHAR2(20):=NVL(P_MODE,'ALWAYS');
  BEGIN
    IF V_MODE='ALWAYS' THEN RETURN 'Y'; END IF;
    IF V_MODE='VISUAL' THEN RETURN 'Y'; END IF;
    IF V_MODE='SQL' THEN
      IF P_SQL_EXPR IS NULL THEN RETURN 'Y'; END IF;
      IF SQL_HAS_FORBIDDEN_KEYWORD(P_SQL_EXPR)='Y' THEN IF P_ON_ERROR='BLOCK' THEN RAISE_APPLICATION_ERROR(-20910,'Forbidden SQL keyword'); END IF; RETURN 'N'; END IF;
      GET_TABLE_INFO(P_TABLE_CODE,V_TARGET_TABLE,V_PK_COLUMN); VALIDATE_IDENTIFIER(V_TARGET_TABLE,'TARGET_TABLE'); VALIDATE_IDENTIFIER(V_PK_COLUMN,'PK_COLUMN');
      V_EXPR := DBMS_LOB.SUBSTR(P_SQL_EXPR,30000,1);
      V_EXPR := REPLACE(V_EXPR, ':BILL_ID', TO_CHAR(P_BILL_ID));
      V_EXPR := REPLACE(V_EXPR, ':CURRENT_USER_ID', TO_CHAR(P_CURRENT_USER_ID));
      V_EXPR := REPLACE(V_EXPR, ':PAGE_CODE', ''''||REPLACE(P_PAGE_CODE,'''','''''')||'''');
      V_EXPR := REPLACE(V_EXPR, ':TABLE_CODE', ''''||REPLACE(P_TABLE_CODE,'''','''''')||'''');
      V_SQL := 'SELECT COUNT(1) FROM '||V_TARGET_TABLE||' M WHERE M.'||V_PK_COLUMN||'=:BILL_ID AND M.DELETED=0 AND ('||V_EXPR||')';
      EXECUTE IMMEDIATE V_SQL INTO V_COUNT USING P_BILL_ID;
      IF V_COUNT>0 THEN RETURN 'Y'; ELSE RETURN 'N'; END IF;
    END IF;
    RETURN 'Y';
  EXCEPTION WHEN OTHERS THEN
    IF P_ON_ERROR='BLOCK' THEN RAISE; END IF; RETURN 'N';
  END;

  FUNCTION GET_FORCE_APPROVER(P_TABLE_CODE IN VARCHAR2, P_BILL_ID IN NUMBER, O_NAME OUT VARCHAR2) RETURN NUMBER AS
    V_TARGET_TABLE VARCHAR2(128); V_PK_COLUMN VARCHAR2(128); V_SQL VARCHAR2(4000); V_USER_ID NUMBER;
  BEGIN
    GET_TABLE_INFO(P_TABLE_CODE,V_TARGET_TABLE,V_PK_COLUMN); VALIDATE_IDENTIFIER(V_TARGET_TABLE,'TARGET_TABLE'); VALIDATE_IDENTIFIER(V_PK_COLUMN,'PK_COLUMN');
    V_SQL := 'SELECT FORCE_APPROVER_USER_ID, FORCE_APPROVER_NAME FROM '||V_TARGET_TABLE||' WHERE '||V_PK_COLUMN||'=:1 AND DELETED=0';
    EXECUTE IMMEDIATE V_SQL INTO V_USER_ID, O_NAME USING P_BILL_ID;
    RETURN V_USER_ID;
  EXCEPTION WHEN OTHERS THEN O_NAME:=NULL; RETURN NULL;
  END;

  PROCEDURE SELECT_FLOW(P_PAGE_CODE IN VARCHAR2, P_TABLE_CODE IN VARCHAR2, P_BILL_ID IN NUMBER, P_CURRENT_USER_ID IN NUMBER, O_FLOW_ID OUT NUMBER, O_NEED_APPROVAL OUT VARCHAR2) AS
    V_HAS_COND NUMBER; V_HIT VARCHAR2(1);
  BEGIN
    O_FLOW_ID := NULL; O_NEED_APPROVAL := 'N';
    FOR F IN (SELECT FLOW_ID FROM WF_FLOW_DEF WHERE PAGE_CODE=P_PAGE_CODE AND IS_ENABLED=1 ORDER BY FLOW_PRIORITY, FLOW_VERSION DESC, FLOW_ID DESC) LOOP
      SELECT COUNT(1) INTO V_HAS_COND FROM WF_FLOW_CONDITION WHERE FLOW_ID=F.FLOW_ID AND IS_ENABLED=1;
      IF V_HAS_COND=0 THEN V_HIT := 'Y';
      ELSE
        V_HIT := 'N';
        FOR C IN (SELECT CONDITION_MODE, SQL_EXPR, ON_ERROR FROM WF_FLOW_CONDITION WHERE FLOW_ID=F.FLOW_ID AND IS_ENABLED=1 ORDER BY CONDITION_ID) LOOP
          IF EVAL_CONDITION(C.CONDITION_MODE,C.SQL_EXPR,C.ON_ERROR,P_TABLE_CODE,P_BILL_ID,P_CURRENT_USER_ID,P_PAGE_CODE)='Y' THEN V_HIT:='Y'; EXIT; END IF;
        END LOOP;
      END IF;
      IF V_HIT='Y' THEN O_FLOW_ID:=F.FLOW_ID; O_NEED_APPROVAL:='Y'; RETURN; END IF;
    END LOOP;
  END;

  PROCEDURE FINISH_APPROVAL(P_APPROVAL_ID IN NUMBER, P_ROUND_NO IN NUMBER, P_TABLE_CODE IN VARCHAR2, P_BILL_ID IN NUMBER, P_USER_ID IN NUMBER, P_USERNAME IN VARCHAR2, P_REAL_NAME IN VARCHAR2) AS
  BEGIN
    UPDATE WF_APPROVAL_MAIN SET STATUS='APPROVED', CURRENT_LEVEL=NULL, APPROVED_TIME=SYSTIMESTAMP, FINISHED_TIME=SYSTIMESTAMP, UPDATE_BY=P_USERNAME, UPDATE_TIME=SYSTIMESTAMP WHERE APPROVAL_ID=P_APPROVAL_ID;
    UPDATE_BIZ_APPROVAL_STATUS(P_TABLE_CODE,P_BILL_ID,P_APPROVAL_ID,'APPROVED',P_USERNAME);
    ADD_LOG(P_APPROVAL_ID,P_ROUND_NO,NULL,'FINISH',P_USER_ID,P_USERNAME,P_REAL_NAME,'APPROVING','APPROVED',UNISTR('\5BA1\6279\6D41\7A0B\5168\90E8\5B8C\6210'),NULL);
  END;

  PROCEDURE SYSTEM_REJECT_CONDITION(P_APPROVAL_ID IN NUMBER, P_ROUND_NO IN NUMBER, P_TABLE_CODE IN VARCHAR2, P_BILL_ID IN NUMBER, P_NODE_ID IN NUMBER, P_LEVEL IN NUMBER, P_NODE_NAME IN VARCHAR2, P_MODE IN VARCHAR2) AS
    V_DETAIL_ID NUMBER;
  BEGIN
    INSERT INTO WF_APPROVAL_DETAIL(DETAIL_ID,APPROVAL_ID,ROUND_NO,NODE_ID,APPROVAL_LEVEL,NODE_NAME,APPROVAL_MODE,TARGET_TYPE,TARGET_USER_ID,TARGET_USER_NAME,STATUS,OPERATE_USER_ID,OPERATE_USERNAME,OPERATE_REAL_NAME,APPROVE_COMMENT,OPERATE_TIME,AUTO_REASON,CREATE_TIME)
    VALUES(SEQ_WF_APPROVAL_DETAIL.NEXTVAL,P_APPROVAL_ID,P_ROUND_NO,P_NODE_ID,P_LEVEL,P_NODE_NAME,P_MODE,'USER',111,UNISTR('\7CFB\7EDF\7BA1\7406\5458'),'REJECTED',111,'admin',UNISTR('\7CFB\7EDF\7BA1\7406\5458'),UNISTR('\4E0D\6EE1\8DB3\4EFB\4F55\5BA1\6279\6761\4EF6'),SYSTIMESTAMP,'CONDITION_NOT_MATCH',SYSTIMESTAMP)
    RETURNING DETAIL_ID INTO V_DETAIL_ID;

    UPDATE WF_APPROVAL_DETAIL
       SET STATUS='CANCELED', OPERATE_TIME=SYSTIMESTAMP, UPDATE_BY='admin', UPDATE_TIME=SYSTIMESTAMP
     WHERE APPROVAL_ID=P_APPROVAL_ID
       AND ROUND_NO=P_ROUND_NO
       AND DETAIL_ID<>V_DETAIL_ID
       AND STATUS IN ('WAITING','PENDING');

    UPDATE WF_APPROVAL_MAIN
       SET STATUS='REJECTED', CURRENT_LEVEL=NULL, REJECTED_TIME=SYSTIMESTAMP, FINISHED_TIME=SYSTIMESTAMP, UPDATE_BY='admin', UPDATE_TIME=SYSTIMESTAMP
     WHERE APPROVAL_ID=P_APPROVAL_ID;

    UPDATE_BIZ_APPROVAL_STATUS(P_TABLE_CODE,P_BILL_ID,P_APPROVAL_ID,'REJECTED','admin');

    ADD_LOG(P_APPROVAL_ID,P_ROUND_NO,V_DETAIL_ID,'REJECT',111,'admin',UNISTR('\7CFB\7EDF\7BA1\7406\5458'),'WAITING','REJECTED',UNISTR('\4E0D\6EE1\8DB3\4EFB\4F55\5BA1\6279\6761\4EF6'),UNISTR('\7CFB\7EDF\81EA\52A8\9A73\56DE'));
  END;

  PROCEDURE START_NEXT_LEVEL(P_APPROVAL_ID IN NUMBER, P_ROUND_NO IN NUMBER, P_FLOW_ID IN NUMBER, P_START_AFTER_LEVEL IN NUMBER, P_DEPT_ID IN NUMBER, P_TABLE_CODE IN VARCHAR2, P_BILL_ID IN NUMBER, P_USER_ID IN NUMBER, P_USERNAME IN VARCHAR2, P_REAL_NAME IN VARCHAR2, P_PAGE_CODE IN VARCHAR2) AS
    V_LEVEL_COUNT NUMBER; V_DETAIL_ID NUMBER; V_APPROVER_COUNT NUMBER; V_NODE_HIT VARCHAR2(1); V_BRANCH_HIT VARCHAR2(1);
  BEGIN
    FOR N IN (SELECT * FROM WF_FLOW_NODE WHERE FLOW_ID=P_FLOW_ID AND IS_ENABLED=1 AND APPROVAL_LEVEL>P_START_AFTER_LEVEL ORDER BY APPROVAL_LEVEL) LOOP
      V_NODE_HIT := EVAL_CONDITION(N.CONDITION_MODE,N.SQL_EXPR,N.ON_ERROR,P_TABLE_CODE,P_BILL_ID,P_USER_ID,P_PAGE_CODE);
      IF V_NODE_HIT='N' THEN
        SYSTEM_REJECT_CONDITION(P_APPROVAL_ID,P_ROUND_NO,P_TABLE_CODE,P_BILL_ID,N.NODE_ID,N.APPROVAL_LEVEL,N.NODE_NAME,N.APPROVAL_MODE);
        RETURN;
      ELSE
        V_APPROVER_COUNT := 0;
        FOR A IN (SELECT * FROM WF_FLOW_APPROVER A WHERE A.NODE_ID=N.NODE_ID AND A.IS_ENABLED=1 AND (A.APPLY_DEPT_ID=P_DEPT_ID OR (A.APPLY_DEPT_ID IS NULL AND NOT EXISTS(SELECT 1 FROM WF_FLOW_APPROVER X WHERE X.NODE_ID=N.NODE_ID AND X.IS_ENABLED=1 AND X.APPLY_DEPT_ID=P_DEPT_ID))) ORDER BY A.SORT_ORDER,A.ID) LOOP
          V_BRANCH_HIT := EVAL_CONDITION(A.CONDITION_MODE,A.SQL_EXPR,A.ON_ERROR,P_TABLE_CODE,P_BILL_ID,P_USER_ID,P_PAGE_CODE);
          IF V_BRANCH_HIT='Y' THEN
            INSERT INTO WF_APPROVAL_DETAIL(DETAIL_ID,APPROVAL_ID,ROUND_NO,NODE_ID,APPROVAL_LEVEL,NODE_NAME,APPROVAL_MODE,TARGET_TYPE,TARGET_USER_ID,TARGET_USER_NAME,TARGET_ROLE_ID,TARGET_ROLE_CODE,TARGET_ROLE_NAME,STATUS,CREATE_TIME)
            VALUES(SEQ_WF_APPROVAL_DETAIL.NEXTVAL,P_APPROVAL_ID,P_ROUND_NO,N.NODE_ID,N.APPROVAL_LEVEL,N.NODE_NAME,N.APPROVAL_MODE,A.TARGET_TYPE,A.TARGET_USER_ID,A.TARGET_USER_NAME,A.TARGET_ROLE_ID,A.TARGET_ROLE_CODE,A.TARGET_ROLE_NAME,'PENDING',SYSTIMESTAMP);
            V_APPROVER_COUNT := V_APPROVER_COUNT + 1;
          END IF;
        END LOOP;
        IF V_APPROVER_COUNT=0 THEN
          INSERT INTO WF_APPROVAL_DETAIL(DETAIL_ID,APPROVAL_ID,ROUND_NO,NODE_ID,APPROVAL_LEVEL,NODE_NAME,APPROVAL_MODE,TARGET_TYPE,STATUS,AUTO_REASON,CREATE_TIME)
          VALUES(SEQ_WF_APPROVAL_DETAIL.NEXTVAL,P_APPROVAL_ID,P_ROUND_NO,N.NODE_ID,N.APPROVAL_LEVEL,N.NODE_NAME,N.APPROVAL_MODE,'USER','AUTO_APPROVED','NO_APPROVER_MATCHED',SYSTIMESTAMP)
          RETURNING DETAIL_ID INTO V_DETAIL_ID;
          ADD_LOG(P_APPROVAL_ID,P_ROUND_NO,V_DETAIL_ID,'AUTO_APPROVE',P_USER_ID,P_USERNAME,P_REAL_NAME,'WAITING','AUTO_APPROVED',UNISTR('\7B2C')||N.APPROVAL_LEVEL||UNISTR('\7EA7\65E0\4EBA\8BA4\9886\FF0C\81EA\52A8\901A\8FC7'),NULL);
        ELSE
          UPDATE WF_APPROVAL_MAIN SET CURRENT_LEVEL=N.APPROVAL_LEVEL, UPDATE_BY=P_USERNAME, UPDATE_TIME=SYSTIMESTAMP WHERE APPROVAL_ID=P_APPROVAL_ID;
          RETURN;
        END IF;
      END IF;
    END LOOP;
    FINISH_APPROVAL(P_APPROVAL_ID,P_ROUND_NO,P_TABLE_CODE,P_BILL_ID,P_USER_ID,P_USERNAME,P_REAL_NAME);
  END;

  PROCEDURE CHECK_DETAIL_AUTH(P_TARGET_TYPE IN VARCHAR2, P_TARGET_USER_ID IN NUMBER, P_TARGET_ROLE_ID IN NUMBER, P_CURRENT_USER_ID IN NUMBER) AS V_COUNT NUMBER;
  BEGIN
    IF P_TARGET_TYPE='USER' THEN IF P_TARGET_USER_ID<>P_CURRENT_USER_ID THEN RAISE_APPLICATION_ERROR(-20930,'not approver'); END IF;
    ELSIF P_TARGET_TYPE='ROLE' THEN SELECT COUNT(1) INTO V_COUNT FROM T_COST_USER_ROLE UR JOIN T_COST_USER U ON U.ID=UR.USER_ID WHERE UR.USER_ID=P_CURRENT_USER_ID AND UR.ROLE_ID=P_TARGET_ROLE_ID AND U.STATUS='ACTIVE' AND U.DELETED=0; IF V_COUNT=0 THEN RAISE_APPLICATION_ERROR(-20931,'not in role'); END IF;
    ELSE RAISE_APPLICATION_ERROR(-20932,'bad target'); END IF;
  END;

  PROCEDURE APPLY_APPROVAL(P_PAGE_CODE IN VARCHAR2,P_PAGE_NAME IN VARCHAR2,P_TABLE_CODE IN VARCHAR2,P_BILL_ID IN NUMBER,P_BILL_NO IN VARCHAR2,P_BILL_TITLE IN VARCHAR2,P_CURRENT_USER_ID IN NUMBER,P_CONDITION_JSON IN CLOB,O_APPROVAL_ID OUT NUMBER,O_STATUS OUT VARCHAR2,O_MSG OUT VARCHAR2) AS
    V_FLOW_ID NUMBER; V_NEED VARCHAR2(1); V_EXISTS NUMBER:=0; V_EXIST_STATUS VARCHAR2(30); V_AFTER_STATUS VARCHAR2(30); V_OLD_ROUND NUMBER; V_ROUND_NO NUMBER; V_USERNAME VARCHAR2(64); V_REAL_NAME VARCHAR2(128); V_DEPT_ID NUMBER; V_DEPT_NAME VARCHAR2(128); V_FORCE_ID NUMBER; V_FORCE_NAME VARCHAR2(128); V_FORCE_USERNAME VARCHAR2(64); V_FORCE_REAL VARCHAR2(128); V_FORCE_DEPT NUMBER; V_FORCE_DEPT_NAME VARCHAR2(128);
  BEGIN
    O_STATUS:='FAIL'; O_MSG:=NULL; O_APPROVAL_ID:=NULL;
    GET_USER_INFO(P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,V_DEPT_ID,V_DEPT_NAME);
    V_FORCE_ID := GET_FORCE_APPROVER(P_TABLE_CODE,P_BILL_ID,V_FORCE_NAME);
    BEGIN SELECT APPROVAL_ID,STATUS,NVL(CURRENT_ROUND,1) INTO O_APPROVAL_ID,V_EXIST_STATUS,V_OLD_ROUND FROM (SELECT APPROVAL_ID,STATUS,CURRENT_ROUND FROM WF_APPROVAL_MAIN WHERE PAGE_CODE=P_PAGE_CODE AND TABLE_CODE=P_TABLE_CODE AND BILL_ID=P_BILL_ID ORDER BY APPROVAL_ID DESC) WHERE ROWNUM=1; V_EXISTS:=1; EXCEPTION WHEN NO_DATA_FOUND THEN V_EXISTS:=0; END;
    IF V_EXISTS=1 THEN IF V_EXIST_STATUS<>'CANCELED' THEN RAISE_APPLICATION_ERROR(-20970,'Only canceled approval can resubmit'); END IF; V_ROUND_NO:=V_OLD_ROUND+1; ELSE V_ROUND_NO:=1; END IF;
    SELECT_FLOW(P_PAGE_CODE,P_TABLE_CODE,P_BILL_ID,P_CURRENT_USER_ID,V_FLOW_ID,V_NEED);
    IF V_FORCE_ID IS NOT NULL AND V_FLOW_ID IS NULL THEN SELECT FLOW_ID INTO V_FLOW_ID FROM (SELECT FLOW_ID FROM WF_FLOW_DEF WHERE PAGE_CODE=P_PAGE_CODE AND IS_ENABLED=1 ORDER BY FLOW_PRIORITY,FLOW_ID) WHERE ROWNUM=1; V_NEED:='Y'; END IF;
    IF V_EXISTS=0 THEN O_APPROVAL_ID:=SEQ_WF_APPROVAL_MAIN.NEXTVAL; END IF;
    IF V_FLOW_ID IS NULL THEN
      IF V_EXISTS=0 THEN INSERT INTO WF_APPROVAL_MAIN(APPROVAL_ID,FLOW_ID,PAGE_CODE,PAGE_NAME,TABLE_CODE,BILL_ID,BILL_NO,BILL_TITLE,START_USER_ID,START_USERNAME,START_REAL_NAME,START_DEPT_ID,START_DEPT_NAME,START_TIME,STATUS,CURRENT_LEVEL,CURRENT_ROUND,APPROVED_TIME,FINISHED_TIME,CONDITION_JSON,CREATE_BY,CREATE_TIME) VALUES(O_APPROVAL_ID,(SELECT FLOW_ID FROM (SELECT FLOW_ID FROM WF_FLOW_DEF WHERE PAGE_CODE=P_PAGE_CODE ORDER BY FLOW_ID) WHERE ROWNUM=1),P_PAGE_CODE,P_PAGE_NAME,P_TABLE_CODE,P_BILL_ID,P_BILL_NO,P_BILL_TITLE,P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,V_DEPT_ID,V_DEPT_NAME,SYSTIMESTAMP,'APPROVED',NULL,V_ROUND_NO,SYSTIMESTAMP,SYSTIMESTAMP,P_CONDITION_JSON,V_USERNAME,SYSTIMESTAMP);
      ELSE UPDATE WF_APPROVAL_MAIN SET STATUS='APPROVED',CURRENT_LEVEL=NULL,CURRENT_ROUND=V_ROUND_NO,APPROVED_TIME=SYSTIMESTAMP,FINISHED_TIME=SYSTIMESTAMP,UPDATE_BY=V_USERNAME,UPDATE_TIME=SYSTIMESTAMP WHERE APPROVAL_ID=O_APPROVAL_ID; END IF;
      ADD_LOG(O_APPROVAL_ID,V_ROUND_NO,NULL,'AUTO_APPROVE',P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,V_EXIST_STATUS,'APPROVED',UNISTR('\603B\5165\53E3\6761\4EF6\4E0D\6EE1\8DB3\FF0C\81EA\52A8\901A\8FC7'),NULL); UPDATE_BIZ_APPROVAL_STATUS(P_TABLE_CODE,P_BILL_ID,O_APPROVAL_ID,'APPROVED',V_USERNAME); O_STATUS:='SUCCESS'; O_MSG:=UNISTR('\81EA\52A8\901A\8FC7'); RETURN;
    END IF;
    IF V_EXISTS=0 THEN INSERT INTO WF_APPROVAL_MAIN(APPROVAL_ID,FLOW_ID,PAGE_CODE,PAGE_NAME,TABLE_CODE,BILL_ID,BILL_NO,BILL_TITLE,START_USER_ID,START_USERNAME,START_REAL_NAME,START_DEPT_ID,START_DEPT_NAME,START_TIME,STATUS,CURRENT_LEVEL,CURRENT_ROUND,CONDITION_JSON,CREATE_BY,CREATE_TIME) VALUES(O_APPROVAL_ID,V_FLOW_ID,P_PAGE_CODE,P_PAGE_NAME,P_TABLE_CODE,P_BILL_ID,P_BILL_NO,P_BILL_TITLE,P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,V_DEPT_ID,V_DEPT_NAME,SYSTIMESTAMP,'APPROVING',NULL,V_ROUND_NO,P_CONDITION_JSON,V_USERNAME,SYSTIMESTAMP);
    ELSE UPDATE WF_APPROVAL_MAIN SET FLOW_ID=V_FLOW_ID,PAGE_NAME=P_PAGE_NAME,BILL_NO=P_BILL_NO,BILL_TITLE=P_BILL_TITLE,START_USER_ID=P_CURRENT_USER_ID,START_USERNAME=V_USERNAME,START_REAL_NAME=V_REAL_NAME,START_DEPT_ID=V_DEPT_ID,START_DEPT_NAME=V_DEPT_NAME,START_TIME=SYSTIMESTAMP,STATUS='APPROVING',CURRENT_LEVEL=NULL,CURRENT_ROUND=V_ROUND_NO,APPROVED_TIME=NULL,REJECTED_TIME=NULL,CANCELED_TIME=NULL,FINISHED_TIME=NULL,CONDITION_JSON=P_CONDITION_JSON,UPDATE_BY=V_USERNAME,UPDATE_TIME=SYSTIMESTAMP WHERE APPROVAL_ID=O_APPROVAL_ID; END IF;
    ADD_LOG(O_APPROVAL_ID,V_ROUND_NO,NULL,'APPLY',P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,V_EXIST_STATUS,'APPROVING',UNISTR('\53D1\8D77\5BA1\6279'),UNISTR('\8F6E\6B21=')||V_ROUND_NO||UNISTR('\FF0C\5355\636E=')||P_BILL_ID);
    IF V_FORCE_ID IS NOT NULL THEN GET_USER_INFO(V_FORCE_ID,V_FORCE_USERNAME,V_FORCE_REAL,V_FORCE_DEPT,V_FORCE_DEPT_NAME); INSERT INTO WF_APPROVAL_DETAIL(DETAIL_ID,APPROVAL_ID,ROUND_NO,NODE_ID,APPROVAL_LEVEL,NODE_NAME,APPROVAL_MODE,TARGET_TYPE,TARGET_USER_ID,TARGET_USER_NAME,STATUS,IS_FORCED,CREATE_TIME) VALUES(SEQ_WF_APPROVAL_DETAIL.NEXTVAL,O_APPROVAL_ID,V_ROUND_NO,(SELECT NODE_ID FROM (SELECT NODE_ID FROM WF_FLOW_NODE WHERE FLOW_ID=V_FLOW_ID ORDER BY APPROVAL_LEVEL,NODE_ID) WHERE ROWNUM=1),1,UNISTR('\5F3A\5236\6307\5B9A\5BA1\6279'),'OR','USER',V_FORCE_ID,NVL(V_FORCE_NAME,V_FORCE_REAL),'PENDING',1,SYSTIMESTAMP); UPDATE WF_APPROVAL_MAIN SET CURRENT_LEVEL=1 WHERE APPROVAL_ID=O_APPROVAL_ID;
    ELSE START_NEXT_LEVEL(O_APPROVAL_ID,V_ROUND_NO,V_FLOW_ID,0,V_DEPT_ID,P_TABLE_CODE,P_BILL_ID,P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,P_PAGE_CODE); END IF;
    SELECT STATUS INTO V_AFTER_STATUS FROM WF_APPROVAL_MAIN WHERE APPROVAL_ID=O_APPROVAL_ID;
    IF V_AFTER_STATUS='APPROVING' THEN UPDATE_BIZ_APPROVAL_STATUS(P_TABLE_CODE,P_BILL_ID,O_APPROVAL_ID,'APPROVING',V_USERNAME); END IF;
    O_STATUS:='SUCCESS'; O_MSG:=CASE WHEN V_AFTER_STATUS='APPROVING' THEN UNISTR('\5BA1\6279\5DF2\53D1\8D77') ELSE UNISTR('\5BA1\6279\5DF2\5904\7406\5B8C\6210') END;
  EXCEPTION WHEN OTHERS THEN O_STATUS:='FAIL'; O_MSG:=SQLERRM; RAISE;
  END;

  PROCEDURE APPROVE_DETAIL(P_DETAIL_ID IN NUMBER,P_CURRENT_USER_ID IN NUMBER,P_COMMENT IN VARCHAR2,O_STATUS OUT VARCHAR2,O_MSG OUT VARCHAR2) AS
    V_APPROVAL_ID NUMBER; V_MAIN_STATUS VARCHAR2(30); V_CURRENT_LEVEL NUMBER; V_ROUND NUMBER; V_DETAIL_ROUND NUMBER; V_STATUS VARCHAR2(30); V_LEVEL NUMBER; V_MODE VARCHAR2(20); V_TARGET_TYPE VARCHAR2(20); V_TARGET_USER_ID NUMBER; V_TARGET_ROLE_ID NUMBER; V_TABLE_CODE VARCHAR2(64); V_BILL_ID NUMBER; V_FLOW_ID NUMBER; V_IS_FORCED NUMBER; V_USERNAME VARCHAR2(64); V_REAL_NAME VARCHAR2(128); V_DEPT_ID NUMBER; V_DEPT_NAME VARCHAR2(128); V_PENDING NUMBER;
  BEGIN
    O_STATUS:='FAIL'; GET_USER_INFO(P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,V_DEPT_ID,V_DEPT_NAME);
    SELECT M.APPROVAL_ID,M.STATUS,M.CURRENT_LEVEL,M.CURRENT_ROUND,M.TABLE_CODE,M.BILL_ID,M.FLOW_ID,D.ROUND_NO,D.STATUS,D.APPROVAL_LEVEL,D.APPROVAL_MODE,D.TARGET_TYPE,D.TARGET_USER_ID,D.TARGET_ROLE_ID,NVL(D.IS_FORCED,0) INTO V_APPROVAL_ID,V_MAIN_STATUS,V_CURRENT_LEVEL,V_ROUND,V_TABLE_CODE,V_BILL_ID,V_FLOW_ID,V_DETAIL_ROUND,V_STATUS,V_LEVEL,V_MODE,V_TARGET_TYPE,V_TARGET_USER_ID,V_TARGET_ROLE_ID,V_IS_FORCED FROM WF_APPROVAL_DETAIL D JOIN WF_APPROVAL_MAIN M ON M.APPROVAL_ID=D.APPROVAL_ID WHERE D.DETAIL_ID=P_DETAIL_ID FOR UPDATE;
    IF V_MAIN_STATUS<>'APPROVING' OR V_DETAIL_ROUND<>V_ROUND OR V_STATUS<>'PENDING' OR V_CURRENT_LEVEL<>V_LEVEL THEN RAISE_APPLICATION_ERROR(-20940,'invalid approval task'); END IF;
    CHECK_DETAIL_AUTH(V_TARGET_TYPE,V_TARGET_USER_ID,V_TARGET_ROLE_ID,P_CURRENT_USER_ID);
    UPDATE WF_APPROVAL_DETAIL SET STATUS='APPROVED',OPERATE_USER_ID=P_CURRENT_USER_ID,OPERATE_USERNAME=V_USERNAME,OPERATE_REAL_NAME=V_REAL_NAME,APPROVE_COMMENT=P_COMMENT,APPROVE_TIME=SYSTIMESTAMP,OPERATE_TIME=SYSTIMESTAMP,UPDATE_BY=V_USERNAME,UPDATE_TIME=SYSTIMESTAMP WHERE DETAIL_ID=P_DETAIL_ID;
    ADD_LOG(V_APPROVAL_ID,V_ROUND,P_DETAIL_ID,'APPROVE',P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,'PENDING','APPROVED',P_COMMENT,UNISTR('\5BA1\6279\540C\610F'));
    IF V_MODE='OR' THEN UPDATE WF_APPROVAL_DETAIL SET STATUS='SKIPPED',OPERATE_TIME=SYSTIMESTAMP,UPDATE_BY=V_USERNAME,UPDATE_TIME=SYSTIMESTAMP WHERE APPROVAL_ID=V_APPROVAL_ID AND ROUND_NO=V_ROUND AND APPROVAL_LEVEL=V_LEVEL AND STATUS='PENDING' AND DETAIL_ID<>P_DETAIL_ID;
    ELSE SELECT COUNT(1) INTO V_PENDING FROM WF_APPROVAL_DETAIL WHERE APPROVAL_ID=V_APPROVAL_ID AND ROUND_NO=V_ROUND AND APPROVAL_LEVEL=V_LEVEL AND STATUS='PENDING'; IF V_PENDING>0 THEN O_STATUS:='SUCCESS'; O_MSG:=UNISTR('\7B49\5F85\540C\7EA7\5176\4ED6\5BA1\6279\4EBA'); RETURN; END IF; END IF;
    IF V_IS_FORCED=1 THEN FINISH_APPROVAL(V_APPROVAL_ID,V_ROUND,V_TABLE_CODE,V_BILL_ID,P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME); ELSE START_NEXT_LEVEL(V_APPROVAL_ID,V_ROUND,V_FLOW_ID,V_LEVEL,V_DEPT_ID,V_TABLE_CODE,V_BILL_ID,P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,'demand-application'); END IF;
    O_STATUS:='SUCCESS'; O_MSG:=UNISTR('\5BA1\6279\6210\529F');
  EXCEPTION WHEN OTHERS THEN O_STATUS:='FAIL'; O_MSG:=SQLERRM; RAISE;
  END;

  PROCEDURE REJECT_DETAIL(P_DETAIL_ID IN NUMBER,P_CURRENT_USER_ID IN NUMBER,P_COMMENT IN VARCHAR2,O_STATUS OUT VARCHAR2,O_MSG OUT VARCHAR2) AS
    V_APPROVAL_ID NUMBER; V_MAIN_STATUS VARCHAR2(30); V_ROUND NUMBER; V_DETAIL_ROUND NUMBER; V_STATUS VARCHAR2(30); V_LEVEL NUMBER; V_TARGET_TYPE VARCHAR2(20); V_TARGET_USER_ID NUMBER; V_TARGET_ROLE_ID NUMBER; V_TABLE_CODE VARCHAR2(64); V_BILL_ID NUMBER; V_USERNAME VARCHAR2(64); V_REAL_NAME VARCHAR2(128); V_DEPT_ID NUMBER; V_DEPT_NAME VARCHAR2(128);
  BEGIN
    O_STATUS:='FAIL'; GET_USER_INFO(P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,V_DEPT_ID,V_DEPT_NAME);
    SELECT M.APPROVAL_ID,M.STATUS,M.CURRENT_ROUND,M.TABLE_CODE,M.BILL_ID,D.ROUND_NO,D.STATUS,D.APPROVAL_LEVEL,D.TARGET_TYPE,D.TARGET_USER_ID,D.TARGET_ROLE_ID INTO V_APPROVAL_ID,V_MAIN_STATUS,V_ROUND,V_TABLE_CODE,V_BILL_ID,V_DETAIL_ROUND,V_STATUS,V_LEVEL,V_TARGET_TYPE,V_TARGET_USER_ID,V_TARGET_ROLE_ID FROM WF_APPROVAL_DETAIL D JOIN WF_APPROVAL_MAIN M ON M.APPROVAL_ID=D.APPROVAL_ID WHERE D.DETAIL_ID=P_DETAIL_ID FOR UPDATE;
    IF V_MAIN_STATUS<>'APPROVING' OR V_DETAIL_ROUND<>V_ROUND OR V_STATUS<>'PENDING' THEN RAISE_APPLICATION_ERROR(-20950,'invalid reject task'); END IF;
    CHECK_DETAIL_AUTH(V_TARGET_TYPE,V_TARGET_USER_ID,V_TARGET_ROLE_ID,P_CURRENT_USER_ID);
    UPDATE WF_APPROVAL_DETAIL SET STATUS='REJECTED',OPERATE_USER_ID=P_CURRENT_USER_ID,OPERATE_USERNAME=V_USERNAME,OPERATE_REAL_NAME=V_REAL_NAME,APPROVE_COMMENT=P_COMMENT,OPERATE_TIME=SYSTIMESTAMP,UPDATE_BY=V_USERNAME,UPDATE_TIME=SYSTIMESTAMP WHERE DETAIL_ID=P_DETAIL_ID;
    UPDATE WF_APPROVAL_DETAIL SET STATUS='CANCELED',OPERATE_TIME=SYSTIMESTAMP,UPDATE_BY=V_USERNAME,UPDATE_TIME=SYSTIMESTAMP WHERE APPROVAL_ID=V_APPROVAL_ID AND ROUND_NO=V_ROUND AND DETAIL_ID<>P_DETAIL_ID AND STATUS IN ('WAITING','PENDING');
    UPDATE WF_APPROVAL_MAIN SET STATUS='REJECTED',CURRENT_LEVEL=NULL,REJECTED_TIME=SYSTIMESTAMP,FINISHED_TIME=SYSTIMESTAMP,UPDATE_BY=V_USERNAME,UPDATE_TIME=SYSTIMESTAMP WHERE APPROVAL_ID=V_APPROVAL_ID;
    UPDATE_BIZ_APPROVAL_STATUS(V_TABLE_CODE,V_BILL_ID,V_APPROVAL_ID,'REJECTED',V_USERNAME);
    ADD_LOG(V_APPROVAL_ID,V_ROUND,P_DETAIL_ID,'REJECT',P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,'PENDING','REJECTED',P_COMMENT,UNISTR('\5BA1\6279\9A73\56DE'));
    O_STATUS:='SUCCESS'; O_MSG:=UNISTR('\5BA1\6279\5DF2\9A73\56DE');
  EXCEPTION WHEN OTHERS THEN O_STATUS:='FAIL'; O_MSG:=SQLERRM; RAISE;
  END;

  PROCEDURE CANCEL_APPROVAL(P_APPROVAL_ID IN NUMBER,P_CURRENT_USER_ID IN NUMBER,P_COMMENT IN VARCHAR2,O_STATUS OUT VARCHAR2,O_MSG OUT VARCHAR2) AS
    V_STATUS VARCHAR2(30); V_START_USER_ID NUMBER; V_TABLE_CODE VARCHAR2(64); V_BILL_ID NUMBER; V_ROUND NUMBER; V_HANDLED NUMBER; V_USERNAME VARCHAR2(64); V_REAL_NAME VARCHAR2(128); V_DEPT_ID NUMBER; V_DEPT_NAME VARCHAR2(128);
  BEGIN
    O_STATUS:='FAIL'; GET_USER_INFO(P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,V_DEPT_ID,V_DEPT_NAME);
    SELECT STATUS,START_USER_ID,TABLE_CODE,BILL_ID,CURRENT_ROUND INTO V_STATUS,V_START_USER_ID,V_TABLE_CODE,V_BILL_ID,V_ROUND FROM WF_APPROVAL_MAIN WHERE APPROVAL_ID=P_APPROVAL_ID FOR UPDATE;
    IF V_START_USER_ID<>P_CURRENT_USER_ID THEN RAISE_APPLICATION_ERROR(-20960,'only submitter can cancel'); END IF;
    IF V_STATUS IN ('APPROVED','CANCELED') THEN RAISE_APPLICATION_ERROR(-20961,'cannot cancel'); END IF;
    IF V_STATUS='APPROVING' THEN SELECT COUNT(1) INTO V_HANDLED FROM WF_APPROVAL_DETAIL WHERE APPROVAL_ID=P_APPROVAL_ID AND ROUND_NO=V_ROUND AND STATUS IN ('APPROVED','REJECTED'); IF V_HANDLED>0 THEN RAISE_APPLICATION_ERROR(-20962,'handled cannot cancel before reject'); END IF;
    ELSIF V_STATUS<>'REJECTED' THEN RAISE_APPLICATION_ERROR(-20963,'only rejected or unhandled approving can cancel'); END IF;
    UPDATE WF_APPROVAL_DETAIL SET STATUS='CANCELED',OPERATE_TIME=SYSTIMESTAMP,UPDATE_BY=V_USERNAME,UPDATE_TIME=SYSTIMESTAMP WHERE APPROVAL_ID=P_APPROVAL_ID AND ROUND_NO=V_ROUND AND STATUS IN ('WAITING','PENDING');
    UPDATE WF_APPROVAL_MAIN SET STATUS='CANCELED',CURRENT_LEVEL=NULL,CANCELED_TIME=SYSTIMESTAMP,FINISHED_TIME=SYSTIMESTAMP,UPDATE_BY=V_USERNAME,UPDATE_TIME=SYSTIMESTAMP WHERE APPROVAL_ID=P_APPROVAL_ID;
    UPDATE_BIZ_APPROVAL_STATUS(V_TABLE_CODE,V_BILL_ID,P_APPROVAL_ID,'CANCELED',V_USERNAME);
    ADD_LOG(P_APPROVAL_ID,V_ROUND,NULL,'CANCEL',P_CURRENT_USER_ID,V_USERNAME,V_REAL_NAME,V_STATUS,'CANCELED',P_COMMENT,UNISTR('\5BA1\6279\5DF2\64A4\9500'));
    O_STATUS:='SUCCESS'; O_MSG:=UNISTR('\5BA1\6279\5DF2\64A4\9500');
  EXCEPTION WHEN OTHERS THEN O_STATUS:='FAIL'; O_MSG:=SQLERRM; RAISE;
  END;
END PKG_WF_APPROVAL;

