prompt Importing table t_cost_page_component...
set feedback off
set define off

insert into t_cost_page_component (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (175, 'wms-shipping', 'detailTabs', 'TABS', 'root', '{"mode":"multi","tabs":[{"key":"wmsQty","title":"库存汇总","tableCode":"WmsQty","buttons":[{"action":"batchSelect","label":"从库存添加","batchSelectConfig":{"lookupCode":"wmsQtyLookup","title":"选择库存","mapping":{"goodsid":"goodsid","goodsgp":"goodsgp","lotno":"lotno","goodsno":"goodsno","packsize":"packsize","qtyShow":"qty_show","pcs":"pcs"}}},{"action":"deleteRow","label":"删除","requiresRow":true},{"type":"separator"},{"action":"save","label":"保存"},{"type":"separator"},{"action":"clipboard.copy"},{"action":"clipboard.paste"}]},{"key":"wmsQtyDetail","title":"库存明细","tableCode":"WmsQtyDetail","buttons":[{"action":"addRow","label":"新增"},{"action":"deleteRow","label":"删除","requiresRow":true},{"type":"separator"},{"action":"save","label":"保存"},{"type":"separator"},{"action":"clipboard.copy"},{"action":"clipboard.paste"}]}]}', null, null, 2, 0, null, '05-FEB-26 05.40.28.749000 PM', '05-FEB-26 05.57.19.330000 PM', 'system', 'system');

insert into t_cost_page_component (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (85, 'customer-manage', 'detailTabs', 'TABS', 'root', '{"mode":"single","tabs":[{"key":"tranposer","title":"分销商","tableCode":"CostTranposer","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"label":"导出","items":[{"action":"exportSelected","label":"导出选中","requiresSelection":true},{"action":"exportCurrent","label":"导出当前页"},{"action":"exportAll","label":"导出全部"},{"action":"resetExportConfig","label":"重置导出配置"},{"action":"openHeaderConfig","label":"配置导出表头"}]},{"action":"save","label":"保存"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}]}', null, null, 2, 0, null, '26-JAN-26 05.41.09.973000 PM', '26-JAN-26 05.41.09.973000 PM', 'system', null);

insert into t_cost_page_component (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (115, 'cost-pinggu', 'detailTabs', 'TABS', 'root', '{"mode":"multi","tabs":[{"key":"material","title":"原料/辅料","tableCode":"CostMaterial","buttons":[{"action":"addRow","label":"明细新增","position":"both","toolbarAlias":"新增原料"},{"action":"copyRow","label":"明细复制","requiresRow":true,"position":"context"},{"action":"deleteRow","label":"明细删除","requiresRow":true,"position":"both","toolbarAlias":"删除原料"},{"action":"saveGridConfig","label":"保存列配置","position":"context"},{"action":"clipboard.copy","label":"复制","position":"context"},{"action":"clipboard.paste","label":"粘贴","position":"context"}]},{"key":"package","title":"包材","tableCode":"CostPackage","buttons":[{"action":"addRow","label":"明细新增","position":"both","toolbarAlias":"新增包材"},{"action":"copyRow","label":"明细复制","requiresRow":true,"position":"context"},{"action":"deleteRow","label":"明细删除","requiresRow":true,"position":"both","toolbarAlias":"删除包材"},{"action":"saveGridConfig","label":"保存列配置","position":"context"},{"action":"clipboard.copy","label":"复制","position":"context"},{"action":"clipboard.paste","label":"粘贴","position":"context"}]}]}', null, null, 2, 0, null, '28-JAN-26 05.27.15.835000 PM', '09-FEB-26 03.35.12.191000 PM', 'system', null);

insert into t_cost_page_component (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (178, 'cost-pinggu-lq', 'detailTabs', 'TABS', 'root', '{"mode":"multi","tabs":[{"key":"material","title":"原料/辅料","tableCode":"CostMaterialLq","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]},{"key":"package","title":"包材","tableCode":"CostPackageLq","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}]}', null, null, 2, 0, null, '06-FEB-26 02.29.07.090000 PM', '06-FEB-26 02.29.07.090000 PM', 'system', null);

prompt Done.
