prompt Importing table t_cost_page_rule...
set feedback off
set define off

insert into t_cost_page_rule (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (480, 'cost-pinggu', 'material', 'CALC', '[{"field":"batchQty","formulaField":"apexGoodsname","formulas":{"__branch_0":{"key":"胶囊","expression":"apexPl / 10000* (1 + exaddMater / 100) ","triggerFields":["apexPl","exaddMater"],"matchType":"regex"},"__branch_1":{"key":"^(?!.*胶囊).*$","expression":" apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["apexPl","exaddMater"],"matchType":"regex"}}},{"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]}]', 0, null, 0, '28-JAN-26 05.27.11.569000 PM', '10-FEB-26 05.45.39.472000 PM', 'system', null);

insert into t_cost_page_rule (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (484, 'cost-pinggu', 'package', 'CALC', '[{"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]},{"field":"batchQty","formulaField":"apexGoodsname","formulas":{"__branch_0":{"key":"桶|说明书|小盒|标签|瓶|盖","expression":"apexPl / pPerpack * (1 + exaddMater/100)","triggerFields":["apexPl","pPerpack","exaddMater"],"matchType":"regex"},"__branch_1":{"key":"硬片|铝箔|复合膜","expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"],"matchType":"regex"},"__branch_2":{"key":"大纸箱","expression":"ceil(apexPl / (pPerpack * sPerback)* (1 + exaddMater/100))","triggerFields":["apexPl","pPerpack","sPerback","exaddMater"],"matchType":"regex"},"__branch_3":{"key":"托盘","expression":"ceil(apexPl / (pPerpack * sPerback * xPerback)* (1 + exaddMater/100))","triggerFields":["apexPl","pPerpack","sPerback","xPerback","exaddMater"],"matchType":"regex"},"__branch_4":{"key":"中盒","expression":"ceil(apexPl / (mPerpack * sPerback)* (1 + exaddMater/100))","triggerFields":["apexPl","mPerpack","sPerback","exaddMater"],"matchType":"regex"}}}]', 0, null, 0, '28-JAN-26 05.27.12.059000 PM', '10-FEB-26 05.45.39.472000 PM', 'system', null);

insert into t_cost_page_rule (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (604, 'cost-pinggu-lq', 'masterGrid', 'CALC', '[{"field":"salemoney","expression":"outPriceRmb /  apexPl * (yield / 100)","triggerFields":["outPriceRmb","apexPl","yield"]},{"field":"jgfBatch","expression":"salemoney - totalCost","triggerFields":["salemoney","totalCost"]},{"field":"costPerbox","expression":"totalCost / apexPl ","triggerFields":["totalCost","apexPl"]},{"field":"jgfPerqp","expression":"jgfBatch / apexPl * 1000","triggerFields":["jgfBatch","apexPl"]},{"field":"mlPerqp","expression":"jgfPerqp - costPerqp","triggerFields":["jgfPerqp","costPerqp"]},{"field":"yJgRe","expression":"jgfPerqp / annualQty","triggerFields":["jgfPerqp","annualQty"]},{"field":"yMl","expression":"mlPerqp / annualQty","triggerFields":["mlPerqp","annualQty"]},{"field":"ySale","expression":"annualQty*outPriceRmb*yield","triggerFields":["annualQty","outPriceRmb","yield"]}]', 0, null, 0, '06-FEB-26 02.29.08.214000 PM', '10-FEB-26 05.45.39.472000 PM', 'system', null);

insert into t_cost_page_rule (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (616, 'cost-pinggu-lq', 'material', 'CALC', '[{"field":"batchQty","expression":"perHl *  (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","exaddMater"]},{"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]}]', 0, null, 0, '06-FEB-26 02.29.09.118000 PM', '10-FEB-26 05.45.39.472000 PM', 'system', null);

insert into t_cost_page_rule (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (620, 'cost-pinggu-lq', 'package', 'CALC', '[{"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]},{"field":"batchQty","formulaField":"apexGoodsname","formulas":{"__branch_0":{"key":"桶|说明书|小盒|标签|瓶|盖注射器|适配器|量杯|勺|分度器","expression":"apexPl / pPerpack * (1 + exaddMater/100)","triggerFields":["apexPl","pPerpack","exaddMater"],"matchType":"regex"},"__branch_1":{"key":"大纸箱","expression":"ceil(apexPl / (pPerpack * sPerback)* (1 + exaddMater/100))","triggerFields":["apexPl","pPerpack","sPerback","exaddMater"],"matchType":"regex"},"__branch_2":{"key":"托盘","expression":"ceil(apexPl / (pPerpack * sPerback * xPerback)* (1 + exaddMater/100))","triggerFields":["apexPl","pPerpack","sPerback","xPerback","exaddMater"],"matchType":"regex"}}}]', 0, null, 0, '06-FEB-26 02.29.09.753000 PM', '10-FEB-26 05.45.39.472000 PM', 'system', null);

insert into t_cost_page_rule (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (475, 'cost-pinggu', 'masterGrid', 'CALC', '[{"field":"salemoney","expression":"outPriceRmb / pPerpack * apexPl * (yield / 100)","triggerFields":["outPriceRmb","pPerpack","apexPl","yield"]},{"field":"jgfBatch","expression":"salemoney - totalCost","triggerFields":["salemoney","totalCost"]},{"field":"costPerbox","expression":"totalCost / apexPl * pPerpack","triggerFields":["totalCost","apexPl","pPerpack"]},{"field":"jgfPerqp","expression":"jgfBatch / apexPl * 1000","triggerFields":["jgfBatch","apexPl"]},{"field":"mlPerqp","expression":"jgfPerqp - costPerqp","triggerFields":["jgfPerqp","costPerqp"]},{"field":"yJgRe","expression":"jgfPerqp / 1000 * annualQty","triggerFields":["jgfPerqp","annualQty"]},{"field":"yMl","expression":"mlPerqp / 1000 * annualQty","triggerFields":["mlPerqp","annualQty"]},{"field":"ySale","expression":"annualQty/pPerpack*outPriceRmb*yield","triggerFields":["annualQty","pPerpack","outPriceRmb","yield"]}]', 0, null, 0, '28-JAN-26 05.27.10.872000 PM', '10-FEB-26 05.45.39.472000 PM', 'system', null);

prompt Done.
