-- ============================================================
-- 步骤 1：备份所有元数据表（以 20260519 结尾）
-- 执行时间：迁移前第一步
-- 回滚：DROP 新表 → RENAME 备份表回来
-- ============================================================

CREATE TABLE T_COST_TABLE_METADATA_20260519 AS SELECT * FROM T_COST_TABLE_METADATA;
CREATE TABLE T_COST_COLUMN_METADATA_20260519 AS SELECT * FROM T_COST_COLUMN_METADATA;
CREATE TABLE T_COST_PAGE_COMPONENT_20260519 AS SELECT * FROM T_COST_PAGE_COMPONENT;
CREATE TABLE T_COST_PAGE_RULE_20260519 AS SELECT * FROM T_COST_PAGE_RULE;
CREATE TABLE T_COST_RESOURCE_20260519 AS SELECT * FROM T_COST_RESOURCE;
CREATE TABLE T_COST_ROLE_PAGE_20260519 AS SELECT * FROM T_COST_ROLE_PAGE;

-- 验证备份行数
SELECT 'T_COST_TABLE_METADATA' AS TBL, COUNT(*) AS CNT FROM T_COST_TABLE_METADATA_20260519
UNION ALL
SELECT 'T_COST_COLUMN_METADATA', COUNT(*) FROM T_COST_COLUMN_METADATA_20260519
UNION ALL
SELECT 'T_COST_PAGE_COMPONENT', COUNT(*) FROM T_COST_PAGE_COMPONENT_20260519
UNION ALL
SELECT 'T_COST_PAGE_RULE', COUNT(*) FROM T_COST_PAGE_RULE_20260519
UNION ALL
SELECT 'T_COST_RESOURCE', COUNT(*) FROM T_COST_RESOURCE_20260519
UNION ALL
SELECT 'T_COST_ROLE_PAGE', COUNT(*) FROM T_COST_ROLE_PAGE_20260519;
