-- =====================================================
-- 成本管理系统数据库脚本（整合版）
-- 分类：基础结构 / 初始化数�?/ 元数据与页面配置 / 修复补丁
-- 用途：一次执行完成所有建表、初始化与配置，便于维护
-- =====================================================

-- =====================================================
-- A. 基础表结�?
-- =====================================================

-- A1. 元数据模块表结构

CREATE TABLE T_COST_TABLE_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_CODE          VARCHAR2(64)    NOT NULL UNIQUE,
    TABLE_NAME          VARCHAR2(128)   NOT NULL,
    QUERY_VIEW          VARCHAR2(64),
    TARGET_TABLE        VARCHAR2(64)    NOT NULL,
    SEQUENCE_NAME       VARCHAR2(64),
    PK_COLUMN           VARCHAR2(64)    DEFAULT 'ID',
    PARENT_TABLE_CODE   VARCHAR2(64),
    PARENT_FK_COLUMN    VARCHAR2(64),
    AUDIT_ENABLED       NUMBER(1)       DEFAULT 0,
    VALIDATION_RULES    CLOB,
    DESCRIPTION         VARCHAR2(500),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_TABLE_METADATA START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_COLUMN_METADATA (
    ID                  NUMBER(19)      PRIMARY KEY,
    TABLE_METADATA_ID   NUMBER(19)      NOT NULL,
    FIELD_NAME          VARCHAR2(64)    NOT NULL,
    COLUMN_NAME         VARCHAR2(64)    NOT NULL,
    QUERY_COLUMN        VARCHAR2(128),
    TARGET_COLUMN       VARCHAR2(64),
    HEADER_TEXT         VARCHAR2(128)   NOT NULL,
    DATA_TYPE           VARCHAR2(32)    DEFAULT 'text',
    DISPLAY_ORDER       NUMBER(5)       DEFAULT 0,
    WIDTH               NUMBER(5)       DEFAULT 120,
    VISIBLE             NUMBER(1)       DEFAULT 1,
    EDITABLE            NUMBER(1)       DEFAULT 1,
    REQUIRED            NUMBER(1)       DEFAULT 0,
    SEARCHABLE          NUMBER(1)       DEFAULT 0,
    SORTABLE            NUMBER(1)       DEFAULT 1,
    FILTERABLE          NUMBER(1)       DEFAULT 1,
    IS_VIRTUAL          NUMBER(1)       DEFAULT 0,
    DICT_TYPE           VARCHAR2(64),
    LOOKUP_CONFIG_ID    NUMBER(19),
    DEFAULT_VALUE       VARCHAR2(256),
    RULES_CONFIG        CLOB,
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_COLUMN_TABLE FOREIGN KEY (TABLE_METADATA_ID) REFERENCES T_COST_TABLE_METADATA(ID)
);
CREATE SEQUENCE SEQ_COST_COLUMN_METADATA START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_COLUMN_TABLE_ID ON T_COST_COLUMN_METADATA(TABLE_METADATA_ID);

CREATE TABLE T_COST_LOOKUP_CONFIG (
    ID                  NUMBER(19)      PRIMARY KEY,
    LOOKUP_CODE         VARCHAR2(64)    NOT NULL UNIQUE,
    LOOKUP_NAME         VARCHAR2(128)   NOT NULL,
    DATA_SOURCE         VARCHAR2(200)   NOT NULL,
    DISPLAY_COLUMNS     CLOB,
    SEARCH_COLUMNS      CLOB,
    VALUE_FIELD         VARCHAR2(64)    NOT NULL,
    LABEL_FIELD         VARCHAR2(64)    NOT NULL,
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_LOOKUP_CONFIG START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_PAGE_COMPONENT (
    ID                  NUMBER(19)      PRIMARY KEY,
    PAGE_CODE           VARCHAR2(64)    NOT NULL,
    COMPONENT_KEY       VARCHAR2(64)    NOT NULL,
    COMPONENT_TYPE      VARCHAR2(32)    NOT NULL,
    PARENT_KEY          VARCHAR2(64),
    COMPONENT_CONFIG    CLOB,
    REF_TABLE_CODE      VARCHAR2(64),
    SLOT_NAME           VARCHAR2(32),
    SORT_ORDER          NUMBER(5)       DEFAULT 0,
    DELETED             NUMBER(1)       DEFAULT 0,
    DESCRIPTION         VARCHAR2(200),
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_PAGE_COMPONENT START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_PAGE_COMP_PAGE ON T_COST_PAGE_COMPONENT(PAGE_CODE);
CREATE UNIQUE INDEX UK_PAGE_COMP_KEY ON T_COST_PAGE_COMPONENT(PAGE_CODE, COMPONENT_KEY);

CREATE TABLE T_COST_DICTIONARY_TYPE (
    ID                  NUMBER(19)      PRIMARY KEY,
    TYPE_CODE           VARCHAR2(64)    NOT NULL UNIQUE,
    TYPE_NAME           VARCHAR2(128)   NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_DICT_TYPE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_DICTIONARY_ITEM (
    ID                  NUMBER(19)      PRIMARY KEY,
    TYPE_ID             NUMBER(19)      NOT NULL,
    ITEM_CODE           VARCHAR2(64)    NOT NULL,
    ITEM_NAME           VARCHAR2(128)   NOT NULL,
    ITEM_VALUE          VARCHAR2(200),
    SORT_ORDER          NUMBER(5)       DEFAULT 0,
    EXTRA_CONFIG        VARCHAR2(1000),
    DELETED             NUMBER(1)       DEFAULT 0,
    CREATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME         TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY           VARCHAR2(64),
    UPDATE_BY           VARCHAR2(64),
    CONSTRAINT FK_DICT_ITEM_TYPE FOREIGN KEY (TYPE_ID) REFERENCES T_COST_DICTIONARY_TYPE(ID)
);
CREATE SEQUENCE SEQ_COST_DICT_ITEM START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DICT_ITEM_TYPE ON T_COST_DICTIONARY_ITEM(TYPE_ID);

COMMIT;

-- A2. 权限模块表结�?

CREATE TABLE T_COST_DEPARTMENT (
    ID              NUMBER(19) PRIMARY KEY,
    DEPT_CODE       VARCHAR2(64) NOT NULL UNIQUE,
    DEPT_NAME       VARCHAR2(128) NOT NULL,
    PARENT_ID       NUMBER(19),
    SORT_ORDER      NUMBER(5) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_DEPARTMENT START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_USER (
    ID              NUMBER(19) PRIMARY KEY,
    USERNAME        VARCHAR2(64) NOT NULL UNIQUE,
    PASSWORD        VARCHAR2(256) NOT NULL,
    REAL_NAME       VARCHAR2(128),
    EMAIL           VARCHAR2(128),
    PHONE           VARCHAR2(32),
    DEPARTMENT_ID   NUMBER(19),
    STATUS          VARCHAR2(32) DEFAULT 'ACTIVE',
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_ROLE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_CODE       VARCHAR2(64) NOT NULL UNIQUE,
    ROLE_NAME       VARCHAR2(128) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_ROLE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_USER_ROLE (
    ID              NUMBER(19) PRIMARY KEY,
    USER_ID         NUMBER(19) NOT NULL,
    ROLE_ID         NUMBER(19) NOT NULL,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER_ROLE START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_USER_ROLE ON T_COST_USER_ROLE(USER_ID, ROLE_ID);

CREATE TABLE T_COST_ROLE_PAGE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_ID         NUMBER(19) NOT NULL,
    PAGE_CODE       VARCHAR2(64) NOT NULL,
    BUTTON_POLICY   VARCHAR2(1000),
    COLUMN_POLICY   CLOB,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_ROLE_PAGE START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_ROLE_PAGE ON T_COST_ROLE_PAGE(ROLE_ID, PAGE_CODE);

CREATE TABLE T_COST_ROLE_PAGE_DATA_RULE (
    ID              NUMBER(19) PRIMARY KEY,
    ROLE_PAGE_ID    NUMBER(19) NOT NULL,
    RULE_TYPE       VARCHAR2(32) NOT NULL,
    RULE_CONFIG     CLOB NOT NULL,
    PRIORITY        NUMBER(3) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_DATA_RULE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_USER_GRID_CONFIG (
    ID              NUMBER(19) PRIMARY KEY,
    USER_ID         NUMBER(19) NOT NULL,
    PAGE_CODE       VARCHAR2(64) NOT NULL,
    GRID_KEY        VARCHAR2(64) NOT NULL,
    CONFIG_DATA     CLOB,
    DELETED         NUMBER(1) DEFAULT 0,
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_USER_GRID START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX UK_USER_GRID_CONF ON T_COST_USER_GRID_CONFIG(USER_ID, PAGE_CODE, GRID_KEY);

CREATE TABLE T_COST_RESOURCE (
    ID              NUMBER(19) PRIMARY KEY,
    RESOURCE_CODE   VARCHAR2(64) NOT NULL UNIQUE,
    RESOURCE_NAME   VARCHAR2(128) NOT NULL,
    RESOURCE_TYPE   VARCHAR2(20) NOT NULL,
    PAGE_CODE       VARCHAR2(64),
    ICON            VARCHAR2(64),
    ROUTE           VARCHAR2(128),
    PARENT_ID       NUMBER(19),
    SORT_ORDER      NUMBER(5) DEFAULT 0,
    DELETED         NUMBER(1) DEFAULT 0,
    CREATE_BY       VARCHAR2(64),
    CREATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_BY       VARCHAR2(64),
    UPDATE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_RESOURCE START WITH 1 INCREMENT BY 1;

COMMIT;

-- A3. 业务模块表结�?

CREATE TABLE T_COST_EVAL (
    ID              NUMBER(19)      PRIMARY KEY,
    EVAL_NO         VARCHAR2(32)    NOT NULL UNIQUE,
    PRODUCT_NAME    VARCHAR2(128)   NOT NULL,
    APEX_PL         NUMBER(18,4)    DEFAULT 0,
    YIELD           NUMBER(18,4)    DEFAULT 100,
    OUT_PRICE_RMB   NUMBER(18,4)    DEFAULT 0,
    TOTAL_YL        NUMBER(18,2)    DEFAULT 0,
    TOTAL_FL        NUMBER(18,2)    DEFAULT 0,
    TOTAL_PACK      NUMBER(18,2)    DEFAULT 0,
    TOTAL_COST      NUMBER(18,2)    DEFAULT 0,
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_EVAL START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_EVAL_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    EVAL_ID         NUMBER(19)      NOT NULL,
    MATERIAL_NAME   VARCHAR2(128)   NOT NULL,
    USE_FLAG        VARCHAR2(32)    NOT NULL,
    PER_HL          NUMBER(18,6)    DEFAULT 0,
    PRICE           NUMBER(18,4)    DEFAULT 0,
    BATCH_QTY       NUMBER(18,4)    DEFAULT 0,
    COST_BATCH      NUMBER(18,2)    DEFAULT 0,
    PACK_SPEC       VARCHAR2(64),
    PACK_QTY        NUMBER(18,4)    DEFAULT 0,
    PACK_COST       NUMBER(18,2)    DEFAULT 0,
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64),
    CONSTRAINT FK_EVAL_DETAIL FOREIGN KEY (EVAL_ID) REFERENCES T_COST_EVAL(ID)
);
CREATE SEQUENCE SEQ_COST_EVAL_DETAIL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_EVAL_DETAIL_EVAL_ID ON T_COST_EVAL_DETAIL(EVAL_ID);

CREATE TABLE T_COST_ORDER (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_NO        VARCHAR2(32)    NOT NULL UNIQUE,
    ORDER_DATE      DATE            NOT NULL,
    CUSTOMER_NAME   VARCHAR2(128),
    TOTAL_AMOUNT    NUMBER(18,2)    DEFAULT 0,
    TOTAL_FEE       NUMBER(18,2)    DEFAULT 0,
    STATUS          VARCHAR2(32)    DEFAULT 'DRAFT',
    REMARK          VARCHAR2(512),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_ORDER START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_ORDER_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_ID        NUMBER(19)      NOT NULL,
    ITEM_NAME       VARCHAR2(128)   NOT NULL,
    SPEC            VARCHAR2(64),
    UNIT            VARCHAR2(32),
    QUANTITY        NUMBER(18,4)    DEFAULT 0,
    UNIT_PRICE      NUMBER(18,4)    DEFAULT 0,
    AMOUNT          NUMBER(18,2)    DEFAULT 0,
    REMARK          VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64),
    CONSTRAINT FK_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES T_COST_ORDER(ID)
);
CREATE SEQUENCE SEQ_COST_ORDER_DETAIL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DETAIL_ORDER_ID ON T_COST_ORDER_DETAIL(ORDER_ID);

CREATE TABLE T_COST_ORDER_FEE (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_ID        NUMBER(19)      NOT NULL,
    FEE_TYPE        VARCHAR2(32)    NOT NULL,
    FEE_NAME        VARCHAR2(128)   NOT NULL,
    FEE_AMOUNT      NUMBER(18,2)    DEFAULT 0,
    REMARK          VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64),
    CONSTRAINT FK_FEE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES T_COST_ORDER(ID)
);
CREATE SEQUENCE SEQ_COST_ORDER_FEE START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_FEE_ORDER_ID ON T_COST_ORDER_FEE(ORDER_ID);

CREATE TABLE T_COST_CUSTOMER (
    ID              NUMBER(19)      PRIMARY KEY,
    CUSTOMER_CODE   VARCHAR2(32)    NOT NULL UNIQUE,
    CUSTOMER_NAME   VARCHAR2(128)   NOT NULL,
    CONTACT_PERSON  VARCHAR2(64),
    PHONE           VARCHAR2(32),
    ADDRESS         VARCHAR2(256),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_CUSTOMER START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_MATERIAL (
    ID              NUMBER(19)      PRIMARY KEY,
    MATERIAL_CODE   VARCHAR2(32)    NOT NULL UNIQUE,
    MATERIAL_NAME   VARCHAR2(128)   NOT NULL,
    USE_FLAG        VARCHAR2(32)    NOT NULL,
    PER_HL          NUMBER(18,6)    DEFAULT 0,
    PRICE           NUMBER(18,4)    DEFAULT 0,
    UNIT            VARCHAR2(32),
    SPEC            VARCHAR2(64),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_MATERIAL START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_SALES (
    ID              NUMBER(19)      PRIMARY KEY,
    EVAL_ID         NUMBER(19)      NOT NULL,
    EVAL_NO         VARCHAR2(32)    NOT NULL,
    PRODUCT_NAME    VARCHAR2(128)   NOT NULL,
    TOTAL_COST      NUMBER(18,2)    DEFAULT 0,
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_SALES START WITH 1 INCREMENT BY 1;

CREATE TABLE T_COST_DEMO (
    ID              NUMBER(19)      PRIMARY KEY,
    CODE            VARCHAR2(64)    NOT NULL,
    NAME            VARCHAR2(128)   NOT NULL,
    AMOUNT          NUMBER(18,2),
    COST_DATE       DATE,
    STATUS          VARCHAR2(32)    DEFAULT 'DRAFT',
    REMARK          VARCHAR2(512),
    DELETED         NUMBER(1)       DEFAULT 0,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CREATE_BY       VARCHAR2(64),
    UPDATE_BY       VARCHAR2(64)
);
CREATE SEQUENCE SEQ_COST_DEMO START WITH 1 INCREMENT BY 1;

COMMIT;

-- A4. 日志模块表结�?

CREATE TABLE T_COST_OPERATION_LOG (
    ID              NUMBER(19)      PRIMARY KEY,
    USER_ID         NUMBER(19),
    USER_NAME       VARCHAR2(64),
    OPERATION_TYPE  VARCHAR2(32)    NOT NULL,
    TABLE_CODE      VARCHAR2(64),
    RECORD_ID       NUMBER(19),
    RECORD_DESC     VARCHAR2(256),
    TOTAL_SQL_COUNT NUMBER(10)      DEFAULT 0,
    TOTAL_COST_MS   NUMBER(10)      DEFAULT 0,
    STATUS          VARCHAR2(16)    DEFAULT 'SUCCESS',
    ERROR_MSG       VARCHAR2(1000),
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_OPERATION_LOG START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_OPERATION_LOG_USER ON T_COST_OPERATION_LOG(USER_ID);
CREATE INDEX IDX_OPERATION_LOG_TIME ON T_COST_OPERATION_LOG(CREATE_TIME);
CREATE INDEX IDX_OPERATION_LOG_TABLE ON T_COST_OPERATION_LOG(TABLE_CODE);

CREATE TABLE T_COST_OPERATION_LOG_DETAIL (
    ID              NUMBER(19)      PRIMARY KEY,
    LOG_ID          NUMBER(19)      NOT NULL,
    SEQ_NO          NUMBER(5)       NOT NULL,
    SQL_TYPE        VARCHAR2(16),
    SQL_TEXT        CLOB,
    COST_MS         NUMBER(10)      DEFAULT 0,
    AFFECTED_ROWS   NUMBER(10),
    STATUS          VARCHAR2(16)    DEFAULT 'SUCCESS',
    ERROR_MSG       VARCHAR2(1000),
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LOG_DETAIL_LOG FOREIGN KEY (LOG_ID) REFERENCES T_COST_OPERATION_LOG(ID)
);
CREATE SEQUENCE SEQ_COST_OPERATION_LOG_DETAIL START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_LOG_DETAIL_LOG ON T_COST_OPERATION_LOG_DETAIL(LOG_ID);

CREATE TABLE T_COST_AUDIT_LOG (
    ID              NUMBER(19)      PRIMARY KEY,
    USER_NAME       VARCHAR2(100),
    OPERATION_TIME  TIMESTAMP       DEFAULT SYSTIMESTAMP,
    PAGE_CODE       VARCHAR2(100),
    TABLE_CODE      VARCHAR2(100),
    TABLE_NAME      VARCHAR2(200),
    RECORD_ID       NUMBER(19),
    OPERATION_TYPE  VARCHAR2(20),
    FIELD_CHANGES   CLOB,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_COST_AUDIT_LOG START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_AUDIT_LOG_TIME ON T_COST_AUDIT_LOG(OPERATION_TIME);
CREATE INDEX IDX_AUDIT_LOG_USER ON T_COST_AUDIT_LOG(USER_NAME);
CREATE INDEX IDX_AUDIT_LOG_TABLE ON T_COST_AUDIT_LOG(TABLE_CODE);

COMMENT ON TABLE T_COST_AUDIT_LOG IS '业务审计日志（用户可见）';
COMMENT ON COLUMN T_COST_AUDIT_LOG.FIELD_CHANGES IS '字段变更JSON，只记录用户手动修改';

COMMIT;

-- =====================================================
-- B. 初始化基础数据
-- =====================================================

-- B1. 字典初始化数�?
INSERT INTO T_COST_DICTIONARY_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_DICT_TYPE.NEXTVAL, 'COST_STATUS', '成本状�?, '成本单据状�?, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, EXTRA_CONFIG, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'COST_STATUS'), 'DRAFT', '草稿', 'DRAFT', 1, '{"color":"#909399"}', 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, EXTRA_CONFIG, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'COST_STATUS'), 'SUBMITTED', '已提�?, 'SUBMITTED', 2, '{"color":"#E6A23C"}', 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, EXTRA_CONFIG, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'COST_STATUS'), 'APPROVED', '已审�?, 'APPROVED', 3, '{"color":"#67C23A"}', 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, EXTRA_CONFIG, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'COST_STATUS'), 'REJECTED', '已驳�?, 'REJECTED', 4, '{"color":"#F56C6C"}', 'system');

INSERT INTO T_COST_DICTIONARY_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_DICT_TYPE.NEXTVAL, 'FEE_TYPE', '费用类型', '成本单费用类�?, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'FEE_TYPE'), 'TRANSPORT', '运输�?, 'TRANSPORT', 1, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'FEE_TYPE'), 'PACKAGE', '包装�?, 'PACKAGE', 2, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'FEE_TYPE'), 'TAX', '税费', 'TAX', 3, 'system');
INSERT INTO T_COST_DICTIONARY_ITEM (ID, TYPE_ID, ITEM_CODE, ITEM_NAME, ITEM_VALUE, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DICT_ITEM.NEXTVAL, (SELECT ID FROM T_COST_DICTIONARY_TYPE WHERE TYPE_CODE = 'FEE_TYPE'), 'OTHER', '其他', 'OTHER', 4, 'system');

COMMIT;

-- B2. 用户/角色/菜单初始�?
INSERT INTO T_COST_DEPARTMENT (ID, DEPT_CODE, DEPT_NAME, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DEPARTMENT.NEXTVAL, 'ROOT', '总公�?, NULL, 0, 'system');
INSERT INTO T_COST_DEPARTMENT (ID, DEPT_CODE, DEPT_NAME, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DEPARTMENT.NEXTVAL, 'FINANCE', '财务�?, 1, 1, 'system');
INSERT INTO T_COST_DEPARTMENT (ID, DEPT_CODE, DEPT_NAME, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_DEPARTMENT.NEXTVAL, 'PURCHASE', '采购�?, 1, 2, 'system');

INSERT INTO T_COST_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_ROLE.NEXTVAL, 'ADMIN', '系统管理�?, '拥有所有权�?, 'system');
INSERT INTO T_COST_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_ROLE.NEXTVAL, 'FINANCE_MANAGER', '财务经理', '财务部门管理权限', 'system');
INSERT INTO T_COST_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, CREATE_BY)
VALUES (SEQ_COST_ROLE.NEXTVAL, 'FINANCE_STAFF', '财务专员', '财务部门普通权�?, 'system');

-- 默认用户，密�? 123456（BCrypt 已加密）
INSERT INTO T_COST_USER (ID, USERNAME, PASSWORD, REAL_NAME, DEPARTMENT_ID, CREATE_BY)
VALUES (SEQ_COST_USER.NEXTVAL, 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKt6Z5EH', '系统管理�?, 1, 'system');
INSERT INTO T_COST_USER (ID, USERNAME, PASSWORD, REAL_NAME, DEPARTMENT_ID, CREATE_BY)
VALUES (SEQ_COST_USER.NEXTVAL, 'zhangsan', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKt6Z5EH', '张三', 2, 'system');
INSERT INTO T_COST_USER (ID, USERNAME, PASSWORD, REAL_NAME, DEPARTMENT_ID, CREATE_BY)
VALUES (SEQ_COST_USER.NEXTVAL, 'lisi', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKt6Z5EH', '李四', 2, 'system');

INSERT INTO T_COST_USER_ROLE (ID, USER_ID, ROLE_ID, CREATE_BY) VALUES (SEQ_COST_USER_ROLE.NEXTVAL, 1, 1, 'system');
INSERT INTO T_COST_USER_ROLE (ID, USER_ID, ROLE_ID, CREATE_BY) VALUES (SEQ_COST_USER_ROLE.NEXTVAL, 2, 2, 'system');
INSERT INTO T_COST_USER_ROLE (ID, USER_ID, ROLE_ID, CREATE_BY) VALUES (SEQ_COST_USER_ROLE.NEXTVAL, 3, 3, 'system');

INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, CREATE_BY)
VALUES (SEQ_COST_ROLE_PAGE.NEXTVAL, 1, 'cost-eval', '["*"]', NULL, 'system');
INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, CREATE_BY)
VALUES (SEQ_COST_ROLE_PAGE.NEXTVAL, 2, 'cost-eval', '["CREATE","EDIT","DELETE","EXPORT"]', NULL, 'system');
INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, CREATE_BY)
VALUES (SEQ_COST_ROLE_PAGE.NEXTVAL, 3, 'cost-eval', '["EXPORT"]', NULL, 'system');

INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'home', '首页', 'PAGE', 'home', 'mdi:monitor-dashboard', '/home', NULL, 0, 'system');
INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'cost', '成本管理', 'DIRECTORY', NULL, 'mdi:currency-usd', '/cost', NULL, 1, 'system');
DECLARE
    v_parent_id NUMBER;
BEGIN
    SELECT ID INTO v_parent_id FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'cost';
    INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
    VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'eval-v4', '评估�?, 'PAGE', 'cost-eval', 'mdi:calculator', '/cost/eval-v4', v_parent_id, 1, 'system');
END;
/

COMMIT;

-- B3. 业务测试数据
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL001', '阿莫西林原料', '原料', 125.5, 280, 'kg', '医药�?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL002', '淀�?, '原料', 45.2, 15, 'kg', '食品�?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'YL003', '头孢克肟原料', '原料', 200, 450, 'kg', '医药�?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL001', '空心胶囊', '辅料', 1050, 0.035, '�?, '0�?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL002', '硬脂酸镁', '辅料', 2.5, 45, 'kg', '医药�?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'FL003', '微晶纤维�?, '辅料', 80, 25, 'kg', '医药�?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC001', '铝塑�?, '包材', 0, 0.12, '�?, '10�?�?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC002', '纸盒', '包材', 0, 0.35, '�?, '2�?�?, 'system');
INSERT INTO T_COST_MATERIAL (ID, MATERIAL_CODE, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, UNIT, SPEC, CREATE_BY)
VALUES (SEQ_COST_MATERIAL.NEXTVAL, 'BC003', '说明�?, '包材', 0, 0.05, '�?, 'A4', 'system');

INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C001', '华为技术有限公�?, '张三', '13800138001', '深圳市龙岗区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C002', '阿里巴巴集团', '李四', '13800138002', '杭州市余杭区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C003', '腾讯科技', '王五', '13800138003', '深圳市南山区', 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C004', '字节跳动', '赵六', '13800138004', '北京市海淀�?, 'system');
INSERT INTO T_COST_CUSTOMER (ID, CUSTOMER_CODE, CUSTOMER_NAME, CONTACT_PERSON, PHONE, ADDRESS, CREATE_BY)
VALUES (SEQ_COST_CUSTOMER.NEXTVAL, 'C005', '美团点评', '钱七', '13800138005', '北京市朝阳区', 'system');

DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-001', '阿莫西林胶囊', 100, 98, 35.5, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '阿莫西林原料', '原料', 125.5, 280, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '淀�?, '原料', 45.2, 15, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '空心胶囊', '辅料', 1050, 0.035, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '硬脂酸镁', '辅料', 2.5, 45, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PACK_SPEC, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '铝塑�?, '包材', '10�?�?, 0.12, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PACK_SPEC, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '纸盒', '包材', '2�?�?, 0.35, 'system');
    COMMIT;
END;
/

DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-002', '头孢克肟�?, 80, 95, 42.0, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '头孢克肟原料', '原料', 200, 450, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PER_HL, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '微晶纤维�?, '辅料', 80, 25, 'system');
    INSERT INTO T_COST_EVAL_DETAIL (ID, EVAL_ID, MATERIAL_NAME, USE_FLAG, PACK_SPEC, PRICE, CREATE_BY)
    VALUES (SEQ_COST_EVAL_DETAIL.NEXTVAL, v_eval_id, '铝塑�?, '包材', '12�?�?, 0.15, 'system');
    COMMIT;
END;
/

DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-003', '阿莫西林口服液瓶�?, 50, 96, 28.0, 'system');
    COMMIT;
END;
/

DECLARE
    v_eval_id NUMBER;
BEGIN
    SELECT SEQ_COST_EVAL.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_EVAL (ID, EVAL_NO, PRODUCT_NAME, APEX_PL, YIELD, OUT_PRICE_RMB, CREATE_BY)
    VALUES (v_eval_id, 'EVAL-2025-004', '清热解毒颗粒', 60, 94, 32.0, 'system');
    COMMIT;
END;
/

COMMIT;

-- =====================================================
-- C. 元数据与页面配置
-- =====================================================

-- C1. �?列元数据初始化（CostEval、CostMaterial、Customer 等）
DECLARE
    v_eval_id NUMBER;
    v_detail_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_eval_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, VALIDATION_RULES, CREATE_BY)
    VALUES (v_eval_id, 'CostEval', '评估�?, 'T_COST_EVAL', 'T_COST_EVAL', 'SEQ_COST_EVAL', 'ID',
    '[{"order":1,"name":"evalNoUnique","sql":"SELECT COUNT(*) FROM T_COST_EVAL WHERE EVAL_NO = :evalNo AND ID != NVL(:id, -1) AND DELETED = 0","condition":"result == 0","message":"评估单号已存�?},{"order":2,"name":"apexPlPositive","sql":"SELECT CASE WHEN :apexPl > 0 THEN 1 ELSE 0 END FROM DUAL","condition":"result == 1","message":"批量必须大于0"}]',
    'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'id', 'ID', 'ID', 'number', 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'evalNo', 'EVAL_NO', '评估单号', 'text', 1, 0, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'productName', 'PRODUCT_NAME', '产品名称', 'text', 2, 1, 150,
    '{"style":[{"condition":{"type":"contains","pattern":"�?},"cellStyle":{"color":"red","fontWeight":"bold"}},{"condition":{"type":"contains","pattern":"�?},"rowStyle":{"backgroundColor":"#e3f2fd"}}]}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'apexPl', 'APEX_PL', '批量(万片)', 'number', 3, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'yield', 'YIELD', '收率(%)', 'number', 4, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'outPriceRmb', 'OUT_PRICE_RMB', '出厂�?, 'number', 5, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'totalYl', 'TOTAL_YL', '原料合计', 'number', 6, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'totalFl', 'TOTAL_FL', '辅料合计', 'number', 7, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'totalPack', 'TOTAL_PACK', '包材合计', 'number', 8, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_eval_id, 'totalCost', 'TOTAL_COST', '总成�?, 'number', 9, 0, 100, 'system');

    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_detail_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, CREATE_BY)
    VALUES (v_detail_id, 'CostEvalDetail', '物料明细', 'T_COST_EVAL_DETAIL', 'T_COST_EVAL_DETAIL', 'SEQ_COST_EVAL_DETAIL', 'ID', 'CostEval', 'EVAL_ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'id', 'ID', 'ID', 'number', 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'evalId', 'EVAL_ID', '主表ID', 'number', 1, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'materialName', 'MATERIAL_NAME', '物料名称', 'text', 2, 1, 150,
    '{"lookup":{"code":"material","mapping":{"materialName":"materialName","useFlag":"useFlag","perHl":"perHl","price":"price"}}}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'useFlag', 'USE_FLAG', '物料类型', 'text', 3, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'perHl', 'PER_HL', '百万片用�?, 'number', 4, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'price', 'PRICE', '单价', 'number', 5, 1, 100,
    '{"validate":[{"order":1,"type":"notZero","message":"单价不能�?"},{"order":2,"type":"min","value":0,"message":"单价不能为负�?}],"compare":{"enabled":true,"format":"both"}}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'batchQty', 'BATCH_QTY', '批用�?, 'number', 6, 0, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'costBatch', 'COST_BATCH', '批成�?, 'number', 7, 0, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'packSpec', 'PACK_SPEC', '规格', 'text', 8, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'packQty', 'PACK_QTY', '包装数量', 'number', 9, 0, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'packCost', 'PACK_COST', '包装成本', 'number', 10, 0, 1, 100, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-eval', 'root', 'LAYOUT', NULL, 0, '{"direction":"vertical","gap":8}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-eval', 'masterGrid', 'GRID', 'root', 1, 'CostEval', '{"height":"50%","selectionMode":"single"}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-eval', 'detailTabs', 'TABS', 'root', 2, 'CostEvalDetail',
'{
  "mode": "group",
  "groupField": "useFlag",
  "tabs": [
    {"key": "material", "title": "原料", "value": "原料", "columns": ["materialName", "perHl", "price", "batchQty", "costBatch"]},
    {"key": "auxiliary", "title": "辅料", "value": "辅料", "columns": ["materialName", "perHl", "price", "batchQty", "costBatch"]},
    {"key": "package", "title": "包材", "value": "包材", "columns": ["materialName", "packSpec", "price", "packQty", "packCost"]}
  ],
  "broadcast": ["apexPl", "yield"],
  "calcRules": [
    {"field": "batchQty", "expression": "apexPl * perHl / 100 / yield * 100", "triggerFields": ["perHl"], "condition": "useFlag !== ''包材''"},
    {"field": "costBatch", "expression": "batchQty * price", "triggerFields": ["batchQty", "price"], "condition": "useFlag !== ''包材''"},
    {"field": "packQty", "expression": "apexPl * 1000", "triggerFields": [], "condition": "useFlag === ''包材''"},
    {"field": "packCost", "expression": "packQty * price", "triggerFields": ["packQty", "price"], "condition": "useFlag === ''包材''"}
  ],
  "aggregates": [
    {"sourceField": "costBatch", "targetField": "totalYl", "algorithm": "SUM", "filter": "useFlag === ''原料''"},
    {"sourceField": "costBatch", "targetField": "totalFl", "algorithm": "SUM", "filter": "useFlag === ''辅料''"},
    {"sourceField": "packCost", "targetField": "totalPack", "algorithm": "SUM", "filter": "useFlag === ''包材''"},
    {"targetField": "totalCost", "expression": "totalYl + totalFl + totalPack"}
  ]
}', 'system');

COMMIT;

DECLARE
    v_material_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_material_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_material_id, 'CostMaterial', '物料基础数据', 'T_COST_MATERIAL', 'T_COST_MATERIAL', 'SEQ_COST_MATERIAL', 'ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'id', 'ID', 'ID', 'number', 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'materialCode', 'MATERIAL_CODE', '物料编码', 'text', 1, 1, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'materialName', 'MATERIAL_NAME', '物料名称', 'text', 2, 1, 1, 150, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'useFlag', 'USE_FLAG', '物料类型', 'text', 3, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'perHl', 'PER_HL', '百万片用�?, 'number', 4, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'price', 'PRICE', '单价', 'number', 5, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'unit', 'UNIT', '单位', 'text', 6, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_material_id, 'spec', 'SPEC', '规格', 'text', 7, 1, 100, 'system');
    COMMIT;
END;
/

DECLARE
    v_customer_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_customer_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_customer_id, 'Customer', '客户', 'T_COST_CUSTOMER', 'T_COST_CUSTOMER', 'SEQ_COST_CUSTOMER', 'ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'id', 'ID', 'ID', 'number', 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'customerCode', 'CUSTOMER_CODE', '客户编码', 'text', 1, 1, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'customerName', 'CUSTOMER_NAME', '客户名称', 'text', 2, 1, 1, 180, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'contactPerson', 'CONTACT_PERSON', '联系�?, 'text', 3, 1, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'phone', 'PHONE', '电话', 'text', 4, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_customer_id, 'address', 'ADDRESS', '地址', 'text', 5, 1, 200, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_LOOKUP_CONFIG (ID, LOOKUP_CODE, LOOKUP_NAME, DATA_SOURCE, DISPLAY_COLUMNS, SEARCH_COLUMNS, VALUE_FIELD, LABEL_FIELD, CREATE_BY)
VALUES (SEQ_COST_LOOKUP_CONFIG.NEXTVAL, 'material', '物料选择', 'CostMaterial',
  '[{"field":"materialCode","header":"物料编码","width":100},{"field":"materialName","header":"物料名称","width":150},{"field":"useFlag","header":"类型","width":80},{"field":"price","header":"单价","width":80}]',
  '["materialCode","materialName"]', 'id', 'materialName', 'system');
INSERT INTO T_COST_LOOKUP_CONFIG (ID, LOOKUP_CODE, LOOKUP_NAME, DATA_SOURCE, DISPLAY_COLUMNS, SEARCH_COLUMNS, VALUE_FIELD, LABEL_FIELD, CREATE_BY)
VALUES (SEQ_COST_LOOKUP_CONFIG.NEXTVAL, 'customer', '客户选择', 'Customer',
  '[{"field":"customerCode","header":"客户编码","width":100},{"field":"customerName","header":"客户名称","width":180},{"field":"contactPerson","header":"联系�?,"width":100}]',
  '["customerCode","customerName"]', 'id', 'customerName', 'system');

COMMIT;

-- C2. 人员管理页面配置（视�?+ 元数�?+ 页面布局�?
INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'system', '系统管理', 'DIRECTORY', NULL, 'mdi:cog', '/system', NULL, 99, 'system');
DECLARE
    v_parent_id NUMBER;
BEGIN
    SELECT ID INTO v_parent_id FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'system';
    INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
    VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'user', '人员管理', 'PAGE', 'user-manage', 'mdi:account-group', '/system/user', v_parent_id, 1, 'system');
END;
/

DECLARE
    v_user_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_user_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_user_id, 'CostUser', '用户', 'V_COST_USER', 'T_COST_USER', 'SEQ_COST_USER', 'ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'id', 'ID', 'ID', 'number', 0, 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'username', 'USERNAME', '用户�?, 'text', 1, 1, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'realName', 'REAL_NAME', '姓名', 'text', 2, 1, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'email', 'EMAIL', '邮箱', 'text', 3, 1, 150, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'phone', 'PHONE', '手机�?, 'text', 4, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'deptName', 'DEPT_NAME', '部门', 'text', 5, 0, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'status', 'STATUS', '状�?, 'select', 6, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_id, 'createTime', 'CREATE_TIME', '创建时间', 'datetime', 7, 0, 160, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'user-manage', 'root', 'LAYOUT', NULL, 0, '{"direction":"vertical","gap":8}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'user-manage', 'masterGrid', 'GRID', 'root', 1, 'CostUser', '{"height":"100%","selectionMode":"single"}', 'system');

CREATE OR REPLACE VIEW V_COST_USER AS
SELECT 
    u.ID,
    u.USERNAME,
    u.REAL_NAME,
    u.EMAIL,
    u.PHONE,
    u.DEPARTMENT_ID,
    d.DEPT_NAME,
    u.STATUS,
    u.DELETED,
    u.CREATE_BY,
    u.CREATE_TIME,
    u.UPDATE_BY,
    u.UPDATE_TIME
FROM T_COST_USER u
LEFT JOIN T_COST_DEPARTMENT d ON u.DEPARTMENT_ID = d.ID AND d.DELETED = 0;

-- C3. 角色管理页面配置（角色主�?+ 用户关联从表�?
DECLARE
    v_parent_id NUMBER;
BEGIN
    SELECT ID INTO v_parent_id FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'system';
    INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
    VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'role', '角色管理', 'PAGE', 'role-manage', 'mdi:shield-account', '/system/role', v_parent_id, 2, 'system');
END;
/

DECLARE
    v_role_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_role_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, CREATE_BY)
    VALUES (v_role_id, 'CostRole', '角色', 'T_COST_ROLE', 'T_COST_ROLE', 'SEQ_COST_ROLE', 'ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'id', 'ID', 'ID', 'number', 0, 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'roleCode', 'ROLE_CODE', '角色编码', 'text', 1, 1, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'roleName', 'ROLE_NAME', '角色名称', 'text', 2, 1, 1, 150, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'description', 'DESCRIPTION', '描述', 'text', 3, 1, 250, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_role_id, 'createTime', 'CREATE_TIME', '创建时间', 'datetime', 4, 0, 160, 'system');
    COMMIT;
END;
/

DECLARE
    v_user_role_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_user_role_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, CREATE_BY)
    VALUES (v_user_role_id, 'CostUserRole', '角色用户', 'V_COST_USER_ROLE', 'T_COST_USER_ROLE', 'SEQ_COST_USER_ROLE', 'ID', 'CostRole', 'ROLE_ID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'id', 'ID', 'ID', 'number', 0, 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'roleId', 'ROLE_ID', '角色ID', 'number', 1, 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'userId', 'USER_ID', '用户ID', 'number', 2, 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'username', 'USERNAME', '用户�?, 'text', 3, 0, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'realName', 'REAL_NAME', '姓名', 'text', 4, 0, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'deptName', 'DEPT_NAME', '部门', 'text', 5, 0, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_user_role_id, 'createTime', 'CREATE_TIME', '分配时间', 'datetime', 6, 0, 160, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'role-manage', 'root', 'LAYOUT', NULL, 0, '{"direction":"vertical","gap":8}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'role-manage', 'masterGrid', 'GRID', 'root', 1, 'CostRole', '{"height":"50%","selectionMode":"single"}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'role-manage', 'detailTabs', 'TABS', 'root', 2, 'CostUserRole',
'{
  "mode": "group",
  "tabs": [
    {"key": "users", "title": "角色用户", "columns": ["username", "realName", "deptName", "createTime"]}
  ]
}', 'system');

CREATE OR REPLACE VIEW V_COST_USER_ROLE AS
SELECT 
    ur.ID,
    ur.USER_ID,
    ur.ROLE_ID,
    u.USERNAME,
    u.REAL_NAME,
    d.DEPT_NAME,
    ur.DELETED,
    ur.CREATE_BY,
    ur.CREATE_TIME
FROM T_COST_USER_ROLE ur
LEFT JOIN T_COST_USER u ON ur.USER_ID = u.ID AND u.DELETED = 0
LEFT JOIN T_COST_DEPARTMENT d ON u.DEPARTMENT_ID = d.ID AND d.DELETED = 0;

-- C4. 成本评估页面配置（含视图与主从元数据�?
CREATE OR REPLACE VIEW V_COST_PINGGU_DTL AS
SELECT 
    d.DTLID,
    d.DOCID,
    d.DTL_USEFLAG,
    d.APEX_GOODSNAME,
    d.SPEC,
    d.PER_HL,
    d.EXADD_MATER,
    d.BATCH_QTY,
    d.PRICE,
    d.COST_BATCH,
    d.MEMO,
    d.APEX_FACTORYNAME,
    d.APEX_FACTORYID,
    d.APEX_GOODSID,
    d.MODIFYDATE,
    d.ZX_SOURCE,
    d.BASE_PRICE,
    d.SUQTY,
    d.GOODSTYPE,
    d.GOODSNAME_EN,
    CASE
        WHEN d.DTL_USEFLAG IN ('印字包材', '非印字包�?) AND REGEXP_LIKE(d.APEX_GOODSNAME, '桶|说明书|小盒|标签|瓶|�?) THEN 'A'
        WHEN d.DTL_USEFLAG = '辅料' AND REGEXP_LIKE(d.APEX_GOODSNAME, '胶囊') THEN 'B'
        WHEN d.DTL_USEFLAG IN ('印字包材', '非印字包�?) AND REGEXP_LIKE(d.APEX_GOODSNAME, '硬片|铝箔') THEN 'D'
        WHEN d.DTL_USEFLAG IN ('印字包材', '非印字包�?) AND REGEXP_LIKE(d.APEX_GOODSNAME, '大纸�?) THEN 'E'
        WHEN d.DTL_USEFLAG IN ('印字包材', '非印字包�?) AND REGEXP_LIKE(d.APEX_GOODSNAME, '托盘') THEN 'F'
        WHEN d.DTL_USEFLAG IN ('原料', '辅料') THEN 'C'
        ELSE NULL
    END AS FORMULA_TYPE
FROM T_COST_PINGGU_DTL d;

DECLARE
    v_parent_id NUMBER;
BEGIN
    SELECT ID INTO v_parent_id FROM T_COST_RESOURCE WHERE RESOURCE_CODE = 'cost';
    INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
    VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'pinggu', '成本评估', 'PAGE', 'cost-pinggu', 'mdi:calculator-variant', '/cost/pinggu', v_parent_id, 2, 'system');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO T_COST_RESOURCE (ID, RESOURCE_CODE, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, CREATE_BY)
        VALUES (SEQ_COST_RESOURCE.NEXTVAL, 'pinggu', '成本评估', 'PAGE', 'cost-pinggu', 'mdi:calculator-variant', '/pinggu', NULL, 10, 'system');
END;
/

DECLARE
    v_master_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_master_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, PK_COLUMN, CREATE_BY)
    VALUES (v_master_id, 'CostPinggu', '成本评估', 'T_COST_PINGGU', 'T_COST_PINGGU', 'DOCID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'docid', 'DOCID', 'ID', 'number', 0, 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'goodsname', 'GOODSNAME', '产品名称', 'text', 1, 1, 1, 150, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'goodsnameEn', 'GOODSNAME_EN', '产品英文�?, 'text', 2, 1, 200, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'strength', 'STRENGTH', '剂量', 'text', 3, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'dosage', 'DOSAGE', '剂型', 'text', 4, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'form', 'FORM', '片型', 'text', 5, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'maNo', 'MA_NO', '注册�?, 'text', 6, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'mah', 'MAH', '注册持有�?, 'text', 7, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'customname', 'CUSTOMNAME', '客户名称', 'text', 8, 1, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'country', 'COUNTRY', '国家', 'text', 9, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'projectno', 'PROJECTNO', '项目�?, 'text', 10, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'apexPl', 'APEX_PL', '批量', 'number', 11, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'annualQty', 'ANNUAL_QTY', '年需求量', 'number', 12, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'yield', 'YIELD', '收率(%)', 'number', 13, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'pPerpack', 'P_PERPACK', '每盒片数', 'number', 14, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'sPerback', 'S_PERBACK', '每箱装盒�?, 'number', 15, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'xPerback', 'X_PERBACK', '每托盘箱�?, 'number', 16, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'packtype', 'PACKTYPE', '包装形式', 'text', 17, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalYl', 'TOTAL_YL', '原料合计', 'number', 20, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalFl', 'TOTAL_FL', '辅料合计', 'number', 21, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalBc', 'TOTAL_BC', '包材合计', 'number', 22, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'totalCost', 'TOTAL_COST', '总物料成�?, 'number', 23, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'outPriceRmb', 'OUT_PRICE_RMB', '出厂�?RMB)', 'number', 24, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'salemoney', 'SALEMONEY', '每批销售额', 'number', 25, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'jgfBatch', 'JGF_BATCH', '每批加工�?, 'number', 26, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'costPerqp', 'COST_PERQP', '千片成本', 'number', 27, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'jgfPerqp', 'JGF_PERQP', '千片加工�?, 'number', 28, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'mlPerqp', 'ML_PERQP', '千片毛利', 'number', 29, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'yJgRe', 'Y_JG_RE', '年加工收�?, 'number', 30, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'yMl', 'Y_ML', '年毛�?, 'number', 31, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'ySale', 'Y_SALE', '年销售额', 'number', 32, 0, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'usestatus', 'USESTATUS', '状�?, 'text', 33, 1, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_master_id, 'memo', 'MEMO', '备注', 'text', 34, 1, 150, 'system');
    COMMIT;
END;
/

DECLARE
    v_detail_id NUMBER;
BEGIN
    SELECT SEQ_COST_TABLE_METADATA.NEXTVAL INTO v_detail_id FROM DUAL;
    INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, CREATE_BY)
    VALUES (v_detail_id, 'CostPingguDtl', '成本评估明细', 'V_COST_PINGGU_DTL', 'T_COST_PINGGU_DTL', 'DTLID', 'CostPinggu', 'DOCID', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'dtlid', 'DTLID', 'ID', 'number', 0, 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'docid', 'DOCID', '主表ID', 'number', 1, 0, 0, 80, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'dtlUseflag', 'DTL_USEFLAG', '分类', 'text', 2, 1, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, SEARCHABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'apexGoodsname', 'APEX_GOODSNAME', '货品�?, 'text', 3, 1, 1, 150, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'spec', 'SPEC', '规格', 'text', 4, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'perHl', 'PER_HL', '每片含量', 'number', 5, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'exaddMater', 'EXADD_MATER', '额外投料�?, 'number', 6, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'batchQty', 'BATCH_QTY', '每批数量', 'number', 7, 0, 100,
    '{"calculate":{"formulaField":"formulaType","formulas":{"A":{"expression":"apexPl / pPerpack","triggerFields":["apexPl","pPerpack"]},"B":{"expression":"apexPl / 10000","triggerFields":["apexPl"]},"C":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]},"D":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]},"E":{"expression":"ceil(apexPl / (pPerpack * sPerback))","triggerFields":["apexPl","pPerpack","sPerback"]},"F":{"expression":"ceil(apexPl / (pPerpack * sPerback * xPerback))","triggerFields":["apexPl","pPerpack","sPerback","xPerback"]}}}}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'price', 'PRICE', '价格', 'number', 8, 1, 100, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, RULES_CONFIG, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'costBatch', 'COST_BATCH', '每批成本', 'number', 9, 0, 100,
    '{"calculate":{"expression":"batchQty * price","triggerFields":["batchQty","price"]}}', 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'apexFactoryname', 'APEX_FACTORYNAME', '厂家�?, 'text', 10, 1, 120, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'memo', 'MEMO', '备注', 'text', 11, 1, 150, 'system');
    INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, EDITABLE, VISIBLE, IS_VIRTUAL, WIDTH, CREATE_BY)
    VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, v_detail_id, 'formulaType', 'FORMULA_TYPE', '公式类型', 'text', 12, 0, 0, 1, 60, 'system');
    COMMIT;
END;
/

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu', 'root', 'LAYOUT', NULL, 0, '{"direction":"vertical","gap":8}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu', 'masterGrid', 'GRID', 'root', 1, 'CostPinggu', '{"height":"50%","selectionMode":"single"}', 'system');
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, SORT_ORDER, REF_TABLE_CODE, COMPONENT_CONFIG, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu', 'detailTabs', 'TABS', 'root', 2, 'CostPingguDtl',
'{
  "mode": "group",
  "groupField": "dtlUseflag",
  "tabs": [
    {"key": "ylfl", "title": "原料/辅料", "values": ["原料", "辅料"]},
    {"key": "bc", "title": "包材", "values": ["印字包材", "非印字包�?]}
  ],
  "broadcast": ["apexPl", "pPerpack", "sPerback", "xPerback"],
  "aggregates": [
    {"sourceField": "costBatch", "targetField": "totalYl", "algorithm": "SUM", "filter": "dtlUseflag === ''原料''"},
    {"sourceField": "costBatch", "targetField": "totalFl", "algorithm": "SUM", "filter": "dtlUseflag === ''辅料''"},
    {"sourceField": "costBatch", "targetField": "totalBc", "algorithm": "SUM", "filter": "dtlUseflag === ''印字包材'' || dtlUseflag === ''非印字包�?'"},
    {"targetField": "totalCost", "expression": "totalYl + totalFl + totalBc"}
  ],
  "postProcess": "if (totalYl > 0) { totalYl /= 1.13; totalFl /= 1.13; totalBc /= 1.13; totalCost = totalYl + totalFl + totalBc; }",
  "masterCalcRules": [
    {"field": "salemoney", "expression": "outPriceRmb / pPerpack * apexPl * (yield / 100)", "triggerFields": ["outPriceRmb", "pPerpack", "apexPl", "yield", "totalCost"]},
    {"field": "jgfBatch", "expression": "salemoney - totalCost", "triggerFields": ["salemoney", "totalCost"]},
    {"field": "jgfPerqp", "expression": "jgfBatch / apexPl * 1000", "triggerFields": ["jgfBatch", "apexPl"]},
    {"field": "mlPerqp", "expression": "jgfPerqp - costPerqp", "triggerFields": ["jgfPerqp", "costPerqp"]},
    {"field": "yJgRe", "expression": "jgfPerqp / 1000 * annualQty", "triggerFields": ["jgfPerqp", "annualQty"]},
    {"field": "yMl", "expression": "mlPerqp / 1000 * annualQty", "triggerFields": ["mlPerqp", "annualQty"]},
    {"field": "ySale", "expression": "salemoney / apexPl * annualQty", "triggerFields": ["salemoney", "apexPl", "annualQty"]}
  ]
}', 'system');

COMMIT;

-- =====================================================
-- D. 修复补丁（兼容前端字段命名）
-- =====================================================

-- D1. 人员相关视图字段标记为虚拟列
UPDATE T_COST_COLUMN_METADATA 
SET IS_VIRTUAL = 1
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostUser')
  AND FIELD_NAME = 'deptName';
UPDATE T_COST_COLUMN_METADATA 
SET IS_VIRTUAL = 1
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostUserRole')
  AND FIELD_NAME IN ('deptName', 'username', 'realName');

-- D2. 成本评估主键、外键字段命名统一
UPDATE T_COST_COLUMN_METADATA 
SET FIELD_NAME = 'id'
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPinggu')
  AND COLUMN_NAME = 'DOCID';
UPDATE T_COST_COLUMN_METADATA 
SET FIELD_NAME = 'id'
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguDtl')
  AND COLUMN_NAME = 'DTLID';
UPDATE T_COST_COLUMN_METADATA 
SET FIELD_NAME = 'masterId'
WHERE TABLE_METADATA_ID = (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguDtl')
  AND COLUMN_NAME = 'DOCID';

COMMIT;
