-- ============================================================
-- 全量表结构 DDL
-- 按依赖顺序排列，先建被引用的表
-- ============================================================

-- ============================================================
-- 1. 用户/角色/部门
-- ============================================================

CREATE TABLE T_COST_DEPARTMENT (
  ID          NUMBER(19) NOT NULL,
  DEPT_CODE   VARCHAR2(64) NOT NULL,
  DEPT_NAME   VARCHAR2(128) NOT NULL,
  PARENT_ID   NUMBER(19),
  SORT_ORDER  NUMBER(5) DEFAULT 0,
  DELETED     NUMBER(1) DEFAULT 0,
  CREATE_BY   VARCHAR2(64),
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_BY   VARCHAR2(64),
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_COST_DEPARTMENT PRIMARY KEY (ID),
  CONSTRAINT UK_DEPT_CODE UNIQUE (DEPT_CODE)
);

CREATE TABLE T_COST_USER (
  ID            NUMBER(19) NOT NULL,
  USERNAME      VARCHAR2(64) NOT NULL,
  PASSWORD      VARCHAR2(256) NOT NULL,
  REAL_NAME     VARCHAR2(128),
  EMAIL         VARCHAR2(128),
  PHONE         VARCHAR2(32),
  DEPARTMENT_ID NUMBER(19),
  STATUS        VARCHAR2(32) DEFAULT 'ACTIVE',
  DELETED       NUMBER(1) DEFAULT 0,
  CREATE_BY     VARCHAR2(64),
  CREATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_BY     VARCHAR2(64),
  UPDATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_COST_USER PRIMARY KEY (ID),
  CONSTRAINT UK_USER_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE T_COST_ROLE (
  ID          NUMBER(19) NOT NULL,
  ROLE_CODE   VARCHAR2(64) NOT NULL,
  ROLE_NAME   VARCHAR2(128) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  CONSTRAINT PK_COST_ROLE PRIMARY KEY (ID),
  CONSTRAINT UK_ROLE_CODE UNIQUE (ROLE_CODE)
);

CREATE TABLE T_COST_USER_ROLE (
  ID      NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  ROLE_ID NUMBER(19) NOT NULL,
  CONSTRAINT PK_COST_USER_ROLE PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_USER_ROLE ON T_COST_USER_ROLE (USER_ID, ROLE_ID);

-- ============================================================
-- 2. 资源/权限
-- ============================================================

CREATE TABLE T_COST_RESOURCE (
  ID            NUMBER(19) NOT NULL,
  RESOURCE_NAME VARCHAR2(128) NOT NULL,
  RESOURCE_TYPE VARCHAR2(20) NOT NULL,
  PAGE_CODE     VARCHAR2(64),
  ICON          VARCHAR2(64),
  ROUTE         VARCHAR2(128),
  PARENT_ID     NUMBER(19),
  SORT_ORDER    NUMBER(5) DEFAULT 0,
  IS_HARDCODED  NUMBER(1) DEFAULT 0,
  CONSTRAINT PK_COST_RESOURCE PRIMARY KEY (ID)
);

CREATE TABLE T_COST_ROLE_PAGE (
  ID            NUMBER(19) NOT NULL,
  ROLE_ID       NUMBER(19) NOT NULL,
  PAGE_CODE     VARCHAR2(64) NOT NULL,
  BUTTON_POLICY VARCHAR2(1000),
  COLUMN_POLICY CLOB,
  ROW_POLICY    VARCHAR2(2000),
  CONSTRAINT PK_COST_ROLE_PAGE PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_ROLE_PAGE ON T_COST_ROLE_PAGE (ROLE_ID, PAGE_CODE);

-- ============================================================
-- 3. 元数据配置
-- ============================================================

CREATE TABLE T_COST_TABLE_METADATA (
  ID                NUMBER(19) NOT NULL,
  TABLE_CODE        VARCHAR2(64) NOT NULL,
  TABLE_NAME        VARCHAR2(128) NOT NULL,
  QUERY_VIEW        VARCHAR2(64),
  TARGET_TABLE      VARCHAR2(64) NOT NULL,
  SEQUENCE_NAME     VARCHAR2(64),
  PK_COLUMN         VARCHAR2(64) DEFAULT 'ID',
  PARENT_TABLE_CODE VARCHAR2(64),
  PARENT_FK_COLUMN  VARCHAR2(64),
  AUDIT_ENABLED     NUMBER(1) DEFAULT 0,
  VALIDATION_RULES  CLOB,
  ACTION_RULES      CLOB,
  DESCRIPTION       VARCHAR2(500),
  DELETED           NUMBER(1) DEFAULT 0,
  CREATE_TIME       TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME       TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY         VARCHAR2(64),
  UPDATE_BY         VARCHAR2(64),
  CONSTRAINT PK_COST_TABLE_METADATA PRIMARY KEY (ID),
  CONSTRAINT UK_TABLE_CODE UNIQUE (TABLE_CODE)
);

CREATE TABLE T_COST_COLUMN_METADATA (
  ID                NUMBER(19) NOT NULL,
  TABLE_METADATA_ID NUMBER(19) NOT NULL,
  COLUMN_NAME       VARCHAR2(64) NOT NULL,
  QUERY_COLUMN      VARCHAR2(128),
  TARGET_COLUMN     VARCHAR2(64),
  HEADER_TEXT       VARCHAR2(128) NOT NULL,
  DATA_TYPE         VARCHAR2(32) DEFAULT 'text',
  DISPLAY_ORDER     NUMBER(5) DEFAULT 0,
  SORTABLE          NUMBER(1) DEFAULT 1,
  FILTERABLE        NUMBER(1) DEFAULT 1,
  IS_VIRTUAL        NUMBER(1) DEFAULT 0,
  DICT_TYPE         VARCHAR2(64),
  DELETED           NUMBER(1) DEFAULT 0,
  CREATE_TIME       TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME       TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY         VARCHAR2(64),
  UPDATE_BY         VARCHAR2(64),
  CONSTRAINT PK_COST_COLUMN_METADATA PRIMARY KEY (ID),
  CONSTRAINT FK_COLUMN_TABLE FOREIGN KEY (TABLE_METADATA_ID) REFERENCES T_COST_TABLE_METADATA (ID)
);
CREATE INDEX IDX_COLUMN_TABLE_ID ON T_COST_COLUMN_METADATA (TABLE_METADATA_ID);

-- ============================================================
-- 4. 页面组件/规则
-- ============================================================

CREATE TABLE T_COST_PAGE_COMPONENT (
  ID               NUMBER(19) NOT NULL,
  PAGE_CODE        VARCHAR2(64) NOT NULL,
  COMPONENT_KEY    VARCHAR2(64) NOT NULL,
  COMPONENT_TYPE   VARCHAR2(32) NOT NULL,
  PARENT_KEY       VARCHAR2(64),
  COMPONENT_CONFIG CLOB,
  REF_TABLE_CODE   VARCHAR2(64),
  SLOT_NAME        VARCHAR2(32),
  SORT_ORDER       NUMBER(5) DEFAULT 0,
  DELETED          NUMBER(1) DEFAULT 0,
  DESCRIPTION      VARCHAR2(200),
  CREATE_TIME      TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME      TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY        VARCHAR2(64),
  UPDATE_BY        VARCHAR2(64),
  CONSTRAINT PK_COST_PAGE_COMPONENT PRIMARY KEY (ID)
);
CREATE INDEX IDX_PAGE_COMP_PAGE ON T_COST_PAGE_COMPONENT (PAGE_CODE);
CREATE UNIQUE INDEX UK_PAGE_COMP_KEY ON T_COST_PAGE_COMPONENT (PAGE_CODE, COMPONENT_KEY);

CREATE TABLE T_COST_PAGE_RULE (
  ID            NUMBER(19) NOT NULL,
  PAGE_CODE     VARCHAR2(64) NOT NULL,
  COMPONENT_KEY VARCHAR2(64) NOT NULL,
  RULE_TYPE     VARCHAR2(32) NOT NULL,
  RULES         CLOB NOT NULL,
  SORT_ORDER    NUMBER(5) DEFAULT 0,
  DESCRIPTION   VARCHAR2(200),
  DELETED       NUMBER(1) DEFAULT 0,
  CREATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY     VARCHAR2(64),
  UPDATE_BY     VARCHAR2(64),
  CONSTRAINT PK_COST_PAGE_RULE PRIMARY KEY (ID)
);
CREATE INDEX IDX_PAGE_RULE_PAGE ON T_COST_PAGE_RULE (PAGE_CODE);

-- ============================================================
-- 5. 字典
-- ============================================================

CREATE TABLE T_COST_DICTIONARY_TYPE (
  ID          NUMBER(19) NOT NULL,
  TYPE_CODE   VARCHAR2(64) NOT NULL,
  TYPE_NAME   VARCHAR2(128) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  DELETED     NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY   VARCHAR2(64),
  UPDATE_BY   VARCHAR2(64),
  CONSTRAINT PK_COST_DICT_TYPE PRIMARY KEY (ID),
  CONSTRAINT UK_DICT_TYPE_CODE UNIQUE (TYPE_CODE)
);

CREATE TABLE T_COST_DICTIONARY_ITEM (
  ID           NUMBER(19) NOT NULL,
  TYPE_ID      NUMBER(19) NOT NULL,
  ITEM_CODE    VARCHAR2(64) NOT NULL,
  ITEM_NAME    VARCHAR2(128) NOT NULL,
  ITEM_VALUE   VARCHAR2(200),
  SORT_ORDER   NUMBER(5) DEFAULT 0,
  EXTRA_CONFIG VARCHAR2(1000),
  DELETED      NUMBER(1) DEFAULT 0,
  CREATE_TIME  TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME  TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY    VARCHAR2(64),
  UPDATE_BY    VARCHAR2(64),
  CONSTRAINT PK_COST_DICT_ITEM PRIMARY KEY (ID),
  CONSTRAINT FK_DICT_ITEM_TYPE FOREIGN KEY (TYPE_ID) REFERENCES T_COST_DICTIONARY_TYPE (ID)
);
CREATE INDEX IDX_DICT_ITEM_TYPE ON T_COST_DICTIONARY_ITEM (TYPE_ID);

-- ============================================================
-- 6. Lookup 配置
-- ============================================================

CREATE TABLE T_COST_LOOKUP_CONFIG (
  ID              NUMBER(19) NOT NULL,
  LOOKUP_CODE     VARCHAR2(64) NOT NULL,
  LOOKUP_NAME     VARCHAR2(128) NOT NULL,
  DATA_SOURCE     VARCHAR2(200) NOT NULL,
  DISPLAY_COLUMNS CLOB,
  VALUE_FIELD     VARCHAR2(64) NOT NULL,
  LABEL_FIELD     VARCHAR2(64) NOT NULL,
  DELETED         NUMBER(1) DEFAULT 0,
  CREATE_TIME     TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME     TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY       VARCHAR2(64),
  UPDATE_BY       VARCHAR2(64),
  CONSTRAINT PK_COST_LOOKUP_CONFIG PRIMARY KEY (ID),
  CONSTRAINT UK_LOOKUP_CODE UNIQUE (LOOKUP_CODE)
);

-- ============================================================
-- 7. 导出配置
-- ============================================================

CREATE TABLE T_COST_EXPORT_CONFIG (
  ID                 NUMBER(19) NOT NULL,
  EXPORT_CODE        VARCHAR2(100) NOT NULL,
  EXPORT_NAME        VARCHAR2(200) NOT NULL,
  PAGE_CODE          VARCHAR2(100) NOT NULL,
  MASTER_SQL         CLOB NOT NULL,
  MASTER_TABLE_ALIAS VARCHAR2(50),
  PK_COLUMN          VARCHAR2(100),
  PAGE_VIEW_ALIAS    VARCHAR2(50) DEFAULT 'p',
  PAGE_FK_COLUMN     VARCHAR2(100),
  MASTER_LINK_COLUMN VARCHAR2(100),
  COLUMNS            CLOB,
  MASTER_SHEET_NAME  VARCHAR2(100) DEFAULT 'master',
  DISPLAY_ORDER      NUMBER(5) DEFAULT 0,
  DELETED            NUMBER(1) DEFAULT 0,
  CREATE_BY          VARCHAR2(64),
  CREATE_TIME        TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_BY          VARCHAR2(64),
  UPDATE_TIME        TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_COST_EXPORT_CONFIG PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_EXPORT_CONFIG_CODE ON T_COST_EXPORT_CONFIG (EXPORT_CODE);
CREATE INDEX IDX_EXPORT_CONFIG_PAGE ON T_COST_EXPORT_CONFIG (PAGE_CODE);

CREATE TABLE T_COST_EXPORT_CONFIG_DETAIL (
  ID                 NUMBER(19) NOT NULL,
  EXPORT_CONFIG_ID   NUMBER(19) NOT NULL,
  TAB_KEY            VARCHAR2(100),
  SHEET_NAME         VARCHAR2(100),
  DETAIL_SQL         CLOB NOT NULL,
  MASTER_TABLE_ALIAS VARCHAR2(50),
  DETAIL_TABLE_ALIAS VARCHAR2(50),
  DETAIL_LINK_COLUMN VARCHAR2(100),
  COLUMNS            CLOB,
  DISPLAY_ORDER      NUMBER(5) DEFAULT 0,
  CONSTRAINT PK_COST_EXPORT_DTL PRIMARY KEY (ID),
  CONSTRAINT FK_EXPORT_DTL_CONFIG FOREIGN KEY (EXPORT_CONFIG_ID) REFERENCES T_COST_EXPORT_CONFIG (ID)
);
CREATE INDEX IDX_EXPORT_DTL_CONFIG ON T_COST_EXPORT_CONFIG_DETAIL (EXPORT_CONFIG_ID);


-- ============================================================
-- 8. 用户表格配置
-- ============================================================

CREATE TABLE T_COST_USER_GRID_CONFIG (
  ID          NUMBER(19) NOT NULL,
  USER_ID     NUMBER(19) NOT NULL,
  PAGE_CODE   VARCHAR2(64) NOT NULL,
  GRID_KEY    VARCHAR2(64) NOT NULL,
  CONFIG_DATA CLOB,
  DELETED     NUMBER(1) DEFAULT 0,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_COST_USER_GRID_CONFIG PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_USER_GRID_CONF ON T_COST_USER_GRID_CONFIG (USER_ID, PAGE_CODE, GRID_KEY);

-- ============================================================
-- 9. 产品信息
-- ============================================================

CREATE TABLE T_COST_GOODS (
  GOODSID       NUMBER(19) NOT NULL,
  GOODSNO       VARCHAR2(100),
  GOODSNAME     VARCHAR2(1000),
  PRICE         NUMBER,
  SUQTY         NUMBER,
  USEFLAG       VARCHAR2(100) DEFAULT '产成品',
  FACTORYNAME   VARCHAR2(1500),
  STANDARDTYPE  VARCHAR2(500),
  ZX_PL         NUMBER,
  ZX_MINIMUM    NUMBER,
  APPROVEDOCNO  VARCHAR2(500),
  BASEUNITQTY   NUMBER,
  ZX_CUSTOMERID NUMBER(19),
  TARGETMARKET  VARCHAR2(1000),
  HOLDERSNAME   VARCHAR2(1000),
  ISERP         NUMBER(1) DEFAULT 0,
  GOODSTYPE     VARCHAR2(500),
  PACKTYPE      VARCHAR2(500),
  BOMID         NUMBER(19),
  LASTSUQTY     NUMBER,
  TRANPOSID     NUMBER(19),
  DELETED       NUMBER(1) DEFAULT 0,
  CREATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY     VARCHAR2(320),
  UPDATE_BY     VARCHAR2(320),
  CONSTRAINT PK_COST_GOODS PRIMARY KEY (GOODSID)
);

CREATE TABLE T_COST_GOODS_PRICE (
  GOODSID     NUMBER(10) NOT NULL,
  GOODSNAME   VARCHAR2(300),
  PRICE       NUMBER,
  USEFLAG     VARCHAR2(15),
  GOODSTYPE   VARCHAR2(3000),
  PACKTYPE    VARCHAR2(600),
  FACTORYNAME VARCHAR2(300),
  DELETED     NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY   VARCHAR2(64),
  UPDATE_BY   VARCHAR2(64),
  ISERP       NUMBER(1) DEFAULT 0,
  CONSTRAINT PK_COST_GOODS_PRICE PRIMARY KEY (GOODSID)
);

-- ============================================================
-- 10. 客户/分销商
-- ============================================================

CREATE TABLE T_COST_CUSTOMER (
  CUSTOMID    NUMBER(19) NOT NULL,
  ZONE        VARCHAR2(500),
  CUSTOMNAME  VARCHAR2(500),
  ISERP       NUMBER(1) DEFAULT 0,
  DELETED     NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY   VARCHAR2(64),
  UPDATE_BY   VARCHAR2(64),
  CONSTRAINT PK_COST_CUSTOMER PRIMARY KEY (CUSTOMID)
);

CREATE TABLE T_COST_TRANPOSER (
  TRANPOSID   NUMBER(19) NOT NULL,
  CUSTOMID    NUMBER(19),
  TRANPOSNAME VARCHAR2(500),
  ISERP       NUMBER(1) DEFAULT 0,
  DELETED     NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY   VARCHAR2(64),
  UPDATE_BY   VARCHAR2(64),
  CONSTRAINT PK_COST_TRANPOSER PRIMARY KEY (TRANPOSID)
);

-- ============================================================
-- 11. 外币汇率
-- ============================================================

CREATE TABLE T_COST_FORMONEY (
  FMID        NUMBER(10) NOT NULL,
  FMOPCODE    VARCHAR2(60),
  FMNAME      VARCHAR2(120),
  FMSIGN      VARCHAR2(60),
  FMUNIT      VARCHAR2(60),
  FMRATE      NUMBER(16,6),
  USESTATUS   NUMBER(2),
  DELETED     NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY   VARCHAR2(64),
  UPDATE_BY   VARCHAR2(64),
  CONSTRAINT PK_COST_FORMONEY PRIMARY KEY (FMID)
);

-- ============================================================
-- 12. 物料成本核算表（固体）
-- ============================================================

CREATE TABLE T_COST_PINGGU (
  GOODSID       NUMBER,
  GOODSNAME     VARCHAR2(100),
  STRENGTH      VARCHAR2(50),
  MA_NO         VARCHAR2(30),
  APEX_PL       NUMBER,
  MAH           VARCHAR2(100),
  P_PERPACK     NUMBER,
  M_PERPACK     NUMBER,
  FORM          VARCHAR2(20),
  S_PERBACK     NUMBER,
  PACKTYPE      VARCHAR2(30),
  X_PERBACK     NUMBER,
  TOTAL_FL      NUMBER,
  TOTAL_BC      NUMBER,
  TOTAL_YL      NUMBER,
  MEMO          VARCHAR2(100),
  USESTATUS     VARCHAR2(100) DEFAULT 0,
  DOCID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  DOSAGE        VARCHAR2(20),
  ANNUAL_QTY    NUMBER,
  YIELD         NUMBER,
  TOTAL_COST    NUMBER,
  OUT_PRICE_F   NUMBER,
  OUT_PRICE_RMB NUMBER,
  SALEMONEY     NUMBER,
  JGF_BATCH     NUMBER,
  JGF_PERQP     NUMBER,
  COST_PERQP    NUMBER,
  ML_PERQP      NUMBER,
  Y_JG_RE       NUMBER,
  Y_ML          NUMBER,
  Y_SALE        NUMBER,
  CUSTOMID      NUMBER,
  CUSTOMNAME    VARCHAR2(50),
  COUNTRY       VARCHAR2(20),
  PROJECTNO     VARCHAR2(20),
  USEFLAG       NUMBER DEFAULT 0,
  YIELD_TIME    DATE DEFAULT SYSDATE,
  APEX_PL_TIME  DATE DEFAULT SYSDATE,
  FMNAME        VARCHAR2(100) DEFAULT '人民币',
  FMRATE        NUMBER DEFAULT 1,
  GOODSNAME_EN  VARCHAR2(2000),
  LIVERY        VARCHAR2(100),
  TRANPOSID     NUMBER,
  DELETED       NUMBER(1) DEFAULT 0,
  CREATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY     VARCHAR2(64),
  UPDATE_BY     VARCHAR2(64),
  COST_PERBOX   NUMBER,
  CONSTRAINT PK_COST_PINGGU PRIMARY KEY (DOCID)
);
COMMENT ON COLUMN T_COST_PINGGU.COST_PERBOX IS '每盒成本';

CREATE TABLE T_COST_PINGGU_DTL (
  DOCID        NUMBER(10) NOT NULL,
  GOODSID      NUMBER(10),
  PER_HL       NUMBER,
  EXADD_MATER  NUMBER,
  BATCH_QTY    NUMBER,
  PRICE        NUMBER,
  COST_BATCH   NUMBER,
  MEMO         VARCHAR2(100),
  DTLID        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  MODIFYDATE   DATE,
  BASE_PRICE   NUMBER,
  SUQTY        NUMBER,
  DELETED      NUMBER(1) DEFAULT 0,
  CREATE_TIME  TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME  TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY    VARCHAR2(64),
  UPDATE_BY    VARCHAR2(64),
  FACTORYID    NUMBER(10),
  CONSTRAINT PK_COST_PINGGU_DTL PRIMARY KEY (DTLID)
);

CREATE TABLE T_COST_PINGGU_HIS (
  GOODSID       NUMBER,
  GOODSNAME     VARCHAR2(100),
  STRENGTH      VARCHAR2(50),
  MA_NO         VARCHAR2(30),
  APEX_PL       NUMBER,
  MAH           VARCHAR2(100),
  P_PERPACK     NUMBER,
  M_PERPACK     NUMBER,
  FORM          VARCHAR2(20),
  S_PERBACK     NUMBER,
  PACKTYPE      VARCHAR2(30),
  X_PERBACK     NUMBER,
  TOTAL_FL      NUMBER,
  TOTAL_BC      NUMBER,
  TOTAL_YL      NUMBER,
  MEMO          VARCHAR2(100),
  USESTATUS     VARCHAR2(100),
  DOCID         NUMBER NOT NULL,
  DOSAGE        VARCHAR2(20),
  ANNUAL_QTY    NUMBER,
  YIELD         NUMBER,
  TOTAL_COST    NUMBER,
  OUT_PRICE_F   NUMBER,
  OUT_PRICE_RMB NUMBER,
  SALEMONEY     NUMBER,
  JGF_BATCH     NUMBER,
  JGF_PERQP     NUMBER,
  COST_PERQP    NUMBER,
  ML_PERQP      NUMBER,
  Y_JG_RE       NUMBER,
  Y_ML          NUMBER,
  Y_SALE        NUMBER,
  CUSTOMID      NUMBER,
  CUSTOMNAME    VARCHAR2(50),
  COUNTRY       VARCHAR2(20),
  PROJECTNO     VARCHAR2(20),
  USEFLAG       NUMBER,
  YIELD_TIME    DATE,
  APEX_PL_TIME  DATE,
  ZX_SOURCE     VARCHAR2(100),
  FMNAME        VARCHAR2(100),
  FMRATE        NUMBER,
  GOODSNAME_EN  VARCHAR2(2000),
  LIVERY        VARCHAR2(100),
  TRANPOSID     NUMBER,
  DELETED       NUMBER(1),
  CREATE_TIME   TIMESTAMP(6),
  UPDATE_TIME   TIMESTAMP(6),
  CREATE_BY     VARCHAR2(64),
  UPDATE_BY     VARCHAR2(64),
  BACKUP_TIME   DATE,
  COST_PERBOX   NUMBER
);
CREATE UNIQUE INDEX UK_PINGGU_HIS ON T_COST_PINGGU_HIS (DOCID, BACKUP_TIME);

CREATE TABLE T_COST_PINGGU_DTL_HIS (
  DOCID        NUMBER(10) NOT NULL,
  GOODSID      NUMBER(10),
  PER_HL       NUMBER,
  EXADD_MATER  NUMBER,
  BATCH_QTY    NUMBER,
  PRICE        NUMBER,
  COST_BATCH   NUMBER,
  MEMO         VARCHAR2(100),
  DTLID        NUMBER(10) NOT NULL,
  MODIFYDATE   DATE,
  BASE_PRICE   NUMBER,
  SUQTY        NUMBER,
  DELETED      NUMBER(1),
  CREATE_TIME  TIMESTAMP(6),
  UPDATE_TIME  TIMESTAMP(6),
  CREATE_BY    VARCHAR2(64),
  UPDATE_BY    VARCHAR2(64),
  BACKUP_TIME  DATE,
  FACTORYID    NUMBER(10)
);
CREATE UNIQUE INDEX UK_PINGGU_DTL_HIS ON T_COST_PINGGU_DTL_HIS (DTLID, BACKUP_TIME);

-- ============================================================
-- 13. 审计日志
-- ============================================================

CREATE TABLE T_COST_AUDIT_LOG (
  ID             NUMBER(19) NOT NULL,
  USER_NAME      VARCHAR2(100),
  OPERATION_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  PAGE_CODE      VARCHAR2(100),
  TABLE_CODE     VARCHAR2(100),
  TABLE_NAME     VARCHAR2(200),
  RECORD_ID      NUMBER(19),
  OPERATION_TYPE VARCHAR2(20),
  FIELD_CHANGES  CLOB,
  CREATE_TIME    TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_COST_AUDIT_LOG PRIMARY KEY (ID)
);

-- ============================================================
-- 14. 操作日志
-- ============================================================

CREATE TABLE T_COST_OPERATION_LOG (
  ID              NUMBER(19) NOT NULL,
  USER_ID         NUMBER(19),
  USER_NAME       VARCHAR2(64),
  OPERATION_TYPE  VARCHAR2(32) NOT NULL,
  TABLE_CODE      VARCHAR2(64),
  RECORD_ID       NUMBER(19),
  RECORD_DESC     VARCHAR2(256),
  TOTAL_SQL_COUNT NUMBER(10) DEFAULT 0,
  TOTAL_COST_MS   NUMBER(10) DEFAULT 0,
  STATUS          VARCHAR2(16) DEFAULT 'SUCCESS',
  ERROR_MSG       VARCHAR2(1000),
  CREATE_TIME     TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_COST_OPERATION_LOG PRIMARY KEY (ID)
);
CREATE INDEX IDX_OPERATION_LOG_USER ON T_COST_OPERATION_LOG (USER_ID);
CREATE INDEX IDX_OPERATION_LOG_TIME ON T_COST_OPERATION_LOG (CREATE_TIME);

CREATE TABLE T_COST_OPERATION_LOG_DETAIL (
  ID            NUMBER(19) NOT NULL,
  LOG_ID        NUMBER(19) NOT NULL,
  SEQ_NO        NUMBER(5) NOT NULL,
  SQL_TYPE      VARCHAR2(16),
  SQL_TEXT      CLOB,
  COST_MS       NUMBER(10) DEFAULT 0,
  AFFECTED_ROWS NUMBER(10),
  STATUS        VARCHAR2(16) DEFAULT 'SUCCESS',
  ERROR_MSG     VARCHAR2(1000),
  CREATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_COST_OP_LOG_DETAIL PRIMARY KEY (ID),
  CONSTRAINT FK_LOG_DETAIL_LOG FOREIGN KEY (LOG_ID) REFERENCES T_COST_OPERATION_LOG (ID)
);

-- ============================================================
-- 15. 成品发运单（WMS）
-- ============================================================

CREATE TABLE T_WMS_QTY (
  ID          NUMBER(19) NOT NULL,
  CONID       NUMBER(19),
  GOODSID     NUMBER(19),
  GOODSGP     VARCHAR2(500),
  LOTNO       VARCHAR2(100),
  GOODSNO     VARCHAR2(100),
  PACKSIZE    NUMBER(18,6),
  QTY_SHOW    VARCHAR2(500),
  PCS         NUMBER,
  DELETED     NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY   VARCHAR2(64),
  UPDATE_BY   VARCHAR2(64),
  TRANPOSNAME VARCHAR2(500),
  CONSTRAINT PK_T_WMS_QTY PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_WMS_QTY ON T_WMS_QTY (CONID, GOODSID, LOTNO);

CREATE TABLE T_WMS_QTY_DETAIL (
  ID          NUMBER(19) NOT NULL,
  RN          NUMBER(10),
  CONID       NUMBER(19),
  GOODSID     NUMBER(19),
  GOODSNAME   VARCHAR2(500),
  LOTNO       VARCHAR2(100),
  GOODSQTY    NUMBER(18,6),
  PCS         NUMBER,
  VALIDDATE   DATE,
  CONTAINERNO VARCHAR2(100),
  JZ          NUMBER(18,6),
  MZ          NUMBER(18,6),
  TJ          NUMBER(18,6),
  DELETED     NUMBER(1) DEFAULT 0,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY   VARCHAR2(64),
  UPDATE_BY   VARCHAR2(64),
  MEMO        VARCHAR2(500),
  CONSTRAINT PK_T_WMS_QTY_DETAIL PRIMARY KEY (ID)
);
CREATE INDEX IDX_WMS_QTY_DETAIL_CONID ON T_WMS_QTY_DETAIL (CONID);
CREATE UNIQUE INDEX UK_WMS_QTY_DETAIL ON T_WMS_QTY_DETAIL (CONID, RN);


-- ============================================================
-- 16. 物料成本核算表（液体）
-- ============================================================

CREATE TABLE T_COST_PINGGU_LQ (
  GOODSID       NUMBER,
  GOODSNAME     VARCHAR2(100),
  STRENGTH      VARCHAR2(50),
  MA_NO         VARCHAR2(30),
  APEX_PL       NUMBER,
  MAH           VARCHAR2(100),
  P_PERPACK     NUMBER,
  M_PERPACK     NUMBER,
  FORM          VARCHAR2(20),
  S_PERBACK     NUMBER,
  PACKTYPE      VARCHAR2(30),
  X_PERBACK     NUMBER,
  TOTAL_FL      NUMBER,
  TOTAL_BC      NUMBER,
  TOTAL_YL      NUMBER,
  MEMO          VARCHAR2(100),
  USESTATUS     VARCHAR2(100) DEFAULT 0,
  DOCID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  DOSAGE        VARCHAR2(20),
  ANNUAL_QTY    NUMBER,
  YIELD         NUMBER,
  TOTAL_COST    NUMBER,
  OUT_PRICE_F   NUMBER,
  OUT_PRICE_RMB NUMBER,
  SALEMONEY     NUMBER,
  JGF_BATCH     NUMBER,
  JGF_PERQP     NUMBER,
  COST_PERQP    NUMBER,
  ML_PERQP      NUMBER,
  Y_JG_RE       NUMBER,
  Y_ML          NUMBER,
  Y_SALE        NUMBER,
  CUSTOMID      NUMBER,
  CUSTOMNAME    VARCHAR2(50),
  COUNTRY       VARCHAR2(20),
  PROJECTNO     VARCHAR2(20),
  USEFLAG       NUMBER DEFAULT 0,
  YIELD_TIME    DATE DEFAULT SYSDATE,
  APEX_PL_TIME  DATE DEFAULT SYSDATE,
  FMNAME        VARCHAR2(100) DEFAULT '人民币',
  FMRATE        NUMBER DEFAULT 1,
  GOODSNAME_EN  VARCHAR2(2000),
  LIVERY        VARCHAR2(100),
  TRANPOSID     NUMBER,
  DELETED       NUMBER(1) DEFAULT 0,
  CREATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY     VARCHAR2(64),
  UPDATE_BY     VARCHAR2(64),
  COST_PERBOX   NUMBER,
  CONSTRAINT PK_COST_PINGGU_LQ PRIMARY KEY (DOCID)
);
COMMENT ON COLUMN T_COST_PINGGU_LQ.COST_PERBOX IS '每盒成本';

CREATE TABLE T_COST_PINGGU_DTL_LQ (
  DOCID        NUMBER(10) NOT NULL,
  GOODSID      NUMBER(10),
  GOODSNAME    VARCHAR2(500),
  DTL_USEFLAG  VARCHAR2(100),
  STANDARDTYPE VARCHAR2(100),
  PER_HL       NUMBER,
  EXADD_MATER  NUMBER,
  BATCH_QTY    NUMBER,
  PRICE        NUMBER,
  COST_BATCH   NUMBER,
  MEMO         VARCHAR2(100),
  DTLID        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  FACTORYNAME  VARCHAR2(200),
  FACTORYID    NUMBER(10),
  MODIFYDATE   DATE,
  BASE_PRICE   NUMBER,
  SUQTY        NUMBER,
  GOODSTYPE    VARCHAR2(4000),
  GOODSNAME_EN VARCHAR2(2000),
  DELETED      NUMBER(1) DEFAULT 0,
  CREATE_TIME  TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  UPDATE_TIME  TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  CREATE_BY    VARCHAR2(64),
  UPDATE_BY    VARCHAR2(64),
  CONSTRAINT PK_COST_PINGGU_DTL_LQ PRIMARY KEY (DTLID)
);

CREATE TABLE T_COST_PINGGU_HIS_LQ (
  GOODSID       NUMBER,
  GOODSNAME     VARCHAR2(100),
  STRENGTH      VARCHAR2(50),
  MA_NO         VARCHAR2(30),
  APEX_PL       NUMBER,
  MAH           VARCHAR2(100),
  P_PERPACK     NUMBER,
  M_PERPACK     NUMBER,
  FORM          VARCHAR2(20),
  S_PERBACK     NUMBER,
  PACKTYPE      VARCHAR2(30),
  X_PERBACK     NUMBER,
  TOTAL_FL      NUMBER,
  TOTAL_BC      NUMBER,
  TOTAL_YL      NUMBER,
  MEMO          VARCHAR2(100),
  USESTATUS     VARCHAR2(100),
  DOCID         NUMBER NOT NULL,
  DOSAGE        VARCHAR2(20),
  ANNUAL_QTY    NUMBER,
  YIELD         NUMBER,
  TOTAL_COST    NUMBER,
  OUT_PRICE_F   NUMBER,
  OUT_PRICE_RMB NUMBER,
  SALEMONEY     NUMBER,
  JGF_BATCH     NUMBER,
  JGF_PERQP     NUMBER,
  COST_PERQP    NUMBER,
  ML_PERQP      NUMBER,
  Y_JG_RE       NUMBER,
  Y_ML          NUMBER,
  Y_SALE        NUMBER,
  CUSTOMID      NUMBER,
  CUSTOMNAME    VARCHAR2(50),
  COUNTRY       VARCHAR2(20),
  PROJECTNO     VARCHAR2(20),
  USEFLAG       NUMBER,
  YIELD_TIME    DATE,
  APEX_PL_TIME  DATE,
  ZX_SOURCE     VARCHAR2(100),
  FMNAME        VARCHAR2(100),
  FMRATE        NUMBER,
  GOODSNAME_EN  VARCHAR2(2000),
  LIVERY        VARCHAR2(100),
  TRANPOSID     NUMBER,
  DELETED       NUMBER(1),
  CREATE_TIME   TIMESTAMP(6),
  UPDATE_TIME   TIMESTAMP(6),
  CREATE_BY     VARCHAR2(64),
  UPDATE_BY     VARCHAR2(64),
  BACKUP_TIME   DATE,
  COST_PERBOX   NUMBER
);
CREATE UNIQUE INDEX UK_PINGGU_HIS_LQ ON T_COST_PINGGU_HIS_LQ (DOCID, BACKUP_TIME);

CREATE TABLE T_COST_PINGGU_DTL_HIS_LQ (
  DOCID        NUMBER(10) NOT NULL,
  GOODSID      NUMBER(10),
  GOODSNAME    VARCHAR2(500),
  DTL_USEFLAG  VARCHAR2(100),
  STANDARDTYPE VARCHAR2(100),
  PER_HL       NUMBER,
  EXADD_MATER  NUMBER,
  BATCH_QTY    NUMBER,
  PRICE        NUMBER,
  COST_BATCH   NUMBER,
  MEMO         VARCHAR2(100),
  DTLID        NUMBER(10) NOT NULL,
  FACTORYNAME  VARCHAR2(200),
  FACTORYID    NUMBER(10),
  MODIFYDATE   DATE,
  BASE_PRICE   NUMBER,
  SUQTY        NUMBER,
  GOODSTYPE    VARCHAR2(4000),
  GOODSNAME_EN VARCHAR2(2000),
  DELETED      NUMBER(1),
  CREATE_TIME  TIMESTAMP(6),
  UPDATE_TIME  TIMESTAMP(6),
  CREATE_BY    VARCHAR2(64),
  UPDATE_BY    VARCHAR2(64),
  BACKUP_TIME  DATE
);
CREATE UNIQUE INDEX UK_PINGGU_DTL_HIS_LQ ON T_COST_PINGGU_DTL_HIS_LQ (DTLID, BACKUP_TIME);
