-- ============================================================
-- 序列定义
-- 成本管理系统所有序列
-- ============================================================

-- 审计日志序列
CREATE SEQUENCE SEQ_COST_AUDIT_LOG START WITH 1 INCREMENT BY 1 CACHE 20;

-- 列元数据序列
CREATE SEQUENCE SEQ_COST_COLUMN_METADATA START WITH 1 INCREMENT BY 1 CACHE 20;

-- 客户序列
CREATE SEQUENCE SEQ_COST_CUSTOMER START WITH 1 INCREMENT BY 1 CACHE 20;

-- 部门序列
CREATE SEQUENCE SEQ_COST_DEPARTMENT START WITH 1 INCREMENT BY 1 CACHE 20;

-- 字典项序列
CREATE SEQUENCE SEQ_COST_DICT_ITEM START WITH 1 INCREMENT BY 1 CACHE 20;

-- 字典类型序列
CREATE SEQUENCE SEQ_COST_DICT_TYPE START WITH 1 INCREMENT BY 1 CACHE 20;

-- 导出配置序列
CREATE SEQUENCE SEQ_COST_EXPORT_CONFIG START WITH 1 INCREMENT BY 1 CACHE 20;

-- 导出配置明细序列
CREATE SEQUENCE SEQ_COST_EXPORT_CONFIG_DTL START WITH 1 INCREMENT BY 1 CACHE 20;

-- 外币序列
CREATE SEQUENCE SEQ_COST_FORMONEY START WITH 1 INCREMENT BY 1 CACHE 20;

-- 产品序列
CREATE SEQUENCE SEQ_COST_GOODS START WITH 1 INCREMENT BY 1 CACHE 20;

-- 物料价格序列
CREATE SEQUENCE SEQ_COST_GOODS_PRICE START WITH 1 INCREMENT BY 1 CACHE 20;

-- Lookup配置序列
CREATE SEQUENCE SEQ_COST_LOOKUP_CONFIG START WITH 1 INCREMENT BY 1 CACHE 20;

-- 操作日志序列
CREATE SEQUENCE SEQ_COST_OPERATION_LOG START WITH 1 INCREMENT BY 1 CACHE 20;

-- 操作日志明细序列
CREATE SEQUENCE SEQ_COST_OPERATION_LOG_DETAIL START WITH 1 INCREMENT BY 1 CACHE 20;

-- 页面组件序列
CREATE SEQUENCE SEQ_COST_PAGE_COMPONENT START WITH 1 INCREMENT BY 1 CACHE 20;

-- 页面规则序列
CREATE SEQUENCE SEQ_COST_PAGE_RULE START WITH 1 INCREMENT BY 1 CACHE 20;

-- 成本核算主表序列
CREATE SEQUENCE SEQ_COST_PINGGU START WITH 100000 INCREMENT BY 1 CACHE 20;

-- 成本核算明细序列
CREATE SEQUENCE SEQ_COST_PINGGU_DTL START WITH 100000 INCREMENT BY 1 CACHE 20;

-- 资源序列
CREATE SEQUENCE SEQ_COST_RESOURCE START WITH 1 INCREMENT BY 1 CACHE 20;

-- 角色序列
CREATE SEQUENCE SEQ_COST_ROLE START WITH 1 INCREMENT BY 1 CACHE 20;

-- 角色页面权限序列
CREATE SEQUENCE SEQ_COST_ROLE_PAGE START WITH 1 INCREMENT BY 1 CACHE 20;

-- 表元数据序列
CREATE SEQUENCE SEQ_COST_TABLE_METADATA START WITH 1 INCREMENT BY 1 CACHE 20;

-- 分销商序列
CREATE SEQUENCE SEQ_COST_TRANPOSER START WITH 1 INCREMENT BY 1 CACHE 20;

-- 用户序列
CREATE SEQUENCE SEQ_COST_USER START WITH 1 INCREMENT BY 1 CACHE 20;

-- 用户表格配置序列
CREATE SEQUENCE SEQ_COST_USER_GRID START WITH 1 INCREMENT BY 1 CACHE 20;

-- 用户角色关联序列
CREATE SEQUENCE SEQ_COST_USER_ROLE START WITH 1 INCREMENT BY 1 CACHE 20;

-- WMS发运单序列
CREATE SEQUENCE SEQ_WMS_CON_DOC START WITH 1 INCREMENT BY 1 CACHE 20;

-- WMS库存汇总序列
CREATE SEQUENCE SEQ_WMS_QTY START WITH 1 INCREMENT BY 1 CACHE 20;

-- WMS库存明细序列
CREATE SEQUENCE SEQ_WMS_QTY_DETAIL START WITH 1 INCREMENT BY 1 CACHE 20;

-- WMS库存明细(备用)序列
CREATE SEQUENCE SEQ_WMS_QTY_DTL START WITH 1 INCREMENT BY 1 CACHE 20;
