

-- ============================================================
-- 5. 表元数据
-- ============================================================
INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostPingguLq', '物料成本核算表_液体', 'T_COST_PINGGU_LQ', 'T_COST_PINGGU_LQ', 'SEQ_COST_PINGGU_LQ', 'DOCID', NULL, NULL, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostMaterialLq', '原辅料明细_液体', 'V_COST_PINGGU_MATERIAL_LQ', 'T_COST_PINGGU_DTL_LQ', 'SEQ_COST_PINGGU_DTL_LQ', 'DTLID', 'CostPingguLq', 'DOCID', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostPackageLq', '包材明细_液体', 'V_COST_PINGGU_PACKAGE_LQ', 'T_COST_PINGGU_DTL_LQ', 'SEQ_COST_PINGGU_DTL_LQ', 'DTLID', 'CostPingguLq', 'DOCID', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 6. 列元数据 - CostPingguLq (主表)
-- ============================================================
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'DOCID', 'ID', 'number', 0, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'GOODSID', '产品ID', 'number', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'GOODSNAME', '产品名称', 'text', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'GOODSNAME_EN', '产品英文名', 'text', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'STRENGTH', '剂量', 'text', 3, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'CUSTOMID', '客户ID', 'number', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'CUSTOMNAME', '客户名称', 'text', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'COUNTRY', '国家', 'text', 5, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'PROJECTNO', '项目号', 'text', 6, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'APEX_PL', '批量', 'number', 7, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'ANNUAL_QTY', '年需求量', 'number', 8, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'YIELD', '收率(%)', 'number', 9, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'P_PERPACK', '每盒片数', 'number', 10, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'M_PERPACK', '中盒装盒数', 'number', 11, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'S_PERBACK', '每箱装盒数', 'number', 12, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'X_PERBACK', '每托盘箱数', 'number', 13, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'PACKTYPE', '包装形式', 'text', 14, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'TOTAL_YL', '原料合计', 'number', 20, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'TOTAL_FL', '辅料合计', 'number', 21, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'TOTAL_BC', '包材合计', 'number', 22, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'TOTAL_COST', '总物料成本', 'number', 23, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'OUT_PRICE_RMB', '出厂价(RMB)', 'number', 24, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'SALEMONEY', '每批销售额', 'number', 25, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'JGF_BATCH', '每批加工费', 'number', 26, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'COST_PERQP', '千片成本', 'number', 27, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'COST_PERBOX', '每盒成本', 'number', 28, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'JGF_PERQP', '千片加工费', 'number', 28, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'ML_PERQP', '千片毛利', 'number', 29, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'Y_JG_RE', '年加工费', 'number', 30, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'Y_ML', '年毛利', 'number', 31, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'Y_SALE', '年销售额', 'number', 32, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'FMNAME', '币种', 'text', 33, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'FMRATE', '汇率', 'number', 34, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'MEMO', '备注', 'text', 35, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'LIVERY', '分销商', 'text', 36, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'TRANPOSID', '分销商ID', 'number', 37, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 7. 列元数据 - CostMaterialLq (原辅料明细)
-- ============================================================
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'DTLID', 'DTLID', 'ID', 'number', 0, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'DOCID', 'DOCID', 'DOCID', '主表ID', 'number', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'GOODSID', '物料ID', 'number', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'DTL_USEFLAG', '分类', 'text', 3, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'GOODSNAME', '物料名称', 'text', 4, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'STANDARDTYPE', '规格', 'text', 5, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'PER_HL', '每片含量', 'number', 6, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'EXADD_MATER', '额外投料量', 'number', 7, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'PRICE', '单价', 'number', 8, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'BATCH_QTY', '每批数量', 'number', 9, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'COST_BATCH', '每批成本', 'number', 10, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'FACTORYNAME', '供应商', 'text', 11, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'GOODSTYPE', '物料分类', 'text', 12, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'BASE_PRICE', '参考采购价', 'number', 13, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 8. 列元数据 - CostPackageLq (包材明细)
-- ============================================================
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'DTLID', 'DTLID', 'ID', 'number', 0, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'DOCID', 'DOCID', 'DOCID', '主表ID', 'number', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'GOODSID', '物料ID', 'number', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'DTL_USEFLAG', '包材类型', 'text', 3, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'GOODSNAME', '包材名称', 'text', 4, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'SPEC', '规格型号', 'text', 5, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'SUQTY', '用量', 'number', 6, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'PRICE', '包材单价', 'number', 7, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'BATCH_QTY', '每批数量', 'number', 8, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'COST_BATCH', '包材成本', 'number', 9, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'FACTORYNAME', '包材供应商', 'text', 10, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'GOODSTYPE', '包材分类', 'text', 11, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'BASE_PRICE', '参考采购价', 'number', 12, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 9. 页面组件
-- ============================================================
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu-lq', 'root', 'LAYOUT', NULL, '{"direction":"vertical","gap":8}', NULL, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'GRID', 'root', '{"height":"50%","selectionMode":"single","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"generateFromBom","label":"由BOM生成明细","requiresRow":true,"procedure":"P_COST_BOM_INSERT_LQ","params":[{"source":"data.DOCID","mode":"IN","jdbcType":"NUMERIC"}]},{"action":"syncPrice","label":"同步采购价","procedure":"P_PINGGU_COMPUTE_ALL_LQ","params":[]},{"action":"saveGridConfig","label":"保存列配置"},{"action":"save","label":"保存"}]}', 'CostPingguLq', 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'TABS', 'root', '{"mode":"multi","tabs":[{"key":"material","title":"原料/辅料","tableCode":"CostMaterialLq","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]},{"key":"package","title":"包材","tableCode":"CostPackageLq","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}]}', NULL, 2, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 10. 页面规则 - masterGrid
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'COLUMN_OVERRIDE', '[{"columnName":"DOCID","visible":true,"editable":false},{"columnName":"GOODSID","visible":true,"editable":false},{"columnName":"GOODSNAME","visible":true,"editable":true,"searchable":true},{"columnName":"GOODSNAME_EN","visible":true,"editable":true},{"columnName":"STRENGTH","visible":true,"editable":true},{"columnName":"CUSTOMID","visible":true,"editable":false},{"columnName":"CUSTOMNAME","visible":true,"editable":true,"searchable":true},{"columnName":"COUNTRY","visible":true,"editable":true},{"columnName":"TRANPOSID","visible":true,"editable":false},{"columnName":"LIVERY","visible":true,"editable":true},{"columnName":"PROJECTNO","visible":true,"editable":true},{"columnName":"APEX_PL","visible":true,"editable":true},{"columnName":"ANNUAL_QTY","visible":true,"editable":true},{"columnName":"YIELD","visible":true,"editable":true},{"columnName":"P_PERPACK","visible":true,"editable":true},{"columnName":"M_PERPACK","visible":true,"editable":true},{"columnName":"S_PERBACK","visible":true,"editable":true},{"columnName":"X_PERBACK","visible":true,"editable":true},{"columnName":"PACKTYPE","visible":true,"editable":true},{"columnName":"TOTAL_YL","visible":true,"editable":false},{"columnName":"TOTAL_FL","visible":true,"editable":false},{"columnName":"TOTAL_BC","visible":true,"editable":false},{"columnName":"TOTAL_COST","visible":true,"editable":false},{"columnName":"OUT_PRICE_RMB","visible":true,"editable":true},{"columnName":"SALEMONEY","visible":true,"editable":false},{"columnName":"JGF_BATCH","visible":true,"editable":false},{"columnName":"COST_PERQP","visible":true,"editable":true},{"columnName":"COST_PERBOX","visible":true,"editable":false},{"columnName":"JGF_PERQP","visible":true,"editable":false},{"columnName":"ML_PERQP","visible":true,"editable":false},{"columnName":"Y_JG_RE","visible":true,"editable":false},{"columnName":"Y_ML","visible":true,"editable":false},{"columnName":"Y_SALE","visible":true,"editable":false},{"columnName":"FMNAME","visible":true,"editable":true},{"columnName":"FMRATE","visible":true,"editable":true},{"columnName":"MEMO","visible":true,"editable":true}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'VALIDATION', '[]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'CALC', '[
  {"field":"SALEMONEY","expression":"CostPingguLq.OUT_PRICE_RMB * CostPingguLq.APEX_PL * (CostPingguLq.YIELD / 100)","triggerFields":["CostPingguLq.OUT_PRICE_RMB","CostPingguLq.APEX_PL","CostPingguLq.YIELD"]},
  {"field":"JGF_BATCH","expression":"CostPingguLq.SALEMONEY - CostPingguLq.TOTAL_COST","triggerFields":["CostPingguLq.SALEMONEY","CostPingguLq.TOTAL_COST"]},
  {"field":"COST_PERBOX","expression":"CostPingguLq.TOTAL_COST / CostPingguLq.APEX_PL","triggerFields":["CostPingguLq.TOTAL_COST","CostPingguLq.APEX_PL"]},
  {"field":"JGF_PERQP","expression":"CostPingguLq.JGF_BATCH / CostPingguLq.APEX_PL","triggerFields":["CostPingguLq.JGF_BATCH","CostPingguLq.APEX_PL"]},
  {"field":"ML_PERQP","expression":"CostPingguLq.JGF_PERQP - CostPingguLq.COST_PERQP","triggerFields":["CostPingguLq.JGF_PERQP","CostPingguLq.COST_PERQP"]},
  {"field":"Y_JG_RE","expression":"CostPingguLq.JGF_PERQP * CostPingguLq.ANNUAL_QTY","triggerFields":["CostPingguLq.JGF_PERQP","CostPingguLq.ANNUAL_QTY"]},
  {"field":"Y_ML","expression":"CostPingguLq.ML_PERQP * CostPingguLq.ANNUAL_QTY","triggerFields":["CostPingguLq.ML_PERQP","CostPingguLq.ANNUAL_QTY"]},
  {"field":"Y_SALE","expression":"CostPingguLq.ANNUAL_QTY * CostPingguLq.OUT_PRICE_RMB * CostPingguLq.YIELD","triggerFields":["CostPingguLq.ANNUAL_QTY","CostPingguLq.OUT_PRICE_RMB","CostPingguLq.YIELD"]},
  {"field":"TOTAL_YL","expression":"SUM_IF(''CostMaterialLq.COST_BATCH'', \"DTL_USEFLAG == ''原料''\") * (SUM_IF(''CostMaterialLq.COST_BATCH'', \"DTL_USEFLAG == ''原料''\") > 0 ? 1 / 1.13 : 1)","triggerFields":["CostMaterialLq.COST_BATCH","CostMaterialLq.DTL_USEFLAG"],"order":8},
  {"field":"TOTAL_FL","expression":"SUM_IF(''CostMaterialLq.COST_BATCH'', \"DTL_USEFLAG == ''辅料''\") * (SUM_IF(''CostMaterialLq.COST_BATCH'', \"DTL_USEFLAG == ''原料''\") > 0 ? 1 / 1.13 : 1)","triggerFields":["CostMaterialLq.COST_BATCH","CostMaterialLq.DTL_USEFLAG"],"order":9},
  {"field":"TOTAL_BC","expression":"SUM_IF(''CostPackageLq.COST_BATCH'', \"DTL_USEFLAG == ''印字包材'' || DTL_USEFLAG == ''非印字包材''\") * (SUM_IF(''CostMaterialLq.COST_BATCH'', \"DTL_USEFLAG == ''原料''\") > 0 ? 1 / 1.13 : 1)","triggerFields":["CostPackageLq.COST_BATCH","CostPackageLq.DTL_USEFLAG","CostMaterialLq.COST_BATCH","CostMaterialLq.DTL_USEFLAG"],"order":10},
  {"field":"TOTAL_COST","expression":"CostPingguLq.TOTAL_YL + CostPingguLq.TOTAL_FL + CostPingguLq.TOTAL_BC","triggerFields":["CostPingguLq.TOTAL_YL","CostPingguLq.TOTAL_FL","CostPingguLq.TOTAL_BC"],"order":11}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'AGGREGATE', '[]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'LOOKUP', '[{"columnName":"GOODSNAME","lookupCode":"costGoods","mapping":{"GOODSID":"GOODSID","GOODSNAME":"GOODSNAME","MA_NO":"MA_NO","APEX_PL":"APEX_PL","MAH":"MAH","P_PERPACK":"P_PERPACK","M_PERPACK":"M_PERPACK","S_PERBACK":"S_PERBACK","CUSTOMID":"CUSTOMID","CUSTOMNAME":"CUSTOMNAME","MEMO":"MEMO","STRENGTH":"STRENGTH","LIVERY":"LIVERY","TRANPOSID":"TRANPOSID"}},{"columnName":"FMNAME","lookupCode":"formoney","mapping":{"FMNAME":"FMNAME","FMRATE":"FMRATE"}},{"columnName":"CUSTOMNAME","lookupCode":"costCustomer","mapping":{"CUSTOMID":"CUSTOMID","CUSTOMNAME":"CUSTOMNAME","COUNTRY":"COUNTRY","TRANPOSID":"TRANPOSID","LIVERY":"LIVERY"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'ROLE_BINDING', '{"role":"MASTER_GRID"}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'GRID_OPTIONS', '{"cellSelection":true,"sideBar":true}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'ROW_CLASS', '[{"field":"MEMO","operator":"eq","value":"ERP未搭建BOM","style":{"backgroundColor":"#ffcccc"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 11. 页面规则 - detailTabs
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'ROLE_BINDING', '{"role":"DETAIL_TABS"}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'RELATION', '{"masterKey":"masterGrid","detailKey":"detailTabs"}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'BROADCAST', '["APEX_PL","P_PERPACK","M_PERPACK","S_PERBACK","X_PERBACK"]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'SUMMARY_CONFIG', '{"enabled":true,"groupLabelField":"groupLabel","groupLabelHeader":"分类","summaryColumns":[{"field":"totalAmount","headerName":"汇总金额","width":null},{"field":"rowCount","headerName":"行数","width":null}],"summaryAggregates":[{"sourceField":"COST_BATCH","targetField":"totalAmount","algorithm":"SUM"},{"sourceField":"COST_BATCH","targetField":"rowCount","algorithm":"COUNT"}]}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 12. 页面规则 - material (原辅料明细)
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'COLUMN_OVERRIDE', '[{"columnName":"DTLID","visible":true,"editable":false},{"columnName":"DOCID","visible":true,"editable":false},{"columnName":"GOODSID","visible":true,"editable":false},{"columnName":"DTL_USEFLAG","visible":true,"editable":false},{"columnName":"GOODSNAME","visible":true,"editable":true},{"columnName":"STANDARDTYPE","visible":true,"editable":false},{"columnName":"PER_HL","visible":true,"editable":true},{"columnName":"EXADD_MATER","visible":true,"editable":true},{"columnName":"PRICE","visible":true,"editable":true},{"columnName":"BATCH_QTY","visible":true,"editable":false},{"columnName":"COST_BATCH","visible":true,"editable":false},{"columnName":"FACTORYNAME","visible":true,"editable":false},{"columnName":"BASE_PRICE","visible":true,"editable":false}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'VALIDATION', '[{"field":"PER_HL","required":true,"min":0.001,"message":"每片含量必填且必须大于0"},{"field":"PRICE","required":true,"min":0,"message":"单价必填且不能为负数"}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'CALC', '[
  {"field":"BATCH_QTY","expression":"CostMaterialLq.PER_HL * CostPingguLq.APEX_PL * (1 + CostMaterialLq.EXADD_MATER / 100) / 1000000","triggerFields":["CostMaterialLq.PER_HL","CostPingguLq.APEX_PL","CostMaterialLq.EXADD_MATER"]},
  {"field":"COST_BATCH","expression":"CostMaterialLq.BATCH_QTY * CostMaterialLq.PRICE","triggerFields":["CostMaterialLq.BATCH_QTY","CostMaterialLq.PRICE"]}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'LOOKUP', '[{"columnName":"GOODSNAME","lookupCode":"costMaterial","mapping":{"GOODSID":"GOODSID","GOODSNAME":"GOODSNAME","STANDARDTYPE":"GOODSTYPE","PRICE":"PRICE","FACTORYNAME":"FACTORYNAME","BASE_PRICE":"PRICE"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 13. 页面规则 - package (包材明细)
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'COLUMN_OVERRIDE', '[{"columnName":"DTLID","visible":true,"editable":false},{"columnName":"DOCID","visible":true,"editable":false},{"columnName":"GOODSID","visible":true,"editable":false},{"columnName":"DTL_USEFLAG","visible":true,"editable":false},{"columnName":"GOODSNAME","visible":true,"editable":true},{"columnName":"SPEC","visible":true,"editable":false},{"columnName":"SUQTY","visible":true,"editable":false},{"columnName":"PRICE","visible":true,"editable":true},{"columnName":"BATCH_QTY","visible":true,"editable":false},{"columnName":"COST_BATCH","visible":true,"editable":false},{"columnName":"FACTORYNAME","visible":true,"editable":false},{"columnName":"BASE_PRICE","visible":true,"editable":false}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'VALIDATION', '[{"field":"PRICE","min":0,"message":"包材单价不能为负数"}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'CALC', '[
  {"field":"COST_BATCH","expression":"CostPackageLq.BATCH_QTY * CostPackageLq.PRICE","triggerFields":["CostPackageLq.BATCH_QTY","CostPackageLq.PRICE"]},
  {"field":"BATCH_QTY","formulaField":"CostPackageLq.GOODSNAME","formulas":{"__branch_0":{"key":"桶|说明书|小盒|标签|瓶|盖注射器|适配器|量杯|勺|分度器","expression":"CostPingguLq.APEX_PL / CostPingguLq.P_PERPACK * (1 + CostPackageLq.EXADD_MATER / 100)","triggerFields":["CostPingguLq.APEX_PL","CostPingguLq.P_PERPACK","CostPackageLq.EXADD_MATER"],"matchType":"regex"},"__branch_1":{"key":"大纸箱","expression":"ceil(CostPingguLq.APEX_PL / (CostPingguLq.P_PERPACK * CostPingguLq.S_PERBACK) * (1 + CostPackageLq.EXADD_MATER / 100))","triggerFields":["CostPingguLq.APEX_PL","CostPingguLq.P_PERPACK","CostPingguLq.S_PERBACK","CostPackageLq.EXADD_MATER"],"matchType":"regex"},"__branch_2":{"key":"托盘","expression":"ceil(CostPingguLq.APEX_PL / (CostPingguLq.P_PERPACK * CostPingguLq.S_PERBACK * CostPingguLq.X_PERBACK) * (1 + CostPackageLq.EXADD_MATER / 100))","triggerFields":["CostPingguLq.APEX_PL","CostPingguLq.P_PERPACK","CostPingguLq.S_PERBACK","CostPingguLq.X_PERBACK","CostPackageLq.EXADD_MATER"],"matchType":"regex"}}}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'LOOKUP', '[{"columnName":"GOODSNAME","lookupCode":"costMaterial","mapping":{"GOODSID":"GOODSID","GOODSNAME":"GOODSNAME","SPEC":"GOODSTYPE","PRICE":"PRICE","FACTORYNAME":"FACTORYNAME","SUQTY":"LASTSUQTY"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 14. 菜单资源 + 角色权限
-- ============================================================
-- 菜单资源（放在"物料成本核算表"同级）
INSERT INTO T_COST_RESOURCE (ID, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, IS_HARDCODED)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, '物料成本核算表_液体', 'PAGE', 'cost-pinggu-lq', 'mdi:calculator-variant', '/cost/cost-pinggu-lq', NULL, 2, 0);

-- ADMIN角色授权
INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, ROW_POLICY)
VALUES (SEQ_COST_ROLE_PAGE.NEXTVAL, 3, 'cost-pinggu-lq', '["*"]', NULL, NULL);

-- ============================================================
-- 提交
-- ============================================================
COMMIT;
