-- ============================================================
-- 物料成本核算表_液体 一键部署脚本
-- 包含: 建表、序列、视图、存储过程、元数据
-- 共用: T_COST_BOM_GOODS_TREE_V, T_COST_GOODS_PRICE
-- ============================================================

-- ============================================================
-- 1. 建表
-- ============================================================

-- 主表
create table T_COST_PINGGU_LQ
(
  goodsid       NUMBER,
  goodsname     VARCHAR2(100),
  strength      VARCHAR2(50),
  ma_no         VARCHAR2(30),
  apex_pl       NUMBER,
  mah           VARCHAR2(100),
  p_perpack     NUMBER,
  form          VARCHAR2(20),
  s_perback     NUMBER,
  packtype      VARCHAR2(30),
  x_perback     NUMBER,
  total_fl      NUMBER,
  total_bc      NUMBER,
  total_yl      NUMBER,
  memo          VARCHAR2(100),
  usestatus     VARCHAR2(100) default 0,
  docid         NUMBER generated by default on null as identity,
  dosage        VARCHAR2(20),
  annual_qty    NUMBER,
  yield         NUMBER,
  total_cost    NUMBER,
  out_price_f   NUMBER,
  out_price_rmb NUMBER,
  salemoney     NUMBER,
  jgf_batch     NUMBER,
  jgf_perqp     NUMBER,
  cost_perqp    NUMBER,
  ml_perqp      NUMBER,
  y_jg_re       NUMBER,
  y_ml          NUMBER,
  y_sale        NUMBER,
  customid      NUMBER,
  customname    VARCHAR2(50),
  country       VARCHAR2(20),
  projectno     VARCHAR2(20),
  useflag       NUMBER default 0,
  yield_time    DATE default SYSDATE,
  apex_pl_time  DATE default SYSDATE,
  fmname        VARCHAR2(100) default '人民币',
  fmrate        NUMBER default 1,
  goodsname_en  VARCHAR2(2000),
  livery        VARCHAR2(100),
  deleted       NUMBER(1) default 0,
  create_time   TIMESTAMP(6) default SYSTIMESTAMP,
  update_time   TIMESTAMP(6) default SYSTIMESTAMP,
  create_by     VARCHAR2(64),
  update_by     VARCHAR2(64),
  cost_perbox   NUMBER
);
comment on column T_COST_PINGGU_LQ.cost_perbox is '每盒成本';
alter table T_COST_PINGGU_LQ add constraint PK_COST_PINGGU_LQ primary key (DOCID);

-- 明细表
create table T_COST_PINGGU_DTL_LQ
(
  docid            NUMBER(10) not null,
  apex_goodsid     NUMBER(10),
  apex_goodsname   VARCHAR2(500),
  dtl_useflag      VARCHAR2(100),
  spec             VARCHAR2(100),
  per_hl           NUMBER,
  exadd_mater      NUMBER,
  batch_qty        NUMBER,
  price            NUMBER,
  cost_batch       NUMBER,
  memo             VARCHAR2(100),
  dtlid            NUMBER(10) generated by default on null as identity,
  apex_factoryname VARCHAR2(200),
  apex_factoryid   NUMBER(10),
  modifydate       DATE,
  base_price       NUMBER,
  suqty            NUMBER,
  goodstype        VARCHAR2(4000),
  goodsname_en     VARCHAR2(2000),
  deleted          NUMBER(1) default 0,
  create_time      TIMESTAMP(6) default SYSTIMESTAMP,
  update_time      TIMESTAMP(6) default SYSTIMESTAMP,
  create_by        VARCHAR2(64),
  update_by        VARCHAR2(64)
);
alter table T_COST_PINGGU_DTL_LQ add constraint PK_COST_PINGGU_DTL_LQ primary key (DTLID);

-- 主表历史备份
create table T_COST_PINGGU_HIS_LQ
(
  goodsid       NUMBER,
  goodsname     VARCHAR2(100),
  strength      VARCHAR2(50),
  ma_no         VARCHAR2(30),
  apex_pl       NUMBER,
  mah           VARCHAR2(100),
  p_perpack     NUMBER,
  form          VARCHAR2(20),
  s_perback     NUMBER,
  packtype      VARCHAR2(30),
  x_perback     NUMBER,
  total_fl      NUMBER,
  total_bc      NUMBER,
  total_yl      NUMBER,
  memo          VARCHAR2(100),
  usestatus     VARCHAR2(100),
  docid         NUMBER not null,
  dosage        VARCHAR2(20),
  annual_qty    NUMBER,
  yield         NUMBER,
  total_cost    NUMBER,
  out_price_f   NUMBER,
  out_price_rmb NUMBER,
  salemoney     NUMBER,
  jgf_batch     NUMBER,
  jgf_perqp     NUMBER,
  cost_perqp    NUMBER,
  ml_perqp      NUMBER,
  y_jg_re       NUMBER,
  y_ml          NUMBER,
  y_sale        NUMBER,
  customid      NUMBER,
  customname    VARCHAR2(50),
  country       VARCHAR2(20),
  projectno     VARCHAR2(20),
  useflag       NUMBER,
  yield_time    DATE,
  apex_pl_time  DATE,
  zx_source     VARCHAR2(100),
  fmname        VARCHAR2(100),
  fmrate        NUMBER,
  goodsname_en  VARCHAR2(2000),
  livery        VARCHAR2(100),
  deleted       NUMBER(1),
  create_time   TIMESTAMP(6),
  update_time   TIMESTAMP(6),
  create_by     VARCHAR2(64),
  update_by     VARCHAR2(64),
  backup_time   DATE,
  cost_perbox   NUMBER
);
create unique index UK_PINGGU_HIS_LQ on T_COST_PINGGU_HIS_LQ (DOCID, BACKUP_TIME);

-- 明细历史备份
create table T_COST_PINGGU_DTL_HIS_LQ
(
  docid            NUMBER(10) not null,
  apex_goodsid     NUMBER(10),
  apex_goodsname   VARCHAR2(500),
  dtl_useflag      VARCHAR2(100),
  spec             VARCHAR2(100),
  per_hl           NUMBER,
  exadd_mater      NUMBER,
  batch_qty        NUMBER,
  price            NUMBER,
  cost_batch       NUMBER,
  memo             VARCHAR2(100),
  dtlid            NUMBER(10) not null,
  apex_factoryname VARCHAR2(200),
  apex_factoryid   NUMBER(10),
  modifydate       DATE,
  base_price       NUMBER,
  suqty            NUMBER,
  goodstype        VARCHAR2(4000),
  goodsname_en     VARCHAR2(2000),
  deleted          NUMBER(1),
  create_time      TIMESTAMP(6),
  update_time      TIMESTAMP(6),
  create_by        VARCHAR2(64),
  update_by        VARCHAR2(64),
  backup_time      DATE
);
create unique index UK_PINGGU_DTL_HIS_LQ on T_COST_PINGGU_DTL_HIS_LQ (DTLID, BACKUP_TIME);

-- ============================================================
-- 2. 序列
-- ============================================================
CREATE SEQUENCE SEQ_COST_PINGGU_LQ START WITH 100000 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE SEQ_COST_PINGGU_DTL_LQ START WITH 100000 INCREMENT BY 1 CACHE 20;

-- ============================================================
-- 3. 视图
-- ============================================================

-- 明细关联主表视图
CREATE OR REPLACE VIEW T_COST_PINGGU_DTL_LQ_V AS
SELECT a.docid, a.apex_goodsid, a.apex_goodsname, a.dtl_useflag, a.spec, a.per_hl, a.exadd_mater,
       a.batch_qty, a.price, a.cost_batch, a.memo, a.dtlid, a.apex_factoryname, a.apex_factoryid,
       a.modifydate, a.base_price, a.suqty, a.goodstype, a.goodsname_en,
       b.APEX_PL, b.P_PERPACK, b.S_PERBACK, b.X_PERBACK
FROM t_cost_pinggu_dtl_lq a, t_cost_pinggu_lq b
WHERE a.docid = b.docid;

-- 原辅料明细视图
CREATE OR REPLACE VIEW V_COST_PINGGU_MATERIAL_LQ AS
SELECT d.DTLID AS ID, d.DOCID AS MASTER_ID, d.APEX_GOODSID, d.APEX_GOODSNAME, d.DTL_USEFLAG,
    d.SPEC, d.PER_HL, d.PRICE, d.BATCH_QTY, d.COST_BATCH, d.APEX_FACTORYNAME,
    d.BASE_PRICE, d.GOODSTYPE, d.EXADD_MATER, d.MEMO, d.DELETED, d.CREATE_TIME, d.UPDATE_TIME,
    d.CREATE_BY, d.UPDATE_BY,
    CASE WHEN d.DTL_USEFLAG = '辅料' AND REGEXP_LIKE(d.APEX_GOODSNAME, '胶囊') THEN 'B'
         WHEN d.DTL_USEFLAG IN ('原料', '辅料') THEN 'C' ELSE NULL END AS FORMULA_TYPE
FROM T_COST_PINGGU_DTL_LQ d
WHERE d.DTL_USEFLAG IN ('原料', '辅料') AND (d.DELETED = 0 OR d.DELETED IS NULL);

-- 包材明细视图
CREATE OR REPLACE VIEW V_COST_PINGGU_PACKAGE_LQ AS
SELECT d.DTLID AS ID, d.DOCID AS MASTER_ID, d.APEX_GOODSID, d.APEX_GOODSNAME, d.DTL_USEFLAG,
    d.SPEC, d.PER_HL, d.EXADD_MATER, d.PRICE, d.BATCH_QTY, d.COST_BATCH, d.SUQTY,
    d.APEX_FACTORYNAME, d.MEMO, d.DELETED, d.CREATE_TIME, d.UPDATE_TIME, d.CREATE_BY, d.UPDATE_BY,
    CASE WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '桶|说明书|小盒|标签|瓶|盖') THEN 'A'
         WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '硬片|铝箔|复合膜') THEN 'D'
         WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '大纸箱') THEN 'E'
         WHEN REGEXP_LIKE(d.APEX_GOODSNAME, '托盘') THEN 'F' ELSE NULL END AS FORMULA_TYPE
FROM T_COST_PINGGU_DTL_LQ d
WHERE d.DTL_USEFLAG IN ('非印字包材', '印字包材') AND (d.DELETED = 0 OR d.DELETED IS NULL);

-- 按物料查成品视图
CREATE OR REPLACE VIEW V_COST_PGOODS_BY_MGOODS_LQ AS
SELECT a.apex_goodsid goodsid, a.apex_goodsname, a.dtl_useflag, b.factoryname, a.price, b.goodsno,
       d.goodsid pgoodsid, d.goodsno pgoodsno, d.goodsname, c.apex_pl, a.batch_qty, a.deleted
FROM T_COST_PINGGU_DTL_LQ a, t_cost_goods b, t_cost_pinggu_lq c, t_cost_goods d
WHERE a.apex_goodsid = b.goodsid AND a.docid = c.docid AND c.goodsid = d.goodsid
  AND a.deleted = 0 AND b.deleted = 0 AND c.deleted = 0 AND d.deleted = 0;

-- ============================================================
-- 4. 存储过程
-- ============================================================

-- 成本核算明细计算(液体)
CREATE OR REPLACE PROCEDURE p_pinggu_dtl_compute_lq(p_docid NUMBER, is_all_comp NUMBER) AS
  v_apex_pl NUMBER; v_dtl_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_dtl_count FROM t_cost_pinggu_dtl_lq WHERE docid = p_docid;
  IF v_dtl_count = 0 THEN RETURN; END IF;
  BEGIN SELECT a.apex_pl INTO v_apex_pl FROM t_cost_pinggu_lq a WHERE a.docid = p_docid;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN; END;
  
  IF is_all_comp = 0 THEN
    UPDATE t_cost_pinggu_dtl_lq a SET a.per_hl = a.batch_qty / v_apex_pl * 1000000
    WHERE a.docid = p_docid AND a.dtl_useflag IN ('原料', '辅料');
    UPDATE t_cost_pinggu_dtl_lq a SET a.per_hl = a.batch_qty / v_apex_pl * 1000000
    WHERE a.docid = p_docid AND a.dtl_useflag IN ('印字包材', '非印字包材') AND REGEXP_LIKE(a.apex_goodsname, '硬片|铝箔');
  END IF;
  
  UPDATE t_cost_pinggu_dtl_lq a SET a.cost_batch = a.batch_qty * a.price WHERE a.docid = p_docid;
END;
/

-- 成本核算主表计算(液体)
CREATE OR REPLACE PROCEDURE p_pinggu_compute_lq (p_docid IN NUMBER) IS
  v_apex_pl NUMBER; v_p_perpack NUMBER; v_yield NUMBER; v_out_price_rmb NUMBER; v_annual_qty NUMBER;
  v_total_fl NUMBER; v_total_bc NUMBER; v_total_yl NUMBER; v_total_cost NUMBER;
  v_salemoney NUMBER; v_jgf_batch NUMBER; v_jgf_perqp NUMBER; v_cost_perqp NUMBER;
  v_ml_perqp NUMBER; v_y_jg_re NUMBER; v_y_ml NUMBER; v_y_sale NUMBER; v_cost_perbox NUMBER;
  v_sum_yl NUMBER := 0; is_exists NUMBER;
BEGIN
  SELECT COUNT(1) INTO is_exists FROM t_cost_pinggu_lq WHERE docid = p_docid;
  IF is_exists > 0 THEN
    SELECT apex_pl, p_perpack, yield, out_price_rmb, annual_qty, cost_perqp
    INTO v_apex_pl, v_p_perpack, v_yield, v_out_price_rmb, v_annual_qty, v_cost_perqp
    FROM t_cost_pinggu_lq WHERE docid = p_docid;
    
    SELECT NVL(SUM(CASE WHEN dtl_useflag = '原料' THEN cost_batch ELSE 0 END), 0) INTO v_sum_yl
    FROM t_cost_pinggu_dtl_lq WHERE docid = p_docid;
    
    IF v_sum_yl > 0 THEN
      SELECT NVL(SUM(CASE WHEN dtl_useflag = '原料' THEN cost_batch / 1.13 ELSE 0 END), 0),
             NVL(SUM(CASE WHEN dtl_useflag = '辅料' THEN cost_batch / 1.13 ELSE 0 END), 0),
             NVL(SUM(CASE WHEN dtl_useflag IN ('非印字包材', '印字包材') THEN cost_batch / 1.13 ELSE 0 END), 0)
      INTO v_total_yl, v_total_fl, v_total_bc FROM t_cost_pinggu_dtl_lq WHERE docid = p_docid;
    ELSE
      SELECT NVL(SUM(CASE WHEN dtl_useflag = '原料' THEN cost_batch ELSE 0 END), 0),
             NVL(SUM(CASE WHEN dtl_useflag = '辅料' THEN cost_batch ELSE 0 END), 0),
             NVL(SUM(CASE WHEN dtl_useflag IN ('非印字包材', '印字包材') THEN cost_batch ELSE 0 END), 0)
      INTO v_total_yl, v_total_fl, v_total_bc FROM t_cost_pinggu_dtl_lq WHERE docid = p_docid;
    END IF;
    
    v_total_cost := v_total_fl + v_total_bc + v_total_yl;
    v_salemoney := ROUND(NVL(v_out_price_rmb, 0) / NULLIF(v_p_perpack, 0) * NVL(v_apex_pl, 0) * (NVL(v_yield, 0) / 100), 2);
    v_jgf_batch := ROUND(NVL(v_salemoney, 0) - NVL(v_total_cost, 0), 2);
    v_cost_perbox := ROUND(NVL(v_total_cost, 0) / NULLIF(v_apex_pl, 0) * NVL(v_p_perpack, 0), 2);
    v_jgf_perqp := ROUND(NVL(v_jgf_batch, 0) / NULLIF(v_apex_pl, 0) * 1000, 2);
    v_ml_perqp := ROUND(NVL(v_jgf_perqp, 0) - NVL(v_cost_perqp, 0), 2);
    v_y_jg_re := ROUND(NVL(v_jgf_perqp, 0) / 1000 * NVL(v_annual_qty, 0), 2);
    v_y_ml := ROUND(NVL(v_ml_perqp, 0) / 1000 * NVL(v_annual_qty, 0), 2);
    v_y_sale := ROUND(NVL(v_salemoney, 0) / NULLIF(v_apex_pl, 0) * NVL(v_annual_qty, 0), 2);
    
    UPDATE t_cost_pinggu_lq SET salemoney = v_salemoney, jgf_batch = v_jgf_batch, jgf_perqp = v_jgf_perqp,
           cost_perbox = v_cost_perbox, ml_perqp = v_ml_perqp, y_jg_re = v_y_jg_re, y_ml = v_y_ml, y_sale = v_y_sale,
           total_fl = v_total_fl, total_bc = v_total_bc, total_yl = v_total_yl, total_cost = v_total_cost
    WHERE docid = p_docid;
  END IF;
EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK; RAISE; WHEN OTHERS THEN ROLLBACK; RAISE;
END p_pinggu_compute_lq;
/

-- BOM生成明细(液体)
CREATE OR REPLACE PROCEDURE P_COST_BOM_INSERT_LQ (p_docid IN t_cost_pinggu_lq.docid%TYPE) AS
    v_goodsid varchar2(20);
    v_raw_goodsid t_cost_pinggu_lq.goodsid%TYPE;
BEGIN
    SELECT goodsid INTO v_raw_goodsid FROM t_cost_pinggu_lq WHERE docid = p_docid;
    IF v_raw_goodsid IS NULL THEN RAISE_APPLICATION_ERROR(-20003, '该产品在ERP中不存在BOM'); END IF;
    v_goodsid := '-' || v_raw_goodsid || '-';
    DELETE FROM t_cost_pinggu_dtl_lq WHERE docid = p_docid;
    INSERT INTO t_cost_pinggu_dtl_lq (dtlid, docid, apex_goodsid, spec, batch_qty, price, BASE_PRICE, modifydate, cost_batch,
                                   DTL_USEFLAG, APEX_GOODSNAME, APEX_FACTORYNAME, GOODSTYPE)
    SELECT SEQ_COST_PINGGU_DTL_LQ.NEXTVAL, p_docid, v.goodsid, v.standardtype, v.useqty, f.PRICE, f.PRICE, sysdate,
           nvl(v.useqty,0)*nvl(f.price,0), decode(v.useflag,4,'原料',2,'辅料',3,'非印字包材',5,'印字包材'),
           f.GOODSNAME, f.FACTORYNAME, f.GOODSTYPE
    FROM t_cost_bom_goods_tree_v v, PUB_GOODS_V f
    WHERE v.treeid LIKE v_goodsid||'%' AND v.pid <> '-1' AND v.USEFLAG NOT IN (0,1) AND v.goodsid = f.goodsid(+);
    p_pinggu_dtl_compute_lq(p_docid, 0);
    p_pinggu_compute_lq(p_docid);
    COMMIT;
END P_COST_BOM_INSERT_LQ;
/

-- 批量计算所有成本核算(液体)
CREATE OR REPLACE PROCEDURE p_pinggu_compute_all_lq AS
BEGIN
  UPDATE t_cost_pinggu_dtl_lq a SET a.price = (SELECT PRICE FROM t_cost_goods_price x WHERE x.GOODSID = a.apex_goodsid AND x.USEFLAG NOT IN ('产成品'));
  FOR i IN (SELECT DOCID FROM t_cost_pinggu_lq) LOOP
    p_pinggu_dtl_compute_lq(i.docid, 1);
    p_pinggu_compute_lq(i.docid);
  END LOOP;
END;
/

-- 备份成本核算表(液体)
CREATE OR REPLACE PROCEDURE sp_backup_pinggu_tables_lq AS
BEGIN
  INSERT INTO t_cost_pinggu_his_lq (goodsid, goodsname, strength, ma_no, apex_pl, mah, p_perpack, form, s_perback, packtype,
    x_perback, total_fl, total_bc, total_yl, memo, usestatus, docid, dosage, annual_qty, yield, total_cost, out_price_f,
    out_price_rmb, salemoney, jgf_batch, jgf_perqp, cost_perqp, ml_perqp, y_jg_re, y_ml, y_sale, customid, customname,
    country, projectno, useflag, yield_time, apex_pl_time, fmname, fmrate, goodsname_en, livery, deleted, create_time,
    update_time, create_by, update_by, cost_perbox, backup_time)
  SELECT t.goodsid, t.goodsname, t.strength, t.ma_no, t.apex_pl, t.mah, t.p_perpack, t.form, t.s_perback, t.packtype,
    t.x_perback, t.total_fl, t.total_bc, t.total_yl, t.memo, t.usestatus, t.docid, t.dosage, t.annual_qty, t.yield,
    t.total_cost, t.out_price_f, t.out_price_rmb, t.salemoney, t.jgf_batch, t.jgf_perqp, t.cost_perqp, t.ml_perqp,
    t.y_jg_re, t.y_ml, t.y_sale, t.customid, t.customname, t.country, t.projectno, t.useflag, t.yield_time, t.apex_pl_time,
    t.fmname, t.fmrate, t.goodsname_en, t.livery, t.deleted, t.create_time, t.update_time, t.create_by, t.update_by,
    t.cost_perbox, SYSDATE FROM t_cost_pinggu_lq t;
  INSERT INTO t_cost_pinggu_dtl_his_lq (docid, apex_goodsid, apex_goodsname, dtl_useflag, spec, per_hl, exadd_mater, batch_qty,
    price, cost_batch, memo, dtlid, apex_factoryname, apex_factoryid, modifydate, base_price, suqty, goodstype, goodsname_en,
    deleted, create_time, update_time, create_by, update_by, backup_time)
  SELECT t.docid, t.apex_goodsid, t.apex_goodsname, t.dtl_useflag, t.spec, t.per_hl, t.exadd_mater, t.batch_qty, t.price,
    t.cost_batch, t.memo, t.dtlid, t.apex_factoryname, t.apex_factoryid, t.modifydate, t.base_price, t.suqty, t.goodstype,
    t.goodsname_en, t.deleted, t.create_time, t.update_time, t.create_by, t.update_by, SYSDATE FROM t_cost_pinggu_dtl_lq t;
  COMMIT;
END;
/

-- ============================================================
-- 5. 表元数据
-- ============================================================
INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostPingguLq', '物料成本核算表_液体', 'T_COST_PINGGU_LQ', 'T_COST_PINGGU_LQ', 'SEQ_COST_PINGGU_LQ', 'DOCID', NULL, NULL, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostMaterialLq', '原辅料明细_液体', 'V_COST_PINGGU_MATERIAL_LQ', 'T_COST_PINGGU_DTL_LQ', 'SEQ_COST_PINGGU_DTL_LQ', 'DTLID', 'CostPingguLq', 'DOCID', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostPackageLq', '包材明细_液体', 'V_COST_PINGGU_PACKAGE_LQ', 'T_COST_PINGGU_DTL_LQ', 'SEQ_COST_PINGGU_DTL_LQ', 'DTLID', 'CostPingguLq', 'DOCID', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 6. 列元数据 - CostPingguLq (主表)
-- ============================================================
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'id', 'DOCID', 'ID', 'number', 0, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'goodsid', 'GOODSID', '产品ID', 'number', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'goodsname', 'GOODSNAME', '产品名称', 'text', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'goodsnameEn', 'GOODSNAME_EN', '产品英文名', 'text', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'strength', 'STRENGTH', '剂量', 'text', 3, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'customid', 'CUSTOMID', '客户ID', 'number', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'customname', 'CUSTOMNAME', '客户名称', 'text', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'country', 'COUNTRY', '国家', 'text', 5, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'projectno', 'PROJECTNO', '项目号', 'text', 6, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'apexPl', 'APEX_PL', '批量', 'number', 7, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'annualQty', 'ANNUAL_QTY', '年需求量', 'number', 8, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'yield', 'YIELD', '收率(%)', 'number', 9, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'pPerpack', 'P_PERPACK', '每盒片数', 'number', 10, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'sPerback', 'S_PERBACK', '每箱装盒数', 'number', 11, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'xPerback', 'X_PERBACK', '每托盘箱数', 'number', 12, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'packtype', 'PACKTYPE', '包装形式', 'text', 13, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'totalYl', 'TOTAL_YL', '原料合计', 'number', 20, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'totalFl', 'TOTAL_FL', '辅料合计', 'number', 21, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'totalBc', 'TOTAL_BC', '包材合计', 'number', 22, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'totalCost', 'TOTAL_COST', '总物料成本', 'number', 23, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'outPriceRmb', 'OUT_PRICE_RMB', '出厂价(RMB)', 'number', 24, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'salemoney', 'SALEMONEY', '每批销售额', 'number', 25, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'jgfBatch', 'JGF_BATCH', '每批加工费', 'number', 26, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'costPerqp', 'COST_PERQP', '千片成本', 'number', 27, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'costPerbox', 'COST_PERBOX', '每盒成本', 'number', 28, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'jgfPerqp', 'JGF_PERQP', '千片加工费', 'number', 28, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'mlPerqp', 'ML_PERQP', '千片毛利', 'number', 29, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'yJgRe', 'Y_JG_RE', '年加工费', 'number', 30, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'yMl', 'Y_ML', '年毛利', 'number', 31, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'ySale', 'Y_SALE', '年销售额', 'number', 32, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'fmname', 'FMNAME', '币种', 'text', 33, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'fmrate', 'FMRATE', '汇率', 'number', 34, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'memo', 'MEMO', '备注', 'text', 35, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'livery', 'LIVERY', '分销商', 'text', 36, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'tranposid', 'TRANPOSID', '分销商ID', 'number', 37, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 7. 列元数据 - CostMaterialLq (原辅料明细)
-- ============================================================
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'id', 'ID', 'DTLID', 'ID', 'number', 0, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'masterId', 'MASTER_ID', 'MASTER_ID', 'DOCID', '主表ID', 'number', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'apexGoodsid', 'APEX_GOODSID', '物料ID', 'number', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'dtlUseflag', 'DTL_USEFLAG', '分类', 'text', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'apexGoodsname', 'APEX_GOODSNAME', '物料名称', 'text', 3, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'spec', 'SPEC', '规格', 'text', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'perHl', 'PER_HL', '每片含量', 'number', 5, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'exaddMater', 'EXADD_MATER', '额外投料量', 'number', 6, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'price', 'PRICE', '单价', 'number', 7, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'batchQty', 'BATCH_QTY', '每批数量', 'number', 8, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'costBatch', 'COST_BATCH', '每批成本', 'number', 9, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'apexFactoryname', 'APEX_FACTORYNAME', '供应商', 'text', 10, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'formulaType', 'FORMULA_TYPE', '公式类型', 'text', 11, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'basePrice', 'BASE_PRICE', '参考采购价', 'number', 12, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 8. 列元数据 - CostPackageLq (包材明细)
-- ============================================================
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'id', 'ID', 'DTLID', 'ID', 'number', 0, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'masterId', 'MASTER_ID', 'MASTER_ID', 'DOCID', '主表ID', 'number', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'apexGoodsid', 'APEX_GOODSID', '物料ID', 'number', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'dtlUseflag', 'DTL_USEFLAG', '包材类型', 'text', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'apexGoodsname', 'APEX_GOODSNAME', '包材名称', 'text', 3, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'spec', 'SPEC', '规格型号', 'text', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'suqty', 'SUQTY', '用量', 'number', 5, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'price', 'PRICE', '包材单价', 'number', 6, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'batchQty', 'BATCH_QTY', '每批数量', 'number', 7, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'costBatch', 'COST_BATCH', '包材成本', 'number', 8, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'apexFactoryname', 'APEX_FACTORYNAME', '包材供应商', 'text', 9, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'formulaType', 'FORMULA_TYPE', '公式类型', 'text', 10, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'basePrice', 'BASE_PRICE', '参考采购价', 'number', 11, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 9. 页面组件
-- ============================================================
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu-lq', 'root', 'LAYOUT', NULL, '{"direction":"vertical","gap":8}', NULL, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'GRID', 'root', '{"height":"50%","selectionMode":"single","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"generateFromBom","label":"由BOM生成明细","requiresRow":true,"procedure":"P_COST_BOM_INSERT_LQ","params":[{"source":"data.id","mode":"IN","jdbcType":"NUMERIC"}]},{"action":"syncPrice","label":"同步采购价","procedure":"P_PINGGU_COMPUTE_ALL_LQ","params":[]},{"action":"saveGridConfig","label":"保存列配置"},{"action":"save","label":"保存"}]}', 'CostPingguLq', 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'TABS', 'root', '{"mode":"multi","tabs":[{"key":"material","title":"原料/辅料","tableCode":"CostMaterialLq","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]},{"key":"package","title":"包材","tableCode":"CostPackageLq","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}]}', NULL, 2, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 10. 页面规则 - masterGrid
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'COLUMN_OVERRIDE', '[{"field":"id","visible":true,"editable":false},{"field":"goodsid","visible":true,"editable":false},{"field":"goodsname","visible":true,"editable":true,"searchable":true},{"field":"goodsnameEn","visible":true,"editable":true},{"field":"strength","visible":true,"editable":true},{"field":"customid","visible":true,"editable":false},{"field":"customname","visible":true,"editable":true,"searchable":true},{"field":"country","visible":true,"editable":true},{"field":"tranposid","visible":true,"editable":false},{"field":"livery","visible":true,"editable":true},{"field":"projectno","visible":true,"editable":true},{"field":"apexPl","visible":true,"editable":true},{"field":"annualQty","visible":true,"editable":true},{"field":"yield","visible":true,"editable":true},{"field":"pPerpack","visible":true,"editable":true},{"field":"sPerback","visible":true,"editable":true},{"field":"xPerback","visible":true,"editable":true},{"field":"packtype","visible":true,"editable":true},{"field":"totalYl","visible":true,"editable":false},{"field":"totalFl","visible":true,"editable":false},{"field":"totalBc","visible":true,"editable":false},{"field":"totalCost","visible":true,"editable":false},{"field":"outPriceRmb","visible":true,"editable":true},{"field":"salemoney","visible":true,"editable":false},{"field":"jgfBatch","visible":true,"editable":false},{"field":"costPerqp","visible":true,"editable":true},{"field":"jgfPerqp","visible":true,"editable":false},{"field":"mlPerqp","visible":true,"editable":false},{"field":"yJgRe","visible":true,"editable":false},{"field":"yMl","visible":true,"editable":false},{"field":"ySale","visible":true,"editable":false},{"field":"fmname","visible":true,"editable":true},{"field":"fmrate","visible":true,"editable":true},{"field":"memo","visible":true,"editable":true}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'VALIDATION', '[]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'CALC', '[
  {"field":"salemoney","expression":"outPriceRmb / pPerpack * apexPl * (yield / 100)","triggerFields":["outPriceRmb","pPerpack","apexPl","yield"]},
  {"field":"jgfBatch","expression":"salemoney - totalCost","triggerFields":["salemoney","totalCost"]},
  {"field":"costPerbox","expression":"totalCost / apexPl * pPerpack","triggerFields":["totalCost","apexPl","pPerpack"]},
  {"field":"jgfPerqp","expression":"jgfBatch / apexPl * 1000","triggerFields":["jgfBatch","apexPl"]},
  {"field":"mlPerqp","expression":"jgfPerqp - costPerqp","triggerFields":["jgfPerqp","costPerqp"]},
  {"field":"yJgRe","expression":"jgfPerqp / 1000 * annualQty","triggerFields":["jgfPerqp","annualQty"]},
  {"field":"yMl","expression":"mlPerqp / 1000 * annualQty","triggerFields":["mlPerqp","annualQty"]},
  {"field":"ySale","expression":"salemoney / apexPl * annualQty","triggerFields":["salemoney","apexPl","annualQty"]}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'AGGREGATE', '[
  {"sourceField":"costBatch","targetField":"totalYl","algorithm":"SUM","sourceTab":"material","filter":"dtlUseflag === ''原料''"},
  {"sourceField":"costBatch","targetField":"totalFl","algorithm":"SUM","sourceTab":"material","filter":"dtlUseflag === ''辅料''"},
  {"sourceField":"costBatch","targetField":"totalBc","algorithm":"SUM","sourceTab":"package","filter":"dtlUseflag === ''非印字包材'' || dtlUseflag === ''印字包材''"},
  {"targetField":"totalYl","expression":"totalYl > 0 ? totalYl / 1.13 : totalYl"},
  {"targetField":"totalFl","expression":"totalYl > 0 ? totalFl / 1.13 : totalFl"},
  {"targetField":"totalBc","expression":"totalYl > 0 ? totalBc / 1.13 : totalBc"},
  {"targetField":"totalCost","expression":"totalYl + totalFl + totalBc"}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'LOOKUP', '[{"field":"goodsname","lookupCode":"costGoods","mapping":{"goodsid":"goodsid","goodsname":"goodsname","maNo":"maNo","apexPl":"apexPl","mah":"mah","pPerpack":"pPerpack","sPerback":"sPerback","customid":"customid","customname":"customname","memo":"memo","strength":"strength","livery":"livery"}},{"field":"fmname","lookupCode":"formoney","mapping":{"fmname":"fmname","fmrate":"fmrate"}},{"field":"customname","lookupCode":"costCustomer","mapping":{"customid":"customid","customname":"customname","country":"country","tranposid":"tranposid","livery":"livery"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'ROLE_BINDING', '{"role":"MASTER_GRID"}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'GRID_OPTIONS', '{"cellSelection":true,"sideBar":true}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'ROW_CLASS', '[{"field":"memo","operator":"eq","value":"ERP未搭建BOM","style":{"backgroundColor":"#ffcccc"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 11. 页面规则 - detailTabs
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'ROLE_BINDING', '{"role":"DETAIL_TABS"}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'RELATION', '{"masterKey":"masterGrid","detailKey":"detailTabs"}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'BROADCAST', '["apexPl","pPerpack","sPerback","xPerback"]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'SUMMARY_CONFIG', '{"enabled":true,"groupLabelField":"groupLabel","groupLabelHeader":"分类","summaryColumns":[{"field":"totalAmount","headerName":"汇总金额","width":null},{"field":"rowCount","headerName":"行数","width":null}],"summaryAggregates":[{"sourceField":"costBatch","targetField":"totalAmount","algorithm":"SUM"},{"sourceField":"costBatch","targetField":"rowCount","algorithm":"COUNT"}]}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 12. 页面规则 - material (原辅料明细)
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'COLUMN_OVERRIDE', '[{"field":"id","visible":true,"editable":false},{"field":"masterId","visible":true,"editable":false},{"field":"apexGoodsid","visible":true,"editable":false},{"field":"dtlUseflag","visible":true,"editable":true,"cellEditor":"agSelectCellEditor","cellEditorParams":{"values":["原料","辅料"]}},{"field":"apexGoodsname","visible":true,"editable":true},{"field":"spec","visible":true,"editable":true},{"field":"perHl","visible":true,"editable":true},{"field":"exaddMater","visible":true,"editable":true},{"field":"price","visible":true,"editable":true},{"field":"batchQty","visible":true,"editable":false},{"field":"costBatch","visible":true,"editable":false},{"field":"apexFactoryname","visible":true,"editable":true},{"field":"formulaType","visible":false,"editable":false}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'VALIDATION', '[{"field":"perHl","required":true,"min":0.001,"message":"每片含量必填且必须大于0"},{"field":"price","required":true,"min":0,"message":"单价必填且不能为负数"}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'CALC', '[
  {"field":"batchQty","formulaField":"formulaType","formulas":{
    "B":{"expression":"apexPl / 10000","triggerFields":["apexPl"]},
    "C":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]}
  }},
  {"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'LOOKUP', '[{"field":"apexGoodsname","lookupCode":"costMaterial","mapping":{"apexGoodsid":"goodsid","apexGoodsname":"goodsname","spec":"goodstype","price":"price","apexFactoryname":"factoryname","goodstype":"goodstype","basePrice":"price"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 13. 页面规则 - package (包材明细)
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'COLUMN_OVERRIDE', '[{"field":"id","visible":true,"editable":false},{"field":"masterId","visible":true,"editable":false},{"field":"apexGoodsid","visible":true,"editable":false},{"field":"dtlUseflag","visible":true,"editable":true,"cellEditor":"agSelectCellEditor","cellEditorParams":{"values":["印字包材","非印字包材"]}},{"field":"apexGoodsname","visible":true,"editable":true},{"field":"spec","visible":true,"editable":true},{"field":"suqty","visible":true,"editable":true},{"field":"price","visible":true,"editable":true},{"field":"batchQty","visible":true,"editable":false},{"field":"costBatch","visible":true,"editable":false},{"field":"apexFactoryname","visible":true,"editable":true},{"field":"formulaType","visible":false,"editable":false}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'VALIDATION', '[{"field":"price","min":0,"message":"包材单价不能为负数"}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'CALC', '[
  {"field":"batchQty","formulaField":"formulaType","formulas":{
    "A":{"expression":"apexPl / pPerpack * (1 + exaddMater)","triggerFields":["apexPl","pPerpack","exaddMater"]},
    "D":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]},
    "E":{"expression":"ceil(apexPl / (pPerpack * sPerback))","triggerFields":["apexPl","pPerpack","sPerback"]},
    "F":{"expression":"ceil(apexPl / (pPerpack * sPerback * xPerback))","triggerFields":["apexPl","pPerpack","sPerback","xPerback"]}
  }},
  {"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'LOOKUP', '[{"field":"apexGoodsname","lookupCode":"costMaterial","mapping":{"apexGoodsid":"goodsid","apexGoodsname":"goodsname","spec":"goodstype","price":"price","apexFactoryname":"factoryname","suqty":"lastsuqty"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 14. 菜单资源 + 角色权限
-- ============================================================
-- 菜单资源（放在"物料成本核算表"同级）
INSERT INTO T_COST_RESOURCE (ID, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, IS_HARDCODED)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, '物料成本核算表_液体', 'PAGE', 'cost-pinggu-lq', 'mdi:calculator-variant', '/cost/cost-pinggu-lq', NULL, 2, 0);

-- ADMIN角色授权
INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, ROW_POLICY)
VALUES (SEQ_COST_ROLE_PAGE.NEXTVAL, 3, 'cost-pinggu-lq', '["*"]', NULL, NULL);

-- ============================================================
-- 提交
-- ============================================================
COMMIT;
