

-- ============================================================
-- 5. 表元数据
-- ============================================================
INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostPingguLq', '物料成本核算表_液体', 'T_COST_PINGGU_LQ', 'T_COST_PINGGU_LQ', 'SEQ_COST_PINGGU_LQ', 'DOCID', NULL, NULL, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostMaterialLq', '原辅料明细_液体', 'V_COST_PINGGU_MATERIAL_LQ', 'T_COST_PINGGU_DTL_LQ', 'SEQ_COST_PINGGU_DTL_LQ', 'DTLID', 'CostPingguLq', 'DOCID', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_TABLE_METADATA.NEXTVAL, 'CostPackageLq', '包材明细_液体', 'V_COST_PINGGU_PACKAGE_LQ', 'T_COST_PINGGU_DTL_LQ', 'SEQ_COST_PINGGU_DTL_LQ', 'DTLID', 'CostPingguLq', 'DOCID', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 6. 列元数据 - CostPingguLq (主表)
-- ============================================================
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'id', 'DOCID', 'ID', 'number', 0, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'goodsid', 'GOODSID', '产品ID', 'number', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'goodsname', 'GOODSNAME', '产品名称', 'text', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'goodsnameEn', 'GOODSNAME_EN', '产品英文名', 'text', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'strength', 'STRENGTH', '剂量', 'text', 3, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'customid', 'CUSTOMID', '客户ID', 'number', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'customname', 'CUSTOMNAME', '客户名称', 'text', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'country', 'COUNTRY', '国家', 'text', 5, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'projectno', 'PROJECTNO', '项目号', 'text', 6, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'apexPl', 'APEX_PL', '批量', 'number', 7, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'annualQty', 'ANNUAL_QTY', '年需求量', 'number', 8, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'yield', 'YIELD', '收率(%)', 'number', 9, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'pPerpack', 'P_PERPACK', '每盒片数', 'number', 10, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'sPerback', 'S_PERBACK', '每箱装盒数', 'number', 11, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'xPerback', 'X_PERBACK', '每托盘箱数', 'number', 12, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'packtype', 'PACKTYPE', '包装形式', 'text', 13, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'totalYl', 'TOTAL_YL', '原料合计', 'number', 20, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'totalFl', 'TOTAL_FL', '辅料合计', 'number', 21, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'totalBc', 'TOTAL_BC', '包材合计', 'number', 22, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'totalCost', 'TOTAL_COST', '总物料成本', 'number', 23, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'outPriceRmb', 'OUT_PRICE_RMB', '出厂价(RMB)', 'number', 24, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'salemoney', 'SALEMONEY', '每批销售额', 'number', 25, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'jgfBatch', 'JGF_BATCH', '每批加工费', 'number', 26, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'costPerqp', 'COST_PERQP', '千片成本', 'number', 27, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'costPerbox', 'COST_PERBOX', '每盒成本', 'number', 28, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'jgfPerqp', 'JGF_PERQP', '千片加工费', 'number', 28, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'mlPerqp', 'ML_PERQP', '千片毛利', 'number', 29, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'yJgRe', 'Y_JG_RE', '年加工费', 'number', 30, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'yMl', 'Y_ML', '年毛利', 'number', 31, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'ySale', 'Y_SALE', '年销售额', 'number', 32, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'fmname', 'FMNAME', '币种', 'text', 33, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'fmrate', 'FMRATE', '汇率', 'number', 34, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'memo', 'MEMO', '备注', 'text', 35, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'livery', 'LIVERY', '分销商', 'text', 36, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPingguLq'), 'tranposid', 'TRANPOSID', '分销商ID', 'number', 37, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 7. 列元数据 - CostMaterialLq (原辅料明细)
-- ============================================================
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'id', 'ID', 'DTLID', 'ID', 'number', 0, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'masterId', 'MASTER_ID', 'MASTER_ID', 'DOCID', '主表ID', 'number', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'apexGoodsid', 'APEX_GOODSID', '物料ID', 'number', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'dtlUseflag', 'DTL_USEFLAG', '分类', 'text', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'apexGoodsname', 'APEX_GOODSNAME', '物料名称', 'text', 3, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'spec', 'SPEC', '规格', 'text', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'perHl', 'PER_HL', '每片含量', 'number', 5, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'exaddMater', 'EXADD_MATER', '额外投料量', 'number', 6, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'price', 'PRICE', '单价', 'number', 7, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'batchQty', 'BATCH_QTY', '每批数量', 'number', 8, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'costBatch', 'COST_BATCH', '每批成本', 'number', 9, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'apexFactoryname', 'APEX_FACTORYNAME', '供应商', 'text', 10, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'formulaType', 'FORMULA_TYPE', '公式类型', 'text', 11, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostMaterialLq'), 'basePrice', 'BASE_PRICE', '参考采购价', 'number', 12, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 8. 列元数据 - CostPackageLq (包材明细)
-- ============================================================
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'id', 'ID', 'DTLID', 'ID', 'number', 0, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'masterId', 'MASTER_ID', 'MASTER_ID', 'DOCID', '主表ID', 'number', 1, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'apexGoodsid', 'APEX_GOODSID', '物料ID', 'number', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'dtlUseflag', 'DTL_USEFLAG', '包材类型', 'text', 2, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'apexGoodsname', 'APEX_GOODSNAME', '包材名称', 'text', 3, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'spec', 'SPEC', '规格型号', 'text', 4, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'suqty', 'SUQTY', '用量', 'number', 5, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'price', 'PRICE', '包材单价', 'number', 6, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'batchQty', 'BATCH_QTY', '每批数量', 'number', 7, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'costBatch', 'COST_BATCH', '包材成本', 'number', 8, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'apexFactoryname', 'APEX_FACTORYNAME', '包材供应商', 'text', 9, 1, 1, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'formulaType', 'FORMULA_TYPE', '公式类型', 'text', 10, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');
INSERT INTO T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_COLUMN_METADATA.NEXTVAL, (SELECT ID FROM T_COST_TABLE_METADATA WHERE TABLE_CODE = 'CostPackageLq'), 'basePrice', 'BASE_PRICE', '参考采购价', 'number', 11, 1, 1, 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 9. 页面组件
-- ============================================================
INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu-lq', 'root', 'LAYOUT', NULL, '{"direction":"vertical","gap":8}', NULL, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'GRID', 'root', '{"height":"50%","selectionMode":"single","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"generateFromBom","label":"由BOM生成明细","requiresRow":true,"procedure":"P_COST_BOM_INSERT_LQ","params":[{"source":"data.id","mode":"IN","jdbcType":"NUMERIC"}]},{"action":"syncPrice","label":"同步采购价","procedure":"P_PINGGU_COMPUTE_ALL_LQ","params":[]},{"action":"saveGridConfig","label":"保存列配置"},{"action":"save","label":"保存"}]}', 'CostPingguLq', 1, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_COMPONENT.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'TABS', 'root', '{"mode":"multi","tabs":[{"key":"material","title":"原料/辅料","tableCode":"CostMaterialLq","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]},{"key":"package","title":"包材","tableCode":"CostPackageLq","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}]}', NULL, 2, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 10. 页面规则 - masterGrid
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'COLUMN_OVERRIDE', '[{"field":"id","visible":true,"editable":false},{"field":"goodsid","visible":true,"editable":false},{"field":"goodsname","visible":true,"editable":true,"searchable":true},{"field":"goodsnameEn","visible":true,"editable":true},{"field":"strength","visible":true,"editable":true},{"field":"customid","visible":true,"editable":false},{"field":"customname","visible":true,"editable":true,"searchable":true},{"field":"country","visible":true,"editable":true},{"field":"tranposid","visible":true,"editable":false},{"field":"livery","visible":true,"editable":true},{"field":"projectno","visible":true,"editable":true},{"field":"apexPl","visible":true,"editable":true},{"field":"annualQty","visible":true,"editable":true},{"field":"yield","visible":true,"editable":true},{"field":"pPerpack","visible":true,"editable":true},{"field":"sPerback","visible":true,"editable":true},{"field":"xPerback","visible":true,"editable":true},{"field":"packtype","visible":true,"editable":true},{"field":"totalYl","visible":true,"editable":false},{"field":"totalFl","visible":true,"editable":false},{"field":"totalBc","visible":true,"editable":false},{"field":"totalCost","visible":true,"editable":false},{"field":"outPriceRmb","visible":true,"editable":true},{"field":"salemoney","visible":true,"editable":false},{"field":"jgfBatch","visible":true,"editable":false},{"field":"costPerqp","visible":true,"editable":true},{"field":"jgfPerqp","visible":true,"editable":false},{"field":"mlPerqp","visible":true,"editable":false},{"field":"yJgRe","visible":true,"editable":false},{"field":"yMl","visible":true,"editable":false},{"field":"ySale","visible":true,"editable":false},{"field":"fmname","visible":true,"editable":true},{"field":"fmrate","visible":true,"editable":true},{"field":"memo","visible":true,"editable":true}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'VALIDATION', '[]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'CALC', '[
  {"field":"salemoney","expression":"outPriceRmb / pPerpack * apexPl * (yield / 100)","triggerFields":["outPriceRmb","pPerpack","apexPl","yield"]},
  {"field":"jgfBatch","expression":"salemoney - totalCost","triggerFields":["salemoney","totalCost"]},
  {"field":"costPerbox","expression":"totalCost / apexPl * pPerpack","triggerFields":["totalCost","apexPl","pPerpack"]},
  {"field":"jgfPerqp","expression":"jgfBatch / apexPl * 1000","triggerFields":["jgfBatch","apexPl"]},
  {"field":"mlPerqp","expression":"jgfPerqp - costPerqp","triggerFields":["jgfPerqp","costPerqp"]},
  {"field":"yJgRe","expression":"jgfPerqp / 1000 * annualQty","triggerFields":["jgfPerqp","annualQty"]},
  {"field":"yMl","expression":"mlPerqp / 1000 * annualQty","triggerFields":["mlPerqp","annualQty"]},
  {"field":"ySale","expression":"salemoney / apexPl * annualQty","triggerFields":["salemoney","apexPl","annualQty"]}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'AGGREGATE', '[
  {"sourceField":"costBatch","targetField":"totalYl","algorithm":"SUM","sourceTab":"material","filter":"dtlUseflag === ''原料''"},
  {"sourceField":"costBatch","targetField":"totalFl","algorithm":"SUM","sourceTab":"material","filter":"dtlUseflag === ''辅料''"},
  {"sourceField":"costBatch","targetField":"totalBc","algorithm":"SUM","sourceTab":"package","filter":"dtlUseflag === ''非印字包材'' || dtlUseflag === ''印字包材''"},
  {"targetField":"totalYl","expression":"totalYl > 0 ? totalYl / 1.13 : totalYl"},
  {"targetField":"totalFl","expression":"totalYl > 0 ? totalFl / 1.13 : totalFl"},
  {"targetField":"totalBc","expression":"totalYl > 0 ? totalBc / 1.13 : totalBc"},
  {"targetField":"totalCost","expression":"totalYl + totalFl + totalBc"}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'LOOKUP', '[{"field":"goodsname","lookupCode":"costGoods","mapping":{"goodsid":"goodsid","goodsname":"goodsname","maNo":"maNo","apexPl":"apexPl","mah":"mah","pPerpack":"pPerpack","sPerback":"sPerback","customid":"customid","customname":"customname","memo":"memo","strength":"strength","livery":"livery"}},{"field":"fmname","lookupCode":"formoney","mapping":{"fmname":"fmname","fmrate":"fmrate"}},{"field":"customname","lookupCode":"costCustomer","mapping":{"customid":"customid","customname":"customname","country":"country","tranposid":"tranposid","livery":"livery"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'ROLE_BINDING', '{"role":"MASTER_GRID"}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'GRID_OPTIONS', '{"cellSelection":true,"sideBar":true}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'masterGrid', 'ROW_CLASS', '[{"field":"memo","operator":"eq","value":"ERP未搭建BOM","style":{"backgroundColor":"#ffcccc"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 11. 页面规则 - detailTabs
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'ROLE_BINDING', '{"role":"DETAIL_TABS"}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'RELATION', '{"masterKey":"masterGrid","detailKey":"detailTabs"}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'BROADCAST', '["apexPl","pPerpack","sPerback","xPerback"]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'detailTabs', 'SUMMARY_CONFIG', '{"enabled":true,"groupLabelField":"groupLabel","groupLabelHeader":"分类","summaryColumns":[{"field":"totalAmount","headerName":"汇总金额","width":null},{"field":"rowCount","headerName":"行数","width":null}],"summaryAggregates":[{"sourceField":"costBatch","targetField":"totalAmount","algorithm":"SUM"},{"sourceField":"costBatch","targetField":"rowCount","algorithm":"COUNT"}]}', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 12. 页面规则 - material (原辅料明细)
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'COLUMN_OVERRIDE', '[{"field":"id","visible":true,"editable":false},{"field":"masterId","visible":true,"editable":false},{"field":"apexGoodsid","visible":true,"editable":false},{"field":"dtlUseflag","visible":true,"editable":true,"cellEditor":"agSelectCellEditor","cellEditorParams":{"values":["原料","辅料"]}},{"field":"apexGoodsname","visible":true,"editable":true},{"field":"spec","visible":true,"editable":true},{"field":"perHl","visible":true,"editable":true},{"field":"exaddMater","visible":true,"editable":true},{"field":"price","visible":true,"editable":true},{"field":"batchQty","visible":true,"editable":false},{"field":"costBatch","visible":true,"editable":false},{"field":"apexFactoryname","visible":true,"editable":true},{"field":"formulaType","visible":false,"editable":false}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'VALIDATION', '[{"field":"perHl","required":true,"min":0.001,"message":"每片含量必填且必须大于0"},{"field":"price","required":true,"min":0,"message":"单价必填且不能为负数"}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'CALC', '[
  {"field":"batchQty","formulaField":"formulaType","formulas":{
    "B":{"expression":"apexPl / 10000","triggerFields":["apexPl"]},
    "C":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]}
  }},
  {"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'material', 'LOOKUP', '[{"field":"apexGoodsname","lookupCode":"costMaterial","mapping":{"apexGoodsid":"goodsid","apexGoodsname":"goodsname","spec":"goodstype","price":"price","apexFactoryname":"factoryname","goodstype":"goodstype","basePrice":"price"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 13. 页面规则 - package (包材明细)
-- ============================================================
INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'COLUMN_OVERRIDE', '[{"field":"id","visible":true,"editable":false},{"field":"masterId","visible":true,"editable":false},{"field":"apexGoodsid","visible":true,"editable":false},{"field":"dtlUseflag","visible":true,"editable":true,"cellEditor":"agSelectCellEditor","cellEditorParams":{"values":["印字包材","非印字包材"]}},{"field":"apexGoodsname","visible":true,"editable":true},{"field":"spec","visible":true,"editable":true},{"field":"suqty","visible":true,"editable":true},{"field":"price","visible":true,"editable":true},{"field":"batchQty","visible":true,"editable":false},{"field":"costBatch","visible":true,"editable":false},{"field":"apexFactoryname","visible":true,"editable":true},{"field":"formulaType","visible":false,"editable":false}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'VALIDATION', '[{"field":"price","min":0,"message":"包材单价不能为负数"}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'CALC', '[
  {"field":"batchQty","formulaField":"formulaType","formulas":{
    "A":{"expression":"apexPl / pPerpack * (1 + exaddMater)","triggerFields":["apexPl","pPerpack","exaddMater"]},
    "D":{"expression":"perHl * apexPl * (1 + exaddMater / 100) / 1000000","triggerFields":["perHl","apexPl","exaddMater"]},
    "E":{"expression":"ceil(apexPl / (pPerpack * sPerback))","triggerFields":["apexPl","pPerpack","sPerback"]},
    "F":{"expression":"ceil(apexPl / (pPerpack * sPerback * xPerback))","triggerFields":["apexPl","pPerpack","sPerback","xPerback"]}
  }},
  {"field":"costBatch","expression":"batchQty * price","triggerFields":["batchQty","price"]}
]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

INSERT INTO T_COST_PAGE_RULE (ID, PAGE_CODE, COMPONENT_KEY, RULE_TYPE, RULES, SORT_ORDER, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY)
VALUES (SEQ_COST_PAGE_RULE.NEXTVAL, 'cost-pinggu-lq', 'package', 'LOOKUP', '[{"field":"apexGoodsname","lookupCode":"costMaterial","mapping":{"apexGoodsid":"goodsid","apexGoodsname":"goodsname","spec":"goodstype","price":"price","apexFactoryname":"factoryname","suqty":"lastsuqty"}}]', 0, 0, SYSTIMESTAMP, SYSTIMESTAMP, 'system');

-- ============================================================
-- 14. 菜单资源 + 角色权限
-- ============================================================
-- 菜单资源（放在"物料成本核算表"同级）
INSERT INTO T_COST_RESOURCE (ID, RESOURCE_NAME, RESOURCE_TYPE, PAGE_CODE, ICON, ROUTE, PARENT_ID, SORT_ORDER, IS_HARDCODED)
VALUES (SEQ_COST_RESOURCE.NEXTVAL, '物料成本核算表_液体', 'PAGE', 'cost-pinggu-lq', 'mdi:calculator-variant', '/cost/cost-pinggu-lq', NULL, 2, 0);

-- ADMIN角色授权
INSERT INTO T_COST_ROLE_PAGE (ID, ROLE_ID, PAGE_CODE, BUTTON_POLICY, COLUMN_POLICY, ROW_POLICY)
VALUES (SEQ_COST_ROLE_PAGE.NEXTVAL, 3, 'cost-pinggu-lq', '["*"]', NULL, NULL);

-- ============================================================
-- 提交
-- ============================================================
COMMIT;
