prompt Importing table T_COST_COLUMN_METADATA...
set feedback off
set define off

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (734, 70, 'id', 'CUSTOMID', null, null, '客户ID', 'number', 0, 1, 1, 0, null, 0, '26-JAN-26 05.41.09.211000 PM', '26-JAN-26 05.41.09.211000 PM', 'system', null, 'CostCustomer');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (735, 70, 'customname', 'CUSTOMNAME', null, null, '客户名称', 'text', 1, 1, 1, 0, null, 0, '26-JAN-26 05.41.09.211000 PM', '26-JAN-26 05.41.09.211000 PM', 'system', null, 'CostCustomer');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (736, 70, 'zone', 'ZONE', null, null, '区域', 'text', 2, 1, 1, 0, null, 0, '26-JAN-26 05.41.09.212000 PM', '26-JAN-26 05.41.09.212000 PM', 'system', null, 'CostCustomer');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (737, 70, 'iserp', 'ISERP', null, null, '是否ERP', 'number', 99, 1, 1, 1, null, 0, '26-JAN-26 05.41.09.213000 PM', '26-JAN-26 05.41.09.213000 PM', 'system', null, 'CostCustomer');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1377, 125, 'customid', 'CUSTOMID', null, null, '客户ID', 'number', 0, 1, 1, 0, null, 0, '28-JAN-26 05.27.08.162000 PM', '28-JAN-26 05.27.08.162000 PM', 'system', null, 'CostCustomerLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1378, 125, 'customname', 'CUSTOMNAME', null, null, '客户名称', 'text', 1, 1, 1, 0, null, 0, '28-JAN-26 05.27.08.163000 PM', '28-JAN-26 05.27.08.163000 PM', 'system', null, 'CostCustomerLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1379, 125, 'country', 'COUNTRY', null, null, '国家', 'text', 2, 1, 1, 0, null, 0, '28-JAN-26 05.27.08.163000 PM', '28-JAN-26 05.27.08.163000 PM', 'system', null, 'CostCustomerLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1380, 125, 'livery', 'LIVERY', null, null, '分销商', 'text', 3, 1, 1, 0, null, 0, '28-JAN-26 05.27.08.163000 PM', '28-JAN-26 05.27.08.163000 PM', 'system', null, 'CostCustomerLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (35, 6, 'id', 'ID', null, null, 'ID', 'number', 1, 1, 1, 0, null, 0, '26-JAN-26 09.53.11.879000 AM', '26-JAN-26 09.53.11.879000 AM', 'system', null, 'CostDepartment');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (36, 6, 'deptCode', 'DEPT_CODE', null, null, '部门编码', 'text', 2, 1, 1, 0, null, 0, '26-JAN-26 09.53.11.940000 AM', '26-JAN-26 09.53.11.940000 AM', 'system', null, 'CostDepartment');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (37, 6, 'deptName', 'DEPT_NAME', null, null, '部门名称', 'text', 3, 1, 1, 0, null, 0, '26-JAN-26 09.53.12.103000 AM', '26-JAN-26 09.53.12.103000 AM', 'system', null, 'CostDepartment');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (38, 6, 'parentId', 'PARENT_ID', null, null, '上级部门ID', 'number', 4, 1, 1, 0, null, 0, '26-JAN-26 09.53.12.185000 AM', '26-JAN-26 09.53.12.185000 AM', 'system', null, 'CostDepartment');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (39, 6, 'sortOrder', 'SORT_ORDER', null, null, '排序', 'number', 5, 1, 1, 0, null, 0, '26-JAN-26 09.53.12.244000 AM', '26-JAN-26 09.53.12.244000 AM', 'system', null, 'CostDepartment');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (341, 41, 'id', 'FMID', null, null, '外币ID', 'number', 0, 1, 1, 0, null, 0, '26-JAN-26 04.53.18.652000 PM', '26-JAN-26 04.53.18.652000 PM', 'system', null, 'CostFormoney');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (342, 41, 'fmopcode', 'FMOPCODE', null, null, '外币编码', 'text', 1, 1, 1, 0, null, 0, '26-JAN-26 04.53.18.653000 PM', '26-JAN-26 04.53.18.653000 PM', 'system', null, 'CostFormoney');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (343, 41, 'fmname', 'FMNAME', null, null, '外币名称', 'text', 2, 1, 1, 0, null, 0, '26-JAN-26 04.53.18.654000 PM', '26-JAN-26 04.53.18.654000 PM', 'system', null, 'CostFormoney');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (344, 41, 'fmsign', 'FMSIGN', null, null, '外币符号', 'text', 3, 1, 1, 0, null, 0, '26-JAN-26 04.53.18.654000 PM', '26-JAN-26 04.53.18.654000 PM', 'system', null, 'CostFormoney');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (345, 41, 'fmunit', 'FMUNIT', null, null, '外币单位', 'text', 4, 1, 1, 0, null, 0, '26-JAN-26 04.53.18.655000 PM', '26-JAN-26 04.53.18.655000 PM', 'system', null, 'CostFormoney');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (346, 41, 'fmrate', 'FMRATE', null, null, '汇率', 'number', 5, 1, 1, 0, null, 0, '26-JAN-26 04.53.18.656000 PM', '26-JAN-26 04.53.18.656000 PM', 'system', null, 'CostFormoney');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (347, 41, 'usestatus', 'USESTATUS', null, null, '使用状态', 'number', 6, 1, 1, 0, null, 0, '26-JAN-26 04.53.18.656000 PM', '26-JAN-26 04.53.18.656000 PM', 'system', null, 'CostFormoney');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1414, 131, 'id', 'GOODSID', null, null, '产品ID', 'number', 0, 1, 1, 0, null, 0, '29-JAN-26 05.12.14.524000 PM', '29-JAN-26 05.12.14.524000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1415, 131, 'goodsno', 'GOODSNO', null, null, '华益代码', 'text', 1, 1, 1, 0, null, 0, '29-JAN-26 05.12.14.525000 PM', '29-JAN-26 05.12.14.525000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1416, 131, 'goodsname', 'GOODSNAME', null, null, '产品名称', 'text', 2, 1, 1, 0, null, 0, '29-JAN-26 05.12.14.526000 PM', '29-JAN-26 05.12.14.526000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1417, 131, 'goodstype', 'GOODSTYPE', null, null, '规格', 'text', 3, 1, 1, 0, null, 0, '29-JAN-26 05.12.14.527000 PM', '29-JAN-26 05.12.14.527000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1418, 131, 'packtype', 'PACKTYPE', null, null, '包装规格', 'text', 4, 1, 1, 0, null, 0, '29-JAN-26 05.12.14.527000 PM', '29-JAN-26 05.12.14.527000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1419, 131, 'tranposid', 'TRANPOSID', null, null, '分销商ID', 'number', 5, 1, 1, 0, null, 0, '29-JAN-26 05.12.14.528000 PM', '29-JAN-26 05.12.14.528000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1420, 131, 'tranposname', 'TRANPOSNAME', null, null, '分销商', 'text', 6, 1, 1, 1, null, 0, '29-JAN-26 05.12.14.529000 PM', '29-JAN-26 05.12.14.529000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1421, 131, 'zxCustomerid', 'ZX_CUSTOMERID', null, null, '客户ID', 'number', 7, 1, 1, 0, null, 0, '29-JAN-26 05.12.14.529000 PM', '29-JAN-26 05.12.14.529000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1422, 131, 'customname', 'CUSTOMNAME', null, null, '客户名称', 'text', 8, 1, 1, 1, null, 0, '29-JAN-26 05.12.14.530000 PM', '29-JAN-26 05.12.14.530000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1423, 131, 'zone', 'ZONE', null, null, '国家', 'text', 9, 1, 1, 1, null, 0, '29-JAN-26 05.12.14.531000 PM', '29-JAN-26 05.12.14.531000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1424, 131, 'iserp', 'ISERP', null, null, '是否ERP', 'number', 98, 1, 1, 1, null, 0, '29-JAN-26 05.12.14.531000 PM', '29-JAN-26 05.12.14.531000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1425, 131, 'createBy', 'CREATE_BY', null, null, '创建人', 'text', 99, 1, 1, 0, null, 0, '29-JAN-26 05.12.14.531000 PM', '29-JAN-26 05.12.14.531000 PM', 'system', null, 'CostGoods');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1393, 129, 'pGoodsid', 'P_GOODSID', null, null, '产品ID', 'number', 0, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.657000 PM', '29-JAN-26 04.26.50.657000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1394, 129, 'goodsname', 'GOODSNAME', null, null, '产品名称', 'text', 1, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.657000 PM', '29-JAN-26 04.26.50.657000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1395, 129, 'goodstype', 'GOODSTYPE', null, null, '规格', 'text', 2, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.658000 PM', '29-JAN-26 04.26.50.658000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1396, 129, 'packtype', 'PACKTYPE', null, null, '包装规格', 'text', 3, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.659000 PM', '29-JAN-26 04.26.50.659000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1397, 129, 'tranposid', 'TRANPOSID', null, null, '分销商ID', 'number', 4, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.660000 PM', '29-JAN-26 04.26.50.660000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1398, 129, 'tranposname', 'TRANPOSNAME', null, null, '分销商', 'text', 5, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.660000 PM', '29-JAN-26 04.26.50.660000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1399, 129, 'zxCustomerid', 'ZX_CUSTOMERID', null, null, '客户ID', 'number', 6, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.661000 PM', '29-JAN-26 04.26.50.661000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1400, 129, 'customname', 'CUSTOMNAME', null, null, '客户名称', 'text', 7, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.662000 PM', '29-JAN-26 04.26.50.662000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1401, 129, 'zone', 'ZONE', null, null, '国家', 'text', 8, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.662000 PM', '29-JAN-26 04.26.50.662000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1402, 129, 'goodsid', 'GOODSID', null, null, '物料ID', 'number', 9, 1, 1, 0, null, 0, '29-JAN-26 04.26.50.663000 PM', '29-JAN-26 04.26.50.663000 PM', 'system', null, 'CostGoodsByApex');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1365, 124, 'goodsid', 'GOODSID', null, null, '产品ID', 'number', 0, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.599000 PM', '28-JAN-26 05.27.07.599000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1366, 124, 'goodsname', 'GOODSNAME', null, null, '产品名称', 'text', 1, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.599000 PM', '28-JAN-26 05.27.07.599000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1367, 124, 'maNo', 'MA_NO', null, null, '批准文号', 'text', 2, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.599000 PM', '28-JAN-26 05.27.07.599000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1368, 124, 'apexPl', 'APEX_PL', null, null, '批量', 'number', 3, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.599000 PM', '28-JAN-26 05.27.07.599000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1369, 124, 'mah', 'MAH', null, null, '持证商', 'text', 4, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.599000 PM', '28-JAN-26 05.27.07.599000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1370, 124, 'pPerpack', 'P_PERPACK', null, null, '每盒片数', 'number', 5, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.599000 PM', '28-JAN-26 05.27.07.599000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1371, 124, 'sPerback', 'S_PERBACK', null, null, '每箱装盒数', 'number', 6, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.599000 PM', '28-JAN-26 05.27.07.599000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1372, 124, 'customid', 'CUSTOMID', null, null, '客户ID', 'number', 7, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.600000 PM', '28-JAN-26 05.27.07.600000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1373, 124, 'customname', 'CUSTOMNAME', null, null, '客户名称', 'text', 8, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.600000 PM', '28-JAN-26 05.27.07.600000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1374, 124, 'memo', 'MEMO', null, null, 'BOM状态', 'text', 9, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.600000 PM', '28-JAN-26 05.27.07.600000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1375, 124, 'strength', 'STRENGTH', null, null, '剂量', 'text', 10, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.600000 PM', '28-JAN-26 05.27.07.600000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1376, 124, 'livery', 'LIVERY', null, null, '分销商', 'text', 11, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.600000 PM', '28-JAN-26 05.27.07.600000 PM', 'system', null, 'CostGoodsLookup');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1426, 132, 'id', 'GOODSID', null, null, '物料ID', 'number', 0, 1, 1, 0, null, 0, '29-JAN-26 05.25.30.958000 PM', '29-JAN-26 05.25.30.958000 PM', 'system', null, 'CostGoodsPrice');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1427, 132, 'goodsname', 'GOODSNAME', null, null, '物料名称', 'text', 1, 1, 1, 0, null, 0, '29-JAN-26 05.25.30.958000 PM', '29-JAN-26 05.25.30.958000 PM', 'system', null, 'CostGoodsPrice');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1428, 132, 'price', 'PRICE', null, null, '价格', 'number', 2, 1, 1, 0, null, 0, '29-JAN-26 05.25.30.959000 PM', '29-JAN-26 05.25.30.959000 PM', 'system', null, 'CostGoodsPrice');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1429, 132, 'useflag', 'USEFLAG', null, null, '用途', 'text', 3, 1, 1, 0, null, 0, '29-JAN-26 05.25.30.960000 PM', '29-JAN-26 05.25.30.960000 PM', 'system', null, 'CostGoodsPrice');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1430, 132, 'goodstype', 'GOODSTYPE', null, null, '规格', 'text', 4, 1, 1, 0, null, 0, '29-JAN-26 05.25.30.961000 PM', '29-JAN-26 05.25.30.961000 PM', 'system', null, 'CostGoodsPrice');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1431, 132, 'packtype', 'PACKTYPE', null, null, '包装规格', 'text', 5, 1, 1, 0, null, 0, '29-JAN-26 05.25.30.962000 PM', '29-JAN-26 05.25.30.962000 PM', 'system', null, 'CostGoodsPrice');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1432, 132, 'factoryname', 'FACTORYNAME', null, null, '供应商', 'text', 6, 1, 1, 0, null, 0, '29-JAN-26 05.25.30.962000 PM', '29-JAN-26 05.25.30.962000 PM', 'system', null, 'CostGoodsPrice');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1433, 132, 'iserp', 'ISERP', null, null, '是否ERP', 'number', 7, 1, 1, 0, null, 0, '29-JAN-26 05.25.30.963000 PM', '29-JAN-26 05.25.30.963000 PM', 'system', null, 'CostGoodsPrice');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1342, 122, 'id', 'ID', null, 'DTLID', 'ID', 'number', 0, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1343, 122, 'masterId', 'MASTER_ID', 'MASTER_ID', 'DOCID', '主表ID', 'number', 1, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1447, 122, 'apexGoodsid', 'APEX_GOODSID', null, null, '物料ID', 'number', 2, 1, 1, 0, null, 0, '04-FEB-26 03.33.37.671000 PM', '04-FEB-26 03.33.37.671000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1344, 122, 'dtlUseflag', 'DTL_USEFLAG', null, null, '分类', 'text', 2, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1345, 122, 'apexGoodsname', 'APEX_GOODSNAME', null, null, '物料名称', 'text', 3, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1346, 122, 'spec', 'SPEC', null, null, '规格', 'text', 4, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1347, 122, 'perHl', 'PER_HL', null, null, '每片含量', 'number', 5, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1348, 122, 'exaddMater', 'EXADD_MATER', null, null, '额外投料量', 'number', 6, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1349, 122, 'price', 'PRICE', null, null, '单价', 'number', 7, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1350, 122, 'batchQty', 'BATCH_QTY', null, null, '每批数量', 'number', 8, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1351, 122, 'costBatch', 'COST_BATCH', null, null, '每批成本', 'number', 9, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1352, 122, 'apexFactoryname', 'APEX_FACTORYNAME', null, null, '供应商', 'text', 10, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1353, 122, 'formulaType', 'FORMULA_TYPE', null, null, '公式类型', 'text', 11, 1, 1, 1, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1444, 122, 'basePrice', 'BASE_PRICE', null, null, '参考采购价', 'number', 12, 1, 1, 1, null, 0, '04-FEB-26 01.15.34.345000 PM', '04-FEB-26 01.15.34.345000 PM', 'system', null, 'CostMaterial');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1354, 123, 'id', 'ID', null, 'DTLID', 'ID', 'number', 0, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1355, 123, 'masterId', 'MASTER_ID', 'MASTER_ID', 'DOCID', '主表ID', 'number', 1, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1448, 123, 'apexGoodsid', 'APEX_GOODSID', null, null, '物料ID', 'number', 2, 1, 1, 0, null, 0, '04-FEB-26 03.33.37.696000 PM', '04-FEB-26 03.33.37.696000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1356, 123, 'dtlUseflag', 'DTL_USEFLAG', null, null, '包材类型', 'text', 2, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1357, 123, 'apexGoodsname', 'APEX_GOODSNAME', null, null, '包材名称', 'text', 3, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1358, 123, 'spec', 'SPEC', null, null, '规格型号', 'text', 4, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1359, 123, 'suqty', 'SUQTY', null, null, '用量', 'number', 5, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1360, 123, 'price', 'PRICE', null, null, '包材单价', 'number', 6, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1361, 123, 'batchQty', 'BATCH_QTY', null, null, '每批数量', 'number', 7, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1362, 123, 'costBatch', 'COST_BATCH', null, null, '包材成本', 'number', 8, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.009000 PM', '28-JAN-26 05.27.07.009000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1363, 123, 'apexFactoryname', 'APEX_FACTORYNAME', null, null, '包材供应商', 'text', 9, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.009000 PM', '28-JAN-26 05.27.07.009000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1364, 123, 'formulaType', 'FORMULA_TYPE', null, null, '公式类型', 'text', 10, 1, 1, 1, null, 0, '28-JAN-26 05.27.07.009000 PM', '28-JAN-26 05.27.07.009000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1445, 123, 'basePrice', 'BASE_PRICE', null, null, '参考采购价', 'number', 11, 1, 1, 1, null, 0, '04-FEB-26 01.15.34.366000 PM', '04-FEB-26 01.15.34.366000 PM', 'system', null, 'CostPackage');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1313, 121, 'id', 'DOCID', null, null, 'ID', 'number', 0, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.004000 PM', '28-JAN-26 05.27.07.004000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1314, 121, 'goodsname', 'GOODSNAME', null, null, '产品名称', 'text', 1, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.004000 PM', '28-JAN-26 05.27.07.004000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1446, 121, 'goodsid', 'GOODSID', null, null, '产品ID', 'number', 1, 1, 1, 0, null, 0, '04-FEB-26 03.33.37.640000 PM', '04-FEB-26 03.33.37.640000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1315, 121, 'goodsnameEn', 'GOODSNAME_EN', null, null, '产品英文名', 'text', 2, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.004000 PM', '28-JAN-26 05.27.07.004000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1316, 121, 'strength', 'STRENGTH', null, null, '剂量', 'text', 3, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.004000 PM', '28-JAN-26 05.27.07.004000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1317, 121, 'customname', 'CUSTOMNAME', null, null, '客户名称', 'text', 4, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.004000 PM', '28-JAN-26 05.27.07.004000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1450, 121, 'customid', 'CUSTOMID', null, null, '客户ID', 'number', 4, 1, 1, 0, null, 0, '04-FEB-26 04.36.06.643000 PM', '04-FEB-26 04.36.06.643000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1318, 121, 'country', 'COUNTRY', null, null, '国家', 'text', 5, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.004000 PM', '28-JAN-26 05.27.07.004000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1319, 121, 'projectno', 'PROJECTNO', null, null, '项目号', 'text', 6, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.004000 PM', '28-JAN-26 05.27.07.004000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1320, 121, 'apexPl', 'APEX_PL', null, null, '批量', 'number', 7, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.004000 PM', '28-JAN-26 05.27.07.004000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1321, 121, 'annualQty', 'ANNUAL_QTY', null, null, '年需求量', 'number', 8, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.005000 PM', '28-JAN-26 05.27.07.005000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1322, 121, 'yield', 'YIELD', null, null, '收率(%)', 'number', 9, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.005000 PM', '28-JAN-26 05.27.07.005000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1323, 121, 'pPerpack', 'P_PERPACK', null, null, '每盒片数', 'number', 10, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.005000 PM', '28-JAN-26 05.27.07.005000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1324, 121, 'sPerback', 'S_PERBACK', null, null, '每箱装盒数', 'number', 11, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.005000 PM', '28-JAN-26 05.27.07.005000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1325, 121, 'xPerback', 'X_PERBACK', null, null, '每托盘箱数', 'number', 12, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.005000 PM', '28-JAN-26 05.27.07.005000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1326, 121, 'packtype', 'PACKTYPE', null, null, '包装形式', 'text', 13, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.005000 PM', '28-JAN-26 05.27.07.005000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1327, 121, 'totalYl', 'TOTAL_YL', null, null, '原料合计', 'number', 20, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.005000 PM', '28-JAN-26 05.27.07.005000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1328, 121, 'totalFl', 'TOTAL_FL', null, null, '辅料合计', 'number', 21, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.005000 PM', '28-JAN-26 05.27.07.005000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1329, 121, 'totalBc', 'TOTAL_BC', null, null, '包材合计', 'number', 22, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1330, 121, 'totalCost', 'TOTAL_COST', null, null, '总物料成本', 'number', 23, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1331, 121, 'outPriceRmb', 'OUT_PRICE_RMB', null, null, '出厂价(RMB)', 'number', 24, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1332, 121, 'salemoney', 'SALEMONEY', null, null, '每批销售额', 'number', 25, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1333, 121, 'jgfBatch', 'JGF_BATCH', null, null, '每批加工费', 'number', 26, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1334, 121, 'costPerqp', 'COST_PERQP', null, null, '千片成本', 'number', 27, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1335, 121, 'jgfPerqp', 'JGF_PERQP', null, null, '千片加工费', 'number', 28, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1443, 121, 'costPerbox', 'COST_PERBOX', null, null, '每盒成本', 'number', 28, 1, 1, 0, null, 0, '04-FEB-26 11.11.41.634000 AM', '04-FEB-26 11.11.41.634000 AM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1336, 121, 'mlPerqp', 'ML_PERQP', null, null, '千片毛利', 'number', 29, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1337, 121, 'yJgRe', 'Y_JG_RE', null, null, '年加工费', 'number', 30, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1338, 121, 'yMl', 'Y_ML', null, null, '年毛利', 'number', 31, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1339, 121, 'ySale', 'Y_SALE', null, null, '年销售额', 'number', 32, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.006000 PM', '28-JAN-26 05.27.07.006000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1340, 121, 'fmname', 'FMNAME', null, null, '币种', 'text', 33, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1341, 121, 'fmrate', 'FMRATE', null, null, '汇率', 'number', 34, 1, 1, 0, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1449, 121, 'memo', 'MEMO', null, null, '备注', 'text', 35, 1, 1, 0, null, 0, '04-FEB-26 04.07.46.533000 PM', '04-FEB-26 04.07.46.533000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1451, 121, 'livery', 'LIVERY', null, null, '分销商', 'text', 36, 1, 1, 0, null, 0, '04-FEB-26 04.36.06.669000 PM', '04-FEB-26 04.36.06.669000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1452, 121, 'tranposid', 'TRANPOSID', null, null, '分销商ID', 'number', 37, 1, 1, 0, null, 0, '04-FEB-26 04.36.06.694000 PM', '04-FEB-26 04.36.06.694000 PM', 'system', null, 'CostPinggu');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (738, 71, 'id', 'TRANPOSID', null, null, '分销商ID', 'number', 0, 1, 1, 0, null, 0, '26-JAN-26 05.41.09.794000 PM', '26-JAN-26 05.41.09.794000 PM', 'system', null, 'CostTranposer');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (739, 71, 'customid', 'CUSTOMID', null, null, '客户ID', 'number', 1, 1, 1, 0, null, 0, '26-JAN-26 05.41.09.795000 PM', '26-JAN-26 05.41.09.795000 PM', 'system', null, 'CostTranposer');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (740, 71, 'tranposname', 'TRANPOSNAME', null, null, '分销商名称', 'text', 2, 1, 1, 0, null, 0, '26-JAN-26 05.41.09.796000 PM', '26-JAN-26 05.41.09.796000 PM', 'system', null, 'CostTranposer');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (741, 71, 'iserp', 'ISERP', null, null, '是否ERP', 'number', 99, 1, 1, 1, null, 0, '26-JAN-26 05.41.09.796000 PM', '26-JAN-26 05.41.09.796000 PM', 'system', null, 'CostTranposer');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (27, 5, 'id', 'ID', null, null, 'ID', 'number', 1, 1, 1, 0, null, 0, '26-JAN-26 09.53.11.342000 AM', '26-JAN-26 09.53.11.342000 AM', 'system', null, 'CostUser');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (28, 5, 'username', 'USERNAME', null, null, '用户名', 'text', 2, 1, 1, 0, null, 0, '26-JAN-26 09.53.11.429000 AM', '26-JAN-26 09.53.11.429000 AM', 'system', null, 'CostUser');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (29, 5, 'realName', 'REAL_NAME', null, null, '姓名', 'text', 3, 1, 1, 0, null, 0, '26-JAN-26 09.53.11.509000 AM', '26-JAN-26 09.53.11.509000 AM', 'system', null, 'CostUser');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (30, 5, 'email', 'EMAIL', null, null, '邮箱', 'text', 4, 1, 1, 0, null, 0, '26-JAN-26 09.53.11.579000 AM', '26-JAN-26 09.53.11.579000 AM', 'system', null, 'CostUser');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (31, 5, 'phone', 'PHONE', null, null, '电话', 'text', 5, 1, 1, 0, null, 0, '26-JAN-26 09.53.11.643000 AM', '26-JAN-26 09.53.11.643000 AM', 'system', null, 'CostUser');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (32, 5, 'departmentId', 'DEPARTMENT_ID', null, null, '部门ID', 'number', 6, 1, 1, 0, null, 0, '26-JAN-26 09.53.11.698000 AM', '26-JAN-26 09.53.11.698000 AM', 'system', null, 'CostUser');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (33, 5, 'deptName', 'DEPT_NAME', null, null, '部门名称', 'text', 7, 1, 1, 1, null, 0, '26-JAN-26 09.53.11.758000 AM', '26-JAN-26 09.53.11.758000 AM', 'system', null, 'CostUser');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (34, 5, 'status', 'STATUS', null, null, '状态', 'text', 8, 1, 1, 0, null, 0, '26-JAN-26 09.53.11.801000 AM', '26-JAN-26 09.53.11.801000 AM', 'system', null, 'CostUser');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1633, 173, 'id', 'CONID', null, null, '合同ID', 'number', 0, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.266000 PM', '05-FEB-26 05.40.28.266000 PM', 'system', null, 'WmsConDoc');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1634, 173, 'conno', 'CONNO', null, null, '合同编号', 'text', 1, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.266000 PM', '05-FEB-26 05.40.28.266000 PM', 'system', null, 'WmsConDoc');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1635, 173, 'customname', 'CUSTOMNAME', null, null, '客户名称', 'text', 2, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null, 'WmsConDoc');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1636, 173, 'targetposname', 'TARGETPOSNAME', null, null, '目的地', 'text', 3, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null, 'WmsConDoc');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1637, 173, 'inputmanname', 'INPUTMANNAME', null, null, '录入人', 'text', 4, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null, 'WmsConDoc');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1638, 174, 'id', 'ID', null, null, 'ID', 'number', 0, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null, 'WmsQty');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1639, 174, 'masterId', 'CONID', 'CONID', 'CONID', '合同ID', 'number', 1, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null, 'WmsQty');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1640, 174, 'goodsid', 'GOODSID', null, null, '产品ID', 'number', 2, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null, 'WmsQty');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1641, 174, 'goodsgp', 'GOODSGP', null, null, '产品名称', 'text', 3, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null, 'WmsQty');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1642, 174, 'lotno', 'LOTNO', null, null, '批号', 'text', 4, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null, 'WmsQty');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1643, 174, 'goodsno', 'GOODSNO', null, null, '产品编码', 'text', 5, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null, 'WmsQty');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1644, 174, 'packsize', 'PACKSIZE', null, null, '包装规格', 'number', 6, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQty');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1645, 174, 'qtyShow', 'QTY_SHOW', null, null, '库存显示', 'text', 7, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQty');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1646, 174, 'pcs', 'PCS', null, null, '件数', 'number', 8, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQty');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1647, 175, 'id', 'ID', null, null, 'ID', 'number', 0, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1648, 175, 'masterId', 'CONID', 'CONID', 'CONID', '合同ID', 'number', 1, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1649, 175, 'rn', 'RN', null, null, '序号', 'number', 2, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1650, 175, 'goodsid', 'GOODSID', null, null, '产品ID', 'number', 3, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1651, 175, 'goodsname', 'GOODSNAME', null, null, '产品名称', 'text', 4, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1652, 175, 'lotno', 'LOTNO', null, null, '批号', 'text', 5, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1653, 175, 'goodsqty', 'GOODSQTY', null, null, '数量', 'number', 6, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1654, 175, 'pcs', 'PCS', null, null, '件数', 'number', 7, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1655, 175, 'validdate', 'VALIDDATE', null, null, '有效期', 'date', 8, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1656, 175, 'containerno', 'CONTAINERNO', null, null, '柜号', 'text', 9, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.269000 PM', '05-FEB-26 05.40.28.269000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1657, 175, 'memo', 'MEMO', null, null, '备注', 'text', 10, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.269000 PM', '05-FEB-26 05.40.28.269000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1658, 175, 'jz', 'JZ', null, null, '净重(KG)', 'number', 11, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.269000 PM', '05-FEB-26 05.40.28.269000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1659, 175, 'mz', 'MZ', null, null, '毛重(KG)', 'number', 12, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.269000 PM', '05-FEB-26 05.40.28.269000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1660, 175, 'tj', 'TJ', null, null, '体积(M3)', 'number', 13, 1, 1, 0, null, 0, '05-FEB-26 05.40.28.269000 PM', '05-FEB-26 05.40.28.269000 PM', 'system', null, 'WmsQtyDetail');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1503, 146, 'id', 'ID', null, null, 'ID', 'number', 1, 1, 1, 0, null, 0, '04-FEB-26 06.16.19.388000 PM', '04-FEB-26 06.16.19.388000 PM', null, null, 'auditLog');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1504, 146, 'userName', 'USER_NAME', null, null, '操作用户', 'text', 2, 1, 1, 0, null, 0, '04-FEB-26 06.16.19.444000 PM', '04-FEB-26 06.16.19.444000 PM', null, null, 'auditLog');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1505, 146, 'operationTime', 'OPERATION_TIME', null, null, '操作时间', 'datetime', 3, 1, 1, 0, null, 0, '04-FEB-26 06.16.19.488000 PM', '04-FEB-26 06.16.19.488000 PM', null, null, 'auditLog');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1506, 146, 'pageCode', 'PAGE_CODE', null, null, '页面编码', 'text', 4, 1, 1, 0, null, 0, '04-FEB-26 06.16.19.540000 PM', '04-FEB-26 06.16.19.540000 PM', null, null, 'auditLog');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1507, 146, 'tableCode', 'TABLE_CODE', null, null, '表编码', 'text', 5, 1, 1, 0, null, 0, '04-FEB-26 06.16.19.586000 PM', '04-FEB-26 06.16.19.586000 PM', null, null, 'auditLog');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1508, 146, 'tableName', 'TABLE_NAME', null, null, '表名称', 'text', 6, 1, 1, 0, null, 0, '04-FEB-26 06.16.19.627000 PM', '04-FEB-26 06.16.19.627000 PM', null, null, 'auditLog');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1509, 146, 'recordId', 'RECORD_ID', null, null, '记录ID', 'number', 7, 1, 1, 0, null, 0, '04-FEB-26 06.16.19.684000 PM', '04-FEB-26 06.16.19.684000 PM', null, null, 'auditLog');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1510, 146, 'operationType', 'OPERATION_TYPE', null, null, '操作类型', 'text', 8, 1, 1, 0, null, 0, '04-FEB-26 06.16.19.745000 PM', '04-FEB-26 06.16.19.745000 PM', null, null, 'auditLog');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1511, 146, 'fieldChanges', 'FIELD_CHANGES', null, null, '字段变更', 'text', 9, 1, 0, 0, null, 0, '04-FEB-26 06.16.19.794000 PM', '04-FEB-26 06.16.19.794000 PM', null, null, 'auditLog');

insert into T_COST_COLUMN_METADATA (ID, TABLE_METADATA_ID, FIELD_NAME, COLUMN_NAME, QUERY_COLUMN, TARGET_COLUMN, HEADER_TEXT, DATA_TYPE, DISPLAY_ORDER, SORTABLE, FILTERABLE, IS_VIRTUAL, DICT_TYPE, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, TABLE_CODE)
values (1512, 146, 'createTime', 'CREATE_TIME', null, null, '创建时间', 'datetime', 10, 1, 1, 0, null, 0, '04-FEB-26 06.16.19.844000 PM', '04-FEB-26 06.16.19.844000 PM', null, null, 'auditLog');

prompt Done.
