prompt Importing table user_sequences...
set feedback off
set define off

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_AUDIT_LOG', 1, 1E28, 1, 'N', 'N', 20, 601, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_COLUMN_METADATA', 1, 1E28, 1, 'N', 'N', 20, 1661, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_CUSTOMER', 1, 1E28, 1, 'N', 'N', 20, 1, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_DEPARTMENT', 1, 1E28, 1, 'N', 'N', 20, 1, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_DICT_ITEM', 1, 1E28, 1, 'N', 'N', 20, 1, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_DICT_TYPE', 1, 1E28, 1, 'N', 'N', 20, 1, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_EXPORT_CONFIG', 1, 1E28, 1, 'N', 'N', 20, 41, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_EXPORT_CONFIG_DTL', 1, 1E28, 1, 'N', 'N', 20, 21, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_FORMONEY', 1, 1E28, 1, 'N', 'N', 20, 1, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_GOODS', 1, 1E28, 1, 'N', 'N', 20, 21, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_GOODS_PRICE', 1, 1E28, 1, 'N', 'N', 20, 1, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_LOOKUP_CONFIG', 1, 1E28, 1, 'N', 'N', 20, 141, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_OPERATION_LOG', 1, 1E28, 1, 'N', 'N', 20, 301, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_OPERATION_LOG_DETAIL', 1, 1E28, 1, 'N', 'N', 20, 1541, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_PAGE_COMPONENT', 1, 1E28, 1, 'N', 'N', 20, 181, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_PAGE_RULE', 1, 1E28, 1, 'N', 'N', 20, 621, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_PINGGU', 1, 1E28, 1, 'N', 'N', 20, 100000, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_PINGGU_DTL', 1, 1E28, 1, 'N', 'N', 20, 100300, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_RESOURCE', 1, 1E28, 1, 'N', 'N', 20, 141, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_ROLE', 1, 1E28, 1, 'N', 'N', 20, 61, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_ROLE_PAGE', 1, 1E28, 1, 'N', 'N', 20, 141, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_TABLE_METADATA', 1, 1E28, 1, 'N', 'N', 20, 181, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_TRANPOSER', 1, 1E28, 1, 'N', 'N', 20, 21, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_USER', 1, 1E28, 1, 'N', 'N', 20, 181, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_USER_GRID', 1, 1E28, 1, 'N', 'N', 20, 61, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_COST_USER_ROLE', 1, 1E28, 1, 'N', 'N', 20, 61, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_WMS_CON_DOC', 1, 1E28, 1, 'N', 'N', 20, 1, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_WMS_QTY', 1, 1E28, 1, 'N', 'N', 20, 22421, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_WMS_QTY_DETAIL', 1, 1E28, 1, 'N', 'N', 20, 361, 'N', 'N', 'N', 'N', 'N');

insert into user_sequences (SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE)
values ('SEQ_WMS_QTY_DTL', 1, 1E28, 1, 'N', 'N', 20, 1, 'N', 'N', 'N', 'N', 'N');

prompt Done.
