prompt Importing table T_COST_TABLE_METADATA...
set feedback off
set define off

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (70, 'CostCustomer', '客户信息', 'T_COST_CUSTOMER_V', 'T_COST_CUSTOMER', 'SEQ_COST_CUSTOMER', 'CUSTOMID', null, null, 0, null, null, null, 0, '26-JAN-26 05.41.09.210000 PM', '26-JAN-26 05.41.09.210000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (125, 'CostCustomerLookup', '客户选择', 'V_COST_CUSTOMER_LOOKUP', 'T_COST_CUSTOMER_V', null, 'CUSTOMID', null, null, 0, null, null, null, 0, '28-JAN-26 05.27.08.162000 PM', '28-JAN-26 05.27.08.162000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (6, 'CostDepartment', '部门管理', 'T_COST_DEPARTMENT', 'T_COST_DEPARTMENT', 'SEQ_COST_DEPARTMENT', 'ID', null, null, 0, null, null, null, 0, '26-JAN-26 09.53.11.194000 AM', '26-JAN-26 09.53.11.194000 AM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (41, 'CostFormoney', '外币管理', 'T_COST_FORMONEY_V', 'T_COST_FORMONEY', 'SEQ_COST_FORMONEY', 'FMID', null, null, 0, null, null, null, 0, '26-JAN-26 04.53.18.651000 PM', '26-JAN-26 04.53.18.651000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (131, 'CostGoods', '产品信息维护', 'T_COST_GOODS_V', 'T_COST_GOODS', 'SEQ_COST_GOODS', 'GOODSID', null, null, 0, null, null, null, 0, '29-JAN-26 05.12.14.524000 PM', '29-JAN-26 05.12.14.524000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (129, 'CostGoodsByApex', '产品选择(按物料)', 'V_COST_GOODS_BY_APEX', 'V_COST_GOODS_BY_APEX', null, 'GOODSID', null, null, 0, null, null, null, 0, '29-JAN-26 04.26.50.656000 PM', '29-JAN-26 04.26.50.656000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (124, 'CostGoodsLookup', '产品选择', 'V_COST_GOODS_LOOKUP', 'T_COST_GOODS', null, 'GOODSID', null, null, 0, null, null, null, 0, '28-JAN-26 05.27.07.598000 PM', '28-JAN-26 05.27.07.598000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (132, 'CostGoodsPrice', '物料清单及成本', 'T_COST_GOODS_PRICE_V', 'T_COST_GOODS_PRICE', 'SEQ_COST_GOODS_PRICE', 'GOODSID', null, null, 0, null, null, null, 0, '29-JAN-26 05.25.30.958000 PM', '29-JAN-26 05.25.30.958000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (122, 'CostMaterial', '原辅料明细', 'V_COST_PINGGU_MATERIAL', 'T_COST_PINGGU_DTL', 'SEQ_COST_PINGGU_DTL', 'DTLID', 'CostPinggu', 'DOCID', 0, null, null, null, 0, '28-JAN-26 05.27.07.007000 PM', '28-JAN-26 05.27.07.007000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (123, 'CostPackage', '包材明细', 'V_COST_PINGGU_PACKAGE', 'T_COST_PINGGU_DTL', 'SEQ_COST_PINGGU_DTL', 'DTLID', 'CostPinggu', 'DOCID', 0, null, null, null, 0, '28-JAN-26 05.27.07.008000 PM', '28-JAN-26 05.27.07.008000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (121, 'CostPinggu', '物料成本核算表', 'T_COST_PINGGU', 'T_COST_PINGGU', 'SEQ_COST_PINGGU', 'DOCID', null, null, 0, null, null, null, 0, '28-JAN-26 05.27.07.003000 PM', '28-JAN-26 05.27.07.003000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (71, 'CostTranposer', '分销商信息', 'T_COST_TRANPOSER_V', 'T_COST_TRANPOSER', 'SEQ_COST_TRANPOSER', 'TRANPOSID', 'CostCustomer', 'CUSTOMID', 0, null, null, null, 0, '26-JAN-26 05.41.09.794000 PM', '26-JAN-26 05.41.09.794000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (5, 'CostUser', '用户管理', 'V_COST_USER', 'T_COST_USER', 'SEQ_COST_USER', 'ID', null, null, 0, null, null, null, 0, '26-JAN-26 09.53.11.126000 AM', '26-JAN-26 09.53.11.126000 AM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (173, 'WmsConDoc', '成品发运单', 'T_WMS_CON_DOC_V', 'T_WMS_CON_DOC_V', null, 'CONID', null, null, 0, null, null, null, 0, '05-FEB-26 05.40.28.265000 PM', '05-FEB-26 05.40.28.265000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (174, 'WmsQty', '库存汇总', 'T_WMS_QTY', 'T_WMS_QTY', 'SEQ_WMS_QTY', 'ID', 'WmsConDoc', 'CONID', 0, null, null, null, 0, '05-FEB-26 05.40.28.267000 PM', '05-FEB-26 05.40.28.267000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (175, 'WmsQtyDetail', '库存明细', 'T_WMS_QTY_DETAIL', 'T_WMS_QTY_DETAIL', 'SEQ_WMS_QTY_DETAIL', 'ID', 'WmsConDoc', 'CONID', 0, null, null, null, 0, '05-FEB-26 05.40.28.268000 PM', '05-FEB-26 05.40.28.268000 PM', 'system', null);

insert into T_COST_TABLE_METADATA (ID, TABLE_CODE, TABLE_NAME, QUERY_VIEW, TARGET_TABLE, SEQUENCE_NAME, PK_COLUMN, PARENT_TABLE_CODE, PARENT_FK_COLUMN, AUDIT_ENABLED, VALIDATION_RULES, ACTION_RULES, DESCRIPTION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (146, 'auditLog', '审计追踪', 'V_COST_AUDIT_LOG', 'T_COST_AUDIT_LOG', 'SEQ_COST_AUDIT_LOG', 'ID', null, null, 0, null, null, '系统审计日志', 0, '04-FEB-26 06.16.19.341000 PM', '04-FEB-26 06.16.19.341000 PM', null, null);

prompt Done.
