prompt Importing table T_COST_PAGE_COMPONENT...
set feedback off
set define off

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (146, 'auditLog', 'masterGrid', 'GRID', null, null, 'auditLog', null, 1, 0, '审计追踪主表格', '04-FEB-26 06.16.19.885000 PM', '04-FEB-26 06.16.19.885000 PM', null, null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (113, 'cost-pinggu', 'root', 'LAYOUT', null, '{"direction":"vertical","gap":8}', null, null, 0, 0, null, '28-JAN-26 05.27.15.218000 PM', '28-JAN-26 05.27.15.218000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (114, 'cost-pinggu', 'masterGrid', 'GRID', 'root', '{"height":"50%","selectionMode":"single","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"generateFromBom","label":"由BOM生成明细","requiresRow":true,"procedure":"P_COST_BOM_INSERT","params":[{"source":"data.id","mode":"IN","jdbcType":"NUMERIC"}]},{"action":"syncPrice","label":"同步采购价","procedure":"P_PINGGU_COMPUTE_ALL","params":[]},{"action":"saveGridConfig","label":"保存列配置"},{"action":"save","label":"保存"}]}', 'CostPinggu', null, 1, 0, null, '28-JAN-26 05.27.15.537000 PM', '28-JAN-26 05.27.15.537000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (115, 'cost-pinggu', 'detailTabs', 'TABS', 'root', '{"mode":"multi","tabs":[{"key":"material","title":"原料/辅料","tableCode":"CostMaterial","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]},{"key":"package","title":"包材","tableCode":"CostPackage","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}]}', null, null, 2, 0, null, '28-JAN-26 05.27.15.835000 PM', '28-JAN-26 05.27.15.835000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (83, 'customer-manage', 'root', 'LAYOUT', null, '{"direction":"vertical","gap":8}', null, null, 0, 0, null, '26-JAN-26 05.41.09.869000 PM', '26-JAN-26 05.41.09.869000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (84, 'customer-manage', 'masterGrid', 'GRID', 'root', '{"height":"50%","selectionMode":"single","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"label":"导出","items":[{"action":"exportSelected","label":"导出选中","requiresSelection":true},{"action":"exportCurrent","label":"导出当前页"},{"action":"exportAll","label":"导出全部"},{"action":"resetExportConfig","label":"重置导出配置"},{"action":"openHeaderConfig","label":"配置导出表头"}]},{"action":"save","label":"保存"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}', 'CostCustomer', null, 1, 0, null, '26-JAN-26 05.41.09.937000 PM', '26-JAN-26 05.41.09.937000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (85, 'customer-manage', 'detailTabs', 'TABS', 'root', '{"mode":"single","tabs":[{"key":"tranposer","title":"分销商","tableCode":"CostTranposer","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"label":"导出","items":[{"action":"exportSelected","label":"导出选中","requiresSelection":true},{"action":"exportCurrent","label":"导出当前页"},{"action":"exportAll","label":"导出全部"},{"action":"resetExportConfig","label":"重置导出配置"},{"action":"openHeaderConfig","label":"配置导出表头"}]},{"action":"save","label":"保存"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}]}', null, null, 2, 0, null, '26-JAN-26 05.41.09.973000 PM', '26-JAN-26 05.41.09.973000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (6, 'dept-manage', 'masterGrid', 'GRID', null, '{"buttons":[{"action":"addRow","label":"新增"},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"save","label":"保存"}]}', 'CostDepartment', null, 0, 0, null, '26-JAN-26 09.53.12.387000 AM', '26-JAN-26 09.53.12.387000 AM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (61, 'formoney-manage', 'root', 'LAYOUT', null, '{"direction":"vertical","gap":8}', null, null, 0, 0, null, '26-JAN-26 04.53.18.796000 PM', '26-JAN-26 04.53.18.796000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (62, 'formoney-manage', 'grid', 'GRID', 'root', '{"height":"100%","selectionMode":"single","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"label":"导出","items":[{"action":"exportSelected","label":"导出选中","requiresSelection":true},{"action":"exportCurrent","label":"导出当前页"},{"action":"exportAll","label":"导出全部"},{"action":"resetExportConfig","label":"重置导出配置"},{"action":"openHeaderConfig","label":"配置导出表头"}]},{"action":"save","label":"保存"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"},{"action":"SYNC_ERP_RATE","label":"同步ERP汇率","position":"toolbar","type":"primary","sql":"UPDATE T_COST_FORMONEY SET FMRATE = NULL, CREATE_TIME = NULL, UPDATE_TIME = NULL WHERE CREATE_BY = ''system''"}]}', 'CostFormoney', null, 1, 0, null, '26-JAN-26 04.53.18.832000 PM', '26-JAN-26 04.53.18.832000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (123, 'goods-manage', 'root', 'LAYOUT', null, '{"direction":"vertical"}', null, null, 0, 0, null, '29-JAN-26 05.12.14.776000 PM', '29-JAN-26 05.12.14.776000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (124, 'goods-manage', 'grid', 'GRID', 'root', '{"height":"100%","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"label":"导出","items":[{"action":"exportSelected","label":"导出选中","requiresSelection":true},{"action":"exportCurrent","label":"导出当前页"},{"action":"exportAll","label":"导出全部"},{"action":"resetExportConfig","label":"重置导出配置"},{"action":"openHeaderConfig","label":"配置导出表头"}]},{"action":"save","label":"保存"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}', 'CostGoods', null, 1, 0, null, '29-JAN-26 05.12.14.808000 PM', '29-JAN-26 05.12.14.808000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (125, 'goods-price-manage', 'root', 'LAYOUT', null, '{"direction":"vertical"}', null, null, 0, 0, null, '29-JAN-26 05.25.31.158000 PM', '29-JAN-26 05.25.31.158000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (126, 'goods-price-manage', 'grid', 'GRID', 'root', '{"height":"100%","buttons":[{"action":"addRow","label":"新增"},{"action":"copyRow","label":"复制","requiresRow":true},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"saveGridConfig","label":"保存列配置"},{"label":"导出","items":[{"action":"exportSelected","label":"导出选中","requiresSelection":true},{"action":"exportCurrent","label":"导出当前页"},{"action":"exportAll","label":"导出全部"},{"action":"resetExportConfig","label":"重置导出配置"},{"action":"openHeaderConfig","label":"配置导出表头"}]},{"action":"save","label":"保存"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}', 'CostGoodsPrice', null, 1, 0, null, '29-JAN-26 05.25.31.187000 PM', '29-JAN-26 05.25.31.187000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (5, 'user-manage', 'masterGrid', 'GRID', null, '{"buttons":[{"action":"addRow","label":"新增"},{"action":"deleteRow","label":"删除","requiresRow":true},{"action":"resetPassword","label":"初始化密码","position":"toolbar","requiresRow":true,"method":"userService.resetPassword"},{"action":"save","label":"保存"}]}', 'CostUser', null, 0, 0, null, '26-JAN-26 09.53.12.347000 AM', '26-JAN-26 09.53.12.347000 AM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (173, 'wms-shipping', 'root', 'LAYOUT', null, '{"direction":"vertical","gap":8}', null, null, 0, 0, null, '05-FEB-26 05.40.28.673000 PM', '05-FEB-26 05.40.28.673000 PM', 'system', null);

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (174, 'wms-shipping', 'masterGrid', 'GRID', 'root', '{"height":"50%","selectionMode":"single","buttons":[{"action":"syncWmsQty","label":"同步库存","requiresRow":true,"procedure":"P_WMS_SYNC_BY_CONID","params":[{"source":"data.id","mode":"IN","jdbcType":"NUMERIC"}],"refreshMode":"detail"},{"action":"save","label":"保存"},{"action":"clipboard.copy","label":"复制"},{"action":"clipboard.paste","label":"粘贴"}]}', 'WmsConDoc', null, 1, 0, null, '05-FEB-26 05.40.28.712000 PM', '06-FEB-26 08.58.09.156000 AM', 'system', 'system');

insert into T_COST_PAGE_COMPONENT (ID, PAGE_CODE, COMPONENT_KEY, COMPONENT_TYPE, PARENT_KEY, COMPONENT_CONFIG, REF_TABLE_CODE, SLOT_NAME, SORT_ORDER, DELETED, DESCRIPTION, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY)
values (175, 'wms-shipping', 'detailTabs', 'TABS', 'root', '{"mode":"multi","tabs":[{"key":"wmsQty","title":"库存汇总","tableCode":"WmsQty","buttons":[{"action":"batchSelect","label":"从库存添加","batchSelectConfig":{"lookupCode":"wmsQtyLookup","title":"选择库存","mapping":{"goodsid":"goodsid","goodsgp":"goodsgp","lotno":"lotno","goodsno":"goodsno","packsize":"packsize","qtyShow":"qty_show","pcs":"pcs"}}},{"action":"deleteRow","label":"删除","requiresRow":true},{"type":"separator"},{"action":"save","label":"保存"},{"type":"separator"},{"action":"clipboard.copy"},{"action":"clipboard.paste"}]},{"key":"wmsQtyDetail","title":"库存明细","tableCode":"WmsQtyDetail","buttons":[{"action":"addRow","label":"新增"},{"action":"deleteRow","label":"删除","requiresRow":true},{"type":"separator"},{"action":"save","label":"保存"},{"type":"separator"},{"action":"clipboard.copy"},{"action":"clipboard.paste"}]}]}', null, null, 2, 0, null, '05-FEB-26 05.40.28.749000 PM', '05-FEB-26 05.57.19.330000 PM', 'system', 'system');

prompt Done.
